// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://giznqbjxcxllmgamxgaa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdpem5xYmp4Y3hsbG1nYW14Z2FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODk1NjEsImV4cCI6MjA2OTU2NTU2MX0.KoDcKxTYlrUhF-Vf2_e3A6LeMA_UgIaQe6TYXkzNzek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});