-- Add 30 new foods to continue building Livsmedel A-Ö database (fixing array type issue)

-- Insert remaining Grönsaker (12 foods)
INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

('Tomat', 'tomat', 'T',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Fruktgrönsak',
'Rumstemperatur, kylskåp när mogen',
'3-5 dagar',
'1 vecka',
true,
'Skär i bitar innan frysning',
ARRAY['juni', 'juli', 'augusti', 'september'],
ARRAY[]::text[],
18, 0.9, 0.2, 3.9, 1.2, 0.005,
'{"C": "14mg", "K": "8μg", "Folat": "15μg"}'::jsonb,
'{"kalium": "237mg", "fosfor": "24mg"}'::jsonb,
'Saftig fruktgrönsak rik på lycopene och vitamin C.',
ARRAY['Sallader', 'Såser', 'Soppa', 'Pizza'],
'[{"name": "Körsbärstomater", "reason": "Sötare och mindre"}, {"name": "San Marzano", "reason": "Perfekt för såser"}]'::jsonb,
'Tomat - Näringsvärde och Odling | Livsmedel A-Ö',
'Komplett guide om tomater: näringsvärde, olika sorter, odling och användning i matlagning.',
'[{"question": "Ska tomater förvaras i kylskåp?", "answer": "Nej, mogna tomater förvaras bäst i rumstemperatur för bästa smak."}, {"question": "Vad är lycopene?", "answer": "En antioxidant som ger tomater röd färg och kan ha hälsofördelar."}]'::jsonb,
ARRAY['Italiensk mat', 'Sallader', 'Sommarmiddag']),

('Gurka', 'gurka', 'G',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Fruktgrönsak',
'Kylskåp 8-10°C',
'1 vecka',
'1-2 veckor',
false,
'Rekommenderas ej att frysa',
ARRAY['juni', 'juli', 'augusti', 'september'],
ARRAY[]::text[],
16, 0.7, 0.1, 3.6, 0.5, 0.002,
'{"K": "16μg", "C": "2.8mg"}'::jsonb,
'{"kalium": "147mg", "magnesium": "13mg"}'::jsonb,
'Krispig grönsak med hög vattenhalt, perfekt för sallader.',
ARRAY['Sallader', 'Tzatziki', 'Inläggning', 'Smoothies'],
'[{"name": "Zucchini", "reason": "Liknande mild smak"}, {"name": "Selleri", "reason": "Samma krispighet"}]'::jsonb,
'Gurka - Näringsvärde och Användning | Livsmedel A-Ö',
'Allt om gurka: näringsvärde, förvaring, olika sorter och användning i matlagning.',
'[{"question": "Varför blir gurka besk?", "answer": "Beska ämnen bildas vid stress, välj små gurkor och skala bort ändarna."}, {"question": "Kan man äta gurkskal?", "answer": "Ja, skalet innehåller fiber och näringsämnen - skölj bara ordentligt."}]'::jsonb,
ARRAY['Sallader', 'Grekisk mat', 'Sommarmat']),

('Paprika Röd', 'paprika-rod', 'P',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Fruktgrönsak',
'Kylskåp 7-10°C',
'1 vecka',
'1-2 veckor',
true,
'Skär i remsor innan frysning',
ARRAY['juli', 'augusti', 'september'],
ARRAY[]::text[],
31, 1.0, 0.3, 6.0, 2.5, 0.004,
'{"C": "128mg", "A": "157μg", "B6": "0.3mg"}'::jsonb,
'{"kalium": "211mg", "folat": "46μg"}'::jsonb,
'Söt och färgstark grönsak med mycket vitamin C.',
ARRAY['Wok', 'Sallader', 'Grillad', 'Fyllning'],
'[{"name": "Gul paprika", "reason": "Liknande sötma"}, {"name": "Chilipaprika", "reason": "Hetare variant"}]'::jsonb,
'Paprika Röd - Vitamin C Källa | Livsmedel A-Ö',
'Komplett guide om röd paprika: näringsvärde, vitamin C fördelar, tillagning och odling.',
'[{"question": "Varför är röd paprika sötare?", "answer": "Röd paprika är fullt mogen och har utvecklat mer socker än grön paprika."}, {"question": "Kan man äta paprikakärnor?", "answer": "Ja, de är ätbara men kan vara lite beska."}]'::jsonb,
ARRAY['Wok mat', 'Medelhavsmat', 'Vitamin C']),

('Lök Gul', 'lok-gul', 'L',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Rotgrönsak',
'Mörkt, torrt och svalt',
'2-3 månader',
'2-3 månader',
true,
'Hacka innan frysning',
ARRAY['augusti', 'september', 'oktober'],
ARRAY[]::text[],
40, 1.1, 0.1, 9.3, 1.7, 0.004,
'{"C": "7.4mg", "B6": "0.1mg", "Folat": "19μg"}'::jsonb,
'{"kalium": "146mg", "mangan": "0.1mg"}'::jsonb,
'Grundläggande aromgrönsak, bas i de flesta maträtter.',
ARRAY['Bas för såser', 'Stekt', 'Karamelliserad', 'Soppa'],
'[{"name": "Schalottenlök", "reason": "Mildare smak"}, {"name": "Rödlök", "reason": "Starkare smak, bra rå"}]'::jsonb,
'Lök Gul - Grundsmaker och Förvaring | Livsmedel A-Ö',
'Allt om gul lök: näringsvärde, förvaring, olika typer och grundläggande matlagning.',
'[{"question": "Hur undviker man tårar när man hackar lök?", "answer": "Kyl löken först, använd vass kniv och andas genom munnen."}, {"question": "Varför blir lök söt när man steker den?", "answer": "Värme bryter ner sura föreningar och förvandlar dem till socker."}]'::jsonb,
ARRAY['Grundsmaker', 'Svensk husmanskost', 'Daglig matlagning']),

('Potatis', 'potatis', 'P',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Rotgrönsak',
'Mörkt, torrt och svalt 4-8°C',
'2-3 månader',
'2-3 månader',
true,
'Koka innan frysning',
ARRAY['augusti', 'september', 'oktober'],
ARRAY[]::text[],
77, 2.0, 0.1, 17.0, 2.2, 0.006,
'{"C": "20mg", "B6": "0.3mg", "Folat": "15μg"}'::jsonb,
'{"kalium": "429mg", "fosfor": "57mg", "magnesium": "23mg"}'::jsonb,
'Sveriges viktigaste grundgrönsak, rik på stärkelse.',
ARRAY['Kokt', 'Bakad', 'Stekt', 'Mos'],
'[{"name": "Sötpotatis", "reason": "Sötare smak, mer vitamin A"}, {"name": "Pasta", "reason": "Annan kolhydratkälla"}]'::jsonb,
'Potatis - Näringsvärde och Svenska Sorter | Livsmedel A-Ö',
'Komplett guide om potatis: näringsvärde, svenska sorter, förvaring och tillagningsmetoder.',
'[{"question": "Vilken potatis är bäst för kokning?", "answer": "Mandelpotatis håller formen bäst, mjöliga sorter passar bäst för mos."}, {"question": "Kan man äta grön potatis?", "answer": "Nej, grön färg indikerar solanin som är giftigt - skala bort gröna delar."}]'::jsonb,
ARRAY['Svensk husmanskost', 'Grundmat', 'Vardagsmiddag']),

('Morot', 'morot', 'M',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Rotgrönsak',
'Kylskåp 0-4°C',
'3-4 veckor',
'1 månad',
true,
'Skär i bitar innan frysning',
ARRAY['augusti', 'september', 'oktober', 'november'],
ARRAY[]::text[],
41, 0.9, 0.2, 9.6, 2.8, 0.069,
'{"A": "835μg", "K": "13μg", "B6": "0.1mg"}'::jsonb,
'{"kalium": "320mg", "biotin": "6μg"}'::jsonb,
'Söt rotgrönsak extremt rik på betakaroten (vitamin A).',
ARRAY['Rå i sallad', 'Soppa', 'Juice', 'Bakad'],
'[{"name": "Palsternacka", "reason": "Liknande rotgrönsak"}, {"name": "Sötpotatis", "reason": "Liknande sötma och färg"}]'::jsonb,
'Morot - Vitamin A Källa och Användning | Livsmedel A-Ö',
'Allt om morötter: näringsvärde, vitamin A fördelar, odling och olika tillagningssätt.',
'[{"question": "Varför är morötter bra för synen?", "answer": "Betakaroten omvandlas till vitamin A som behövs för bildningen av rhodopsin i ögat."}, {"question": "Blir morötter sötare efter frost?", "answer": "Ja, kyla omvandlar stärkelse till socker som en naturlig frostskydd."}]'::jsonb,
ARRAY['Vitamin A källa', 'Barnmat', 'Hälsosam kost']),

('Broccoli', 'broccoli', 'B',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Kålväxt',
'Kylskåp 0-4°C',
'3-5 dagar',
'1 vecka',
true,
'Blanchera innan frysning',
ARRAY['juni', 'juli', 'augusti', 'september'],
ARRAY[]::text[],
34, 2.8, 0.4, 7.0, 2.6, 0.033,
'{"C": "89mg", "K": "102μg", "Folat": "63μg"}'::jsonb,
'{"kalium": "316mg", "järn": "0.7mg", "kalcium": "47mg"}'::jsonb,
'Näringsrik kålväxt med högt innehåll av vitamin C och K.',
ARRAY['Ångkokt', 'Wok', 'Gratäng', 'Soppa'],
'[{"name": "Blomkål", "reason": "Liknande textur"}, {"name": "Romanesco", "reason": "Nötighare smak"}]'::jsonb,
'Broccoli - Supervärden och Tillagning | Livsmedel A-Ö',
'Komplett guide om broccoli: näringsvärde, hälsofördelar, tillagning för bästa smak och näring.',
'[{"question": "Hur kokar man broccoli utan att förlora näring?", "answer": "Ångkoka i 3-4 minuter eller koka i lite vatten kort tid för att bevara vitaminer."}, {"question": "Kan man äta broccoli rå?", "answer": "Ja, rå broccoli i sallader ger mest näring och en krispig textur."}]'::jsonb,
ARRAY['Hälsosam mat', 'Vitamin C källa', 'Antioxidanter']),

('Spenat', 'spenat', 'S',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Bladgrönsak',
'Kylskåp 0-4°C',
'3-5 dagar',
'1 vecka',
true,
'Blanchera innan frysning',
ARRAY['mars', 'april', 'maj', 'september', 'oktober'],
ARRAY[]::text[],
23, 2.9, 0.4, 3.6, 2.2, 0.079,
'{"K": "483μg", "Folat": "194μg", "A": "469μg"}'::jsonb,
'{"järn": "2.7mg", "magnesium": "79mg", "kalium": "558mg"}'::jsonb,
'Järnrik bladgrönsak med mycket folsyra och vitamin K.',
ARRAY['Sallad', 'Smoothies', 'Stuvad', 'Pasta'],
'[{"name": "Mangold", "reason": "Liknande bladgrönsak"}, {"name": "Rucola", "reason": "Starkare smak"}]'::jsonb,
'Spenat - Järn och Folsyra | Livsmedel A-Ö',
'Allt om spenat: näringsvärde, järninnehåll, tillagning och användning i hälsosam kost.',
'[{"question": "Är spenat verkligen så järnrik?", "answer": "Ja, men järnet från växter absorberas sämre - kombinera med vitamin C för bättre upptag."}, {"question": "Kan man äta mycket spenat?", "answer": "Spenat innehåller oxalater som kan påverka kalciumupptag - variera med andra grönsaker."}]'::jsonb,
ARRAY['Järnkälla', 'Smoothies', 'Hälsosam kost']),

('Vitlök', 'vitlok', 'V',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Lökväxt',
'Mörkt, torrt och svalt',
'3-6 månader',
'6 månader',
true,
'Hacka innan frysning',
ARRAY['juli', 'augusti'],
ARRAY[]::text[],
149, 6.4, 0.5, 33.1, 2.1, 0.017,
'{"C": "31mg", "B6": "1.2mg", "Mangan": "1.7mg"}'::jsonb,
'{"fosfor": "153mg", "kalium": "401mg", "selen": "14μg"}'::jsonb,
'Kraftfull aromgrönsak med antibakteriella egenskaper.',
ARRAY['Marinader', 'Såser', 'Stekt', 'Rå i dressing'],
'[{"name": "Schalottenlök", "reason": "Mildare aromgrönsak"}, {"name": "Ingefära", "reason": "Annan stark smaksättare"}]'::jsonb,
'Vitlök - Hälsofördelar och Användning | Livsmedel A-Ö',
'Komplett guide om vitlök: näringsvärde, hälsofördelar, förvaring och kulinarisk användning.',
'[{"question": "Vilka hälsofördelar har vitlök?", "answer": "Allicin i vitlök kan ha antibakteriella och hjärt-kärlskyddande effekter."}, {"question": "Hur får man bort vitlöksandedräkt?", "answer": "Tugga persilja, drick mjölk eller ät äpple efter vitlök."}]'::jsonb,
ARRAY['Medelhavsmat', 'Hälsosam krydda', 'Antibakteriellt']),

('Avokado', 'avokado', 'A',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Fruktgrönsak',
'Rumstemperatur tills mogen',
'2-3 dagar mogen',
'3-7 dagar',
true,
'Mosa innan frysning',
ARRAY[]::text[],
ARRAY[]::text[],
160, 2.0, 14.7, 8.5, 6.7, 0.007,
'{"K": "21μg", "Folat": "20μg", "E": "2.1mg"}'::jsonb,
'{"kalium": "485mg", "magnesium": "29mg", "fiber": "6.7g"}'::jsonb,
'Näringsrik frukt med hälsosamma enfettade fetter.',
ARRAY['Guacamole', 'Sallad', 'Smoothies', 'Toast'],
'[{"name": "Olivolja", "reason": "Liknande hälsosamma fetter"}, {"name": "Nötter", "reason": "Andra källor till bra fetter"}]'::jsonb,
'Avokado - Hälsosamma Fetter och Näring | Livsmedel A-Ö',
'Komplett guide om avokado: näringsvärde, hälsosamma fetter, mognad och användning.',
'[{"question": "Hur vet man att avokado är mogen?", "answer": "Ska ge lätt efter tryck men inte vara för mjuk, färg spelar mindre roll."}, {"question": "Varför blir avokado brun?", "answer": "Oxidation när frukten exponeras för luft - citronjuice förhindrar brunfärgning."}]'::jsonb,
ARRAY['Hälsosamma fetter', 'Vegetarisk kost', 'Trendig mat']),

('Zucchini', 'zucchini', 'Z',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Fruktgrönsak',
'Kylskåp 4-8°C',
'1 vecka',
'1-2 veckor',
true,
'Skär i skivor innan frysning',
ARRAY['juni', 'juli', 'augusti', 'september'],
ARRAY[]::text[],
17, 1.2, 0.3, 3.1, 1.0, 0.008,
'{"C": "18mg", "Folat": "24μg", "K": "4.3μg"}'::jsonb,
'{"kalium": "261mg", "mangan": "0.2mg"}'::jsonb,
'Mild fruktgrönsak med lågt kaloriinnehåll, mångsidig.',
ARRAY['Spiraler som pasta', 'Gratäng', 'Bröd', 'Grillad'],
'[{"name": "Gurka", "reason": "Liknande mild smak"}, {"name": "Squash", "reason": "Samma familj"}]'::jsonb,
'Zucchini - Låg Kalori Alternativ | Livsmedel A-Ö',
'Allt om zucchini: näringsvärde, kreativa tillagningssätt, zucchininudlar och bakning.',
'[{"question": "Kan man äta zucchini rå?", "answer": "Ja, perfekt rå i sallader eller som spiraler istället för pasta."}, {"question": "Varför blir zucchini vattnig?", "answer": "Hög vattenhalten - salta och låt rinna av före tillagning för fastare textur."}]'::jsonb,
ARRAY['Låg kolhydrat', 'Pasta alternativ', 'Sommarmat']),

('Rucola', 'rucola', 'R',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Bladgrönsak',
'Kylskåp 2-4°C',
'3-5 dagar',
'1 vecka',
false,
'Rekommenderas ej att frysa',
ARRAY['april', 'maj', 'juni', 'september', 'oktober'],
ARRAY[]::text[],
25, 2.6, 0.7, 3.7, 1.6, 0.027,
'{"K": "109μg", "Folat": "97μg", "C": "15mg"}'::jsonb,
'{"kalcium": "160mg", "järn": "1.5mg", "kalium": "369mg"}'::jsonb,
'Pepprig bladgrönsak med distinkt smak, populär i Italien.',
ARRAY['Sallad', 'Pizza topping', 'Pesto', 'Pasta'],
'[{"name": "Spenat", "reason": "Mildare bladgrönsak"}, {"name": "Vattenkrasse", "reason": "Liknande pepprig smak"}]'::jsonb,
'Rucola - Pepprig Smak och Näring | Livsmedel A-Ö',
'Komplett guide om rucola: näringsvärde, pepprig smak, odling och användning i italiensk mat.',
'[{"question": "Varför är rucola så pepprig?", "answer": "Innehåller senapsoljeglykoside som ger den karakteristiska skarpa smaken."}, {"question": "Kan man koka rucola?", "answer": "Ja, men blir mild - tillsätt i slutet av tillagningen för att behålla lite sting."}]'::jsonb,
ARRAY['Italiensk mat', 'Gourmet sallader', 'Pizza']);

-- Insert Frukt & Bär (6 foods)
INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

('Banan', 'banan', 'B',
(SELECT id FROM public.food_categories WHERE slug = 'frukt-bar'),
'Tropisk frukt',
'Rumstemperatur',
'2-7 dagar',
'3-7 dagar',
true,
'Skala och skär innan frysning',
ARRAY[]::text[],
ARRAY[]::text[],
89, 1.1, 0.3, 23.0, 2.6, 0.001,
'{"C": "8.7mg", "B6": "0.4mg", "Folat": "20μg"}'::jsonb,
'{"kalium": "358mg", "magnesium": "27mg", "mangan": "0.3mg"}'::jsonb,
'Näringsrik tropisk frukt rik på kalium och naturligt socker.',
ARRAY['Smoothies', 'Bakad i bröd', 'Mellanmål', 'Müsli'],
'[{"name": "Plantain", "reason": "Liknande frukt för matlagning"}, {"name": "Dadlar", "reason": "Annan sött frukt med kalium"}]'::jsonb,
'Banan - Kalium och Naturlig Energi | Livsmedel A-Ö',
'Komplett guide om bananer: näringsvärde, kalium fördelar, mognadsstadier och användning.',
'[{"question": "Varför är bananer bra efter träning?", "answer": "Snabba kolhydrater och kalium hjälper återställa energi och vätske-elektrolytbalans."}, {"question": "Kan man äta bruna bananer?", "answer": "Ja, de är bara mörkare och sötare - perfekta för smoothies och bakning."}]'::jsonb,
ARRAY['Träningsmat', 'Frukost smoothies', 'Barnmat']),

('Äpple', 'apple', 'Ä',
(SELECT id FROM public.food_categories WHERE slug = 'frukt-bar'),
'Kärnfrukt',
'Kylskåp 0-4°C',
'1-2 månader',
'1-3 månader',
true,
'Skär i bitar innan frysning',
ARRAY['augusti', 'september', 'oktober', 'november'],
ARRAY[]::text[],
52, 0.3, 0.2, 14.0, 2.4, 0.001,
'{"C": "4.6mg", "K": "2.2μg"}'::jsonb,
'{"kalium": "107mg", "fosfor": "11mg", "pektin": "hög halt"}'::jsonb,
'Sveriges mest populära frukt, rik på fiber och antioxidanter.',
ARRAY['Rå som mellanmål', 'Paj', 'Mos', 'Juice'],
'[{"name": "Päron", "reason": "Liknande kärnfrukt"}, {"name": "Kvitten", "reason": "Bra för kokning och sylt"}]'::jsonb,
'Äpple - Fiber och Antioxidanter | Livsmedel A-Ö',
'Allt om äpplen: näringsvärde, svenska sorter, förvaring och traditionell användning.',
'[{"question": "Vilka äppelsorter är bäst för bakning?", "answer": "Fasta sorter som Granny Smith och Ingrid Marie behåller formen bäst."}, {"question": "Varför säger man \"ett äpple om dagen\"?", "answer": "Äpplen innehåller fiber, antioxidanter och pektin som kan stödja hälsan."}]'::jsonb,
ARRAY['Hälsosam frukt', 'Svensk tradition', 'Barnmat']),

('Citron', 'citron', 'C',
(SELECT id FROM public.food_categories WHERE slug = 'frukt-bar'),
'Citrusfrukt',
'Rumstemperatur 1 vecka, kylskåp 1 månad',
'1 månad',
'1 månad',
true,
'Pressa saft innan frysning',
ARRAY[]::text[],
ARRAY[]::text[],
29, 1.1, 0.3, 9.0, 2.8, 0.002,
'{"C": "53mg", "Folat": "6μg", "Citroflavonoider": "högt"}'::jsonb,
'{"kalium": "138mg", "citrat": "hög halt"}'::jsonb,
'Sur citrusfrukt extremt rik på vitamin C och citrat.',
ARRAY['Dressing', 'Marinader', 'Bakning', 'Dryck'],
'[{"name": "Lime", "reason": "Liknande sur smak"}, {"name": "Vinäger", "reason": "Annan syrlig smaksättare"}]'::jsonb,
'Citron - Vitamin C Bomb | Livsmedel A-Ö',
'Komplett guide om citron: näringsvärde, vitamin C fördelar, användning i matlagning och hälsa.',
'[{"question": "Hjälper citron med viktminskning?", "answer": "Pektin i citron kan ge mättnadskänsla, men ingen magisk viktminskning."}, {"question": "Kan man äta citronskal?", "answer": "Ja, skalet innehåller mycket eteriska oljor - välj ekologiska citroner."}]'::jsonb,
ARRAY['Vitamin C källa', 'Matlagning', 'Detox drycker']),

('Apelsin', 'apelsin', 'A',
(SELECT id FROM public.food_categories WHERE slug = 'frukt-bar'),
'Citrusfrukt',
'Rumstemperatur 1 vecka, kylskåp 2 veckor',
'2 veckor',
'2-3 veckor',
true,
'Skala och dela innan frysning',
ARRAY[]::text[],
ARRAY[]::text[],
47, 0.9, 0.1, 12.0, 2.4, 0.000,
'{"C": "53mg", "Folat": "40μg", "A": "11μg"}'::jsonb,
'{"kalium": "181mg", "kalcium": "40mg", "hesperidin": "högt"}'::jsonb,
'Söt citrusfrukt rik på vitamin C och folsyra.',
ARRAY['Frukost juice', 'Mellanmål', 'Sallad', 'Marmelad'],
'[{"name": "Mandarin", "reason": "Sötare och lättare att skala"}, {"name": "Grapefrukt", "reason": "Större citrusfrukt"}]'::jsonb,
'Apelsin - Vitamin C och Immun | Livsmedel A-Ö',
'Allt om apelsiner: näringsvärde, immunförstärkning, juice vs hel frukt och olika sorter.',
'[{"question": "Är färskpressad juice lika bra som hel frukt?", "answer": "Hel frukt ger mer fiber och mättnad, men båda ger vitamin C."}, {"question": "Vilken sort apelsin är sötast?", "answer": "Navelapelsiner och blodapelsiner är ofta sötare än vanliga apelsiner."}]'::jsonb,
ARRAY['Vitamin C källa', 'Frukostjuice', 'Immunförsvar']),

('Jordgubbar', 'jordgubbar', 'J',
(SELECT id FROM public.food_categories WHERE slug = 'frukt-bar'),
'Bär',
'Kylskåp 2-4°C',
'2-3 dagar',
'3-5 dagar',
true,
'Rensa och frys hela',
ARRAY['juni', 'juli'],
ARRAY[]::text[],
32, 0.7, 0.3, 7.7, 2.0, 0.001,
'{"C": "59mg", "Folat": "24μg", "K": "2.2μg"}'::jsonb,
'{"kalium": "153mg", "mangan": "0.4mg", "antocyaniner": "högt"}'::jsonb,
'Svenska sommarbär med extremt hög vitamin C halt.',
ARRAY['Dessert', 'Sylt', 'Smoothies', 'Tårtor'],
'[{"name": "Hallon", "reason": "Liknande bär"}, {"name": "Blåbär", "reason": "Andra antioxidantrika bär"}]'::jsonb,
'Jordgubbar - Svensk Sommar och Vitamin C | Livsmedel A-Ö',
'Komplett guide om jordgubbar: näringsvärde, svensk säsong, plockning och bevarande.',
'[{"question": "När är jordgubbssäsong i Sverige?", "answer": "Juni-juli är högsäsong för svenska jordgubbar, med klimatet varierar säsongen."}, {"question": "Ska man tvätta jordgubbar innan förvaring?", "answer": "Nej, tvätta först när du ska äta dem för att undvika fukt och mögel."}]'::jsonb,
ARRAY['Svensk sommar', 'Midsommar', 'Vitamin C källa']),

('Blåbär', 'blaber', 'B',
(SELECT id FROM public.food_categories WHERE slug = 'frukt-bar'),
'Vilda bär',
'Kylskåp 0-4°C',
'1 vecka',
'1-2 veckor',
true,
'Frys direkt utan tvätt',
ARRAY['juli', 'augusti'],
ARRAY[]::text[],
57, 0.7, 0.3, 14.5, 2.4, 0.001,
'{"C": "9.7mg", "K": "19μg", "E": "0.6mg"}'::jsonb,
'{"mangan": "0.3mg", "antocyaniner": "extremt högt", "antioxidanter": "mycket högt"}'::jsonb,
'Vilda svenska bär med extremt höga antioxidantnivåer.',
ARRAY['Pannkakor', 'Müsli', 'Smoothies', 'Paj'],
'[{"name": "Lingon", "reason": "Andra svenska vilda bär"}, {"name": "Açaibär", "reason": "Liknande antioxidantnivåer"}]'::jsonb,
'Blåbär - Antioxidanter och Svensk Natur | Livsmedel A-Ö',
'Komplett guide om blåbär: antioxidanter, svensk skogstradition, plockning och hälsofördelar.',
'[{"question": "Varför är blåbär så hälsosamma?", "answer": "Extremt höga nivåer av antocyaniner som kan skydda hjärna, hjärta och syn."}, {"question": "Skillnad mellan skogs- och trädgårdsblåbär?", "answer": "Skogsblåbär har mörkare kött och mer intensiv smak och näringsinnehåll."}]'::jsonb,
ARRAY['Antioxidanter', 'Svensk skogstradition', 'Hälsosam kost']);

-- Insert Kryddor & Örter (4 foods)
INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

('Basilika', 'basilika', 'B',
(SELECT id FROM public.food_categories WHERE slug = 'kryddor-orter'),
'Färsk ört',
'Kylskåp i vatten som blommor',
'1 vecka',
'3-5 dagar',
true,
'Frys i olivolja eller som pesto',
ARRAY['juni', 'juli', 'augusti', 'september'],
ARRAY[]::text[],
22, 3.2, 0.6, 2.6, 1.6, 0.004,
'{"K": "415μg", "A": "264μg", "C": "18mg"}'::jsonb,
'{"kalium": "295mg", "kalcium": "177mg", "järn": "3.2mg"}'::jsonb,
'Aromatisk italiensk ört med sött, kryddigt arom.',
ARRAY['Pesto', 'Pasta', 'Pizza', 'Caprese'],
'[{"name": "Oregano", "reason": "Annan italiensk ört"}, {"name": "Mynta", "reason": "Liknande fräsch smak"}]'::jsonb,
'Basilika - Italiensk Ört och Pesto | Livsmedel A-Ö',
'Komplett guide om basilika: odling, förvaring, pesto recept och användning i italiensk matlagning.',
'[{"question": "Hur håller basilika längst?", "answer": "Som blommor i vatten i kylskåp, eller frys in som pesto med olivolja."}, {"question": "Kan man äta basilika blommor?", "answer": "Ja, de är ätbara och har en mild basiliksmak - fin som garnering."}]'::jsonb,
ARRAY['Italiensk mat', 'Pesto', 'Pizza']),

('Oregano', 'oregano', 'O',
(SELECT id FROM public.food_categories WHERE slug = 'kryddor-orter'),
'Torkad ört',
'Torrt och mörkt',
'2 år',
'2-3 år',
false,
'Redan torkad',
ARRAY['juli', 'augusti'],
ARRAY[]::text[],
265, 9.0, 4.3, 69.0, 42.5, 0.025,
'{"K": "622μg", "E": "18.3mg", "A": "85μg"}'::jsonb,
'{"kalium": "1260mg", "kalcium": "1597mg", "järn": "36.8mg"}'::jsonb,
'Klassisk medelhavsört med starkt, varmt arom.',
ARRAY['Pizza', 'Pasta såser', 'Grekisk mat', 'Marinader'],
'[{"name": "Mejram", "reason": "Liknande medelhavsört"}, {"name": "Timjan", "reason": "Annan stark ört"}]'::jsonb,
'Oregano - Medelhavsört och Pizza | Livsmedel A-Ö',
'Allt om oregano: användning i medelhavsmat, pizza, skillnad mellan färsk och torkad oregano.',
'[{"question": "Skillnad mellan oregano och mejram?", "answer": "Oregano är starkare och mer bitter, mejram är mildare och sötare."}, {"question": "När tillsätter man oregano?", "answer": "Torkad oregano tål värme - tillsätt tidigt. Färsk oregano i slutet av tillagningen."}]'::jsonb,
ARRAY['Pizza', 'Italiensk mat', 'Grekisk mat']),

('Timjan', 'timjan', 'T',
(SELECT id FROM public.food_categories WHERE slug = 'kryddor-orter'),
'Färsk/torkad ört',
'Kylskåp färsk, mörkt torr',
'1 vecka färsk, 2 år torkad',
'3-5 dagar färsk',
true,
'Frys färska kvistar',
ARRAY['maj', 'juni', 'juli', 'augusti'],
ARRAY[]::text[],
101, 5.6, 1.7, 24.0, 14.0, 0.009,
'{"C": "50mg", "A": "190μg", "K": "275μg"}'::jsonb,
'{"järn": "17.5mg", "mangan": "1.7mg", "kalium": "609mg"}'::jsonb,
'Nordisk ört med subtil, jordnära smak.',
ARRAY['Köttgryta', 'Rosmarin kyckling', 'Soppa', 'Fisk'],
'[{"name": "Rosmarin", "reason": "Annan stark ört för kött"}, {"name": "Salvia", "reason": "Liknande jordnära smak"}]'::jsonb,
'Timjan - Nordisk Ört och Köttgryta | Livsmedel A-Ö',
'Komplett guide om timjan: användning i nordisk matlagning, förvaring och kombinationer med andra kryddor.',
'[{"question": "Hur plockar man timjan från kvistar?", "answer": "Dra fingrarna mot bladens växtriktning längs kvisten för att lätt lossa bladen."}, {"question": "Passar timjan till fisk?", "answer": "Ja, perfekt till vit fisk och i fiskfärser - ger en subtil, ren smak."}]'::jsonb,
ARRAY['Köttgryta', 'Nordisk mat', 'Köttkrydda']),

('Havssalt', 'havssalt', 'H',
(SELECT id FROM public.food_categories WHERE slug = 'kryddor-orter'),
'Mineralsalt',
'Torrt och mörkt',
'Obegränsat',
'Obegränsat',
false,
'Ej aktuellt',
ARRAY[]::text[],
ARRAY[]::text[],
0, 0.0, 0.0, 0.0, 0.0, 38758,
'{}'::jsonb,
'{"natrium": "38758mg", "klorid": "59900mg", "spårmineraler": "varierande"}'::jsonb,
'Naturligt salt från havsvatten med spårmineraler.',
ARRAY['All matlagning', 'Bakning', 'Konservering', 'Finishing salt'],
'[{"name": "Himalayasalt", "reason": "Annat mineralsalt"}, {"name": "Bordssalt", "reason": "Finare struktur"}]'::jsonb,
'Havssalt - Naturligt Salt och Mineraler | Livsmedel A-Ö',
'Allt om havssalt: tillverkning, mineraler, olika typer och användning i matlagning.',
'[{"question": "Är havssalt nyttigare än vanligt salt?", "answer": "Minimala skillnader i näring - huvudvärdet är smak och textur från spårmineraler."}, {"question": "Vilket salt passar bäst till vad?", "answer": "Fint salt för bakning, grovt havssalt som finishing salt för textur och smak."}]'::jsonb,
ARRAY['Grundkrydda', 'All matlagning', 'Bakning']);

-- Insert Bakning & Torrvaror (2 foods)
INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

('Spaghetti', 'spaghetti', 'S',
(SELECT id FROM public.food_categories WHERE slug = 'spannmal-baljvaxter'),
'Pasta',
'Torrt och mörkt',
'Obegränsat torr',
'2-3 år',
true,
'Koka innan frysning',
ARRAY[]::text[],
ARRAY['gluten'],
371, 13.0, 1.5, 74.0, 3.2, 0.006,
'{"B1": "0.9mg", "Folat": "18μg", "Niacin": "5.9mg"}'::jsonb,
'{"fosfor": "189mg", "kalium": "223mg", "selen": "26μg"}'::jsonb,
'Klassisk långsträckt italiensk pasta av durumvete.',
ARRAY['Carbonara', 'Bolognese', 'Aglio e olio', 'Köttbullar'],
'[{"name": "Linguine", "reason": "Liknande lång pasta"}, {"name": "Penne", "reason": "Kort pasta alternativ"}]'::jsonb,
'Spaghetti - Italiensk Pasta Klassiker | Livsmedel A-Ö',
'Komplett guide om spaghetti: tillagning, italienska recept, olika typer och perfekt al dente.',
'[{"question": "Hur kokar man spaghetti al dente?", "answer": "Koka 1-2 minuter kortare tid än förpackningen anger och testa genom att bita."}, {"question": "Ska man hälla olja i pastavattnet?", "answer": "Nej, det hindrar såsen från att fästa - salta vattnet istället och rör om."}]'::jsonb,
ARRAY['Italiensk mat', 'Pasta carbonara', 'Vardagsmiddag']),

('Jasminris', 'jasminris', 'J',
(SELECT id FROM public.food_categories WHERE slug = 'spannmal-baljvaxter'),
'Långkornigt ris',
'Torrt och mörkt',
'Obegränsat',
'2-3 år',
true,
'Koka innan frysning',
ARRAY[]::text[],
ARRAY[]::text[],
365, 7.1, 0.7, 80.0, 0.4, 0.005,
'{"B1": "0.4mg", "B3": "1.5mg", "Folat": "8μg"}'::jsonb,
'{"fosfor": "115mg", "kalium": "115mg", "mangan": "1.1mg"}'::jsonb,
'Aromatiskt långkornigt ris från Thailand med blommig doft.',
ARRAY['Thailändsk mat', 'Curry', 'Stir-fry', 'Sushi'],
'[{"name": "Basmatiiris", "reason": "Annat aromatiskt långkorns ris"}, {"name": "Vanligt ris", "reason": "Mindre aromatiskt alternativ"}]'::jsonb,
'Jasminris - Aromatiskt Thailändskt Ris | Livsmedel A-Ö',
'Allt om jasminris: ursprung från Thailand, tillagning, aromatiska egenskaper och användning i asiatisk mat.',
'[{"question": "Vad ger jasminris sin doft?", "answer": "Naturliga föreningar som 2-acetyl-1-pyrolin ger den karakteristiska blommiga doften."}, {"question": "Ska man skölja jasminris?", "answer": "Ja, skölja tills vattnet blir klart för att få luftigt ris utan för mycket stärkelse."}]'::jsonb,
ARRAY['Thailändsk mat', 'Asiatisk mat', 'Curry']);

-- Set up cross-references between related foods (updating existing ones with new food references)
UPDATE public.foods SET related_foods = 
ARRAY(SELECT id FROM public.foods WHERE slug IN ('mozzarella', 'basilika', 'tomat') LIMIT 3)
WHERE slug = 'parmigiano-reggiano';

UPDATE public.foods SET related_foods = 
ARRAY(SELECT id FROM public.foods WHERE slug IN ('parmigiano-reggiano', 'basilika', 'tomat') LIMIT 3)
WHERE slug = 'mozzarella';

UPDATE public.foods SET related_foods = 
ARRAY(SELECT id FROM public.foods WHERE slug IN ('spaghetti', 'parmigiano-reggiano', 'basilika') LIMIT 3)
WHERE slug IN ('tomat', 'vitlok');

UPDATE public.foods SET related_foods = 
ARRAY(SELECT id FROM public.foods WHERE slug IN ('tomat', 'mozzarella', 'oregano') LIMIT 3)
WHERE slug = 'basilika';

UPDATE public.foods SET related_foods = 
ARRAY(SELECT id FROM public.foods WHERE slug IN ('tomat', 'spaghetti', 'vitlok') LIMIT 3)
WHERE slug IN ('oregano', 'basilika');