-- Complete the final foods and update all timestamps
UPDATE foods SET long_description = 'Konserverad tonfisk är en praktisk och näringsrik proteinbölla som är rik på omega-3-fettsyror, protein och selen. 100 gram tonfisk innehåller cirka 25 gram protein och är en bra källa till vitamin D och B12. Tonfisk på vatten har lägre kaloriinnehåll än tonfisk i olja. Välj tonfisk från hållbara källor när det är möjligt och begränsa konsumtionen på grund av potentiell kvicksilverexponering. Tonfisk är perfekt i sallader, mackor, pasta eller som snabb proteinbölla. Skölj konserverad tonfisk för att minska salthalten.' WHERE slug = 'tonfisk-konserverad';

UPDATE foods SET long_description = 'Torsk är en mager vitfisk som är en utmärkt källa till protein (cirka 18 gram per 100 gram) med mycket låg fetthalt. Den är rik på selen, vitamin B12 och fosfor. Torsk har mild smak och fast konsistens som passar många tillagningsmetoder. Färsk torsk ska lukta hav och ha fast, vit kött. Torsk är populär i nordisk matkultur och är bas för rätter som fish and chips. Tillaga försiktigt för att undvika att köttet blir torrt. Perfekt grillad, stekt, bakad eller kokt.' WHERE slug = 'torsk';

UPDATE foods SET long_description = 'Vitlök är en aromatisk lökvät som innehåller kraftfulla svavelhaltiga föreningar, särskilt allicin, som har antimikrobiella och anti-inflammatoriska egenskaper. Vitlök kan hjälpa till att sänka blodtryck och kolesterol enligt flera studier. Den innehåller också mangan, vitamin B6 och vitamin C. Vitlök får sina hälsoegenskaper när den krossas eller hackas och allicin frigörs. Låt krossad vitlök vila några minuter före tillagning för maximal effekt. Förvara i torr, mörk plats med god luftcirkulation.' WHERE slug = 'vitlok';

UPDATE foods SET long_description = 'Naturell yoghurt är en fermenterad mjölkprodukt som innehåller levande probiotiska bakterier som kan gynna tarmhälsan och immunförsvaret. Den är rik på protein, kalcium och riboflavin. Grekisk yoghurt har högre proteininnehåll än vanlig yoghurt. Välj yoghurt utan tillsatt socker för bästa hälsoeffekt. Probiotika i yoghurt kan hjälpa till att förbättra laktostolerans. Yoghurt är mångsidig och kan ätas som den är, i smoothies, som tillbehör eller i marinader för kött.' WHERE slug = 'yoghurt-naturell';

UPDATE foods SET long_description = 'Zucchini är en mångsidig sommarsquash som är mycket kalorifattig (endast 17 kalorier per 100 gram) men rik på vatten och fiber. Den innehåller vitamin C, mangan och antioxidanter som lutein och zeaxantin. Zucchini har mild smak och kan användas på otaliga sätt - spiraliserad som "zoodles", grillad, bakad eller i bakverk som zucchinibröd. Skalet är ätbart och innehåller många näringsämnen. Välj fasta zucchini utan mjuka fläckar. Förvara i kylskåp och använd inom en vecka.' WHERE slug = 'zucchini';

-- Update timestamps for all foods with new descriptions
UPDATE foods SET updated_at = NOW() WHERE long_description IS NOT NULL AND long_description != '';