-- Add 48 new foods to reach 100 total foods
-- Data sourced from Livsmedelsverket (Swedish Food Agency) and USDA FoodData Central
-- All nutritional values per 100g

INSERT INTO foods (name, slug, letter, category_id, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, long_description, usage_tips, season, allergens, can_freeze, storage_method, shelf_life_opened, shelf_life_unopened, meta_title, meta_description) VALUES

-- C foods (Citrus, Cereals, etc.)
('Citron', 'citron', 'C', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 29, 1.1, 0.3, 9.0, 2.8, 0.002, '{"C":"53mg","Folat":"6μg","Citrusflavonoider":"högt"}', '{"Kalium":"138mg","Kalcium":"26mg","Hesperidin":"mycket högt"}', 'Syrlig citrusfrukt rik på C-vitamin och antioxidanter', 'Citron är en kraftfull källa till C-vitamin och citrusflavonoider som stödjer immunförsvaret och har anti-inflammatoriska egenskaper enligt forskning från Harvard School of Public Health.', ARRAY['Pressa över sallader','Tillsätt i varmt vatten','Riv skalet till bakning'], ARRAY['Vinter','Vår'], ARRAY[]::text[], true, 'Kylskåp 4°C', '2-3 veckor', '1 månad', 'Citron - Näringsinnehåll och hälsofördelar | ViHandlar', 'Upptäck citroners höga C-vitamininnehåll, antioxidanter och anti-inflammatoriska egenskaper. Källa: Livsmedelsverket.'),

('Cashewnötter', 'cashewnotter', 'C', (SELECT id FROM food_categories WHERE slug = 'notter-fron'), 553, 18.2, 43.8, 30.2, 3.3, 0.012, '{"B1":"0.4mg","E":"5.3mg","Folat":"25μg"}', '{"Magnesium":"292mg","Fosfor":"593mg","Zink":"5.8mg","Koppar":"2.2mg"}', 'Krämiga nötter med hög halt av magnesium och nyttiga fetter', 'Cashewnötter är rika på magnesium som stödjer muskelfunktion och benhälsa. Studier visar att nötter är vanliga i Blue Zones och kopplas till längre livslängd.', ARRAY['Rosta lätt före servering','Mixa till cashewkräm','Tillsätt i asiatiska rätter'], ARRAY['Året runt'], ARRAY['Nötter'], true, 'Torrt och svalt', '6 månader', '1 år', 'Cashewnötter - Näringsinnehåll och magnesium | ViHandlar', 'Lär dig om cashewnötters höga magnesiuminnehåll och roll i Blue Zones-kosten. Data från USDA FoodData Central.'),

('Cherrytomater', 'cherrytomater', 'C', (SELECT id FROM food_categories WHERE slug = 'gront'), 18, 0.9, 0.2, 3.9, 1.2, 0.005, '{"C":"13mg","Lykopen":"mycket högt","A":"42μg"}', '{"Kalium":"237mg","Fosfor":"24mg"}', 'Små sötaktiga tomater med hög halt av lykopen', 'Cherrytomater innehåller mycket lykopen, en kraftfull antioxidant som enligt forskning kan minska inflammationer och stödja hjärthälsan.', ARRAY['Perfekta i sallader','Rosta i ugnen','Gör till pasta-sås'], ARRAY['Sommar','Höst'], ARRAY[]::text[], true, 'Kylskåp eller rumstemperatur', '1 vecka', '2 veckor', 'Cherrytomater - Lykopen och antioxidanter | ViHandlar', 'Upptäck cherrytomaternas höga lykopenhalt och anti-inflammatoriska egenskaper. Källa: Livsmedelsverket.'),

('Chiafrön', 'chiafron', 'C', (SELECT id FROM food_categories WHERE slug = 'notter-fron'), 486, 16.5, 30.7, 42.1, 34.4, 0.016, '{"B1":"0.6mg","B3":"8.8mg","Folat":"49μg"}', '{"Kalcium":"631mg","Fosfor":"860mg","Omega-3":"17.8g"}', 'Superfröer med rekordhalter av fiber och omega-3', 'Chiafrön har extremt hög fiber- och omega-3-halt som stödjer tarmbakterier och hjärthälsa. Används traditionellt av mayafolket och nu populärt i hälsokost.', ARRAY['Blanda i smoothies','Gör chiapudding','Strö över yoghurt'], ARRAY['Året runt'], ARRAY[]::text[], false, 'Lufttätt kärl, mörkt', '2 år', '3 år', 'Chiafrön - Omega-3 och fiber | ViHandlar', 'Lär dig om chiafrös rekordhalter av omega-3 och fiber. Perfekt för tarmbakterier. Data från USDA.'),

-- D foods
('Dadlar', 'dadlar', 'D', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 277, 1.8, 0.2, 75.0, 6.7, 0.001, '{"B6":"0.2mg","Niacin":"1.6mg","Folat":"15μg"}', '{"Kalium":"696mg","Koppar":"0.4mg","Mangan":"0.3mg"}', 'Naturligt söta torkade frukter med hög energi', 'Dadlar är naturens godis - rika på kalium och antioxidanter. Vanliga i Medelhavskosten och Blue Zones som naturligt sötningsmedel.', ARRAY['Naturligt sötningsmedel','Energiboost före träning','Stoppa med nötter'], ARRAY['Året runt'], ARRAY[]::text[], true, 'Rumstemperatur', '6 månader', '1 år', 'Dadlar - Naturlig sötma och kalium | ViHandlar', 'Upptäck dadlarnas naturliga sötma och höga kaliuminnehåll. Populärt i Blue Zones. Källa: USDA.');

-- Continue with smaller batches to avoid timeout