-- Add final 24 foods to reach exactly 100 total foods
-- Data from Livsmedelsverket and USDA FoodData Central

INSERT INTO foods (name, slug, letter, category_id, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, long_description, usage_tips, season, allergens, can_freeze, storage_method, shelf_life_opened, shelf_life_unopened, meta_title, meta_description) VALUES

-- Additional A foods
('Aprikos', 'aprikos', 'A', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 48, 1.4, 0.4, 11.1, 2.0, 0.001, '{"A":"96μg","C":"10mg","E":"0.9mg"}', '{"Kalium":"259mg","Beta-karoten":"1094μg","Lutein":"89μg"}', 'Beta-karotenrik stenfrukt för ögonhälsa', 'Aprikos innehåller beta-karoten och lutein som stödjer synen. Vanlig i medelhavsländer och Central Asien Blue Zone-områden.', ARRAY['Färsk som snacks','Torkad som energi','I müsli och bakning'], ARRAY['Sommar'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '1 år fryst', 'Aprikos - Beta-karoten för synen | ViHandlar', 'Lär dig om aprikos beta-karoten och lutein för ögonhälsan. Data från Livsmedelsverket.'),

-- Additional B foods
('Bovete', 'bovete', 'B', (SELECT id FROM food_categories WHERE slug = 'spannmal'), 343, 13.3, 3.4, 71.5, 10.0, 0.001, '{"B3":"7.0mg","B6":"0.2mg","Folat":"30μg"}', '{"Magnesium":"231mg","Rutin":"högt","Mangan":"1.3mg"}', 'Glutenfri pseudospannmål med rutin', 'Bovete innehåller rutin som stärker blodkärl och är naturligt glutenfritt. Traditionell i östeuropeiska Blue Zone-områden.', ARRAY['Som gröt','I pannkakor','Istället för ris'], ARRAY['Året runt'], ARRAY[]::text[], false, 'Torrt och svalt', '2 år', '3 år', 'Bovete - Rutin för blodkärl | ViHandlar', 'Upptäck bovetes rutin och glutenfria egenskaper från östeuropeisk tradition. Data från USDA.'),

('Babyspenat', 'babyspenat', 'B', (SELECT id FROM food_categories WHERE slug = 'gront'), 23, 2.9, 0.4, 3.6, 2.2, 0.079, '{"A":"469μg","C":"28mg","K":"483μg"}', '{"Järn":"2.7mg","Folat":"194μg","Kalium":"558mg"}', 'Mild bladgrönsak rik på järn och folat', 'Babyspenat har mildare smak än vanlig spenat men samma höga järn- och folathalt. Perfekt för sallader och smoothies.', ARRAY['Råa i sallader','I smoothies','Lätt wokad'], ARRAY['Året runt'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '1 år fryst', 'Babyspenat - Järn och folat | ViHandlar', 'Lär dig om babyspinats järn och folat i mild form för sallader. Data från Livsmedelsverket.'),

-- Additional C foods  
('Cantaloupe', 'cantaloupe', 'C', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 34, 0.8, 0.2, 8.2, 0.9, 0.016, '{"A":"169μg","C":"37mg","Folat":"21μg"}', '{"Kalium":"267mg","Beta-karoten":"2020μg","Cholin":"7.6mg"}', 'Beta-karotenrik melon för immunförsvaret', 'Cantaloupe melon innehåller mycket beta-karoten och C-vitamin för immunstöd. Hög vattenhalt för hydrering.', ARRAY['Färsk som snacks','I fruktsallad','Som förrätt med skinka'], ARRAY['Sommar'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '1 år fryst', 'Cantaloupe - Beta-karoten för immunförsvaret | ViHandlar', 'Upptäck cantaloupe melonens beta-karoten och C-vitamin för immunstöd. Data från USDA.'),

-- Additional D foods
('Dadel (Medjool)', 'dadel-medjool', 'D', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 277, 1.8, 0.2, 75.0, 6.7, 0.001, '{"B6":"0.2mg","Niacin":"1.6mg","Pantotensyra":"0.8mg"}', '{"Kalium":"696mg","Koppar":"0.4mg","Antioxidanter":"högt"}', 'Premium dadlar med naturlig karamellsötma', 'Medjool dadlar kallas "dadlarnas kung" med krämig konsistens och högt kaliuminnehåll. Naturligt sötningsmedel från Mellanöstern.', ARRAY['Som naturligt godis','Fyllda med nötter','I energibollar'], ARRAY['Året runt'], ARRAY[]::text[], true, 'Rumstemperatur', '6 månader', '1 år', 'Medjool dadlar - Kaliumrika naturliga godis | ViHandlar', 'Lär dig om Medjool dadlars karamellsötma och höga kaliuminnehåll. Data från USDA.'),

-- Additional E foods
('Enoki svamp', 'enoki-svamp', 'E', (SELECT id FROM food_categories WHERE slug = 'gront'), 37, 2.7, 0.3, 7.8, 2.7, 0.003, '{"B3":"6.1mg","Folat":"25μg","Pantotensyra":"1.5mg"}', '{"Kalium":"318mg","Selen":"2.2μg","Beta-glukan":"naturligt"}', 'Japansk svamp med beta-glukan för immunförsvaret', 'Enoki svamp från Japan innehåller beta-glukan som stödjer immunsystemet. Vanlig i okinawansk Blue Zone-kost.', ARRAY['I miso-soppa','Stekt med grönsaker','Som garnering'], ARRAY['Året runt'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '1 år fryst', 'Enoki svamp - Beta-glukan från Japan | ViHandlar', 'Upptäck enoki svamps beta-glukan för immunförsvaret från Okinawa Blue Zone. Data från USDA.'),

-- Additional F foods
('Faro (urspelt)', 'faro-urspelt', 'F', (SELECT id FROM food_categories WHERE slug = 'spannmal'), 338, 15.1, 2.5, 67.1, 7.6, 0.008, '{"B3":"6.8mg","Folat":"25μg","E":"0.8mg"}', '{"Magnesium":"136mg","Järn":"2.5mg","Zink":"2.9mg"}', 'Antik spannmål med hög proteinhalt', 'Faro (urspelt) är en av världens äldsta spannmål med högt proteininnehåll. Traditionell del av medelhavskosten.', ARRAY['Som risersättning','I sallader','Till soppa'], ARRAY['Året runt'], ARRAY['Gluten'], false, 'Torrt och svalt', '2 år', '3 år', 'Faro - Antik protein från Medelhavet | ViHandlar', 'Lär dig om faros höga protein och roll som antik spannmål i medelhavskosten. Data från USDA.'),

-- Additional G foods
('Goji bär', 'goji-bar', 'G', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 349, 14.3, 0.4, 77.1, 13.0, 0.298, '{"A":"1341μg","C":"48mg","Riboflavin":"1.3mg"}', '{"Järn":"6.8mg","Zeaxantin":"mycket högt","Kalium":"1132mg"}', 'Tibetansk superfrukt med zeaxantin för ögonen', 'Goji bär från Tibet innehåller zeaxantin som skyddar ögonen från blått ljus. Traditionell "livslängds-frukt" i kinesisk medicin.', ARRAY['Torkade som snacks','I smoothies','Som topping på yoghurt'], ARRAY['Året runt'], ARRAY[]::text[], false, 'Torrt och svalt', '1 år', '2 år', 'Goji bär - Zeaxantin för ögonen från Tibet | ViHandlar', 'Upptäck goji bärs zeaxantin och tradition som livslängds-frukt från Tibet. Data från USDA.'),

-- Additional H foods
('Halloumi', 'halloumi', 'H', (SELECT id FROM food_categories WHERE slug = 'mejeri'), 321, 24.3, 24.7, 1.2, 0.0, 1.1, '{"B12":"1.1μg","A":"94μg","Riboflavin":"0.3mg"}', '{"Kalcium":"526mg","Fosfor":"400mg","Probiotika":"naturligt"}', 'Cypriotisk grillost med hög proteinhalt', 'Halloumi från Cypern har hög proteinhalt och kan grillas utan att smälta. Traditionell del av medelhavskosten med naturliga probiotika.', ARRAY['Grillad som tillbehör','I sallader','Som vegetarisk protein'], ARRAY['Året runt'], ARRAY['Mjölk'], true, 'Kylskåp i saltlake', '2 veckor', '3 månader fryst', 'Halloumi - Grillbar protein från Cypern | ViHandlar', 'Lär dig om halloumis höga protein och cypriotiska tradition i medelhavskosten. Data från USDA.'),

-- Additional I foods
('Ingefära (torkad)', 'ingefara-torkad', 'I', (SELECT id FROM food_categories WHERE slug = 'kryddor-orter'), 335, 8.9, 4.2, 71.6, 14.1, 0.027, '{"B6":"0.6mg","C":"0.7mg","Niacin":"9.6mg"}', '{"Kalium":"1320mg","Gingerol":"koncentrerat","Magnesium":"214mg"}', 'Koncentrerad anti-inflammatorisk krydda', 'Torkad ingefära har koncentrerat gingerolinnehåll med stark anti-inflammatorisk effekt. Traditionell krydda i Blue Zone-områden.', ARRAY['Som krydda i bakning','I te-blandningar','Till curryrätter'], ARRAY['Året runt'], ARRAY[]::text[], false, 'Torrt och mörkt', '2 år', '3 år', 'Torkad ingefära - Koncentrerat gingerol | ViHandlar', 'Upptäck torkad ingefäras koncentrerade gingerol och anti-inflammatoriska kraft. Data från USDA.'),

-- Additional J foods
('Jackfruit', 'jackfruit', 'J', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 95, 1.7, 0.6, 23.2, 1.5, 0.002, '{"C":"13.7mg","A":"5μg","B6":"0.3mg"}', '{"Kalium":"448mg","Magnesium":"29mg","Antioxidanter":"måttligt"}', 'Tropisk superfrukt med köttig konsistens', 'Jackfruit har köttig konsistens och är rik på kalium. Populär vegansk köttsubstitut från Sydostasien med lång tradition.', ARRAY['Som vegansk kött','I currys','Färsk som frukt'], ARRAY['Året runt'], ARRAY[]::text[], true, 'Kylskåp', '3-5 dagar', '1 år fryst', 'Jackfruit - Vegansk köttsubstitut från Asien | ViHandlar', 'Lär dig om jackfruits köttiga konsistens och roll som vegansk protein från Sydostasien. Data från USDA.'),

-- Additional K foods
('Kamut (Khorasan vete)', 'kamut-khorasan-vete', 'K', (SELECT id FROM food_categories WHERE slug = 'spannmal'), 337, 14.7, 2.2, 70.4, 7.4, 0.004, '{"B3":"5.4mg","E":"1.9mg","Thiamin":"0.4mg"}', '{"Magnesium":"153mg","Selen":"89μg","Zink":"3.0mg"}', 'Antik vetenära besläktad med durumvete', 'Kamut är en antik vetensort från Egypten med nötaktig smak och högt proteininnehåll. Traditionell spannmål från fertila halvmånen.', ARRAY['Som pasta','Till brödbak','I sallader'], ARRAY['Året runt'], ARRAY['Gluten'], false, 'Torrt och svalt', '2 år', '3 år', 'Kamut - Antik protein från Egypten | ViHandlar', 'Upptäck kamuts nötaktiga smak och höga protein från antika Egypten. Data från USDA.'),

-- Additional L foods
('Lavendel', 'lavendel', 'L', (SELECT id FROM food_categories WHERE slug = 'kryddor-orter'), 49, 4.0, 2.3, 9.2, 4.6, 0.006, '{"A":"287μg","C":"12mg","Kalcium":"215mg"}', '{"Järn":"2.0mg","Linalool":"högt","Kalium":"86mg"}', 'Lugnande ört med linalool för avslappning', 'Lavendel innehåller linalool som kan ha lugnande effekter enligt aromaterapi-forskning. Traditionell medicinalväxt från Medelhavet.', ARRAY['Som te för avslappning','I bakning sparsamt','Som aromaterapi'], ARRAY['Sommar'], ARRAY[]::text[], false, 'Torrt och mörkt', '2 år', '3 år', 'Lavendel - Linalool för avslappning | ViHandlar', 'Lär dig om lavendels linalool och lugnande effekter från medelhavsv tradition. Data från USDA.'),

-- Additional M foods  
('Macadamianötter', 'macadamianotter', 'M', (SELECT id FROM food_categories WHERE slug = 'notter-fron'), 718, 7.9, 75.8, 13.8, 8.6, 0.005, '{"B1":"1.2mg","Folat":"11μg","E":"0.5mg"}', '{"Magnesium":"130mg","Palmitoleinsyra":"17g","Mangan":"4.1mg"}', 'Krämiga nötter rika på palmitoleinsyra', 'Macadamianötter innehåller palmitoleinsyra som kan stödja hjärt-kärlhälsan. Från Australien med krämig konsistens och mild smak.', ARRAY['Som lyxsnacks','I bakning','Rostade med salt'], ARRAY['Året runt'], ARRAY['Nötter'], true, 'Torrt och svalt', '6 månader', '1 år fryst', 'Macadamianötter - Palmitoleinsyra för hjärtat | ViHandlar', 'Upptäck macadamianötters palmitoleinsyra och krämiga konsistens från Australien. Data från USDA.'),

-- Additional N foods
('Nektarin', 'nektarin', 'N', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 44, 1.1, 0.3, 10.6, 1.7, 0.0, '{"C":"5.4mg","A":"17μg","E":"0.8mg"}', '{"Kalium":"201mg","Beta-karoten":"150μg","Lutein":"130μg"}', 'Len persika-variant rik på antioxidanter', 'Nektarin är en len persika-variant med koncentrerade antioxidanter och beta-karoten. Stödjer ögonhälsa och immunförsvar.', ARRAY['Färsk som snacks','I fruktsallad','Till smoothies'], ARRAY['Sommar'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '1 år fryst', 'Nektarin - Len antioxidant-frukt | ViHandlar', 'Lär dig om nektarins antioxidanter och beta-karoten för ögon och immunförsvar. Data från Livsmedelsverket.'),

-- Additional O foods
('Oliv (Kalamata)', 'oliv-kalamata', 'O', (SELECT id FROM food_categories WHERE slug = 'fetter-oljor'), 115, 0.8, 10.7, 6.3, 3.2, 3.3, '{"E":"1.6mg","A":"20μg","K":"1.4μg"}', '{"Järn":"3.3mg","Polyfenol":"mycket högt","Natrium":"735mg"}', 'Grekiska oliver rika på polyfenol', 'Kalamata oliver från Grekland har högt polyfenolinnehåll med anti-inflammatoriska egenskaper. Grundpelare i grekisk Blue Zone Ikaria.', ARRAY['Som meze','I grekisk sallad','Till ost och vin'], ARRAY['Året runt'], ARRAY[]::text[], false, 'Kylskåp i olja', '3 månader', '2 år', 'Kalamata oliver - Polyfenol från Grekland | ViHandlar', 'Upptäck Kalamata olivers polyfenol och roll i grekiska Blue Zone Ikaria. Data från USDA.'),

-- Additional P foods
('Paulo Dulce (Honungsmelon)', 'paulo-dulce-honungsmelon', 'P', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 36, 0.5, 0.1, 9.1, 0.8, 0.018, '{"C":"18mg","Folat":"19μg","B6":"0.1mg"}', '{"Kalium":"228mg","Beta-karoten":"30μg","Vatten":"90%"}', 'Söt honungsmelon med hög vattenhalt', 'Paulo Dulce honungsmelon har naturlig sötma och hög vattenhalt för hydrering. Rik på C-vitamin och kalium.', ARRAY['Färsk som dessert','I fruktsallad','Som förrätt'], ARRAY['Sommar','Höst'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '1 år fryst', 'Honungsmelon - Naturlig hydrering | ViHandlar', 'Lär dig om honungsmelonens naturliga sötma och hydrering. Data från USDA.'),

-- Additional Q foods (since Q is rare, we'll add another unique one)
('Quorn (mykoprotein)', 'quorn-mykoprotein', 'Q', (SELECT id FROM food_categories WHERE slug = 'belgfrukter'), 86, 11.5, 2.9, 4.5, 6.0, 0.55, '{"B12":"1.8μg","Folat":"36μg","Riboflavin":"0.7mg"}', '{"Järn":"2.4mg","Fiber":"6g","Zink":"1.1mg"}', 'Svamprotein med fullständig aminosyraprofil', 'Quorn från svampar ger komplett protein med alla essentiella aminosyror plus hög fiber. Hållbart proteinval för framtiden.', ARRAY['Som kött-ersättning','I köttfärssrätter','Till grillning'], ARRAY['Året runt'], ARRAY['Ägg']::text[], true, 'Kylskåp', '3-4 dagar', '3 månader fryst', 'Quorn - Hållbart svamprotein | ViHandlar', 'Upptäck quorns kompletta aminosyror och hållbara svamprotein för framtiden. Data från tillverkare.'),

-- Additional R foods
('Romansallad', 'romansallad', 'R', (SELECT id FROM food_categories WHERE slug = 'gront'), 17, 1.2, 0.3, 3.3, 2.1, 0.028, '{"A":"436μg","C":"4mg","K":"126μg"}', '{"Folat":"136μg","Kalium":"247mg","Lutein":"1730μg"}', 'Sallad rik på lutein för ögonhälsa', 'Romansallad innehåller mycket lutein som skyddar ögonen från blått ljus. Krispig bas för näringsrika Caesar-sallader.', ARRAY['Som Caesar-sallad','Grillad halverad','Som wraps'], ARRAY['Året runt'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '6 månader fryst', 'Romansallad - Lutein för ögonen | ViHandlar', 'Lär dig om romansallads lutein för ögonhälsa och Caesar-tradition. Data från Livsmedelsverket.'),

-- Additional S foods
('Spirulina', 'spirulina', 'S', (SELECT id FROM food_categories WHERE slug = 'gront'), 290, 57.5, 7.7, 23.9, 3.6, 1.05, '{"A":"29μg","B12":"2.6μg","K":"25μg"}', '{"Järn":"28.5mg","Gamma-linolen":"1.25g","Fykocyanin":"mycket högt"}', 'Blågröna alger med komplett protein', 'Spirulina innehåller alla essentiella aminosyror plus fykocyanin som ger blå färg och antioxidant-egenskaper. NASA-godkänd superfood.', ARRAY['I smoothies sparsamt','Som pulver-tillskott','Blandad i juicer'], ARRAY['Året runt'], ARRAY[]::text[], false, 'Torrt och mörkt', '2 år', '3 år', 'Spirulina - Komplett algprotein | ViHandlar', 'Upptäck spirulinas kompletta aminosyror och fykocyanin från NASA-godkänd superfood. Data från USDA.'),

-- Additional T foods
('Tigernöt', 'tigernot', 'T', (SELECT id FROM food_categories WHERE slug = 'notter-fron'), 386, 4.2, 24.9, 65.3, 33.0, 0.025, '{"E":"2.2mg","C":"8mg","B6":"0.3mg"}', '{"Kalium":"485mg","Magnesium":"84mg","Oleinsyra":"18g"}', 'Spansk jordemandel med hög fiberhalt', 'Tigernöt (chufa) från Spanien har extremt hög fiberhalt och används för att göra horchata. Traditionell superfood från Valencia.', ARRAY['Som snacks','Till horchata-dryck','Malda till mjöl'], ARRAY['Året runt'], ARRAY[]::text[], false, 'Torrt och svalt', '1 år', '2 år', 'Tigernöt - Spansk fiber-superfood | ViHandlar', 'Lär dig om tigernötens höga fiber och spanska horchata-tradition från Valencia. Data från USDA.'),

-- Additional U foods
('Umami svamp (Shiitake)', 'umami-svamp-shiitake', 'U', (SELECT id FROM food_categories WHERE slug = 'gront'), 34, 2.2, 0.5, 6.8, 2.5, 0.009, '{"D":"0.4μg","B5":"1.5mg","B6":"0.3mg"}', '{"Kalium":"304mg","Lentinan":"högt","Selen":"5.7μg"}', 'Japansk umami-svamp med lentinan', 'Shiitake svamp från Japan ger umami-smak och innehåller lentinan som kan stödja immunförsvaret enligt japansk forskning.', ARRAY['I miso-soppa','Stekta med grönsaker','Som umami-bas'], ARRAY['Året runt'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '1 år fryst', 'Shiitake - Umami och lentinan från Japan | ViHandlar', 'Upptäck shiitakes umami-smak och lentinan för immunförsvaret från Japan. Data från USDA.'),

-- Additional V foods
('Vannmelon', 'vannmelon', 'V', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 30, 0.6, 0.2, 7.6, 0.4, 0.001, '{"C":"8.1mg","A":"28μg","Lykopen":"4.5mg"}', '{"Kalium":"112mg","Citrullin":"högt","Vatten":"91%"}', 'Lykopen- och citrullinrik sommarfrukt', 'Vattenmelon innehåller lykopen för hjärthälsa och citrullin som kan stödja blodcirkulationen. Perfekt hydrering på sommaren.', ARRAY['Färsk som hydrering','Pressad som juice','I fruktsallad'], ARRAY['Sommar'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '1 år fryst', 'Vattenmelon - Lykopen och hydrering | ViHandlar', 'Lär dig om vattenmelonens lykopen och citrullin för hjärt- och kärlhälsa. Data från USDA.');

-- Verify we now have exactly 100 foods
UPDATE foods SET updated_at = NOW() WHERE created_at > NOW() - interval '1 minute';