-- Komplettera E-ämnes databasen med saknade ämnen från Livsmedelsverket
-- Del 1: Korrigerad version med rätt longevity_impact värden

INSERT INTO e_additives (
  e_number, name, common_name, category, slug, 
  short_description, long_description, risk_score, 
  adi_value, adi_source, origin, health_effects, 
  common_products, avoidance_tips, natural_alternatives,
  children_note, longevity_impact
) VALUES

-- E103 - Alkannin (förbjudet i Sverige men listat)
('E103', 'Alkannin', 'Chrysoin S', 'Färgämne', 'e103-alkannin',
'Rött färgämne från växten Alkanna tinctoria. Förbjudet i EU.',
'Alkannin är ett naturligt rött pigment som utvinns från roten av växten Alkanna tinctoria. Trots sitt naturliga ursprung har det förbjudits i EU på grund av potentiella hälsorisker.',
9, NULL, 'EU förbjudit', 'Växt (Alkanna tinctoria)',
'{"positive": [], "negative": ["Potentiellt cancerframkallande", "Förbjudet i EU sedan 1994"], "neutral": ["Naturligt pigment"]}',
'{"categories": [], "note": "Förbjudet att använda"}',
ARRAY['Kontrollera ingredienslistor noga', 'Undvik produkter från länder utanför EU'],
ARRAY['Rödbetsjuice', 'E162 (Rödbetsrött)', 'Naturliga antocyaner'],
'Särskilt viktigt att undvika för barn',
'Negativ'),

-- E105 - Fast Yellow AB (förbjudet)
('E105', 'Fast Yellow AB', 'Gul färg AB', 'Färgämne', 'e105-fast-yellow-ab',
'Syntetiskt gult färgämne som är förbjudet i EU.',
'Fast Yellow AB är en azoförebindelse som användes som gult livsmedelsfärgämne men förbjöds i EU på grund av hälsorisker.',
9, NULL, 'EU förbjudit', 'Syntetisk',
'{"positive": [], "negative": ["Förbjudet i EU", "Potentiellt allergiframkallande"], "neutral": ["Syntetiskt färgämne"]}',
'{"categories": [], "note": "Förbjudet att använda"}',
ARRAY['Läs ingredienslistor noggrant', 'Undvik import från länder med lösare regler'],
ARRAY['Kurkumin (E100)', 'Naturlig betakaroten', 'Saffran'],
'Undviks helt för barn',
'Negativ'),

-- E111 - Orange GGN (förbjudet)
('E111', 'Orange GGN', 'Alpha-naftolgulorange', 'Färgämne', 'e111-orange-ggn',
'Orangeött syntetiskt färgämne som förbjudits i EU.',
'Orange GGN är en azoförebindelse som tidigare användes som orangeött livsmedelsfärgämne men förbjöds på grund av potentiella hälsorisker.',
9, NULL, 'EU förbjudit', 'Syntetisk',
'{"positive": [], "negative": ["Förbjudet i EU", "Potentiellt cancerframkallande"], "neutral": []}',
'{"categories": [], "note": "Förbjudet att använda"}',
ARRAY['Undvik produkter från oreglerade marknader'],
ARRAY['Paprikaextrakt', 'Naturlig betakaroten'],
'Helt förbjudet för barn',
'Negativ'),

-- E125 - Ponceau SX (förbjudet i många länder)
('E125', 'Ponceau SX', 'Scharlakansrött SX', 'Färgämne', 'e125-ponceau-sx',
'Rött syntetiskt färgämne som är förbjudet i många länder.',
'Ponceau SX är en azoförebindelse som kan orsaka allergiska reaktioner och hyperaktivitet hos känsliga personer.',
8, NULL, 'Förbjudet i många länder', 'Syntetisk',
'{"positive": [], "negative": ["Kan orsaka hyperaktivitet", "Allergiframkallande", "Förbjudet i Norge och USA"], "neutral": ["Röd azofärg"]}',
'{"categories": ["Godis", "Bakverk"], "note": "Används sällan"}',
ARRAY['Undvik produkter med röda azofärger', 'Läs ingredienslistor noggrant'],
ARRAY['E162 (Rödbetsrött)', 'Naturliga antocyaner från bär'],
'Undviks för barn under 3 år',
'Negativ'),

-- E128 - Red 2G (förbjudet)
('E128', 'Red 2G', 'Rött 2G', 'Färgämne', 'e128-red-2g',
'Rött syntetiskt färgämne som förbjudits i EU.',
'Red 2G var en azoförebindelse som förbjöds i EU 2007 efter att studier visat potentiella cancerrisker.',
9, NULL, 'EU förbjudit 2007', 'Syntetisk',
'{"positive": [], "negative": ["Förbjudet i EU", "Potentiellt cancerframkallande", "Kan brytas ner till anilin"], "neutral": []}',
'{"categories": [], "note": "Förbjudet sedan 2007"}',
ARRAY['Undvik gamla produkter eller import från oreglerade länder'],
ARRAY['Rödbetsjuice', 'Naturliga antocyaner'],
'Helt förbjudet för barn',
'Negativ'),

-- E150b - Sockerkulör kaustiksulfitprocessen
('E150b', 'Sockerkulör', 'Kaustiksulfitprocessen', 'Färgämne', 'e150b-sockerkulor-kaustiksulfit',
'Brun sockerkulör framställd genom kaustiksulfitprocessen.',
'Denna typ av sockerkulör framställs genom behandling av socker med kaustiksulfit. Används för att ge brun färg åt livsmedel.',
3, NULL, 'Ej fastställt', 'Socker',
'{"positive": ["Naturligt ursprung från socker"], "negative": [], "neutral": ["Vanlig livsmedelsfärg"]}',
'{"categories": ["Läsk", "Öl", "Såser", "Bakverk"], "note": "Vanligt i mörka drycker"}',
ARRAY['Generellt säkert att använda'],
ARRAY['Karamelliserat socker', 'Mörk sirap'],
'Säkert för barn',
'Neutral'),

-- E150c - Sockerkulör ammoniakprocessen  
('E150c', 'Sockerkulör', 'Ammoniakprocessen', 'Färgämne', 'e150c-sockerkulor-ammoniak',
'Brun sockerkulör framställd genom ammoniakprocessen.',
'Framställs genom behandling av socker med ammoniak. Kan innehålla spår av 4-metylimidazol som kan vara problematiskt i stora mängder.',
4, NULL, 'Ej fastställt', 'Socker',
'{"positive": ["Naturligt ursprung"], "negative": ["Kan innehålla 4-metylimidazol"], "neutral": ["Vanligt använt"]}',
'{"categories": ["Cola", "Mörka läsk", "Såser"], "note": "Vanligt i mörka drycker"}',
ARRAY['Måttlig konsumtion av produkter med E150c', 'Variera dryckesval'],
ARRAY['E150a (enkel sockerkulör)', 'Naturligt karamelliserat socker'],
'Måttlig användning för barn',
'Negativ'),

-- E153 - Vegetabiliskt kol
('E153', 'Vegetabiliskt kol', 'Kolsvart', 'Färgämne', 'e153-vegetabiliskt-kol',
'Svart färgämne framställt från förkolnat växtmaterial.',
'Framställs genom förkolarning av växtmaterial som trä, nötter eller fruktkärnor. Används för att ge svart färg.',
2, NULL, 'Quantum satis', 'Växtmaterial',
'{"positive": ["Naturligt ursprung", "Väl tolererat"], "negative": [], "neutral": ["Ger svart färg"]}',
'{"categories": ["Godis", "Glass", "Kaviarsimulation", "Dekorationer"], "note": "Används för svart färg"}',
ARRAY['Generellt säkert'],
ARRAY['Aktivt kol (ej för färgning)', 'Naturligt svart från bläck från bläckfisk'],
'Säkert för barn',
'Neutral'),

-- E154 - Brun FK (förbjudet)
('E154', 'Brun FK', 'Food Brown 3', 'Färgämne', 'e154-brun-fk',
'Brunt syntetiskt färgämne som förbjudits i EU.',
'Brun FK var en syntetisk brun färg som förbjöds i EU på grund av potentiella hälsorisker.',
9, NULL, 'EU förbjudit', 'Syntetisk',
'{"positive": [], "negative": ["Förbjudet i EU", "Potentiella hälsorisker"], "neutral": []}',
'{"categories": [], "note": "Förbjudet"}',
ARRAY['Undvik helt'],
ARRAY['E150a (Sockerkulör)', 'Karamell', 'Naturlig kakao'],
'Förbjudet för barn',
'Negativ'),

-- E160f - Etylester av beta-apo-8-karotenal
('E160f', 'Etylester av beta-apo-8-karotenal', 'Apokarotenal etylester', 'Färgämne', 'e160f-apokarotenal-etyl',
'Orange färgämne besläktat med betakaroten.',
'En syntetisk variant av karotenoider som ger orange färg. Används sparsamt i livsmedel.',
4, 5, 'mg/kg kroppsvikt/dag - EFSA', 'Syntetisk karotenoid',
'{"positive": ["Relaterat till vitamin A"], "negative": [], "neutral": ["Syntetisk karotenoid"]}',
'{"categories": ["Margarin", "Ost", "Bakverk"], "note": "Begränsad användning"}',
ARRAY['Håll dig inom rekommenderat ADI-värde'],
ARRAY['E160a (Naturlig betakaroten)', 'Morötter', 'Pumpapuré'],
'Säkert i normala mängder för barn',
'Neutral'),

-- E161a - Flavoxantin
('E161a', 'Flavoxantin', 'Gul xantofyll', 'Färgämne', 'e161a-flavoxantin',
'Gult naturligt pigment från gruppen xantofyller.',
'Ett naturligt gult pigment som finns i många gula blommor och frukter. Används sällan kommersiellt.',
2, NULL, 'Ej fastställt', 'Naturlig xantofyll',
'{"positive": ["Naturligt pigment", "Antioxidantegenskaper"], "negative": [], "neutral": ["Sällan använt"]}',
'{"categories": [], "note": "Mycket sällan använt"}',
ARRAY['Generellt säkert'],
ARRAY['Naturlig kurkumin', 'Saffran'],
'Säkert för barn',
'Positiv'),

-- E161c - Kryptoxantin
('E161c', 'Kryptoxantin', 'Beta-kryptoxantin', 'Färgämne', 'e161c-kryptoxantin',
'Orange-gult naturligt pigment med provitamin A-aktivitet.',
'Ett naturligt karotenoidpigment som finns i citrusfrukter och kan omvandlas till vitamin A i kroppen.',
1, NULL, 'Quantum satis', 'Naturlig karotenoid',
'{"positive": ["Provitamin A", "Naturligt", "Antioxidant"], "negative": [], "neutral": ["Sällan tillsatt"]}',
'{"categories": ["Juicer", "Fruktprodukter"], "note": "Naturligt förekommande"}',
ARRAY['Helt säkert'],
ARRAY['Färsk apelsin', 'Persika', 'Papaja'],
'Mycket säkert för barn',
'Positiv'),

-- E161d - Rubixantin
('E161d', 'Rubixantin', 'Röd xantofyll', 'Färgämne', 'e161d-rubixantin',
'Rött naturligt pigment från xantofyllgruppen.',
'Ett naturligt rött pigment som finns i vissa växter och alger. Används mycket sällan kommersiellt.',
2, NULL, 'Ej fastställt', 'Naturlig xantofyll',
'{"positive": ["Naturligt pigment"], "negative": [], "neutral": ["Extremt sällan använt"]}',
'{"categories": [], "note": "Praktiskt taget ej använt"}',
ARRAY['Inga särskilda försiktighetsåtgärder'],
ARRAY['Naturliga röda pigment från tomater'],
'Säkert för barn',
'Neutral'),

-- E161e - Violaxantin  
('E161e', 'Violaxantin', 'Violett xantofyll', 'Färgämne', 'e161e-violaxantin',
'Violett naturligt pigment från xantofyllgruppen.',
'Ett naturligt pigment som bidrar till höstfärgerna i löv. Används inte kommersiellt som livsmedelsfärg.',
2, NULL, 'Ej fastställt', 'Naturlig xantofyll',
'{"positive": ["Naturligt pigment"], "negative": [], "neutral": ["Ej kommersiell användning"]}',
'{"categories": [], "note": "Ej använt kommersiellt"}',
ARRAY['Inga kända risker'],
ARRAY['Naturliga violetta pigment från rödkål'],
'Säkert för barn',
'Neutral'),

-- E161f - Rodoxantin
('E161f', 'Rodoxantin', 'Röd xantofyll', 'Färgämne', 'e161f-rodoxantin',
'Rött naturligt pigment från xantofyllgruppen.',
'Ett naturligt rött pigment som finns i vissa alger och växter. Ej kommersiellt använt.',
2, NULL, 'Ej fastställt', 'Naturlig xantofyll',
'{"positive": ["Naturligt pigment"], "negative": [], "neutral": ["Ej kommersiellt använt"]}',
'{"categories": [], "note": "Teoretisk status"}',
ARRAY['Inga kända risker'],
ARRAY['Naturligt lykopen från tomater'],
'Säkert för barn',
'Neutral'),

-- E161h - Zeaxantin
('E161h', 'Zeaxantin', 'Gul-orange xantofyll', 'Färgämne', 'e161h-zeaxantin',
'Gul-orange naturligt pigment viktigt för ögonhälsa.',
'Ett naturligt karotenoidpigment som är viktigt för ögonens gula fläck (makula). Finns naturligt i majs och gröna grönsaker.',
1, NULL, 'Quantum satis', 'Naturlig karotenoid',
'{"positive": ["Ögonhälsa", "Antioxidant", "Naturligt"], "negative": [], "neutral": ["Sällan tillsatt"]}',
'{"categories": ["Kosttillskott", "Funktionella livsmedel"], "note": "Hälsofrämjande"}',
ARRAY['Helt säkert', 'Kan vara fördelaktigt'],
ARRAY['Färsk majs', 'Spenat', 'Äggula'],
'Fördelaktigt för barn',
'Positiv'),

-- E161i - Citranaxantin  
('E161i', 'Citranaxantin', 'Orange xantofyll', 'Färgämne', 'e161i-citranaxantin',
'Orange naturligt pigment från citrusfrukter.',
'Ett naturligt orange pigment som finns i citrusfrukternas skal. Används sällan kommersiellt.',
2, NULL, 'Ej fastställt', 'Naturlig xantofyll',
'{"positive": ["Naturligt från citrus"], "negative": [], "neutral": ["Mycket sällan använt"]}',
'{"categories": [], "note": "Sällan använt"}',
ARRAY['Inga särskilda risker'],
ARRAY['Färska apelsinskal', 'Naturlig betakaroten'],
'Säkert för barn',
'Neutral'),

-- E161j - Astaxantin
('E161j', 'Astaxantin', 'Röd ketokarotenoid', 'Färgämne', 'e161j-astaxantin',
'Rött naturligt pigment med starka antioxidantegenskaper.',
'Ett kraftfullt antioxidant som ger lax och räkor deras röda färg. Används i fiskfoder och kosttillskott.',
1, NULL, 'Quantum satis', 'Naturlig karotenoid',
'{"positive": ["Kraftfullt antioxidant", "Naturligt", "Anti-inflammatorisk"], "negative": [], "neutral": ["Dyr att producera"]}',
'{"categories": ["Laxfoder", "Kosttillskott", "Funktionella livsmedel"], "note": "Hälsofrämjande"}',
ARRAY['Helt säkert', 'Fördelaktigt för hälsan'],
ARRAY['Vildlax', 'Räkor', 'Kräftor'],
'Fördelaktigt för barn',
'Positiv');