-- Add remaining E-additives from Livsmedelsverket: Antioxidants, Emulsifiers, Sweeteners, and Other additives

INSERT INTO e_additives (e_number, name, category, slug) VALUES 

-- Antioxidationsmedel (Antioxidants)
('E300', 'Askorbinsyra', 'Antioxidationsmedel', 'e300-askorbinsyra'),
('E301', 'Natriumaskorbat', 'Antioxidationsmedel', 'e301-natriumaskorbat'),
('E302', 'Kalciumaskorbat', 'Antioxidationsmedel', 'e302-kalciumaskorbat'),
('E304', 'Askorbinsyraestrar av fettsyror', 'Antioxidationsmedel', 'e304-askorbinsyraestrar-av-fettsyror'),
('E306', 'Tokoferolrika extrakt', 'Antioxidationsmedel', 'e306-tokoferolrika-extrakt'),
('E307', 'Alfa-tokoferol', 'Antioxidationsmedel', 'e307-alfa-tokoferol'),
('E308', 'Gamma-tokoferol', 'Antioxidationsmedel', 'e308-gamma-tokoferol'),
('E309', 'Delta-tokoferol', 'Antioxidationsmedel', 'e309-delta-tokoferol'),
('E310', 'Propylgallat', 'Antioxidationsmedel', 'e310-propylgallat'),
('E315', 'Isoaskorbinsyra', 'Antioxidationsmedel', 'e315-isoaskorbinsyra'),
('E316', 'Natriumisoaskorbat', 'Antioxidationsmedel', 'e316-natriumisoaskorbat'),
('E319', 'Tertiär butylhydrokinon (TBHQ)', 'Antioxidationsmedel', 'e319-tertiar-butylhydrokinon-tbhq'),
('E320', 'Butylhydroxianisol (BHA)', 'Antioxidationsmedel', 'e320-butylhydroxianisol-bha'),
('E321', 'Butylhydroxitoluen (BHT)', 'Antioxidationsmedel', 'e321-butylhydroxitoluen-bht'),
('E322', 'Lecitiner', 'Antioxidationsmedel', 'e322-lecitiner'),
('E325', 'Natriumlaktat', 'Antioxidationsmedel', 'e325-natriumlaktat'),
('E326', 'Kaliumlaktat', 'Antioxidationsmedel', 'e326-kaliumlaktat'),
('E327', 'Kalciumlaktat', 'Antioxidationsmedel', 'e327-kalciumlaktat'),
('E330', 'Citronsyra', 'Antioxidationsmedel', 'e330-citronsyra'),
('E331', 'Natriumcitrater', 'Antioxidationsmedel', 'e331-natriumcitrater'),
('E332', 'Kaliumcitrater', 'Antioxidationsmedel', 'e332-kaliumcitrater'),
('E333', 'Kalciumcitrater', 'Antioxidationsmedel', 'e333-kalciumcitrater'),
('E334', 'L-Vinsyra', 'Antioxidationsmedel', 'e334-l-vinsyra'),
('E335', 'Natriumtartrater', 'Antioxidationsmedel', 'e335-natriumtartrater'),
('E336', 'Kaliumtartrater', 'Antioxidationsmedel', 'e336-kaliumtartrater'),
('E337', 'Natriumkaliumtartrat', 'Antioxidationsmedel', 'e337-natriumkaliumtartrat'),
('E338', 'Fosforsyra', 'Antioxidationsmedel', 'e338-fosforsyra'),
('E339', 'Natriumfosfater', 'Antioxidationsmedel', 'e339-natriumfosfater'),
('E340', 'Kaliumfosfater', 'Antioxidationsmedel', 'e340-kaliumfosfater'),
('E341', 'Kalciumfosfater', 'Antioxidationsmedel', 'e341-kalciumfosfater'),
('E343', 'Magnesiumfosfater', 'Antioxidationsmedel', 'e343-magnesiumfosfater'),
('E350', 'Natriummalater', 'Antioxidationsmedel', 'e350-natriummalater'),
('E351', 'Kaliummalat', 'Antioxidationsmedel', 'e351-kaliummalat'),
('E352', 'Kalciummalater', 'Antioxidationsmedel', 'e352-kalciummalater'),
('E353', 'Metavinsyra', 'Antioxidationsmedel', 'e353-metavinsyra'),
('E354', 'Kalciumtartrat', 'Antioxidationsmedel', 'e354-kalciumtartrat'),
('E355', 'Adipinsyra', 'Antioxidationsmedel', 'e355-adipinsyra'),
('E356', 'Natriumadipat', 'Antioxidationsmedel', 'e356-natriumadipat'),
('E357', 'Kaliumadipat', 'Antioxidationsmedel', 'e357-kaliumadipat'),
('E363', 'Bärnstenssyra', 'Antioxidationsmedel', 'e363-barnstenssyra'),
('E380', 'Triammoniumcitrat', 'Antioxidationsmedel', 'e380-triammoniumcitrat'),
('E385', 'Kalciumdinatriumetylendiamintetraacetat', 'Antioxidationsmedel', 'e385-kalciumdinatriumetylendiamintetraacetat'),
('E392', 'Extrakt av rosmarin', 'Antioxidationsmedel', 'e392-extrakt-av-rosmarin'),
('E586', '4-hexylresorcinol', 'Antioxidationsmedel', 'e586-4-hexylresorcinol'),

-- Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel
('E322a', 'Havrelecitin', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e322a-havrelecitin'),
('E345', 'Trimagnesiumdicitrat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e345-trimagnesiumdicitrat'),
('E400', 'Alginsyra', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e400-alginsyra'),
('E401', 'Natriumalginat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e401-natriumalginat'),
('E402', 'Kaliumalginat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e402-kaliumalginat'),
('E403', 'Ammoniumalginat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e403-ammoniumalginat'),
('E404', 'Kalciumalginat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e404-kalciumalginat'),
('E405', '1,2-Propylenglykolalginat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e405-12-propylenglykolalginat'),
('E406', 'Agar', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e406-agar'),
('E407', 'Karragenan', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e407-karragenan'),
('E407a', 'Bearbetad Eucheumaalg', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e407a-bearbetad-eucheumaalg'),
('E410', 'Fruktkärnmjöl', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e410-fruktkarnmjol'),
('E412', 'Guarkärnmjöl', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e412-guarkarnmjol'),
('E413', 'Dragant', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e413-dragant'),
('E414', 'Gummi arabicum (Akaciagummi)', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e414-gummi-arabicum-akaciagummi'),
('E415', 'Xantangummi', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e415-xantangummi'),
('E416', 'Karayagummi', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e416-karayagummi'),
('E417', 'Taragummi', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e417-taragummi'),
('E418', 'Gellangummi', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e418-gellangummi'),
('E420', 'Sorbitol, sorbitolsirap', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e420-sorbitol-sorbitolsirap'),
('E421', 'Mannitol', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e421-mannitol'),
('E422', 'Glycerol', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e422-glycerol')

ON CONFLICT (e_number) DO NOTHING;