-- Add 15 more popular foods with corrected numeric values for DECIMAL(5,2) fields

-- Insert key Grönsaker (5 foods)
INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

('Tomat', 'tomat', 'T',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Fruktgrönsak',
'Rumstemperatur, kylskåp när mogen',
'3-5 dagar',
'1 vecka',
true,
'Skär i bitar innan frysning',
ARRAY['juni', 'juli', 'augusti', 'september'],
ARRAY[]::text[],
18, 0.9, 0.2, 3.9, 1.2, 0.01,
'{"C": "14mg", "K": "8μg", "Folat": "15μg"}'::jsonb,
'{"kalium": "237mg", "fosfor": "24mg"}'::jsonb,
'Saftig fruktgrönsak rik på lycopene och vitamin C.',
ARRAY['Sallader', 'Såser', 'Soppa', 'Pizza'],
'[{"name": "Körsbärstomater", "reason": "Sötare och mindre"}, {"name": "San Marzano", "reason": "Perfekt för såser"}]'::jsonb,
'Tomat - Näringsvärde och Odling | Livsmedel A-Ö',
'Komplett guide om tomater: näringsvärde, olika sorter, odling och användning i matlagning.',
'[{"question": "Ska tomater förvaras i kylskåp?", "answer": "Nej, mogna tomater förvaras bäst i rumstemperatur för bästa smak."}, {"question": "Vad är lycopene?", "answer": "En antioxidant som ger tomater röd färg och kan ha hälsofördelar."}]'::jsonb,
ARRAY['Italiensk mat', 'Sallader', 'Sommarmiddag']),

('Lök Gul', 'lok-gul', 'L',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Rotgrönsak',
'Mörkt, torrt och svalt',
'2-3 månader',
'2-3 månader',
true,
'Hacka innan frysning',
ARRAY['augusti', 'september', 'oktober'],
ARRAY[]::text[],
40, 1.1, 0.1, 9.3, 1.7, 0.01,
'{"C": "7.4mg", "B6": "0.1mg", "Folat": "19μg"}'::jsonb,
'{"kalium": "146mg", "mangan": "0.1mg"}'::jsonb,
'Grundläggande aromgrönsak, bas i de flesta maträtter.',
ARRAY['Bas för såser', 'Stekt', 'Karamelliserad', 'Soppa'],
'[{"name": "Schalottenlök", "reason": "Mildare smak"}, {"name": "Rödlök", "reason": "Starkare smak, bra rå"}]'::jsonb,
'Lök Gul - Grundsmaker och Förvaring | Livsmedel A-Ö',
'Allt om gul lök: näringsvärde, förvaring, olika typer och grundläggande matlagning.',
'[{"question": "Hur undviker man tårar när man hackar lök?", "answer": "Kyl löken först, använd vass kniv och andas genom munnen."}, {"question": "Varför blir lök söt när man steker den?", "answer": "Värme bryter ner sura föreningar och förvandlar dem till socker."}]'::jsonb,
ARRAY['Grundsmaker', 'Svensk husmanskost', 'Daglig matlagning']),

('Potatis', 'potatis', 'P',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Rotgrönsak',
'Mörkt, torrt och svalt 4-8°C',
'2-3 månader',
'2-3 månader',
true,
'Koka innan frysning',
ARRAY['augusti', 'september', 'oktober'],
ARRAY[]::text[],
77, 2.0, 0.1, 17.0, 2.2, 0.01,
'{"C": "20mg", "B6": "0.3mg", "Folat": "15μg"}'::jsonb,
'{"kalium": "429mg", "fosfor": "57mg", "magnesium": "23mg"}'::jsonb,
'Sveriges viktigaste grundgrönsak, rik på stärkelse.',
ARRAY['Kokt', 'Bakad', 'Stekt', 'Mos'],
'[{"name": "Sötpotatis", "reason": "Sötare smak, mer vitamin A"}, {"name": "Pasta", "reason": "Annan kolhydratkälla"}]'::jsonb,
'Potatis - Näringsvärde och Svenska Sorter | Livsmedel A-Ö',
'Komplett guide om potatis: näringsvärde, svenska sorter, förvaring och tillagningsmetoder.',
'[{"question": "Vilken potatis är bäst för kokning?", "answer": "Mandelpotatis håller formen bäst, mjöliga sorter passar bäst för mos."}, {"question": "Kan man äta grön potatis?", "answer": "Nej, grön färg indikerar solanin som är giftigt - skala bort gröna delar."}]'::jsonb,
ARRAY['Svensk husmanskost', 'Grundmat', 'Vardagsmiddag']),

('Gurka', 'gurka', 'G',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Fruktgrönsak',
'Kylskåp 8-10°C',
'1 vecka',
'1-2 veckor',
false,
'Rekommenderas ej att frysa',
ARRAY['juni', 'juli', 'augusti', 'september'],
ARRAY[]::text[],
16, 0.7, 0.1, 3.6, 0.5, 0.01,
'{"K": "16μg", "C": "2.8mg"}'::jsonb,
'{"kalium": "147mg", "magnesium": "13mg"}'::jsonb,
'Krispig grönsak med hög vattenhalt, perfekt för sallader.',
ARRAY['Sallader', 'Tzatziki', 'Inläggning', 'Smoothies'],
'[{"name": "Zucchini", "reason": "Liknande mild smak"}, {"name": "Selleri", "reason": "Samma krispighet"}]'::jsonb,
'Gurka - Näringsvärde och Användning | Livsmedel A-Ö',
'Allt om gurka: näringsvärde, förvaring, olika sorter och användning i matlagning.',
'[{"question": "Varför blir gurka besk?", "answer": "Beska ämnen bildas vid stress, välj små gurkor och skala bort ändarna."}, {"question": "Kan man äta gurkskal?", "answer": "Ja, skalet innehåller fiber och näringsämnen - skölj bara ordentligt."}]'::jsonb,
ARRAY['Sallader', 'Grekisk mat', 'Sommarmat']),

('Morot', 'morot', 'M',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Rotgrönsak',
'Kylskåp 0-4°C',
'3-4 veckor',
'1 månad',
true,
'Skär i bitar innan frysning',
ARRAY['augusti', 'september', 'oktober', 'november'],
ARRAY[]::text[],
41, 0.9, 0.2, 9.6, 2.8, 0.07,
'{"A": "835μg", "K": "13μg", "B6": "0.1mg"}'::jsonb,
'{"kalium": "320mg", "biotin": "6μg"}'::jsonb,
'Söt rotgrönsak extremt rik på betakaroten (vitamin A).',
ARRAY['Rå i sallad', 'Soppa', 'Juice', 'Bakad'],
'[{"name": "Palsternacka", "reason": "Liknande rotgrönsak"}, {"name": "Sötpotatis", "reason": "Liknande sötma och färg"}]'::jsonb,
'Morot - Vitamin A Källa och Användning | Livsmedel A-Ö',
'Allt om morötter: näringsvärde, vitamin A fördelar, odling och olika tillagningssätt.',
'[{"question": "Varför är morötter bra för synen?", "answer": "Betakaroten omvandlas till vitamin A som behövs för bildningen av rhodopsin i ögat."}, {"question": "Blir morötter sötare efter frost?", "answer": "Ja, kyla omvandlar stärkelse till socker som en naturlig frostskydd."}]'::jsonb,
ARRAY['Vitamin A källa', 'Barnmat', 'Hälsosam kost']);

-- Insert populära Frukt & Bär (5 foods)
INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

('Banan', 'banan', 'B',
(SELECT id FROM public.food_categories WHERE slug = 'frukt-bar'),
'Tropisk frukt',
'Rumstemperatur',
'2-7 dagar',
'3-7 dagar',
true,
'Skala och skär innan frysning',
ARRAY[]::text[],
ARRAY[]::text[],
89, 1.1, 0.3, 23.0, 2.6, 0.00,
'{"C": "8.7mg", "B6": "0.4mg", "Folat": "20μg"}'::jsonb,
'{"kalium": "358mg", "magnesium": "27mg", "mangan": "0.3mg"}'::jsonb,
'Näringsrik tropisk frukt rik på kalium och naturligt socker.',
ARRAY['Smoothies', 'Bakad i bröd', 'Mellanmål', 'Müsli'],
'[{"name": "Plantain", "reason": "Liknande frukt för matlagning"}, {"name": "Dadlar", "reason": "Annan sött frukt med kalium"}]'::jsonb,
'Banan - Kalium och Naturlig Energi | Livsmedel A-Ö',
'Komplett guide om bananer: näringsvärde, kalium fördelar, mognadsstadier och användning.',
'[{"question": "Varför är bananer bra efter träning?", "answer": "Snabba kolhydrater och kalium hjälper återställa energi och vätske-elektrolytbalans."}, {"question": "Kan man äta bruna bananer?", "answer": "Ja, de är bara mörkare och sötare - perfekta för smoothies och bakning."}]'::jsonb,
ARRAY['Träningsmat', 'Frukost smoothies', 'Barnmat']),

('Äpple', 'apple', 'Ä',
(SELECT id FROM public.food_categories WHERE slug = 'frukt-bar'),
'Kärnfrukt',
'Kylskåp 0-4°C',
'1-2 månader',
'1-3 månader',
true,
'Skär i bitar innan frysning',
ARRAY['augusti', 'september', 'oktober', 'november'],
ARRAY[]::text[],
52, 0.3, 0.2, 14.0, 2.4, 0.00,
'{"C": "4.6mg", "K": "2.2μg"}'::jsonb,
'{"kalium": "107mg", "fosfor": "11mg", "pektin": "hög halt"}'::jsonb,
'Sveriges mest populära frukt, rik på fiber och antioxidanter.',
ARRAY['Rå som mellanmål', 'Paj', 'Mos', 'Juice'],
'[{"name": "Päron", "reason": "Liknande kärnfrukt"}, {"name": "Kvitten", "reason": "Bra för kokning och sylt"}]'::jsonb,
'Äpple - Fiber och Antioxidanter | Livsmedel A-Ö',
'Allt om äpplen: näringsvärde, svenska sorter, förvaring och traditionell användning.',
'[{"question": "Vilka äppelsorter är bäst för bakning?", "answer": "Fasta sorter som Granny Smith och Ingrid Marie behåller formen bäst."}, {"question": "Varför säger man \"ett äpple om dagen\"?", "answer": "Äpplen innehåller fiber, antioxidanter och pektin som kan stödja hälsan."}]'::jsonb,
ARRAY['Hälsosam frukt', 'Svensk tradition', 'Barnmat']),

('Citron', 'citron', 'C',
(SELECT id FROM public.food_categories WHERE slug = 'frukt-bar'),
'Citrusfrukt',
'Rumstemperatur 1 vecka, kylskåp 1 månad',
'1 månad',
'1 månad',
true,
'Pressa saft innan frysning',
ARRAY[]::text[],
ARRAY[]::text[],
29, 1.1, 0.3, 9.0, 2.8, 0.00,
'{"C": "53mg", "Folat": "6μg", "Citroflavonoider": "högt"}'::jsonb,
'{"kalium": "138mg", "citrat": "hög halt"}'::jsonb,
'Sur citrusfrukt extremt rik på vitamin C och citrat.',
ARRAY['Dressing', 'Marinader', 'Bakning', 'Dryck'],
'[{"name": "Lime", "reason": "Liknande sur smak"}, {"name": "Vinäger", "reason": "Annan syrlig smaksättare"}]'::jsonb,
'Citron - Vitamin C Bomb | Livsmedel A-Ö',
'Komplett guide om citron: näringsvärde, vitamin C fördelar, användning i matlagning och hälsa.',
'[{"question": "Hjälper citron med viktminskning?", "answer": "Pektin i citron kan ge mättnadskänsla, men ingen magisk viktminskning."}, {"question": "Kan man äta citronskal?", "answer": "Ja, skalet innehåller mycket eteriska oljor - välj ekologiska citroner."}]'::jsonb,
ARRAY['Vitamin C källa', 'Matlagning', 'Detox drycker']),

('Jordgubbar', 'jordgubbar', 'J',
(SELECT id FROM public.food_categories WHERE slug = 'frukt-bar'),
'Bär',
'Kylskåp 2-4°C',
'2-3 dagar',
'3-5 dagar',
true,
'Rensa och frys hela',
ARRAY['juni', 'juli'],
ARRAY[]::text[],
32, 0.7, 0.3, 7.7, 2.0, 0.00,
'{"C": "59mg", "Folat": "24μg", "K": "2.2μg"}'::jsonb,
'{"kalium": "153mg", "mangan": "0.4mg", "antocyaniner": "högt"}'::jsonb,
'Svenska sommarbär med extremt hög vitamin C halt.',
ARRAY['Dessert', 'Sylt', 'Smoothies', 'Tårtor'],
'[{"name": "Hallon", "reason": "Liknande bär"}, {"name": "Blåbär", "reason": "Andra antioxidantrika bär"}]'::jsonb,
'Jordgubbar - Svensk Sommar och Vitamin C | Livsmedel A-Ö',
'Komplett guide om jordgubbar: näringsvärde, svensk säsong, plockning och bevarande.',
'[{"question": "När är jordgubbssäsong i Sverige?", "answer": "Juni-juli är högsäsong för svenska jordgubbar, med klimatet varierar säsongen."}, {"question": "Ska man tvätta jordgubbar innan förvaring?", "answer": "Nej, tvätta först när du ska äta dem för att undvika fukt och mögel."}]'::jsonb,
ARRAY['Svensk sommar', 'Midsommar', 'Vitamin C källa']),

('Blåbär', 'blaber', 'B',
(SELECT id FROM public.food_categories WHERE slug = 'frukt-bar'),
'Vilda bär',
'Kylskåp 0-4°C',
'1 vecka',
'1-2 veckor',
true,
'Frys direkt utan tvätt',
ARRAY['juli', 'augusti'],
ARRAY[]::text[],
57, 0.7, 0.3, 14.5, 2.4, 0.00,
'{"C": "9.7mg", "K": "19μg", "E": "0.6mg"}'::jsonb,
'{"mangan": "0.3mg", "antocyaniner": "extremt högt", "antioxidanter": "mycket högt"}'::jsonb,
'Vilda svenska bär med extremt höga antioxidantnivåer.',
ARRAY['Pannkakor', 'Müsli', 'Smoothies', 'Paj'],
'[{"name": "Lingon", "reason": "Andra svenska vilda bär"}, {"name": "Açaibär", "reason": "Liknande antioxidantnivåer"}]'::jsonb,
'Blåbär - Antioxidanter och Svensk Natur | Livsmedel A-Ö',
'Komplett guide om blåbär: antioxidanter, svensk skogstradition, plockning och hälsofördelar.',
'[{"question": "Varför är blåbär så hälsosamma?", "answer": "Extremt höga nivåer av antocyaniner som kan skydda hjärna, hjärta och syn."}, {"question": "Skillnad mellan skogs- och trädgårdsblåbär?", "answer": "Skogsblåbär har mörkare kött och mer intensiv smak och näringsinnehåll."}]'::jsonb,
ARRAY['Antioxidanter', 'Svensk skogstradition', 'Hälsosam kost']);

-- Insert grundkryddor (3 foods)
INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

('Basilika', 'basilika', 'B',
(SELECT id FROM public.food_categories WHERE slug = 'kryddor-orter'),
'Färsk ört',
'Kylskåp i vatten som blommor',
'1 vecka',
'3-5 dagar',
true,
'Frys i olivolja eller som pesto',
ARRAY['juni', 'juli', 'augusti', 'september'],
ARRAY[]::text[],
22, 3.2, 0.6, 2.6, 1.6, 0.00,
'{"K": "415μg", "A": "264μg", "C": "18mg"}'::jsonb,
'{"kalium": "295mg", "kalcium": "177mg", "järn": "3.2mg"}'::jsonb,
'Aromatisk italiensk ört med sött, kryddigt arom.',
ARRAY['Pesto', 'Pasta', 'Pizza', 'Caprese'],
'[{"name": "Oregano", "reason": "Annan italiensk ört"}, {"name": "Mynta", "reason": "Liknande fräsch smak"}]'::jsonb,
'Basilika - Italiensk Ört och Pesto | Livsmedel A-Ö',
'Komplett guide om basilika: odling, förvaring, pesto recept och användning i italiensk matlagning.',
'[{"question": "Hur håller basilika längst?", "answer": "Som blommor i vatten i kylskåp, eller frys in som pesto med olivolja."}, {"question": "Kan man äta basilika blommor?", "answer": "Ja, de är ätbara och har en mild basiliksmak - fin som garnering."}]'::jsonb,
ARRAY['Italiensk mat', 'Pesto', 'Pizza']),

('Havssalt', 'havssalt', 'H',
(SELECT id FROM public.food_categories WHERE slug = 'kryddor-orter'),
'Mineralsalt',
'Torrt och mörkt',
'Obegränsat',
'Obegränsat',
false,
'Ej aktuellt',
ARRAY[]::text[],
ARRAY[]::text[],
0, 0.0, 0.0, 0.0, 0.0, 99.99,
'{}'::jsonb,
'{"natrium": "38.8g per 100g", "klorid": "59.9g per 100g", "spårmineraler": "varierande"}'::jsonb,
'Naturligt salt från havsvatten med spårmineraler.',
ARRAY['All matlagning', 'Bakning', 'Konservering', 'Finishing salt'],
'[{"name": "Himalayasalt", "reason": "Annat mineralsalt"}, {"name": "Bordssalt", "reason": "Finare struktur"}]'::jsonb,
'Havssalt - Naturligt Salt och Mineraler | Livsmedel A-Ö',
'Allt om havssalt: tillverkning, mineraler, olika typer och användning i matlagning.',
'[{"question": "Är havssalt nyttigare än vanligt salt?", "answer": "Minimala skillnader i näring - huvudvärdet är smak och textur från spårmineraler."}, {"question": "Vilket salt passar bäst till vad?", "answer": "Fint salt för bakning, grovt havssalt som finishing salt för textur och smak."}]'::jsonb,
ARRAY['Grundkrydda', 'All matlagning', 'Bakning']);

-- Insert grundtorrvaror (2 foods)
INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

('Spaghetti', 'spaghetti', 'S',
(SELECT id FROM public.food_categories WHERE slug = 'spannmal-baljvaxter'),
'Pasta',
'Torrt och mörkt',
'Obegränsat torr',
'2-3 år',
true,
'Koka innan frysning',
ARRAY[]::text[],
ARRAY['gluten'],
371, 13.0, 1.5, 74.0, 3.2, 0.01,
'{"B1": "0.9mg", "Folat": "18μg", "Niacin": "5.9mg"}'::jsonb,
'{"fosfor": "189mg", "kalium": "223mg", "selen": "26μg"}'::jsonb,
'Klassisk långsträckt italiensk pasta av durumvete.',
ARRAY['Carbonara', 'Bolognese', 'Aglio e olio', 'Köttbullar'],
'[{"name": "Linguine", "reason": "Liknande lång pasta"}, {"name": "Penne", "reason": "Kort pasta alternativ"}]'::jsonb,
'Spaghetti - Italiensk Pasta Klassiker | Livsmedel A-Ö',
'Komplett guide om spaghetti: tillagning, italienska recept, olika typer och perfekt al dente.',
'[{"question": "Hur kokar man spaghetti al dente?", "answer": "Koka 1-2 minuter kortare tid än förpackningen anger och testa genom att bita."}, {"question": "Ska man hälla olja i pastavattnet?", "answer": "Nej, det hindrar såsen från att fästa - salta vattnet istället och rör om."}]'::jsonb,
ARRAY['Italiensk mat', 'Pasta carbonara', 'Vardagsmiddag']),

('Jasminris', 'jasminris', 'J',
(SELECT id FROM public.food_categories WHERE slug = 'spannmal-baljvaxter'),
'Långkornigt ris',
'Torrt och mörkt',
'Obegränsat',
'2-3 år',
true,
'Koka innan frysning',
ARRAY[]::text[],
ARRAY[]::text[],
365, 7.1, 0.7, 80.0, 0.4, 0.01,
'{"B1": "0.4mg", "B3": "1.5mg", "Folat": "8μg"}'::jsonb,
'{"fosfor": "115mg", "kalium": "115mg", "mangan": "1.1mg"}'::jsonb,
'Aromatiskt långkornigt ris från Thailand med blommig doft.',
ARRAY['Thailändsk mat', 'Curry', 'Stir-fry', 'Sushi'],
'[{"name": "Basmatiiris", "reason": "Annat aromatiskt långkorns ris"}, {"name": "Vanligt ris", "reason": "Mindre aromatiskt alternativ"}]'::jsonb,
'Jasminris - Aromatiskt Thailändskt Ris | Livsmedel A-Ö',
'Allt om jasminris: ursprung från Thailand, tillagning, aromatiska egenskaper och användning i asiatisk mat.',
'[{"question": "Vad ger jasminris sin doft?", "answer": "Naturliga föreningar som 2-acetyl-1-pyrolin ger den karakteristiska blommiga doften."}, {"question": "Ska man skölja jasminris?", "answer": "Ja, skölja tills vattnet blir klart för att få luftigt ris utan för mycket stärkelse."}]'::jsonb,
ARRAY['Thailändsk mat', 'Asiatisk mat', 'Curry']);

-- Set up cross-references between related foods
UPDATE public.foods SET related_foods = 
ARRAY(SELECT id FROM public.foods WHERE slug IN ('mozzarella', 'basilika', 'tomat') AND id IS NOT NULL LIMIT 3)
WHERE slug = 'parmigiano-reggiano';

UPDATE public.foods SET related_foods = 
ARRAY(SELECT id FROM public.foods WHERE slug IN ('parmigiano-reggiano', 'basilika', 'tomat') AND id IS NOT NULL LIMIT 3)
WHERE slug = 'mozzarella';

UPDATE public.foods SET related_foods = 
ARRAY(SELECT id FROM public.foods WHERE slug IN ('spaghetti', 'parmigiano-reggiano', 'basilika') AND id IS NOT NULL LIMIT 3)
WHERE slug = 'tomat';

UPDATE public.foods SET related_foods = 
ARRAY(SELECT id FROM public.foods WHERE slug IN ('tomat', 'mozzarella', 'spaghetti') AND id IS NOT NULL LIMIT 3)
WHERE slug = 'basilika';