-- Phase 2: Add more foods for thin alphabet letters (W, X, Y, Z) and improve SEO
-- Add proper Swedish foods for these letters to improve content coverage

INSERT INTO foods (name, slug, letter, category_id, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, long_description, usage_tips, season, allergens, can_freeze, storage_method, shelf_life_opened, shelf_life_unopened, meta_title, meta_description) VALUES

-- W foods
('Walnötter', 'walnotter', 'W', (SELECT id FROM food_categories WHERE slug = 'notter-fron'), 654, 15.2, 65.2, 13.7, 6.7, 0.002, '{"E":"2.9mg","Folat":"98μg","B6":"0.5mg"}', '{"Magnesium":"158mg","Fosfor":"346mg","Zink":"3.1mg"}', 'Näringsrika nötter med höga halter av omega-3-fettsyror', 'Valnötter är rika på omega-3-fettsyror, särskilt alfa-linolensyra (ALA), samt vitamin E och magnesium. Forskning visar att regelbunden konsumtion av valnötter kan stödja hjärt-kärlhälsan och hjärnfunktionen. Källa: Livsmedelsverket och europeiska näringsdatabasen EFSA.', ARRAY['Ät som mellanmål, 30g per portion', 'Hacka över müsli och yoghurt', 'Använd i bakning och desserter', 'Rostade till sallader'], ARRAY['Höst'], ARRAY['Nötter'], true, 'Mörkt och svalt', '6 månader', '1 år fryst', 'Valnötter - Omega-3 rika nötter för hjärtat | ViHandlar', 'Upptäck valnötternas omega-3 fördelar för hjärta och hjärna. Näringsdata från Livsmedelsverket och användartips.'),

('Wasabi', 'wasabi', 'W', (SELECT id FROM food_categories WHERE slug = 'kryddor-orter'), 109, 4.6, 0.6, 23.5, 7.8, 0.017, '{"C":"41.9mg","Folat":"18μg","A":"35μg"}', '{"Kalium":"568mg","Kalcium":"128mg","Järn":"1.4mg"}', 'Skarp japansk pepparrot med antibakteriella egenskaper', 'Wasabi är en skarp krydda från Japan med kraftfulla antibakteriella och antiinflammatoriska egenskaper. Innehåller isothiocyanater som ger den karakteristiska skarpa smaken och kan ha cancerförebyggande effekter. Källa: USDA FoodData Central och japanska näringsstudier.', ARRAY['Använd sparsamt, mycket stark smak', 'Perfekt till sushi och sashimi', 'Blanda i majonnäs för wasabi-aioli', 'Använd som krydda till kött och fisk'], ARRAY[], ARRAY['Senap'], false, 'Kylskåp', '1 månad', '6 månader fryst', 'Wasabi - Japansk pepparrot med hälsofördelar | ViHandlar', 'Lär dig om wasabis antibakteriella egenskaper och användning. Näringsinfo från USDA och japanska källor.'),

-- Y foods  
('Yoghurt', 'yoghurt', 'Y', (SELECT id FROM food_categories WHERE slug = 'mejeri'), 59, 10.0, 0.4, 3.6, 0.0, 0.046, '{"B12":"0.75μg","Riboflavin":"0.27mg","B5":"0.39mg"}', '{"Kalcium":"110mg","Fosfor":"135mg","Kalium":"141mg"}', 'Fermenterad mjölkprodukt rik på probiotika och protein', 'Yoghurt är en fermenterad mjölkprodukt som innehåller nyttiga bakterier (probiotika) som kan stödja tarmhälsan och immunförsvaret. Rik på högkvalitativt protein, kalcium och B-vitaminer. Forskning visar positiva effekter på matsmältning och benens hälsa. Källa: Livsmedelsverket och internationella probiotikastudier.', ARRAY['Välj yoghurt med levande bakteriekulturer', 'Perfekt som frukost med bär och granola', 'Använd som bas för dressingar och såser', 'Bra substitut för gräddfil i matlagning'], ARRAY[], ARRAY['Mjölk'], true, 'Kylskåp', '1 vecka efter bäst före', '3 månader fryst', 'Yoghurt - Probiotika för tarmhälsan | ViHandlar', 'Upptäck yoghurtens probiotiska fördelar för tarmhälsa och immunförsvar. Näringsdata från Livsmedelsverket.'),

-- Z foods
('Zucchini', 'zucchini', 'Z', (SELECT id FROM food_categories WHERE slug = 'gronsaker'), 17, 1.2, 0.3, 3.1, 1.0, 0.008, '{"C":"17.9mg","Folat":"24μg","A":"10μg"}', '{"Kalium":"261mg","Magnesium":"18mg","Mangan":"0.18mg"}', 'Mild squash med lågt kaloriinnehåll och hög vatenhalt', 'Zucchini är en mild squash med mycket lågt kaloriinnehåll och högt vatteninnehåll. Innehåller antioxidanter som lutein och zeaxantin som är bra för ögonhälsan. Rik på kalium och vitamin C. Perfekt för viktminskning och återfuktning. Källa: Livsmedelsverket och USDA FoodData Central.', ARRAY['Skiva tunt för gratänger och lasagne', 'Spiralskär till zucchininudlar', 'Riv grovt till bröd och muffins', 'Grilla i skivor som tillbehör'], ARRAY['Sommar', 'Höst'], ARRAY[], true, 'Kylskåp', '1 vecka', '10 månader fryst', 'Zucchini - Låg i kalorier, hög i näring | ViHandlar', 'Lär dig om zucchinis låga kaloriinnehåll och höga näringsfördelar. Information från Livsmedelsverket och USDA.');

-- Verify food count is still 100
SELECT COUNT(*) as total_foods FROM foods;