-- Add comprehensive E-additives list from Livsmedelsverket
-- Using INSERT ... ON CONFLICT to avoid duplicates

INSERT INTO e_additives (e_number, name, category, slug) VALUES 
-- Färgämnen (Coloring agents)
('E100', 'Kurkumin', 'Färgämne', 'e100-kurkumin'),
('E101', 'Riboflavin', 'Färgämne', 'e101-riboflavin'),
('E102', 'Tartrazin', 'Färgämne', 'e102-tartrazin'),
('E104', 'Kinolingult', 'Färgämne', 'e104-kinolingult'),
('E110', 'Para-orange', 'Färgämne', 'e110-para-orange'),
('E120', 'Karmin', 'Färgämne', 'e120-karmin'),
('E122', 'Azorubin', 'Färgämne', 'e122-azorubin'),
('E123', 'Amarant', 'Färgämne', 'e123-amarant'),
('E124', 'Nykockin', 'Färgämne', 'e124-nykockin'),
('E127', 'Erytrosin', 'Färgämne', 'e127-erytrosin'),
('E129', 'Allurarött AC', 'Färgämne', 'e129-allurarott-ac'),
('E131', 'Patentblått V', 'Färgämne', 'e131-patentblatt-v'),
('E132', 'Indigotin', 'Färgämne', 'e132-indigotin'),
('E133', 'Briljantblått FCF', 'Färgämne', 'e133-briljantblatt-fcf'),
('E140', 'Klorofyller', 'Färgämne', 'e140-klorofyller'),
('E141', 'Klorofyllkopparkomplex', 'Färgämne', 'e141-klorofyllkopparkomplex'),
('E142', 'Grön S', 'Färgämne', 'e142-gron-s'),
('E150a', 'Sockerkulör', 'Färgämne', 'e150a-sockerkulor'),
('E150b', 'Sockerkulör; kaustiksulfitprocessen', 'Färgämne', 'e150b-sockerkulor-kaustiksulfitprocessen'),
('E150c', 'Sockerkulör; ammoniakprocessen', 'Färgämne', 'e150c-sockerkulor-ammoniakprocessen'),
('E150d', 'Sockerkulör; ammoniaksulfitprocessen', 'Färgämne', 'e150d-sockerkulor-ammoniaksulfitprocessen'),
('E151', 'Briljantsvart PN', 'Färgämne', 'e151-briljantsvart-pn'),
('E153', 'Vegetabiliskt kol', 'Färgämne', 'e153-vegetabiliskt-kol'),
('E155', 'Brun HT', 'Färgämne', 'e155-brun-ht'),
('E160a', 'Karotener', 'Färgämne', 'e160a-karotener'),
('E160b', 'Annattoextrakt', 'Färgämne', 'e160b-annattoextrakt'),
('E160c', 'Paprikaoleoresin', 'Färgämne', 'e160c-paprikaoleoresin'),
('E160d', 'Lykopen', 'Färgämne', 'e160d-lykopen'),
('E160e', 'Beta-apo-8''-karotenal', 'Färgämne', 'e160e-beta-apo-8-karotenal'),
('E161b', 'Lutein', 'Färgämne', 'e161b-lutein'),
('E161g', 'Kantaxantin', 'Färgämne', 'e161g-kantaxantin'),
('E162', 'Rödbetsrött', 'Färgämne', 'e162-rodbetsrott'),
('E163', 'Antocyaner', 'Färgämne', 'e163-antocyaner'),
('E170', 'Kalciumkarbonat', 'Färgämne', 'e170-kalciumkarbonat'),
('E171', 'Titandioxid', 'Färgämne', 'e171-titandioxid'),
('E172', 'Järnoxider och järnhydroxider', 'Färgämne', 'e172-jarnoxider-och-jarnhydroxider'),
('E173', 'Aluminium', 'Färgämne', 'e173-aluminium'),
('E174', 'Silver', 'Färgämne', 'e174-silver'),
('E175', 'Guld', 'Färgämne', 'e175-guld'),
('E180', 'Litolrubin BK', 'Färgämne', 'e180-litolrubin-bk'),

-- Konserveringsmedel (Preservatives)
('E200', 'Sorbinsyra', 'Konserveringsmedel', 'e200-sorbinsyra'),
('E202', 'Kaliumsorbat', 'Konserveringsmedel', 'e202-kaliumsorbat'),
('E210', 'Bensoesyra', 'Konserveringsmedel', 'e210-bensoesyra'),
('E211', 'Natriumbensoat', 'Konserveringsmedel', 'e211-natriumbensoat'),
('E212', 'Kaliumbensoat', 'Konserveringsmedel', 'e212-kaliumbensoat'),
('E213', 'Kalciumbensoat', 'Konserveringsmedel', 'e213-kalciumbensoat'),
('E214', 'p-Hydroxibensoesyraetylester', 'Konserveringsmedel', 'e214-p-hydroxibensoesyraetylester'),
('E215', 'p-Hydroxibensoesyraetylesterns natriumsalt', 'Konserveringsmedel', 'e215-p-hydroxibensoesyraetylesterns-natriumsalt'),
('E218', 'p-Hydroxibensoesyrametylester', 'Konserveringsmedel', 'e218-p-hydroxibensoesyrametylester'),
('E219', 'p-Hydroxibensoesyrametylesterns natriumsalt', 'Konserveringsmedel', 'e219-p-hydroxibensoesyrametylesterns-natriumsalt'),
('E220', 'Svaveldioxid', 'Konserveringsmedel', 'e220-svaveldioxid'),
('E221', 'Natriumsulfit', 'Konserveringsmedel', 'e221-natriumsulfit'),
('E222', 'Natriumvätesulfit', 'Konserveringsmedel', 'e222-natriumvatesulfit'),
('E223', 'Natriumdisulfit', 'Konserveringsmedel', 'e223-natriumdisulfit'),
('E224', 'Kaliumdisulfit', 'Konserveringsmedel', 'e224-kaliumdisulfit'),
('E226', 'Kalciumsulfit', 'Konserveringsmedel', 'e226-kalciumsulfit'),
('E227', 'Kalciumvätesulfit', 'Konserveringsmedel', 'e227-kalciumvatesulfit'),
('E228', 'Kaliumvätesulfit', 'Konserveringsmedel', 'e228-kaliumvatesulfit'),
('E234', 'Nisin', 'Konserveringsmedel', 'e234-nisin'),
('E235', 'Natamycin', 'Konserveringsmedel', 'e235-natamycin'),
('E239', 'Hexametylentetramin', 'Konserveringsmedel', 'e239-hexametylentetramin'),
('E242', 'Dimetyldikarbonat', 'Konserveringsmedel', 'e242-dimetyldikarbonat'),
('E243', 'Etyllauroylarginat', 'Konserveringsmedel', 'e243-etyllauroylarginat'),
('E246', 'Glykolipider', 'Konserveringsmedel', 'e246-glykolipider'),
('E249', 'Kaliumnitrit', 'Konserveringsmedel', 'e249-kaliumnitrit'),
('E250', 'Natriumnitrit', 'Konserveringsmedel', 'e250-natriumnitrit'),
('E251', 'Natriumnitrat', 'Konserveringsmedel', 'e251-natriumnitrat'),
('E252', 'Kaliumnitrat', 'Konserveringsmedel', 'e252-kaliumnitrat'),
('E260', 'Ättiksyra', 'Konserveringsmedel', 'e260-attiksyra'),
('E261', 'Kaliumacetater', 'Konserveringsmedel', 'e261-kaliumacetater'),
('E262', 'Natriumacetater', 'Konserveringsmedel', 'e262-natriumacetater'),
('E263', 'Kalciumacetat', 'Konserveringsmedel', 'e263-kalciumacetat'),
('E267', 'Buffrad vinäger', 'Konserveringsmedel', 'e267-buffrad-vinager'),
('E270', 'Mjölksyra', 'Konserveringsmedel', 'e270-mjolksyra'),
('E280', 'Propionsyra', 'Konserveringsmedel', 'e280-propionsyra'),
('E281', 'Natriumpropionat', 'Konserveringsmedel', 'e281-natriumpropionat'),
('E282', 'Kalciumpropionat', 'Konserveringsmedel', 'e282-kalciumpropionat'),
('E283', 'Kaliumpropionat', 'Konserveringsmedel', 'e283-kaliumpropionat'),
('E284', 'Borsyra', 'Konserveringsmedel', 'e284-borsyra'),
('E285', 'Natriumtetraborat (borax)', 'Konserveringsmedel', 'e285-natriumtetraborat-borax'),
('E290', 'Koldioxid', 'Konserveringsmedel', 'e290-koldioxid'),
('E296', 'Äppelsyra', 'Konserveringsmedel', 'e296-appelsyra'),
('E297', 'Fumarsyra', 'Konserveringsmedel', 'e297-fumarsyra')
ON CONFLICT (e_number) DO NOTHING;