-- Add long descriptions for more essential foods
UPDATE foods SET long_description = 'Crème fraiche är en mjölkprodukt med hög fetthalt (cirka 34%) som har en mild, lätt syrlig smak. Den är rik på kalcium, protein och vitamin A. Till skillnad från vanlig grädde koagulerar inte crème fraiche när den värms upp, vilket gör den perfekt för såser och gratänger. Den innehåller levande mjölksyrabakterier som kan stödja tarmhälsan. Crème fraiche är mer mättande än lättare mejeriprodukter och ger en krämig konsistens till både varma och kalla rätter. Den håller sig längre än vanlig grädde och är mindre känslig för temperaturförändringar. Använd den sparsammt på grund av dess höga kaloriinnehåll.' WHERE slug = 'creme-fraiche';

UPDATE foods SET long_description = 'Entrecôte är en premium köttbit från nötkreaturets rygg som är känd för sin mörhet och rika smak. Den innehåller högkvalitativt protein (cirka 26 gram per 100 gram) med alla essentiella aminosyror. Entrecôte är rik på järn som är viktigt för syretransport i kroppen, samt B-vitaminer särskilt B12, niacin och B6. Den innehåller också zink för immunförsvaret och selen som antioxidant. Välj kött från betesdjur när det är möjligt för högre halter av omega-3-fettsyror. Kött bör tillagas till minst 60°C inuti för säkerhet. Låt köttet vila efter tillagning för jämnare saftfördelning.' WHERE slug = 'entrecote';

UPDATE foods SET long_description = 'Fetaost är en traditionell grekisk ost gjord på får- eller getmjölk som förvaras i saltlake. Den har en karakteristisk salt och krämig smak. Fetaost är rik på kalcium för benhälsa, protein för muskelbyggnad och probiotiska bakterier som kan gynna tarmfloran. Den innehåller också vitamin B12, riboflavin och fosfor. Fetaost har lägre kaloriinnehåll än många andra hårdostar och är naturligt laktosfri när den är vällagrad. Den är perfekt i sallader, på pizza, i gratänger eller som del av en meze. Skölj osten lätt om den är för salt. Förvara i kylskåp i egen lake för bästa hållbarhet.' WHERE slug = 'fetaost';

UPDATE foods SET long_description = 'Fläskfilé är en mager köttbit från grisens rygg som innehåller mycket protein (cirka 22 gram per 100 gram) och relativt lite fett. Den är rik på B-vitaminer, särskilt tiamin (B1) som är viktigt för energiomsättning, samt niacin och B6. Fläskfilé innehåller också järn, zink och selen. Det är viktigt att tillaga fläsk ordentligt till minst 70°C inuti för att undvika smittrisker. Fläskfilé kan snabbt bli torr vid övertillagning, så övervaka temperaturen noggrant. Marinera gärna köttet för extra smak och saftighet. Den är mångsidig och passar till allt från asiatiska wokar till svenska husmanskost.' WHERE slug = 'flaskfile';

UPDATE foods SET long_description = 'Grillkorv är en bearbetad köttprodukt som ofta innehåller en blandning av kött, fett och kryddor. Medan den är rik på protein (cirka 15-20 gram per 100 gram), innehåller den också höga halter av natrium och konserveringsmedel som nitriter. Grillkorv bör konsumeras i måttliga mängder som en del av en balanserad diet. Välj korv med hög kötthalt och utan onödiga tillsatser när det är möjligt. Grilla eller stek korven på måttlig värme för att undvika att skapa skadliga föreningar. Kombinera med grönsaker och fullkornsbröd för en mer balanserad måltid.' WHERE slug = 'grillkorv';

UPDATE foods SET long_description = 'Gurka består till 96% av vatten och är därför mycket kalorifattig (endast 12 kalorier per 100 gram) samtidigt som den är hydrerande. Den innehåller vitamin K för benhälsa, vitamin C för immunförsvaret och kalium för hjärtfunktion. Gurka innehåller också antioxidanter som beta-karoten och flavonoider som kan ha anti-inflammatoriska egenskaper. Skalet innehåller mest näringsämnen, så ät gärna gurkan med skalet efter noggrann tvätt. Gurka är perfekt som mellanmål, i sallader eller som del av detoxvatten. Förvara i kylskåp och konsumera inom en vecka för bästa kvalitet.' WHERE slug = 'gurka';