-- Komplettera E-ämnes databasen med alla saknade ämnen från Livsmedelsverket
-- Del 1: Färgämnen (E100-E199 serien)

INSERT INTO e_additives (
  e_number, name, common_name, category, slug, 
  short_description, long_description, risk_score, 
  adi_value, adi_source, origin, health_effects, 
  common_products, avoidance_tips, natural_alternatives,
  children_note, longevity_impact
) VALUES

-- E103 - Alkannin (förbjudet i Sverige men listat)
('E103', 'Alkannin', 'Chrysoin S', 'Färgämne', 'e103-alkannin',
'Rött färgämne från växten Alkanna tinctoria. Förbjudet i EU.',
'Alkannin är ett naturligt rött pigment som utvinns från roten av växten Alkanna tinctoria. Trots sitt naturliga ursprung har det förbjudits i EU på grund av potentiella hälsorisker.',
9, NULL, 'EU förbjudit', 'Växt (Alkanna tinctoria)',
'{"positive": [], "negative": ["Potentiellt cancerframkallande", "Förbjudet i EU sedan 1994"], "neutral": ["Naturligt pigment"]}',
'{"categories": [], "note": "Förbjudet att använda"}',
ARRAY['Kontrollera ingredienslistor noga', 'Undvik produkter från länder utanför EU'],
ARRAY['Rödbetsjuice', 'E162 (Rödbetsrött)', 'Naturliga antocyaner'],
'Särskilt viktigt att undvika för barn',
'Negativ - förbjudet på grund av cancerrisker'),

-- E105 - Fast Yellow AB (förbjudet)
('E105', 'Fast Yellow AB', 'Gul färg AB', 'Färgämne', 'e105-fast-yellow-ab',
'Syntetiskt gult färgämne som är förbjudet i EU.',
'Fast Yellow AB är en azoförebindelse som användes som gult livsmedelsfärgämne men förbjöds i EU på grund av hälsorisker.',
9, NULL, 'EU förbjudit', 'Syntetisk',
'{"positive": [], "negative": ["Förbjudet i EU", "Potentiellt allergiframkallande"], "neutral": ["Syntetiskt färgämne"]}',
'{"categories": [], "note": "Förbjudet att använda"}',
ARRAY['Läs ingredienslistor noggrant', 'Undvik import från länder med lösare regler'],
ARRAY['Kurkumin (E100)', 'Naturlig betakaroten', 'Saffran'],
'Undviks helt för barn',
'Negativ - förbjudet på grund av hälsorisker'),

-- E111 - Orange GGN (förbjudet)
('E111', 'Orange GGN', 'Alpha-naftolgulorange', 'Färgämne', 'e111-orange-ggn',
'Orangeött syntetiskt färgämne som förbjudits i EU.',
'Orange GGN är en azoförebindelse som tidigare användes som orangeött livsmedelsfärgämne men förbjöds på grund av potentiella hälsorisker.',
9, NULL, 'EU förbjudit', 'Syntetisk',
'{"positive": [], "negative": ["Förbjudet i EU", "Potentiellt cancerframkallande"], "neutral": []}',
'{"categories": [], "note": "Förbjudet att använda"}',
ARRAY['Undvik produkter från oreglerade marknader'],
ARRAY['Paprikaextrakt', 'Naturlig betakaroten'],
'Helt förbjudet för barn',
'Negativ - förbjudet substans'),

-- E125 - Ponceau SX (förbjudet i många länder)
('E125', 'Ponceau SX', 'Scharlakansrött SX', 'Färgämne', 'e125-ponceau-sx',
'Rött syntetiskt färgämne som är förbjudet i många länder.',
'Ponceau SX är en azoförebindelse som kan orsaka allergiska reaktioner och hyperaktivitet hos känsliga personer.',
8, NULL, 'Förbjudet i många länder', 'Syntetisk',
'{"positive": [], "negative": ["Kan orsaka hyperaktivitet", "Allergiframkallande", "Förbjudet i Norge och USA"], "neutral": ["Röd azofärg"]}',
'{"categories": ["Godis", "Bakverk"], "note": "Används sällan"}',
ARRAY['Undvik produkter med röda azofärger', 'Läs ingredienslistor noggrant'],
ARRAY['E162 (Rödbetsrött)', 'Naturliga antocyaner från bär'],
'Undviks för barn under 3 år',
'Negativ - kan påverka beteende hos barn'),

-- E128 - Red 2G (förbjudet)
('E128', 'Red 2G', 'Rött 2G', 'Färgämne', 'e128-red-2g',
'Rött syntetiskt färgämne som förbjudits i EU.',
'Red 2G var en azoförebindelse som förbjöds i EU 2007 efter att studier visat potentiella cancerrisker.',
9, NULL, 'EU förbjudit 2007', 'Syntetisk',
'{"positive": [], "negative": ["Förbjudet i EU", "Potentiellt cancerframkallande", "Kan brytas ner till anilin"], "neutral": []}',
'{"categories": [], "note": "Förbjudet sedan 2007"}',
ARRAY['Undvik gamla produkter eller import från oreglerade länder'],
ARRAY['Rödbetsjuice', 'Naturliga antocyaner'],
'Helt förbjudet för barn',
'Negativ - förbjudet på grund av cancerrisker'),

-- E150b - Sockerkulör kaustiksulfitprocessen
('E150b', 'Sockerkulör', 'Kaustiksulfitprocessen', 'Färgämne', 'e150b-sockerkulor-kaustiksulfit',
'Brun sockerkulör framställd genom kaustiksulfitprocessen.',
'Denna typ av sockerkulör framställs genom behandling av socker med kaustiksulfit. Används för att ge brun färg åt livsmedel.',
3, NULL, 'Ej fastställt', 'Socker',
'{"positive": ["Naturligt ursprung från socker"], "negative": [], "neutral": ["Vanlig livsmedelsfärg"]}',
'{"categories": ["Läsk", "Öl", "Såser", "Bakverk"], "note": "Vanligt i mörka drycker"}',
ARRAY['Generellt säkert att använda'],
ARRAY['Karamelliserat socker', 'Mörk sirap'],
'Säkert för barn',
'Neutral - väl studerat och säkert'),

-- E150c - Sockerkulör ammoniakprocessen  
('E150c', 'Sockerkulör', 'Ammoniakprocessen', 'Färgämne', 'e150c-sockerkulor-ammoniak',
'Brun sockerkulör framställd genom ammoniakprocessen.',
'Framställs genom behandling av socker med ammoniak. Kan innehålla spår av 4-metylimidazol som kan vara problematiskt i stora mängder.',
4, NULL, 'Ej fastställt', 'Socker',
'{"positive": ["Naturligt ursprung"], "negative": ["Kan innehålla 4-metylimidazol"], "neutral": ["Vanligt använt"]}',
'{"categories": ["Cola", "Mörka läsk", "Såser"], "note": "Vanligt i mörka drycker"}',
ARRAY['Måttlig konsumtion av produkter med E150c', 'Variera dryckesval'],
ARRAY['E150a (enkel sockerkulör)', 'Naturligt karamelliserat socker'],
'Måttlig användning för barn',
'Neutral till negativ - innehåller potentiellt problematiska ämnen'),

-- E153 - Vegetabiliskt kol
('E153', 'Vegetabiliskt kol', 'Kolsvart', 'Färgämne', 'e153-vegetabiliskt-kol',
'Svart färgämne framställt från förkolnat växtmaterial.',
'Framställs genom förkolarning av växtmaterial som trä, nötter eller fruktkärnor. Används för att ge svart färg.',
2, NULL, 'Quantum satis', 'Växtmaterial',
'{"positive": ["Naturligt ursprung", "Väl tolererat"], "negative": [], "neutral": ["Ger svart färg"]}',
'{"categories": ["Godis", "Glass", "Kaviarsimulation", "Dekorationer"], "note": "Används för svart färg"}',
ARRAY['Generellt säkert'],
ARRAY['Aktivt kol (ej för färgning)', 'Naturligt svart från bläck från bläckfisk'],
'Säkert för barn',
'Neutral - naturligt och säkert'),

-- E154 - Brun FK (förbjudet)
('E154', 'Brun FK', 'Food Brown 3', 'Färgämne', 'e154-brun-fk',
'Brunt syntetiskt färgämne som förbjudits i EU.',
'Brun FK var en syntetisk brun färg som förbjöds i EU på grund av potentiella hälsorisker.',
9, NULL, 'EU förbjudit', 'Syntetisk',
'{"positive": [], "negative": ["Förbjudet i EU", "Potentiella hälsorisker"], "neutral": []}',
'{"categories": [], "note": "Förbjudet"}',
ARRAY['Undvik helt'],
ARRAY['E150a (Sockerkulör)', 'Karamell', 'Naturlig kakao'],
'Förbjudet för barn',
'Negativ - förbjudet substans'),

-- E160f - Etylester av beta-apo-8-karotenal
('E160f', 'Etylester av beta-apo-8-karotenal', 'Apokarotenal etylester', 'Färgämne', 'e160f-apokarotenal-etyl',
'Orange färgämne besläktat med betakaroten.',
'En syntetisk variant av karotenoider som ger orange färg. Används sparsamt i livsmedel.',
4, 5, 'mg/kg kroppsvikt/dag - EFSA', 'Syntetisk karotenoid',
'{"positive": ["Relaterat till vitamin A"], "negative": [], "neutral": ["Syntetisk karotenoid"]}',
'{"categories": ["Margarin", "Ost", "Bakverk"], "note": "Begränsad användning"}',
ARRAY['Håll dig inom rekommenderat ADI-värde'],
ARRAY['E160a (Naturlig betakaroten)', 'Morötter', 'Pumpapuré'],
'Säkert i normala mängder för barn',
'Neutral - säkert vid normal användning'),

-- E161a - Flavoxantin
('E161a', 'Flavoxantin', 'Gul xantofyll', 'Färgämne', 'e161a-flavoxantin',
'Gult naturligt pigment från gruppen xantofyller.',
'Ett naturligt gult pigment som finns i många gula blommor och frukter. Används sällan kommersiellt.',
2, NULL, 'Ej fastställt', 'Naturlig xantofyll',
'{"positive": ["Naturligt pigment", "Antioxidantegenskaper"], "negative": [], "neutral": ["Sällan använt"]}',
'{"categories": [], "note": "Mycket sällan använt"}',
ARRAY['Generellt säkert'],
ARRAY['Naturlig kurkumin', 'Saffran'],
'Säkert för barn',
'Positiv - naturligt antioxidant'),

-- E161c - Kryptoxantin
('E161c', 'Kryptoxantin', 'Beta-kryptoxantin', 'Färgämne', 'e161c-kryptoxantin',
'Orange-gult naturligt pigment med provitamin A-aktivitet.',
'Ett naturligt karotenoidpigment som finns i citrusfrukter och kan omvandlas till vitamin A i kroppen.',
1, NULL, 'Quantum satis', 'Naturlig karotenoid',
'{"positive": ["Provitamin A", "Naturligt", "Antioxidant"], "negative": [], "neutral": ["Sällan tillsatt"]}',
'{"categories": ["Juicer", "Fruktprodukter"], "note": "Naturligt förekommande"}',
ARRAY['Helt säkert'],
ARRAY['Färsk apelsin', 'Persika', 'Papaja'],
'Mycket säkert för barn',
'Positiv - näringsrikt och naturligt'),

-- E161d - Rubixantin
('E161d', 'Rubixantin', 'Röd xantofyll', 'Färgämne', 'e161d-rubixantin',
'Rött naturligt pigment från xantofyllgruppen.',
'Ett naturligt rött pigment som finns i vissa växter och alger. Används mycket sällan kommersiellt.',
2, NULL, 'Ej fastställt', 'Naturlig xantofyll',
'{"positive": ["Naturligt pigment"], "negative": [], "neutral": ["Extremt sällan använt"]}',
'{"categories": [], "note": "Praktiskt taget ej använt"}',
ARRAY['Inga särskilda försiktighetsåtgärder'],
ARRAY['Naturliga röda pigment från tomater'],
'Säkert för barn',
'Neutral - naturligt men sällan använt'),

-- E161e - Violaxantin  
('E161e', 'Violaxantin', 'Violett xantofyll', 'Färgämne', 'e161e-violaxantin',
'Violett naturligt pigment från xantofyllgruppen.',
'Ett naturligt pigment som bidrar till höstfärgerna i löv. Används inte kommersiellt som livsmedelsfärg.',
2, NULL, 'Ej fastställt', 'Naturlig xantofyll',
'{"positive": ["Naturligt pigment"], "negative": [], "neutral": ["Ej kommersiell användning"]}',
'{"categories": [], "note": "Ej använt kommersiellt"}',
ARRAY['Inga kända risker'],
ARRAY['Naturliga violetta pigment från rödkål'],
'Säkert för barn',
'Neutral - naturligt pigment'),

-- E161f - Rodoxantin
('E161f', 'Rodoxantin', 'Röd xantofyll', 'Färgämne', 'e161f-rodoxantin',
'Rött naturligt pigment från xantofyllgruppen.',
'Ett naturligt rött pigment som finns i vissa alger och växter. Ej kommersiellt använt.',
2, NULL, 'Ej fastställt', 'Naturlig xantofyll',
'{"positive": ["Naturligt pigment"], "negative": [], "neutral": ["Ej kommersiellt använt"]}',
'{"categories": [], "note": "Teoretisk status"}',
ARRAY['Inga kända risker'],
ARRAY['Naturligt lykopen från tomater'],
'Säkert för barn',
'Neutral - naturligt pigment'),

-- E161h - Zeaxantin
('E161h', 'Zeaxantin', 'Gul-orange xantofyll', 'Färgämne', 'e161h-zeaxantin',
'Gul-orange naturligt pigment viktigt för ögonhälsa.',
'Ett naturligt karotenoidpigment som är viktigt för ögonens gula fläck (makula). Finns naturligt i majs och gröna grönsaker.',
1, NULL, 'Quantum satis', 'Naturlig karotenoid',
'{"positive": ["Ögonhälsa", "Antioxidant", "Naturligt"], "negative": [], "neutral": ["Sällan tillsatt"]}',
'{"categories": ["Kosttillskott", "Funktionella livsmedel"], "note": "Hälsofrämjande"}',
ARRAY['Helt säkert', 'Kan vara fördelaktigt'],
ARRAY['Färsk majs', 'Spenat', 'Äggula'],
'Fördelaktigt för barn',
'Positiv - hälsofrämjande naturligt ämne'),

-- E161i - Citranaxantin  
('E161i', 'Citranaxantin', 'Orange xantofyll', 'Färgämne', 'e161i-citranaxantin',
'Orange naturligt pigment från citrusfrukter.',
'Ett naturligt orange pigment som finns i citrusfrukternas skal. Används sällan kommersiellt.',
2, NULL, 'Ej fastställt', 'Naturlig xantofyll',
'{"positive": ["Naturligt från citrus"], "negative": [], "neutral": ["Mycket sällan använt"]}',
'{"categories": [], "note": "Sällan använt"}',
ARRAY['Inga särskilda risker'],
ARRAY['Färska apelsinskal', 'Naturlig betakaroten'],
'Säkert för barn',
'Neutral - naturligt pigment'),

-- E161j - Astaxantin
('E161j', 'Astaxantin', 'Röd ketokarotenoid', 'Färgämne', 'e161j-astaxantin',
'Rött naturligt pigment med starka antioxidantegenskaper.',
'Ett kraftfullt antioxidant som ger lax och räkor deras röda färg. Används i fiskfoder och kosttillskott.',
1, NULL, 'Quantum satis', 'Naturlig karotenoid',
'{"positive": ["Kraftfullt antioxidant", "Naturligt", "Anti-inflammatorisk"], "negative": [], "neutral": ["Dyr att producera"]}',
'{"categories": ["Laxfoder", "Kosttillskott", "Funktionella livsmedel"], "note": "Hälsofrämjande"}',
ARRAY['Helt säkert', 'Fördelaktigt för hälsan'],
ARRAY['Vildlax', 'Räkor', 'Kräftor'],
'Fördelaktigt för barn',
'Positiv - mycket hälsofrämjande naturligt ämne');

-- Fortsätt med nästa batch...
INSERT INTO e_additives (
  e_number, name, common_name, category, slug, 
  short_description, long_description, risk_score, 
  adi_value, adi_source, origin, health_effects, 
  common_products, avoidance_tips, natural_alternatives,
  children_note, longevity_impact
) VALUES

-- E201 - Natriumsorbat
('E201', 'Natriumsorbat', 'Sorbinsyrans natriumsalt', 'Konserveringsmedel', 'e201-natriumsorbat',
'Natriumsalt av sorbinsyra, effektivt konserveringsmedel.',
'Natriumsorbat är natriumsaltet av sorbinsyra och fungerar på samma sätt som E200. Det är vattenlösligt och används för att förhindra mögel och jäst.',
2, 25, 'mg/kg kroppsvikt/dag - WHO/FAO', 'Syntetisk/naturlig',
'{"positive": ["Effektiv konservering", "Låg toxicitet"], "negative": [], "neutral": ["Vanligt använt"]}',
'{"categories": ["Bröd", "Ost", "Vin", "Torkad frukt"], "note": "Vanligt konserveringsmedel"}',
ARRAY['Säkert vid normal användning'],
ARRAY['Kylförvaring', 'Saltning', 'Rökning'],
'Säkert för barn',
'Neutral - säkert konserveringsmedel'),

-- E203 - Kalciumsorbat
('E203', 'Kalciumsorbat', 'Sorbinsyrans kalciumsalt', 'Konserveringsmedel', 'e203-kalciumsorbat',
'Kalciumsalt av sorbinsyra för konservering.',
'Kalciumsorbat är kalciumsaltet av sorbinsyra. Används som konserveringsmedel mot mögel och jäst.',
2, 25, 'mg/kg kroppsvikt/dag - WHO/FAO', 'Syntetisk',
'{"positive": ["Effektiv mot mögel", "Relativt säkert"], "negative": [], "neutral": ["Mindre vanligt än E200/E202"]}',
'{"categories": ["Bakverk", "Ost", "Pålägg"], "note": "Används mer sällan"}',
ARRAY['Normalt säkert att konsumera'],
ARRAY['Naturlig konservering', 'Kylning'],
'Säkert för barn',
'Neutral - säkert konserveringsmedel'),

-- E216 - p-Hydroxibensoesyrapropylester (Propylparaben)
('E216', 'p-Hydroxibensoesyrapropylester', 'Propylparaben', 'Konserveringsmedel', 'e216-propylparaben',
'Propylester av p-hydroxibensoesyra, konserveringsmedel.',
'Propylparaben är en paraben som används som konserveringsmedel. Finns naturligt i vissa växter men produceras huvudsakligen syntetiskt.',
5, 10, 'mg/kg kroppsvikt/dag - EFSA', 'Syntetisk/naturlig',
'{"positive": ["Effektivt konserveringsmedel"], "negative": ["Hormonliknande effekter", "Allergiframkallande"], "neutral": ["Parabenfamiljen"]}',
'{"categories": ["Bakverk", "Kosmetika", "Vissa livsmedel"], "note": "Minskad användning"}',
ARRAY['Undvik vid känslig hud', 'Begränsa exponering'],
ARRAY['Naturliga antioxidanter', 'Kylförvaring'],
'Försiktighet för känsliga barn',
'Negativ - potentiella hormoneffekter'),

-- E217 - p-Hydroxibensoesyrapropylesters natriumsalt
('E217', 'p-Hydroxibensoesyrapropylesters natriumsalt', 'Natriumsalt av propylparaben', 'Konserveringsmedel', 'e217-natrium-propylparaben',
'Natriumsalt av propylparaben, konserveringsmedel.',
'Natriumsaltet av propylparaben. Har samma egenskaper som E216 men är mer vattenlösligt.',
5, 10, 'mg/kg kroppsvikt/dag - EFSA', 'Syntetisk',
'{"positive": ["Vattenlösligt"], "negative": ["Samma risker som E216", "Hormonpåverkan"], "neutral": ["Paraben"]}',
'{"categories": ["Livsmedel", "Kosmetika"], "note": "Begränsad användning"}',
ARRAY['Samma försiktighet som E216'],
ARRAY['Naturlig konservering'],
'Försiktighet för barn',
'Negativ - hormonliknande effekter'),

-- E219 - p-Hydroxibensoesyrametylesterns natriumsalt
('E219', 'p-Hydroxibensoesyrametylesterns natriumsalt', 'Natriumsalt av metylparaben', 'Konserveringsmedel', 'e219-natrium-metylparaben',
'Natriumsalt av metylparaben, konserveringsmedel.',
'Natriumsaltet av metylparaben (E218). Vattenlösligt konserveringsmedel med liknande egenskaper som andra parabener.',
4, 10, 'mg/kg kroppsvikt/dag - EFSA', 'Syntetisk',
'{"positive": ["Effektiv konservering"], "negative": ["Paraben", "Potentiella hormoneffekter"], "neutral": ["Vattenlösligt"]}',
'{"categories": ["Bakverk", "Såser", "Kosmetika"], "note": "Begränsad användning"}',
ARRAY['Begränsa exponering', 'Undvik vid allergi'],
ARRAY['E200-serien (sorbater)', 'Naturlig konservering'],
'Försiktighet för barn',
'Negativ - paraben med potentiella risker'),

-- E222 - Natriumvätesulfit
('E222', 'Natriumvätesulfit', 'Natriumbisulfit', 'Konserveringsmedel', 'e222-natriumvatesulfit',
'Svavelhaltigt konserveringsmedel och antioxidant.',
'Natriumvätesulfit frigör svaveldioxid och fungerar både som konserveringsmedel och antioxidant. Kan orsaka allergiska reaktioner.',
6, 0.7, 'mg/kg kroppsvikt/dag - WHO/FAO', 'Syntetisk',
'{"positive": ["Effektiv konservering", "Antioxidant"], "negative": ["Allergiframkallande", "Astma", "B1-vitaminförstöring"], "neutral": ["Svavelförebindelse"]}',
'{"categories": ["Vin", "Torkad frukt", "Färsk frukt", "Potatis"], "note": "Vanligt i vin"}',
ARRAY['Undvik vid svavelkänslighet', 'Allergiker ska vara försiktiga', 'Kan förstöra B1-vitamin'],
ARRAY['Askorbinsyra (E300)', 'Naturliga antioxidanter', 'Kylning'],
'Undvik för barn med astma',
'Negativ - allergiframkallande och vitaminförstörande'),

-- E226 - Kalciumsulfit
('E226', 'Kalciumsulfit', 'Kalciumsalt av svavelsyrlighet', 'Konserveringsmedel', 'e226-kalciumsulfit',
'Kalciumsalt som frigör svaveldioxid för konservering.',
'Kalciumsulfit fungerar genom att frigöra svaveldioxid som har konserverande och antioxiderande effekt.',
6, 0.7, 'mg/kg kroppsvikt/dag - WHO/FAO', 'Syntetisk',
'{"positive": ["Effektiv konservering"], "negative": ["Samma risker som svaveldioxid", "Allergiframkallande"], "neutral": ["Kalciumsalt"]}',
'{"categories": ["Torkad frukt", "Vissa bageriprodukter"], "note": "Mindre vanligt"}',
ARRAY['Samma försiktighet som för svaveldioxid'],
ARRAY['Naturlig antioxidanter', 'Kylning'],
'Försiktighet för astmatiska barn',
'Negativ - allergiframkallande potential'),

-- E228 - Kaliumvätesulfit  
('E228', 'Kaliumvätesulfit', 'Kaliumbisulfit', 'Konserveringsmedel', 'e228-kaliumvatesulfit',
'Kaliumsalt som fungerar som konserveringsmedel.',
'Kaliumvätesulfit frigör svaveldioxid och har samma egenskaper som andra sulfiter.',
6, 0.7, 'mg/kg kroppsvikt/dag - WHO/FAO', 'Syntetisk',
'{"positive": ["Konserverande effekt"], "negative": ["Allergiframkallande", "Astmautlösande"], "neutral": ["Kaliumsalt"]}',
'{"categories": ["Vin", "Fruktprodukter"], "note": "Används i vinindustrin"}',
ARRAY['Undvik vid svavelkänslighet'],
ARRAY['Naturlig konservering', 'Kylning'],
'Undvik för barn med andningsproblem',
'Negativ - allergiframkallande'),

-- E242 - Dimetyldikarbonat  
('E242', 'Dimetyldikarbonat', 'DMDC', 'Konserveringsmedel', 'e242-dimetyldikarbonat',
'Konserveringsmedel som bryts ner snabbt i vätskor.',
'Dimetyldikarbonat är ett konserveringsmedel som huvudsakligen används i drycker. Det bryts ner snabbt till koldioxid och metanol.',
4, 'Ej fastställt', 'Bryts ner snabbt', 'Syntetisk',
'{"positive": ["Bryts ner snabbt", "Effektiv mot jäst"], "negative": ["Bildade metanol"], "neutral": ["Används i drycker"]}',
'{"categories": ["Vin", "Äppelcider", "Fruktjuicer"], "note": "Huvudsakligen drycker"}',
ARRAY['Generellt säkert vid godkända nivåer'],
ARRAY['Pastörisering', 'Sterilfiltrering'],
'Säkert för barn i normala mängder',
'Neutral - bryts ner snabbt'),

-- E243 - Etyllauroylarginat
('E243', 'Etyllauroylarginat', 'LAE', 'Konserveringsmedel', 'e243-etyllauroylarginat',
'Konserveringsmedel framställt från naturliga aminosyror.',
'Etyllauroylarginat är ett konserveringsmedel baserat på aminosyrorna arginin och laurinsyra. Bryts ner till naturliga komponenter.',
3, 5, 'mg/kg kroppsvikt/dag - EFSA', 'Semi-naturlig',
'{"positive": ["Bryts ner naturligt", "Baserat på aminosyror"], "negative": [], "neutral": ["Relativt nytt"]}',
'{"categories": ["Kött", "Sallader", "Färdigmat"], "note": "Relativt ny konserveringsmetod"}',
ARRAY['Generellt säkert'],
ARRAY['Naturliga aminosyror', 'Kylning'],
'Säkert för barn',
'Positiv - naturligt nedbrytbar'),

-- E246 - Glykolipider
('E246', 'Glykolipider', 'Sukrosestrar', 'Konserveringsmedel', 'e246-glykolipider',
'Naturliga föreningar med konserverande egenskaper.',
'Glykolipider är naturliga föreningar som består av socker bundna till lipider. De har antimikrobiella egenskaper.',
2, NULL, 'Ej fastställt', 'Naturlig',
'{"positive": ["Naturlig ursprung", "Milt konserveringsmedel"], "negative": [], "neutral": ["Sällan använt"]}',
'{"categories": [], "note": "Mycket begränsad användning"}',
ARRAY['Inga kända risker'],
ARRAY['Andra naturliga konserveringsmedel'],
'Säkert för barn',
'Positiv - naturligt ursprung'),

-- E261 - Kaliumacetater
('E261', 'Kaliumacetater', 'Kaliumsalt av ättiksyra', 'Konserveringsmedel', 'e261-kaliumacetat',
'Kaliumsalt av ättiksyra, används som konserveringsmedel.',
'Kaliumacetat är kaliumsaltet av ättiksyra. Används som konserveringsmedel och pH-regulator.',
2, NULL, 'Quantum satis', 'Naturlig/syntetisk',
'{"positive": ["Naturlig syra", "Säker"], "negative": [], "neutral": ["Mild konservering"]}',
'{"categories": ["Bröd", "Konserver", "Såser"], "note": "Mild konserveringseffekt"}',
ARRAY['Mycket säkert'],
ARRAY['Naturlig ättiksyra', 'Fermentering'],
'Helt säkert för barn',
'Positiv - naturligt och säkert'),

-- E262 - Natriumacetater
('E262', 'Natriumacetater', 'Natriumsalt av ättiksyra', 'Konserveringsmedel', 'e262-natriumacetat',
'Natriumsalt av ättiksyra, konserveringsmedel och smakförstärkare.',
'Natriumacetat är natriumsaltet av ättiksyra. Används som konserveringsmedel och kan förstärka salt- och syrlig smak.',
2, NULL, 'Quantum satis', 'Naturlig/syntetisk',
'{"positive": ["Från naturlig ättiksyra", "Säker"], "negative": [], "neutral": ["Smakpåverkan"]}',
'{"categories": ["Snacks", "Såser", "Pickles"], "note": "Ger syrlig smak"}',
ARRAY['Helt säkert'],
ARRAY['Naturlig vinäger', 'Citronsyra'],
'Säkert för barn',
'Positiv - naturligt ursprung'),

-- E263 - Kalciumacetat
('E263', 'Kalciumacetat', 'Kalciumsalt av ättiksyra', 'Konserveringsmedel', 'e263-kalciumacetat',
'Kalciumsalt av ättiksyra för konservering och pH-kontroll.',
'Kalciumacetat fungerar som konserveringsmedel och pH-regulator. Tillför också kalcium.',
2, NULL, 'Quantum satis', 'Naturlig/syntetisk',
'{"positive": ["Kalciumkälla", "Naturlig syra"], "negative": [], "neutral": ["Mild effekt"]}',
'{"categories": ["Bageriprodukter", "Konserver"], "note": "Tillför kalcium"}',
ARRAY['Fördelaktigt för kalciumintag'],
ARRAY['Naturlig ättiksyra', 'Kalciumkarbonat'],
'Fördelaktigt för barn (kalcium)',
'Positiv - naturligt och näring'),

-- E267 - Buffrad vinäger
('E267', 'Buffrad vinäger', 'Dehydrerad vinäger', 'Konserveringsmedel', 'e267-buffrad-vinager',
'Koncentrerad vinäger med konserverande egenskaper.',
'Buffrad vinäger är en koncentrerad form av vinäger som används som naturligt konserveringsmedel.',
1, NULL, 'Quantum satis', 'Naturlig',
'{"positive": ["Helt naturlig", "Traditionell konservering"], "negative": [], "neutral": ["Syrlig smak"]}',
'{"categories": ["Pickles", "Såser", "Marinader"], "note": "Naturlig konservering"}',
ARRAY['Helt säkert och naturligt'],
ARRAY['Färsk vinäger', 'Citronsyra'],
'Mycket säkert för barn',
'Positiv - helt naturligt konserveringsmedel');