-- Add more important E-additives to continue building the database
INSERT INTO e_additives (
  e_number, name, common_name, slug, category, origin, risk_score, longevity_impact,
  adi_value, adi_source, children_note, health_effects, common_products,
  avoidance_tips, natural_alternatives, short_description, long_description,
  meta_title, meta_description
) VALUES 
(
  'E234',
  'Nisin',
  'Nisin',
  'e234-nisin',
  'Konserveringsmedel',
  'Naturlig (bakteriell fermentation)',
  3,
  'Neutral',
  NULL,
  'EFSA',
  'Generellt säkert för barn i godkända mängder',
  '{"documented": ["Allergiska reaktioner (sällsynt)", "Magtarmbesvär vid höga doser"], "suspected": [], "benefits": ["Naturligt konserveringsmedel", "Effektivt mot vissa bakterier"], "risk_groups": ["Personer med mjölkallergi"]}',
  '[{"category": "Mejeriprodukter", "products": ["Processad ost", "Smältost", "Färskost"], "average_amount": "2-10 mg/kg"}, {"category": "Konserver", "products": ["Kött- och fiskkonserver", "Färdigmat"], "average_amount": "1-5 mg/kg"}]',
  '["Välj opastöriserade mejeriprodukter", "Läs ingrediensförteckningar noga", "Välj färska produkter när möjligt"]',
  '["Naturlig syra (citronsyra)", "Salt", "Kylförvaring", "Vinäger"]',
  'Naturligt konserveringsmedel från bakterier som används främst i mejeriprodukter',
  'Nisin är ett naturligt konserveringsmedel som produceras av bakterien Lactococcus lactis. Det används främst i mejeriprodukter och konserver för att förhindra tillväxt av skadliga bakterier. Nisin anses vara säkert och är godkänt för användning i de flesta länder. Det kan dock orsaka allergiska reaktioner hos personer som är känsliga för mjölkprodukter.',
  'E234 Nisin - Natural konserveringsmedel, säkerhet och hälsoeffekter',
  'Lär dig om E234 Nisin, ett naturligt konserveringsmedel som används i mejeriprodukter. Information om säkerhet, hälsoeffekter och var det förekommer.'
),
(
  'E306',
  'Tokoferolrik extrakt',
  'Naturligt vitamin E-extrakt',
  'e306-tokoferolrik-extrakt',
  'Antioxidant',
  'Naturlig (växtolja)',
  2,
  'Positiv',
  NULL,
  'EFSA',
  'Säkert för barn, kan till och med vara fördelaktigt',
  '{"documented": [], "suspected": [], "benefits": ["Vitamin E-tillskott", "Skyddar mot oxidation", "Stöder immunsystemet"], "risk_groups": []}',
  '[{"category": "Oljor och fetter", "products": ["Vegetabiliska oljor", "Margarin", "Smör"], "average_amount": "100-800 mg/kg"}, {"category": "Flingor och spannmål", "products": ["Müsli", "Cornflakes", "Fullkornsprodukter"], "average_amount": "50-200 mg/kg"}]',
  '["Redan naturligt närvarande i många livsmedel", "Inte nödvändigt att undvika"]',
  '["Naturliga nötter och frön", "Vegetabiliska oljor", "Gröna bladgrönsaker"]',
  'Naturligt vitamin E-extrakt som används som antioxidant i livsmedel',
  'Tokoferolrik extrakt är en blandning av naturliga tokoferole (vitamin E) som utvinns från vegetabiliska oljor. Det används som antioxidant för att förhindra harskhet i fetter och oljor. Denna tillsats är inte bara säker utan också näringsmässigt fördelaktig eftersom den tillför vitamin E till kosten. Tokoferole är viktiga för att skydda cellerna mot oxidativ stress.',
  'E306 Tokoferolrik extrakt - Naturligt vitamin E som antioxidant',
  'Upptäck E306 Tokoferolrik extrakt, en naturlig vitamin E-källa som används som antioxidant. Läs om fördelar, säkerhet och förekomst i livsmedel.'
),
(
  'E307',
  'alfa-Tokoferol',
  'Vitamin E',
  'e307-alfa-tokoferol',
  'Antioxidant',
  'Naturlig eller syntetisk',
  1,
  'Positiv',
  NULL,
  'EFSA',
  'Säkert och fördelaktigt för barn',
  '{"documented": [], "suspected": [], "benefits": ["Vitamin E-tillskott", "Cellskydd", "Stärker immunförsvaret", "Motverkar åldrande"], "risk_groups": []}',
  '[{"category": "Kosttillskott", "products": ["Multivitaminer", "Vitamin E-kapslar", "Antioxidantblandningar"], "average_amount": "5-100 mg per dos"}, {"category": "Berikade livsmedel", "products": ["Flingor", "Barnmat", "Drycker"], "average_amount": "2-15 mg/100g"}]',
  '["Inte nödvändigt att undvika", "Kan vara fördelaktigt att konsumera"]',
  '["Mandlar", "Solrosfrön", "Havre", "Spenat", "Avokado"]',
  'Rent vitamin E som används som antioxidant och näringstillskott',
  'Alfa-tokoferol är den mest aktiva formen av vitamin E och används både som antioxidant i livsmedel och som näringstillskott. Det är essentiellt för människors hälsa och skyddar cellmembranen mot oxidativ skada. Alfa-tokoferol kan vara antingen naturligt utvunnet från växtoljor eller syntetiskt framställt. Det anses vara helt säkert och till och med fördelaktigt för hälsan.',
  'E307 Alfa-tokoferol - Vitamin E för hälsa och konservering',
  'Lär dig om E307 Alfa-tokoferol, den aktiva formen av vitamin E. Information om hälsofördelar, säkerhet och användning som antioxidant.'
),
(
  'E315',
  'Isoaskorbinsyra',
  'Erytorbinsyra',
  'e315-isoaskorbinsyra',
  'Antioxidant',
  'Syntetisk',
  3,
  'Neutral',
  NULL,
  'EFSA',
  'Säkert för barn i normala mängder',
  '{"documented": ["Magtarmbesvär vid mycket höga doser"], "suspected": [], "benefits": ["Förhindrar oxidation", "Bibehåller färg i kött"], "risk_groups": []}',
  '[{"category": "Charkprodukter", "products": ["Korv", "Skinka", "Bacon", "Salami"], "average_amount": "50-500 mg/kg"}, {"category": "Konserverat kött", "products": ["Köttkonserver", "Färdigmat med kött"], "average_amount": "100-300 mg/kg"}]',
  '["Välj färskt kött istället för chark", "Begränsa konsumtion av processad kött", "Läs ingredienslistor"]',
  '["Askorbinsyra (C-vitamin)", "Citronsyra", "Naturliga antioxidanter"]',
  'Syntetisk antioxidant som används främst i köttprodukter för att bevara färg',
  'Isoaskorbinsyra är en syntetisk förening som liknar askorbinsyra (vitamin C) men saknar dess vitaminaktivitet. Den används främst i köttprodukter för att förhindra oxidation och bibehålla den röda färgen. Även om den är godkänd som säker, har den inte samma hälsofördelar som äkta vitamin C. I stora mängder kan den orsaka magtarmbesvär.',
  'E315 Isoaskorbinsyra - Antioxidant i köttprodukter, skillnad från vitamin C',
  'Förstå E315 Isoaskorbinsyra, en antioxidant som används i chark och köttprodukter. Lär dig om säkerhet och skillnader från vitamin C.'
),
(
  'E316',
  'Natriumisoaskorbat',
  'Natriumsalt av isoaskorbinsyra',
  'e316-natriumisoaskorbat',
  'Antioxidant',
  'Syntetisk',
  3,
  'Neutral',
  NULL,
  'EFSA',
  'Säkert för barn, men begränsa konsumtion av processade produkter',
  '{"documented": ["Högt natriumintag"], "suspected": [], "benefits": ["Effektiv antioxidant", "Förlänger hållbarhet"], "risk_groups": ["Personer med högt blodtryck", "Hjärt-kärlsjuka"]}',
  '[{"category": "Charkprodukter", "products": ["Korv", "Skinka", "Frankfurterkorv"], "average_amount": "50-500 mg/kg"}, {"category": "Fryst kött", "products": ["Frysta köttbullar", "Fryst färdigmat"], "average_amount": "100-400 mg/kg"}]',
  '["Begränsa chark och processerat kött", "Välj färska alternativ", "Kontrollera natriumintag"]',
  '["Askorbinsyra", "Naturligt vitamin C", "Citronsyra"]',
  'Natriumsalt av isoaskorbinsyra, används som antioxidant i köttprodukter',
  'Natriumisoaskorbat är natriumsaltet av isoaskorbinsyra och används som antioxidant främst i köttprodukter. Det hjälper till att bevara färg och smak samt förhindrar harskhet. Tillsatsen är säker men bidrar till natriumintaget, vilket kan vara problematiskt för personer med högt blodtryck. Som med isoaskorbinsyra saknar det vitaminaktivitet jämfört med äkta vitamin C.',
  'E316 Natriumisoaskorbat - Antioxidant med natriuminnehåll',
  'Lär dig om E316 Natriumisoaskorbat, en antioxidant i köttprodukter. Information om säkerhet, natriuminnehåll och hälsoeffekter.'
),
(
  'E551',
  'Kiseldioxid',
  'Kisel, silika',
  'e551-kiseldioxid',
  'Klumpförebyggande medel',
  'Mineraliskt',
  4,
  'Negativ',
  NULL,
  'EFSA',
  'Undvik nanopartiklar, begränsa intag för barn',
  '{"documented": ["Lungproblem vid inandning", "Mag-tarmbesvär vid höga doser"], "suspected": ["Absorption av nanopartiklar", "Inflammatoriska effekter"], "risk_groups": ["Barn", "Personer med lungproblem", "Äldre"]}',
  '[{"category": "Kryddor och såser", "products": ["Pulverform kryddor", "Soppulver", "Såsmixer"], "average_amount": "10-20 g/kg"}, {"category": "Kosttillskott", "products": ["Pulvertillskott", "Tabletter"], "average_amount": "5-10 g/kg"}]',
  '["Välj färska kryddor istället för pulver", "Undvik mycket processade produkter", "Kontrollera ingredienslistor på kosttillskott"]',
  '["Majsstärkelse", "Rismjöl", "Tapiokastärkelse"]',
  'Mineraliskt klumpförebyggande medel som kan innehålla nanopartiklar',
  'Kiseldioxid används som klumpförebyggande medel i pulverformiga produkter för att förhindra att de klumpar ihop sig. Det finns oro kring nanopartiklar av kiseldioxid som kan ha negativa hälsoeffekter. Medan normala partiklar anses säkra, kan nanopartiklar potentiellt absorberas av kroppen och orsaka inflammation. EFSA håller på att utvärdera säkerheten för nanoformerna.',
  'E551 Kiseldioxid - Klumpförebyggande medel med potentiella risker',
  'Förstå E551 Kiseldioxid, ett klumpförebyggande medel. Lär dig om nanopartiklar, hälsorisker och var det används i livsmedel.'
),
(
  'E180',
  'Litolrubin BK',
  'Rubinpigment',
  'e180-litolrubin-bk',
  'Färgämne',
  'Syntetisk',
  6,
  'Negativ',
  0.1,
  'EFSA',
  'Ska undvikas av barn, kan orsaka hyperaktivitet',
  '{"documented": ["Hyperaktivitet hos barn", "Allergiska reaktioner", "Astma"], "suspected": ["ADHD-symptom", "Inlärningssvårigheter"], "risk_groups": ["Barn", "Personer med astma", "Allergiker"]}',
  '[{"category": "Konfektyr", "products": ["Röda godisar", "Marsipan", "Choklad"], "average_amount": "10-50 mg/kg"}, {"category": "Bakverk", "products": ["Tårtor", "Kakor", "Muffins"], "average_amount": "5-25 mg/kg"}]',
  '["Undvik produkter med röd färg", "Läs ingredienslistor noga", "Välj naturfärgade alternativ", "Begränsa godis för barn"]',
  '["Rödbetsjuice", "Tranbärspulver", "Hibiskusextrakt", "Naturlig röd färg från paprika"]',
  'Syntetiskt rött färgämne med begränsat ADI-värde på grund av hälsorisker',
  'Litolrubin BK är ett syntetiskt rött färgämne som används för att ge livsmedel en röd färg. Det har kopplats till hyperaktivitet hos barn och andra beteendeproblem, vilket lett till att EU kräver varningstexter på produkter som innehåller detta färgämne. ADI-värdet är lågt (0,1 mg/kg kroppsvikt) på grund av säkerhetsproblem. Många länder har förbjudit eller kraftigt begränsat dess användning.',
  'E180 Litolrubin BK - Kontroversiellt rött färgämne med hälsorisker',
  'Lär dig om E180 Litolrubin BK, ett syntetiskt färgämne kopplat till hyperaktivitet hos barn. Information om risker och naturliga alternativ.'
),
(
  'E239',
  'Hexametylentetramin',
  'Urotropin',
  'e239-hexametylentetramin',
  'Konserveringsmedel',
  'Syntetisk',
  7,
  'Negativ',
  0.15,
  'EFSA',
  'Rekommenderas ej för barn, potential cancerframkallande',
  '{"documented": ["Magtarmbesvär", "Hudirritationer", "Allergiska reaktioner"], "suspected": ["Cancerframkallande", "Formaldehyd bildning i kroppen"], "risk_groups": ["Barn", "Gravida", "Äldre", "Personer med leversjukdom"]}',
  '[{"category": "Fiskkonserver", "products": ["Kaviar", "Inlagd sill", "Fiskkonserver"], "average_amount": "25 mg/kg"}, {"category": "Ostprodukter", "products": ["Mozzarella", "Provolost"], "average_amount": "25 mg/kg"}]',
  '["Undvik produkter med E239", "Välj färska fisk- och ostprodukter", "Läs ingredienslistor mycket noga"]',
  '["Natriumbensoat", "Kaliumsorbat", "Naturlig konservering med salt och syra"]',
  'Kontroversiellt konserveringsmedel som kan bilda cancerframkallande formaldehyd',
  'Hexametylentetramin är ett syntetiskt konserveringsmedel som används i begränsade mängder i vissa fisk- och ostprodukter. Det största problemet är att det kan brytas ner till formaldehyd i kroppen, vilket är klassificerat som cancerframkallande. Många länder har förbjudit eller kraftigt begränsat användningen. EU tillåter det endast i mycket specifika produkter och i mycket låga koncentrationer.',
  'E239 Hexametylentetramin - Kontroversiellt konserveringsmedel med cancerrisker',
  'Förstå E239 Hexametylentetramin, ett konserveringsmedel som kan bilda cancerframkallande formaldehyd. Läs om risker och var det används.'
),
(
  'E284',
  'Borsyra',
  'Borax',
  'e284-borsyra',
  'Konserveringsmedel',
  'Mineraliskt',
  8,
  'Negativ',
  0.16,
  'EFSA',
  'Förbjudet för barn, mycket giftigt',
  '{"documented": ["Akut förgiftning", "Reproduktionsskador", "Hudirritationer", "Mag-tarmbesvär"], "suspected": ["Hormonstörningar", "Utvecklingsskador"], "risk_groups": ["Barn", "Gravida", "Ammande", "Alla känsliga grupper"]}',
  '[{"category": "Kaviar", "products": ["Importerad kaviar", "Fiskrom"], "average_amount": "4 g/kg"}]',
  '["Undvik helt produkter med E284", "Välj kaviar utan konserveringsmedel", "Kontrollera ursprung och ingredienser"]',
  '["Natriumklorid (salt)", "Naturlig konservering", "Kylförvaring"]',
  'Mycket giftigt konserveringsmedel som är förbjudet i många länder',
  'Borsyra är ett mycket kontroversiellt konserveringsmedel som endast är tillåtet i kaviar inom EU, och då endast i mycket begränsade mängder. Det är klassificerat som reproduktionstoxiskt och kan orsaka allvarliga hälsoproblem. Många länder har helt förbjudit dess användning i livsmedel. Det extremt låga ADI-värdet (0,16 mg/kg kroppsvikt) visar på dess toxicitet.',
  'E284 Borsyra - Mycket giftigt konserveringsmedel, förbjudet i många länder',
  'Lär dig om E284 Borsyra, ett mycket giftigt konserveringsmedel. Information om allvarliga hälsorisker och varför det är förbjudet.'
),
(
  'E385',
  'Kalciumdinatriumedetat',
  'EDTA-kalcium',
  'e385-kalciumdinatriumedetat',
  'Antioxidant',
  'Syntetisk',
  5,
  'Negativ',
  2.5,
  'EFSA',
  'Begränsa för barn, kan påverka mineralabsorption',
  '{"documented": ["Mineralbrister", "Mag-tarmbesvär", "Njurpåverkan"], "suspected": ["Störd zink- och järnabsorption", "Långsiktiga mineralbrister"], "risk_groups": ["Barn", "Gravida", "Personer med njurproblem", "Äldre"]}',
  '[{"category": "Konserverade grönsaker", "products": ["Inlagda grönsaker", "Konserverade bönor"], "average_amount": "25-250 mg/kg"}, {"category": "Såser och dressingar", "products": ["Majonnäs", "Dressingar", "Såser"], "average_amount": "75 mg/kg"}]',
  '["Begränsa processade livsmedel", "Välj färska grönsaker", "Kontrollera ingredienslistor på såser"]',
  '["Askorbinsyra", "Citronsyra", "Naturliga antioxidanter"]',
  'Syntetisk antioxidant som kan störa mineralabsorptionen i kroppen',
  'Kalciumdinatriumedetat (EDTA) är en syntetisk antioxidant som binder metallioner för att förhindra oxidation. Problemet är att det även kan binda viktiga mineraler som zink, järn och kalcium i kroppen och förhindra deras absorption. Detta kan leda till mineralbrister, särskilt hos barn och andra känsliga grupper. EFSA har satt ett relativt högt ADI-värde, men det finns fortsatt oro för långsiktiga effekter.',
  'E385 Kalciumdinatriumedetat - Antioxidant som kan orsaka mineralbrister',
  'Förstå E385 Kalciumdinatriumedetat (EDTA), en antioxidant som kan störa mineralabsorption. Lär dig om risker och var det används.'
);