-- Add long descriptions for essential remaining foods (batch 1)
UPDATE foods SET long_description = 'Havssalt är en naturlig salt som utvinns genom avdunstning av havsvatten och behåller spårämnen från havet som magnesium, kalium och kalcium. Till skillnad från raffinerat bordssalt, har havssalt en mer komplex smak och innehåller naturliga mineraler. Havssalt innehåller huvudsakligen natriumklorid som är nödvändigt för kroppens vätskebalans och nervfunktion, men bör konsumeras i måttliga mängder. Världshälsoorganisationen rekommenderar max 5 gram salt per dag. Havssalt är perfekt för att krydda mat och framhäva naturliga smaker. Grovkornig havssalt fungerar bra som finishing salt på kött och grönsaker.' WHERE slug = 'havssalt';

UPDATE foods SET long_description = 'Jasminris är en aromatisk långkornig ristyp som ursprungligen kommer från Thailand och har en naturlig blommig doft. Denna ris är rik på kolhydrater som ger snabb energi och innehåller mindre stärkelse än kortkornigt ris, vilket ger en fluffigare konsistens. Jasminris innehåller B-vitaminer, särskilt niacin och tiamin, samt magnesium och fosfor. Den har måttligt glykemiskt index jämfört med vitt ris. Koka jasminris i förhållandet 1:1,5 (ris:vatten) för perfekt konsistens. Skölj riset före kokning för att ta bort överflödig stärkelse. Jasminris passar utmärkt till asiatiska rätter och har en naturligt söt smak.' WHERE slug = 'jasminris';

UPDATE foods SET long_description = 'Jordgubbar är näringsrika bär som innehåller mer vitamin C än apelsiner - 100 gram jordgubbar täcker över 100% av det dagliga behovet av vitamin C. De är också rika på antioxidanter som antocyaniner och ellagsyra som kan hjälpa till att bekämpa inflammation och skydda mot hjärt-kärlsjukdomar. Jordgubbar innehåller folsyra som är viktig under graviditet, samt mangan för benhälsa. De har låg kaloriinnehåll (32 kalorier per 100 gram) och hög fiberhalt. Svenska jordgubbar har ofta högre näringsvärde och sötma än importerade. Välj fasta, röda bär utan mögel och konsumera snabbt för bästa kvalitet.' WHERE slug = 'jordgubbar';

UPDATE foods SET long_description = 'Kalkon är en mager fågel som är en utmärkt källa till högkvalitativt protein (cirka 24 gram per 100 gram) med låg fetthalt. Kalkonkött är rikt på B-vitaminer, särskilt niacin, B6 och B12, samt mineraler som selen, fosfor och zink. Det innehåller tryptofan, en aminosyra som kan främja sömn och välmående. Kalkon är naturligt lågt i mättat fett jämfört med andra köttsorter. Välj ekologisk kalkon när det är möjligt för bästa kvalitet. Tillaga till interntemperatur på minst 74°C för säkerhet. Kalkon är mångsidig och kan stekas, grillas eller användas i röror och sallader.' WHERE slug = 'kalkon';

UPDATE foods SET long_description = 'Kyckling är en av de mest populära proteinböorna globalt och en utmärkt källa till komplett protein (cirka 25 gram per 100 gram). Kycklingbröst är särskilt magert medan lår innehåller mer fett och smak. Kyckling är rik på B-vitaminer, särskilt niacin och B6, samt selen och fosfor. Det innehåller alla essentiella aminosyror som kroppen behöver för muskelbyggnad och reparation. Välj frikläckt kyckling för bättre djurvälfärd och kvalitet. Tillaga till interntemperatur på minst 74°C. Kyckling är extremt mångsidig och kan tillagas på otaliga sätt från grillning till långsamkokning.' WHERE slug = 'kyckling';

UPDATE foods SET long_description = 'Lax är en fet fisk som är exceptionellt rik på omega-3-fettsyror, särskilt EPA och DHA, som är avgörande för hjärn- och hjärthälsa. 100 gram lax innehåller cirka 22 gram protein och över 2 gram omega-3-fettsyror. Lax är också en utmärkt källa till vitamin D, B12, och selen. Vildlax har generellt högre näringsvärde och mindre föroreningar än fiskfarmlax. Laxen innehåller astaxantin, en kraftfull antioxidant som ger den rosa färgen. Tillaga lax till interntemperatur på 63°C för optimal textur. Konsumera 2-3 portioner fet fisk per vecka enligt näringsrekommendationer.' WHERE slug = 'lax';