-- Complete the final 11 foods with long descriptions
UPDATE foods SET long_description = 'Smör är en mejeriproduk med hög fetthalt (cirka 82%) som framställs genom kärnande av grädde. Det innehåller främst mättade fetter men också vitamin A för synhälsa och vitamin E som antioxidant. Smör från betesdjur innehåller högre halter av vitamin K2 och konjugerad linolsyra (CLA). Smör tål värme bättre än många andra fetter och ger rik smak till både bakning och stekning. Osaltat smör är bäst för bakning medan saltat smör håller längre. Förvara i kylskåp och använd inom bäst före-datum. Smör från ekologiska källor är ofta av högre kvalitet.' WHERE slug = 'smor';

UPDATE foods SET long_description = 'Solrosfrön är näringstäta frön som är rika på nyttiga fetter, protein och fiber. De innehåller höga halter av vitamin E, en kraftfull antioxidant som skyddar cellerna. Solrosfrön är också en bra källa till magnesium för muskel- och nervfunktion, samt selen och folsyra. Dessa frön har anti-inflammatoriska egenskaper och kan hjälpa till att sänka kolesterol. Rostade solrosfrön har nötig smak och knaprig konsistens. De är perfekta som mellanmål, i sallader, müsli eller bakning. Förvara i lufttät behållare för att bevara fräschör och förhindra harskhet.' WHERE slug = 'solrosfron';

UPDATE foods SET long_description = 'Spaghetti är en klassisk italiensk pasta gjord av durumvete som är rik på kolhydrater för energi. Den innehåller protein, B-vitaminer och järn enligt berikningsförordningar. Fullkornsspaghetti innehåller mer fiber och näringsämnen än vanlig spaghetti. Pasta har måttligt glykemiskt index, särskilt när den kokas al dente. Koka spaghetti i saltat vatten enligt förpackningens anvisningar. Kombinera med grönsaker, protein och nyttiga fetter för en balanserad måltid. Spaghetti är bas för otaliga rätter från carbonara till marinara.' WHERE slug = 'spaghetti';

UPDATE foods SET long_description = 'Spenat är ett näringstätt grönt bladgrönsak som är rikt på järn, folsyra och vitamin K. Det innehåller också höga halter av antioxidanter som lutein och zeaxantin som är viktiga för ögonhälsan. Spenat är en bra källa till magnesium, vitamin A och vitamin C. Färsk spenat är mer näringsrik än fryst men båda är hälsosamma alternativ. Spenat innehåller oxalater som kan minska järnabsorptionen, så kombinera med vitamin C-rika livsmedel. Perfekt i sallader, smoothies, quiche eller som tillagat tillbehör.' WHERE slug = 'spenat';

UPDATE foods SET long_description = 'Timjan är en aromatisk ört som innehåller eteriska oljor med antimikrobiella egenskaper, särskilt tymol. Det är rikt på vitamin C, vitamin A och mangan. Timjan har använts traditionellt för att lindra hosta och luftvägsproblem tack vare sina expektorerande egenskaper. Torkad timjan har mer koncentrerad smak än färsk och håller längre. Timjan passar utmärkt till kött, fisk, grönsaker och i marinader. Förvara torkad timjan i lufttät behållare borta från ljus. Tillsätt sent i matlagningen för att bevara smaken.' WHERE slug = 'timjan';

UPDATE foods SET long_description = 'Tomater är tekniskt sett frukter som är rika på lycopene, en kraftfull antioxidant som ger tomater sin röda färg och kan skydda mot hjärt-kärlsjukdomar och vissa cancerformer. De innehåller vitamin C, kalium och folsyra. Lycopene absorberas bättre från tillagade tomater än råa. Tomater har låg kaloriinnehåll men hög smak. Olika sorter har olika egenskaper - plomtomater för konservering, körsbärstomater för mellanmål. Förvara mogna tomater i rumstemperatur för bästa smak, omogna kan mogna på fönsterbrädan.' WHERE slug = 'tomat';