-- Add final batch of E-additives: More emulsifiers, sweeteners, and other additives

INSERT INTO e_additives (e_number, name, category, slug) VALUES 

-- More Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel
('E423', 'Gummi arabicum modifierat med oktenylbärnstenssyra', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e423-gummi-arabicum-modifierat-med-oktenylbarnstenssyra'),
('E425', 'Konjakgummi', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e425-konjakgummi'),
('E426', 'Sojabönshemicellulosa', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e426-sojabonshemicellulosa'),
('E427', 'Cassiagummi', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e427-cassiagummi'),
('E431', 'Polyoxietylen(40)stearat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e431-polyoxietylen-40-stearat'),
('E432', 'Polyoxietylensorbitanmonolaurat (Polysorbat 20)', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e432-polyoxietylensorbitanmonolaurat-polysorbat-20'),
('E433', 'Polyoxietylensorbitanmonooleat (Polysorbat 80)', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e433-polyoxietylensorbitanmonooleat-polysorbat-80'),
('E434', 'Polyoxietylensorbitanmonopalmitat (Polysorbat 40)', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e434-polyoxietylensorbitanmonopalmitat-polysorbat-40'),
('E435', 'Polyoxietylensorbitanmonostearat (Polysorbat 60)', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e435-polyoxietylensorbitanmonostearat-polysorbat-60'),
('E436', 'Polyoxietylensorbitantristearat (Polysorbat 65)', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e436-polyoxietylensorbitantristearat-polysorbat-65'),
('E440', 'Pektiner', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e440-pektiner'),
('E442', 'Ammoniumfosfatider', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e442-ammoniumfosfatider'),
('E444', 'Sackarosacetatisobutyrat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e444-sackarosacetatisobutyrat'),
('E445', 'Glycerolestrar av trähartser', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e445-glycerolestrar-av-trahartser'),
('E450', 'Difosfater', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e450-difosfater'),
('E451', 'Trifosfater', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e451-trifosfater'),
('E452', 'Polyfosfater', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e452-polyfosfater'),
('E456', 'Kaliumpolyaspartat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e456-kaliumpolyaspartat'),
('E459', 'Betacyklodextrin', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e459-betacyklodextrin'),
('E460', 'Cellulosa', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e460-cellulosa'),
('E461', 'Metylcellulosa', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e461-metylcellulosa'),
('E462', 'Etylcellulosa', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e462-etylcellulosa'),
('E463', 'Hydroxipropylcellulosa', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e463-hydroxipropylcellulosa'),
('E464', 'Hydroxipropylmetylcellulosa', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e464-hydroxipropylmetylcellulosa'),
('E465', 'Metyletylcellulosa', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e465-metyletylcellulosa'),
('E466', 'Natriumkarboximetylcellulosa', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e466-natriumkarboximetylcellulosa'),
('E468', 'Tvärbunden natriumkarboximetylcellulosa', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e468-tvarbunden-natriumkarboximetylcellulosa'),
('E469', 'Enzymatiskt hydrolyserad karboximetylcellulosa', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e469-enzymatiskt-hydrolyserad-karboximetylcellulosa'),
('E470a', 'Natrium-, kalium- och kalciumsalter av fettsyror', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e470a-natrium-kalium-och-kalciumsalter-av-fettsyror'),
('E470b', 'Magnesiumsalter av fettsyror', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e470b-magnesiumsalter-av-fettsyror'),
('E471', 'Mono- och diglycerider av fettsyror', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e471-mono-och-diglycerider-av-fettsyror'),
('E472a', 'Mono- och diglyceriders ättiksyraestrar', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e472a-mono-och-diglyceriders-attiksyraestrar'),
('E472b', 'Mono- och diglyceriders mjölksyraestrar', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e472b-mono-och-diglyceriders-mjolksyraestrar'),
('E472c', 'Mono- och diglyceriders citronsyraestrar', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e472c-mono-och-diglyceriders-citronsyraestrar'),
('E472d', 'Mono- och diglyceriders vinsyraestrar', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e472d-mono-och-diglyceriders-vinsyraestrar'),
('E472e', 'Mono- och diglyceriders mono- och diacetylvinsyraestrar', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e472e-mono-och-diglyceriders-mono-och-diacetylvinsyraestrar'),
('E472f', 'Blandade ättik- och vinsyraestrar av mono- och diglycerider', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e472f-blandade-attik-och-vinsyraestrar-av-mono-och-diglycerider'),
('E473', 'Sackarosestrar av fettsyror', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e473-sackarosestrar-av-fettsyror'),
('E474', 'Sackarosestrar i blandning med mono- och diglycerider av fettsyror', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e474-sackarosestrar-i-blandning-med-mono-och-diglycerider-av-fettsyror'),
('E475', 'Polyglycerolestrar av fettsyror', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e475-polyglycerolestrar-av-fettsyror'),
('E476', 'Polyglycerolpolyricinoleat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e476-polyglycerolpolyricinoleat'),
('E477', '1,2-Propylenglykolestrar av fettsyror', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e477-12-propylenglykolestrar-av-fettsyror'),
('E479b', 'Termiskt oxiderad sojabönsolja i reaktion med mono- och diglycerider av fettsyror', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e479b-termiskt-oxiderad-sojabonsolja-i-reaktion-med-mono-och-diglycerider-av-fettsyror'),
('E481', 'Natriumstearoyl-2-laktylat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e481-natriumstearoyl-2-laktylat'),
('E482', 'Kalciumstearoyl-2-laktylat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e482-kalciumstearoyl-2-laktylat'),
('E491', 'Sorbitanmonostearat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e491-sorbitanmonostearat'),
('E492', 'Sorbitantristearat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e492-sorbitantristearat'),
('E493', 'Sorbitanmonolaurat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e493-sorbitanmonolaurat'),
('E494', 'Sorbitanmonooleat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e494-sorbitanmonooleat'),
('E495', 'Sorbitanmonopalmitat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e495-sorbitanmonopalmitat'),
('E499', 'Stigmasterolrika växtsteroler', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e499-stigmasterolrika-vaxtsteroler'),
('E1204', 'Pullulan', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e1204-pullulan'),
('E1210', 'Karbomer', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e1210-karbomer'),
('E1404', 'Oxiderad stärkelse', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e1404-oxiderad-starkelse'),
('E1410', 'Monostärkelsefosfat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e1410-monostarkelsefosfat'),
('E1412', 'Distärkelsefosfat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e1412-distarkelsefosfat'),
('E1413', 'Fosfaterat distärkelsefosfat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e1413-fosfaterat-distarkelsefosfat'),
('E1414', 'Acetylerat distärkelsefosfat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e1414-acetylerat-distarkelsefosfat'),
('E1420', 'Stärkelseacetat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e1420-starkelseacetat'),
('E1422', 'Acetylerat distärkelseadipat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e1422-acetylerat-distarkelseadipat'),
('E1440', 'Hydroxipropylstärkelse', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e1440-hydroxipropylstarkelse'),
('E1442', 'Hydroxipropyldistärkelsefosfat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e1442-hydroxipropyldistarkelsefosfat'),
('E1450', 'Natriumoktenylsuccinatstärkelse', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e1450-natriumoktenylsuccinatstarkelse'),
('E1451', 'Acetylerad oxiderad stärkelse', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e1451-acetylerad-oxiderad-starkelse'),
('E1452', 'Stärkelsealuminiumoktenylsuccinat', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e1452-starkelsealuminiumoktenylsuccinat'),

-- Sötningsmedel (Sweeteners)
('E420', 'Sorbitol', 'Sötningsmedel', 'e420-sorbitol'),
('E421', 'Mannitol', 'Sötningsmedel', 'e421-mannitol-sotningsmedel'),
('E950', 'Acesulfam K', 'Sötningsmedel', 'e950-acesulfam-k'),
('E951', 'Aspartam', 'Sötningsmedel', 'e951-aspartam'),
('E952', 'Cyklamater', 'Sötningsmedel', 'e952-cyklamater'),
('E953', 'Isomalt', 'Sötningsmedel', 'e953-isomalt'),
('E954', 'Sackariner', 'Sötningsmedel', 'e954-sackariner'),
('E955', 'Sukralos', 'Sötningsmedel', 'e955-sukralos'),
('E957', 'Taumatin', 'Sötningsmedel', 'e957-taumatin'),
('E959', 'Neohesperidin DC', 'Sötningsmedel', 'e959-neohesperidin-dc'),
('E960a', 'Steviolglykosider från Stevia', 'Sötningsmedel', 'e960a-steviolglykosider-fran-stevia'),
('E960c', 'Enzymatiskt framställda steviolglykosider', 'Sötningsmedel', 'e960c-enzymatiskt-framstallda-steviolglykosider'),
('E960d', 'Glukosylerade steviolglykosider', 'Sötningsmedel', 'e960d-glukosylerade-steviolglykosider'),
('E961', 'Neotam', 'Sötningsmedel', 'e961-neotam'),
('E962', 'Salt av aspartam och acesulfam', 'Sötningsmedel', 'e962-salt-av-aspartam-och-acesulfam'),
('E964', 'Polyglycitolsirap', 'Sötningsmedel', 'e964-polyglycitolsirap'),
('E965', 'Maltitoler', 'Sötningsmedel', 'e965-maltitoler'),
('E966', 'Laktitol', 'Sötningsmedel', 'e966-laktitol'),
('E967', 'Xylitol', 'Sötningsmedel', 'e967-xylitol'),
('E968', 'Erytritol', 'Sötningsmedel', 'e968-erytritol'),
('E969', 'Advantam', 'Sötningsmedel', 'e969-advantam')

ON CONFLICT (e_number) DO NOTHING;