-- Add final 9 foods to reach exactly 50 total

INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

-- Fisk & Skaldjur (3 foods)
('Makrill', 'makrill', 'M',
(SELECT id FROM public.food_categories WHERE slug = 'fisk-skaldjur'),
'Fet fisk',
'Kylskåp 0-4°C på is',
'1-2 dagar',
'1-2 dagar',
true,
'Rengör och frys inom 24 timmar',
ARRAY['april', 'maj', 'juni', 'juli', 'augusti', 'september'],
ARRAY['fisk'],
305, 18.6, 25.1, 0.0, 0.0, 0.15,
'{"D": "4.0μg", "B12": "19μg", "Niacin": "9.7mg"}'::jsonb,
'{"selen": "51.6μg", "fosfor": "217mg", "omega-3": "2670mg"}'::jsonb,
'Mycket fet fisk med högt omega-3 innehåll och stark smak.',
ARRAY['Grillad', 'Rökt', 'Inkokt', 'Stekt'],
'[{"name": "Sill", "reason": "Liknande fet fisk"}, {"name": "Sardiner", "reason": "Mindre storlek samma familj"}]'::jsonb,
'Makrill - Omega-3 Källa och Tillagning | Livsmedel A-Ö',
'Komplett guide om makrill: extremt hög omega-3 halt, tillagning, säsong och hälsofördelar.',
'[{"question": "Varför är makrill så hälsosam?", "answer": "Extremt högt innehåll av omega-3 (över 2g per 100g) och vitamin B12, bra för hjärta och hjärna."}, {"question": "Hur får man bort den starka smaken?", "answer": "Marinera i citron och salt före tillagning, eller välj mindre exemplar som är mildare."}]'::jsonb,
ARRAY['Hälsosam fisk', 'Omega-3 källa', 'Grillmat']),

('Tonfisk Konserverad', 'tonfisk-konserverad', 'T',
(SELECT id FROM public.food_categories WHERE slug = 'fisk-skaldjur'),
'Konserverad fisk',
'Rumstemperatur före öppning',
'3-4 dagar i kylskåp',
'2-5 år oöppnad',
false,
'Rekommenderas ej att frysa',
ARRAY[]::text[],
ARRAY['fisk'],
128, 25.5, 2.5, 0.0, 0.0, 0.40,
'{"B12": "2.6μg", "B3": "18.8mg", "B6": "1.0mg"}'::jsonb,
'{"selen": "78.2μg", "fosfor": "267mg"}'::jsonb,
'Proteinrik konserverad fisk, perfekt för snabba måltider.',
ARRAY['Tonfisksallad', 'Pasta', 'Smörgås', 'Nicoise sallad'],
'[{"name": "Konserverad makrill", "reason": "Högre omega-3 halt"}, {"name": "Konserverad sardiner", "reason": "Mindre fisk med ben"}]'::jsonb,
'Tonfisk Konserverad - Näringsvärde och Användning | Livsmedel A-Ö',
'Allt om konserverad tonfisk: näringsvärde, hållbarhet, olika varianter och snabba recept.',
'[{"question": "Vilken tonfisk är mest hållbar?", "answer": "Leta efter MSC-märkt tonfisk som kommer från hållbart fiske med selektiva fångstmetoder."}, {"question": "Skillnad mellan tonfisk i olja och vatten?", "answer": "Tonfisk i olja är saftigare men mer kaloririk, i vatten är magrare men kan vara torrare."}]'::jsonb,
ARRAY['Snabb lunch', 'Protein källa', 'Vardagsmat']),

-- Nötter & Frön (3 foods)
('Mandel', 'mandel', 'M',
(SELECT id FROM public.food_categories WHERE slug = 'notter-fron'),
'Nötter',
'Torrt och svalt',
'6 månader',
'1 år',
true,
'Frys för längre hållbarhet',
ARRAY[]::text[],
ARRAY['nötter'],
579, 21.2, 49.9, 21.6, 12.5, 0.00,
'{"E": "25.6mg", "B2": "1.0mg", "Niacin": "3.6mg"}'::jsonb,
'{"magnesium": "270mg", "kalcium": "269mg", "järn": "3.7mg"}'::jsonb,
'Näringsrik nöt med högt innehåll av vitamin E och magnesium.',
ARRAY['Snacks', 'Bakning', 'Müsli', 'Mandelmjölk'],
'[{"name": "Valnötter", "reason": "Andra näringsrika nötter"}, {"name": "Cashewnötter", "reason": "Krämigare textur"}]'::jsonb,
'Mandel - Vitamin E och Magnesium | Livsmedel A-Ö',
'Komplett guide om mandlar: näringsvärde, hälsofördelar, olika sorter och användning.',
'[{"question": "Är mandlar bra för hjärtat?", "answer": "Ja, mandlar innehåller enfettade fetter, vitamin E och magnesium som kan stödja hjärthälsan."}, {"question": "Skillnad mellan skalade och oskalade mandlar?", "answer": "Skalet innehåller fiber och antioxidanter, men skalade mandlar är lättare att smälta."}]'::jsonb,
ARRAY['Hälsosamma snacks', 'Nötter', 'Hjärthälsa']),

-- Oljor & Vinäger (2 foods)
('Olivolja Extra Virgin', 'olivolja-extra-virgin', 'O',
(SELECT id FROM public.food_categories WHERE slug = 'oljor-vinager'),
'Kallpressad olja',
'Mörkt och svalt',
'2 år efter öppning',
'2-3 år',
false,
'Rekommenderas ej att frysa',
ARRAY[]::text[],
ARRAY[]::text[],
884, 0.0, 100.0, 0.0, 0.0, 0.00,
'{"E": "14.4mg", "K": "60.2μg"}'::jsonb,
'{"omega-3": "760mg", "omega-6": "9.8g", "monounsaturated": "73g"}'::jsonb,
'Högkvalitativ olivolja från första kallpressning.',
ARRAY['Salladdressing', 'Pasta', 'Dip med bröd', 'Marinader'],
'[{"name": "Rapsolja", "reason": "Neutralare smak"}, {"name": "Avokadoolja", "reason": "Hög rökpunkt"}]'::jsonb,
'Olivolja Extra Virgin - Hälsosamma Fetter | Livsmedel A-Ö',
'Komplett guide om extra virgin olivolja: kvalitet, hälsofördelar, användning och förvaring.',
'[{"question": "Vad betyder \"extra virgin\"?", "answer": "Första kallpressning utan kemiska lösningsmedel, lägsta aciditet och bästa smak."}, {"question": "Kan man steka i olivolja?", "answer": "Extra virgin olivolja passar bäst för låg-medelhög värme, använd raffinerad olivolja för hög värme."}]'::jsonb,
ARRAY['Medelhavsmat', 'Hälsosamma fetter', 'Dressing']),

('Balsamvinäger', 'balsamvinager', 'B',
(SELECT id FROM public.food_categories WHERE slug = 'oljor-vinager'),
'Ädelvinäger',
'Mörkt och svalt',
'5+ år',
'Obegränsat',
false,
'Rekommenderas ej att frysa',
ARRAY[]::text[],
ARRAY[]::text[],
88, 0.5, 0.0, 17.0, 0.0, 0.02,
'{"K": "5μg"}'::jsonb,
'{"kalium": "112mg", "antioxidanter": "måttligt"}'::jsonb,
'Söt och syrig italiensk vinäger från Modena.',
ARRAY['Salladdressing', 'Glazing', 'Caprese', 'Marinader'],
'[{"name": "Äppelcidervinäger", "reason": "Annan mild vinäger"}, {"name": "Rödvinsvinäger", "reason": "Surare alternativ"}]'::jsonb,
'Balsamvinäger - Italiensk Ädelvinäger | Livsmedel A-Ö',
'Allt om balsamvinäger: kvalitet, användning, äkta vs imitationer och italienska traditioner.',
'[{"question": "Skillnad mellan äkta och vanlig balsamvinäger?", "answer": "Äkta Aceto Balsamico di Modena DOP lagras 12+ år, vanlig variant är söt-sur blandning."}, {"question": "Hur använder man balsamvinäger bäst?", "answer": "Droppa över färdiga rätter, reducera till glaze eller använd i dressinger."}]'::jsonb,
ARRAY['Italiensk mat', 'Salladdressing', 'Gourmetmat']),

-- Bakning & Torrvaror (1 food)
('Mjöl Vetemjöl', 'mjol-vetemjol', 'M',
(SELECT id FROM public.food_categories WHERE slug = 'bakning-torrvaror'),
'Bakmjöl',
'Torrt och mörkt',
'6 månader',
'1 år',
true,
'Förpacka tätt innan frysning',
ARRAY[]::text[],
ARRAY['gluten'],
364, 10.3, 1.0, 76.3, 2.7, 0.00,
'{"B1": "0.5mg", "Folat": "22μg", "Niacin": "5.9mg"}'::jsonb,
'{"fosfor": "108mg", "kalium": "107mg", "järn": "1.2mg"}'::jsonb,
'Grundläggande bakmjöl från vete för bröd och bakning.',
ARRAY['Brödbak', 'Tårtor', 'Pizza deg', 'Pannkakor'],
'[{"name": "Dinkelmehl", "reason": "Nötighare smak"}, {"name": "Mandelmjöl", "reason": "Glutenfritt alternativ"}]'::jsonb,
'Mjöl Vetemjöl - Bakning och Användning | Livsmedel A-Ö',
'Komplett guide om vetemjöl: olika typer, bakning, gluteninnehåll och förvaring.',
'[{"question": "Skillnad mellan olika mjöltyper?", "answer": "Speciellt mjöl (låg protein) för kakor, vanligt mjöl (medel) för bröd, starkmelsmjöl (hög) för pizza."}, {"question": "Hur länge håller mjöl?", "answer": "Vetemjöl håller 6-12 månader i rumstemperatur, längre i frysen."}]'::jsonb,
ARRAY['Bakning', 'Hembakad bröd', 'Grundingrediens']),

-- Kött & Fågel (2 more foods)
('Entrecôte', 'entrecote', 'E',
(SELECT id FROM public.food_categories WHERE slug = 'kott'),
'Premium nötkött',
'Kylskåp 0-4°C',
'3-5 dagar',
'3-5 dagar',
true,
'Marinera innan frysning',
ARRAY[]::text[],
ARRAY[]::text[],
291, 26.4, 20.0, 0.0, 0.0, 0.05,
'{"B12": "3.2μg", "B6": "0.5mg", "Niacin": "6.8mg"}'::jsonb,
'{"järn": "2.8mg", "zink": "5.2mg", "selen": "18.6μg"}'::jsonb,
'Marmorerat nötkött från ryggbiff med rik smak.',
ARRAY['Grillad', 'Stekt', 'Café de Paris', 'Bearnaise'],
'[{"name": "Oxfilé", "reason": "Mörare men magrare"}, {"name": "Ryggbiff", "reason": "Liknande styckningsdel"}]'::jsonb,
'Entrecôte - Premium Nötkött | Livsmedel A-Ö',
'Komplett guide om entrecôte: marmorering, tillagning, grader av stekhet och klassiska tillbehör.',
'[{"question": "Vad är marmorering?", "answer": "Vita fettådror i köttet som smälter vid tillagning och ger saftighet och smak."}, {"question": "Vilken stekgrad är bäst för entrecôte?", "answer": "Medium-rare (54-57°C) ger bästa balansen mellan saftighet och smak."}]'::jsonb,
ARRAY['Grillmat', 'Lyxmiddag', 'Fransk matlagning']),

('Kalkon', 'kalkon', 'K',
(SELECT id FROM public.food_categories WHERE slug = 'kott'),
'Fågel',
'Kylskåp 0-4°C',
'2-3 dagar',
'2-3 dagar',
true,
'Tina långsamt i kylskåp',
ARRAY['november', 'december'],
ARRAY[]::text[],
189, 29.0, 7.0, 0.0, 0.0, 0.07,
'{"B3": "6.3mg", "B6": "0.5mg", "B12": "1.6μg"}'::jsonb,
'{"selen": "27.4μg", "fosfor": "230mg", "zink": "2.0mg"}'::jsonb,
'Mager fågel med mild smak, traditionell julmat.',
ARRAY['Helstekt', 'Smörgås pålägg', 'Sallad', 'Soppa'],
'[{"name": "Kyckling", "reason": "Liknande smak men mindre"}, {"name": "And", "reason": "Fetare med starkare smak"}]'::jsonb,
'Kalkon - Näringsvärde och Jultraditioner | Livsmedel A-Ö',
'Komplett guide om kalkon: näringsvärde, tillagning, jultraditioner och amerikanska recept.',
'[{"question": "Hur länge ska kalkon stekas?", "answer": "Ca 20 min per kg vid 175°C, innertemperatur ska nå 74°C i tjockaste delen."}, {"question": "Varför äter man kalkon på jul?", "answer": "Tradition från Amerika som spridit sig, kalkon blev populärt som festmat på 1900-talet."}]'::jsonb,
ARRAY['Julbord', 'Amerikanska recept', 'Festmat']),

-- Spannmål & Baljväxter (1 food)
('Quinoa', 'quinoa', 'Q',
(SELECT id FROM public.food_categories WHERE slug = 'spannmal-baljvaxter'),
'Pseudospannmål',
'Torrt och mörkt',
'6 månader',
'2 år',
true,
'Koka innan frysning',
ARRAY[]::text[],
ARRAY[]::text[],
368, 14.1, 6.1, 64.2, 7.0, 0.01,
'{"B6": "0.5mg", "Folat": "184μg", "E": "2.4mg"}'::jsonb,
'{"magnesium": "197mg", "fosfor": "457mg", "järn": "4.6mg"}'::jsonb,
'Sydamerikansk pseudospannmål med komplett aminosyraprofil.',
ARRAY['Sallader', 'Buddha bowls', 'Risotto-stil', 'Frukost'],
'[{"name": "Bulgur", "reason": "Liknande textur"}, {"name": "Couscous", "reason": "Snabbare tillagning"}]'::jsonb,
'Quinoa - Komplett Protein | Livsmedel A-Ö',
'Allt om quinoa: näringsvärde, komplett protein, glutenfritt alternativ och sydamerikansk tradition.',
'[{"question": "Varför är quinoa ett \"komplett protein\"?", "answer": "Innehåller alla nio essentiella aminosyror som kroppen inte kan producera själv."}, {"question": "Behöver man skölja quinoa?", "answer": "Ja, för att ta bort saponiner som kan ge besk smak - skölja tills vattnet blir klart."}]'::jsonb,
ARRAY['Vegetarisk protein', 'Glutenfritt', 'Hälsosam kost']),

-- Bakning & Torrvaror (1 food)
('Havregryn', 'havregryn', 'H',
(SELECT id FROM public.food_categories WHERE slug = 'bakning-torrvaror'),
'Flingor',
'Torrt och mörkt',
'6 månader',
'1 år',
true,
'Förpacka tätt innan frysning',
ARRAY[]::text[],
ARRAY['gluten'],
389, 16.9, 6.9, 66.3, 10.6, 0.00,
'{"B1": "0.8mg", "B5": "1.3mg", "Folat": "56μg"}'::jsonb,
'{"magnesium": "177mg", "fosfor": "523mg", "järn": "4.7mg", "betaglucan": "4g"}'::jsonb,
'Fibrerrik spannmål med kolesterolsänkande betaglukan.',
ARRAY['Gröt', 'Müsli', 'Smoothies', 'Bakning'],
'[{"name": "Quinoa", "reason": "Proteinrikare alternativ"}, {"name": "Rågflingor", "reason": "Mörkare smak"}]'::jsonb,
'Havregryn - Betaglukan och Kolesterol | Livsmedel A-Ö',
'Komplett guide om havregryn: betaglukan fördelar, kolesterolsänkning, olika typer och användning.',
'[{"question": "Hjälper havre mot kolesterol?", "answer": "Ja, betaglukan i havre kan bidra till att sänka kolesterolnivåerna enligt forskning."}, {"question": "Skillnad mellan stora och små havregryn?", "answer": "Stora gryn ger mer tuggmotstånd, små gryn blir krämigare gröt."}]'::jsonb,
ARRAY['Hälsosam frukost', 'Kolesterolsänkande', 'Fiber källa']),

-- Nötter & Frön (1 food)
('Solrosfrön', 'solrosfron', 'S',
(SELECT id FROM public.food_categories WHERE slug = 'notter-fron'),
'Frön',
'Torrt och mörkt',
'3 månader',
'6 månader',
true,
'Frys för längre hållbarhet',
ARRAY[]::text[],
ARRAY[]::text[],
584, 20.8, 51.5, 20.0, 8.6, 0.01,
'{"E": "35.2mg", "B1": "1.5mg", "B6": "1.3mg"}'::jsonb,
'{"magnesium": "325mg", "fosfor": "660mg", "selen": "53μg"}'::jsonb,
'Näringsrika frön med mycket vitamin E och magnesium.',
ARRAY['Snacks', 'Sallad topping', 'Müsli', 'Fröbröd'],
'[{"name": "Pumpafrön", "reason": "Andra näringsrika frön"}, {"name": "Sesamfrön", "reason": "Mindre frön för garnering"}]'::jsonb,
'Solrosfrön - Vitamin E och Mineraler | Livsmedel A-Ö',
'Komplett guide om solrosfrön: näringsvärde, vitamin E fördelar, rostning och användning.',
'[{"question": "Ska man rosta solrosfrön?", "answer": "Rostning förbättrar smak och textur - rosta i torr panna på medelvärme tills gyllene."}, {"question": "Är solrosfrön bra för huden?", "answer": "Ja, höga halter av vitamin E och zink kan stödja hudhälsan."}]'::jsonb,
ARRAY['Hälsosamma snacks', 'Vitamin E källa', 'Fröblandning']);