-- Add 48 new unique foods to reach 100 total foods
-- Data sourced from Livsmedelsverket (Swedish Food Agency) and USDA FoodData Central
-- All nutritional values per 100g

INSERT INTO foods (name, slug, letter, category_id, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, long_description, usage_tips, season, allergens, can_freeze, storage_method, shelf_life_opened, shelf_life_unopened, meta_title, meta_description) VALUES

-- A foods
('Aubergine', 'aubergine', 'A', (SELECT id FROM food_categories WHERE slug = 'gront'), 25, 1.0, 0.2, 6.0, 3.0, 0.002, '{"C":"2.2mg","K":"3.5μg","Folat":"22μg"}', '{"Kalium":"229mg","Mangan":"0.2mg","Nasunin":"högt"}', 'Lila grönsak rik på nasunin-antioxidanter', 'Aubergine innehåller nasunin, en kraftfull antioxidant som kan skydda hjärnan. Vanlig i medelhavskosten och Blue Zones-områden.', ARRAY['Rosta i ugnen','Grilla i skivor','Gör moussaka'], ARRAY['Sommar','Höst'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '2 veckor fryst', 'Aubergine - Nasunin för hjärnhälsa | ViHandlar', 'Upptäck aubergines nasunin-antioxidanter och roll i medelhavskosten. Data från Livsmedelsverket.'),

('Artskocka', 'artskocka', 'A', (SELECT id FROM food_categories WHERE slug = 'gront'), 47, 3.3, 0.2, 10.5, 5.4, 0.094, '{"C":"11.7mg","Folat":"68μg","K":"14.8μg"}', '{"Kalium":"370mg","Magnesium":"60mg","Cynarin":"högt"}', 'Blomknopp rik på cynarin för leverhälsa', 'Artskocka innehåller cynarin som stödjer leverfunktion och gallproduktion enligt forskning. Traditionell del av medelhavskosten.', ARRAY['Koka hela','Stjälkarna i sallad','Hjärtbladen som delikatess'], ARRAY['Vår','Sommar'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '1 år fryst', 'Artskocka - Cynarin för levern | ViHandlar', 'Lär dig om artskockans cynarin och leverstödjande egenskaper från medelhavskosten. Data från USDA.'),

-- B foods  
('Butternutsquash', 'butternutsquash', 'B', (SELECT id FROM food_categories WHERE slug = 'gront'), 45, 1.0, 0.1, 11.7, 2.0, 0.004, '{"A":"532μg","C":"21mg","E":"1.4mg"}', '{"Kalium":"352mg","Magnesium":"34mg","Beta-karoten":"4570μg"}', 'Beta-karotenrik vintervegetabil', 'Butternutsquash är rik på beta-karoten och fiber. Närbesläktad med sötpotatis från Blue Zones och stödjer immunförsvaret.', ARRAY['Rosta i ugnen','Gör soppa','Som puré'], ARRAY['Höst','Vinter'], ARRAY[]::text[], true, 'Svalt och mörkt', '3 månader', '1 år fryst', 'Butternutsquash - Beta-karoten för immunförsvaret | ViHandlar', 'Upptäck butternutsquashs beta-karoten och närbesläktning med Blue Zones-mat. Data från USDA.'),

('Blodapelsin', 'blodapelsin', 'B', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 47, 0.9, 0.1, 11.8, 2.4, 0.0, '{"C":"53mg","Folat":"40μg","Antocyaniner":"mycket högt"}', '{"Kalium":"181mg","Hesperidin":"högt","Kalcium":"40mg"}', 'Antocyaninrik citrusfrukt med dubbla antioxidanter', 'Blodapelsin kombinerar C-vitamin med antocyaniner som ger den röda färgen. Dubbel antioxidanteffekt jämfört med vanlig apelsin.', ARRAY['Färsk som snacks','Pressa till juice','I fruktmedalj'], ARRAY['Vinter','Vår'], ARRAY[]::text[], true, 'Kylskåp', '2 veckor', '1 månad fryst', 'Blodapelsin - Dubbla antioxidanter | ViHandlar', 'Lär dig om blodapelsins unika kombination av C-vitamin och antocyaniner. Data från Livsmedelsverket.'),

-- C foods
('Cashewkräm', 'cashewkram', 'C', (SELECT id FROM food_categories WHERE slug = 'notter-fron'), 598, 17.8, 46.4, 32.7, 3.3, 0.012, '{"E":"5.3mg","B6":"0.4mg","Folat":"25μg"}', '{"Magnesium":"292mg","Zink":"5.8mg","Koppar":"2.2mg"}', 'Krämig vegansk base från cashewnötter', 'Cashewkräm ger samma näringsämnen som cashewnötter i krämig form - perfekt som vegansk ersättning för grädde och ost.', ARRAY['Som grädde-ersättning','Till pasta-såser','I desserter'], ARRAY['Året runt'], ARRAY['Nötter'], true, 'Kylskåp', '1 vecka', '3 månader fryst', 'Cashewkräm - Vegansk protein | ViHandlar', 'Upptäck cashewkräm som näringsrik vegansk ersättning. Data från USDA FoodData Central.'),

-- D foods  
('Dill', 'dill', 'D', (SELECT id FROM food_categories WHERE slug = 'kryddor-orter'), 43, 3.5, 1.1, 7.0, 2.1, 0.061, '{"C":"85mg","A":"771μg","Folat":"150μg"}', '{"Kalium":"738mg","Kalcium":"208mg","Mangan":"1.3mg"}', 'Skandinavisk ört rik på C-vitamin', 'Dill innehåller mer C-vitamin än citrusfrukter och är traditionell del av nordisk kost med anti-inflammatorinska egenskaper.', ARRAY['Till fisk och potatis','I gurksallad','Som garnering'], ARRAY['Sommar'], ARRAY[]::text[], true, 'Kylskåp i vatten', '1 vecka', '6 månader fryst', 'Dill - Nordisk C-vitaminkälla | ViHandlar', 'Lär dig om dills höga C-vitaminhalt i traditionell nordisk kost. Data från Livsmedelsverket.'),

-- E foods
('Endiv', 'endiv', 'E', (SELECT id FROM food_categories WHERE slug = 'gront'), 17, 1.3, 0.2, 3.4, 3.1, 0.022, '{"A":"108μg","K":"231μg","Folat":"142μg"}', '{"Kalium":"314mg","Inulin":"högt","Kalcium":"52mg"}', 'Bitter salladsgrönsak med prebiotisk inulin', 'Endiv innehåller inulin som stödjer tarmbakterier och har bitter smak som stimulerar leverproduktion enligt traditionell medicin.', ARRAY['I blandade sallader','Gratinerad','Som skedar för dipp'], ARRAY['Höst','Vinter'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '1 år fryst', 'Endiv - Prebiotisk inulin | ViHandlar', 'Upptäck endivs inulin för tarmbakterier och bitter smak för levern. Data från USDA.'),

-- F foods
('Fennel', 'fennel', 'F', (SELECT id FROM food_categories WHERE slug = 'gront'), 31, 1.2, 0.2, 7.3, 3.1, 0.052, '{"C":"12mg","Folat":"27μg","K":"62μg"}', '{"Kalium":"414mg","Anetol":"högt","Kalcium":"49mg"}', 'Anisliknande grönsak med anetol', 'Fänkål innehåller anetol som ger anissmak och kan ha lugnande effekt på matsmältningen enligt traditionell användning.', ARRAY['Skivad i sallader','Rostade i ugnen','Som bas i såser'], ARRAY['Höst','Vinter'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '1 år fryst', 'Fänkål - Anetol för matsmältning | ViHandlar', 'Lär dig om fänkåls anetol och traditionella användning för matsmältningen. Data från Livsmedelsverket.'),

-- G foods
('Granatäpple', 'granatapple', 'G', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 83, 1.7, 1.2, 18.7, 4.0, 0.003, '{"C":"10mg","Folat":"38μg","K":"16μg"}', '{"Kalium":"236mg","Punicalagin":"extremt högt","Ellagsyra":"högt"}', 'Superfrukt med kraftfulla antioxidanter', 'Granatäpple innehåller punicalagin och ellagsyra - antioxidanter som enligt forskning kan ha anti-inflammatorisk och anti-aging effekt.', ARRAY['Färska kärnor','Pressad juice','I sallader'], ARRAY['Höst','Vinter'], ARRAY[]::text[], true, 'Kylskåp', '2 månader', '6 månader fryst', 'Granatäpple - Anti-aging antioxidanter | ViHandlar', 'Upptäck granatäpples punicalagin och ellagsyra för anti-aging. Data från USDA FoodData Central.'),

-- H foods
('Hasselnötter', 'hasselnotter', 'H', (SELECT id FROM food_categories WHERE slug = 'notter-fron'), 628, 15.0, 60.8, 16.7, 9.7, 0.0, '{"E":"15mg","B6":"0.6mg","Folat":"113μg"}', '{"Magnesium":"163mg","Mangan":"6.2mg","Koppar":"1.7mg"}', 'E-vitaminrika nötter för hjärthälsa', 'Hasselnötter har högst E-vitamin bland nötter och är rika på enofettsättade fetter som stödjer hjärthälsan enligt medelhavskosten.', ARRAY['Rostade som snacks','I bakning','Till choklad'], ARRAY['Höst'], ARRAY['Nötter'], true, 'Torrt och svalt', '6 månader', '1 år fryst', 'Hasselnötter - E-vitamin för hjärtat | ViHandlar', 'Lär dig om hasselnötters E-vitamin och roll i hjärthälsosam medelhavsmat. Data från USDA.'),

-- I foods
('Isbergssallad', 'isbergssallad', 'I', (SELECT id FROM food_categories WHERE slug = 'gront'), 14, 0.9, 0.1, 3.0, 1.2, 0.028, '{"C":"2.8mg","K":"24μg","Folat":"29μg"}', '{"Kalium":"141mg","Vatten":"96%","Silika":"naturligt"}', 'Vatten- och mineralrik bas-sallad', 'Isbergssallad består av 96% vatten och ger hydrering plus mineraler. Perfekt bas för näringsrika toppings i Blue Zones-stil.', ARRAY['Som salladsbase','Wraps istället för tortilla','Krossad i smoothies'], ARRAY['Året runt'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '6 månader fryst', 'Isbergssallad - Hydrering och mineraler | ViHandlar', 'Upptäck isbergssallads hydrering och roll som näringsrik salladsbase. Data från Livsmedelsverket.'),

-- J foods  
('Jalapeno', 'jalapeno', 'J', (SELECT id FROM food_categories WHERE slug = 'gront'), 29, 0.9, 0.4, 6.5, 2.8, 0.003, '{"C":"118mg","A":"54μg","B6":"0.4mg"}', '{"Kalium":"248mg","Kapsaicin":"högt","Kalcium":"12mg"}', 'Het chili med kapsaicin för metabolism', 'Jalapeno innehåller kapsaicin som kan öka metabolismen och har anti-inflammatoriska egenskaper enligt forskning från mexikanska Blue Zone Nicoya.', ARRAY['I mexikansk mat','Inlagda som tillbehör','I hot sauce'], ARRAY['Sommar','Höst'], ARRAY[]::text[], true, 'Kylskåp', '2 veckor', '1 år fryst', 'Jalapeno - Kapsaicin för metabolism | ViHandlar', 'Lär dig om jalapeños kapsaicin och metabolism-effekter från Blue Zone Nicoya. Data från USDA.'),

-- K foods
('Kiwi', 'kiwi', 'K', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 61, 1.1, 0.5, 14.7, 3.0, 0.003, '{"C":"93mg","K":"40μg","E":"1.5mg"}', '{"Kalium":"312mg","Actinidin":"naturligt","Folat":"25μg"}', 'C-vitaminbomb med enzymet actinidin', 'Kiwi har mer C-vitamin än apelsiner plus enzymet actinidin som hjälper proteinsmältning. Stödjer immunförsvar och matsmältning.', ARRAY['Färsk som snacks','I smoothies','Som dessert'], ARRAY['Vinter','Vår'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '1 år fryst', 'Kiwi - C-vitamin och actinidin | ViHandlar', 'Upptäck kiwis C-vitamin och actinidin-enzym för matsmältning. Data från Livsmedelsverket.'),

-- L foods
('Lime', 'lime', 'L', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 30, 0.7, 0.2, 10.5, 2.8, 0.002, '{"C":"29mg","Folat":"8μg","Citrusflavonoider":"högt"}', '{"Kalium":"102mg","Hesperidin":"högt","Kalcium":"33mg"}', 'Syrlig citrus rik på flavonoider', 'Lime innehåller citrusflavonoider som har anti-inflammatoriska egenskaper och stödjer absorption av järn från växtbaserad mat.', ARRAY['Pressa över fisk','I cocktails','Till mexikansk mat'], ARRAY['Året runt'], ARRAY[]::text[], true, 'Kylskåp', '2 veckor', '1 månad fryst', 'Lime - Flavonoider och järnabsorption | ViHandlar', 'Lär dig om limes flavonoider och effekt på järnabsorption från växter. Data från USDA.'),

-- M foods
('Mangold', 'mangold', 'M', (SELECT id FROM food_categories WHERE slug = 'gront'), 19, 1.8, 0.2, 3.7, 1.6, 0.213, '{"A":"306μg","C":"30mg","K":"830μg"}', '{"Kalium":"379mg","Magnesium":"81mg","Betalain":"högt"}', 'Färgrik bladgrönsak med betalain', 'Mangold innehåller betalain-pigment som ger färger och har antioxidant-egenskaper. Hög halt av K-vitamin för benmetabolism.', ARRAY['Stjälkarna som sparris','Bladen som spenat','I gratänger'], ARRAY['Sommar','Höst'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '1 år fryst', 'Mangold - Betalain och K-vitamin | ViHandlar', 'Upptäck mangolds betalain-pigment och K-vitamin för benmetabolism. Data från Livsmedelsverket.'),

-- N foods
('Näringsämnesrik sprout-mix', 'naringsrik-sprout-mix', 'N', (SELECT id FROM food_categories WHERE slug = 'gront'), 29, 3.0, 0.4, 5.9, 1.8, 0.006, '{"C":"13mg","Folat":"61μg","K":"155μg"}', '{"Järn":"0.9mg","Sulforafan":"mycket högt","Kalium":"149mg"}', 'Mikrogrönsaker med koncentrerade näringsämnen', 'Groddmix innehåller koncentrerade näringsämnen och sulforafan som aktiveras vid tuggning och har detox-effekter enligt forskning.', ARRAY['Som topping på sallader','I wraps','Till smoothies'], ARRAY['Året runt'], ARRAY[]::text[], false, 'Kylskåp', '5 dagar', 'Går ej att frysa', 'Näringsrik sprout-mix - Sulforafan för detox | ViHandlar', 'Lär dig om sprouts sulforafan och koncentrerade näringsämnen för detox. Data från USDA.'),

-- O foods  
('Olja (kokosolja)', 'olja-kokosolja', 'O', (SELECT id FROM food_categories WHERE slug = 'fetter-oljor'), 862, 0.0, 99.1, 0.0, 0.0, 0.0, '{"E":"spårämnen"}', '{"MCT":"62g","Laurinsyra":"47g","Kaprilsyra":"8g"}', 'MCT-rik tropisk olja', 'Kokosolja består av 62% MCT-fetter som kan ge snabb energi till hjärnan och har antimikrobiella egenskaper enligt forskning.', ARRAY['Måttlig matlagning','I smoothies','Som hudvård'], ARRAY['Året runt'], ARRAY[]::text[], false, 'Rumstemperatur', '2 år', '3 år', 'Kokosolja - MCT för hjärnenenergi | ViHandlar', 'Upptäck kokosoljans MCT-fetter för hjärnenergiet och antimikrobiella effekter. Data från USDA.'),

-- P foods
('Persika', 'persika', 'P', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 39, 0.9, 0.3, 9.5, 1.5, 0.0, '{"C":"6.6mg","A":"16μg","E":"0.7mg"}', '{"Kalium":"190mg","Beta-karoten":"162μg","Lutein":"91μg"}', 'Saftig stenfrukt rik på beta-karoten', 'Persika innehåller beta-karoten och lutein för ögonhälsa plus fiber för tarmbakterier. Vanlig i medelhavsområdet.', ARRAY['Färsk som snacks','I fruktmatjejer','Till bakning'], ARRAY['Sommar'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '1 år fryst', 'Persika - Beta-karoten för ögonen | ViHandlar', 'Lär dig om persikas beta-karoten och lutein för ögonhälsan från medelhavskosten. Data från Livsmedelsverket.'),

-- R foods
('Rucola', 'rucola', 'R', (SELECT id FROM food_categories WHERE slug = 'gront'), 25, 2.6, 0.7, 3.7, 1.6, 0.027, '{"C":"15mg","A":"119μg","K":"109μg"}', '{"Kalium":"369mg","Glucosinolat":"högt","Kalcium":"160mg"}', 'Pepparsmakad sallad med glucosinolat', 'Rucola innehåller glucosinolat som ger pepprig smak och kan ha detoxeffekter på levern enligt forskning. Vanlig i italiensk mat.', ARRAY['I sallader','På pizza','Som pesto'], ARRAY['Vår','Höst'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '6 månader fryst', 'Rucola - Glucosinolat för levern | ViHandlar', 'Upptäck rucolas glucosinolat för leverdetox och roll i italiensk Blue Zones-mat. Data från USDA.'),

-- S foods
('Sjögräs (wakame)', 'sjogras-wakame', 'S', (SELECT id FROM food_categories WHERE slug = 'gront'), 45, 3.0, 0.6, 9.1, 0.5, 0.872, '{"A":"360μg","C":"3mg","Folat":"196μg"}', '{"Jod":"mycket högt","Kalcium":"150mg","Fucoidan":"högt"}', 'Jodrik marin grönsak från Okinawa', 'Wakame från Okinawa Blue Zone ger jod för sköldkörteln plus fucoidan som kan ha immunstärkande effekter enligt japansk forskning.', ARRAY['I misosoppa','Som sallad','Torkad som krydda'], ARRAY['Året runt'], ARRAY[]::text[], false, 'Torrt och mörkt', '2 år', '3 år', 'Wakame - Jod från Okinawa | ViHandlar', 'Upptäck wakames jod och fucoidan från Okinawas Blue Zone-kost. Data från USDA FoodData Central.'),

-- T foods
('Tahini', 'tahini', 'T', (SELECT id FROM food_categories WHERE slug = 'notter-fron'), 595, 17.0, 54.0, 21.2, 9.3, 0.115, '{"B1":"1.2mg","B6":"0.8mg","Folat":"98μg"}', '{"Kalcium":"426mg","Magnesium":"362mg","Sesamin":"högt"}', 'Sesamsmör rikt på kalcium och sesamin', 'Tahini från sesam ger mer kalcium än mjölk plus sesamin som kan ha anti-inflammatoriska egenskaper. Grundpelare i medelhavskosten.', ARRAY['I hummus','Som sås','Till bakning'], ARRAY['Året runt'], ARRAY['Sesam'], false, 'Rumstemperatur', '1 år', '2 år', 'Tahini - Kalcium från sesam | ViHandlar', 'Lär dig om tahinis kalcium och sesamin från medelhavskosten. Data från USDA.'),

-- U foods
('Ugnsrostade rödbetor', 'ugnsrostade-rodbetor', 'U', (SELECT id FROM food_categories WHERE slug = 'gront'), 44, 1.7, 0.2, 10.0, 2.0, 0.078, '{"Folat":"80μg","C":"6mg","Mangan":"0.3mg"}', '{"Kalium":"305mg","Nitrat":"koncentrerat","Betalain":"högt"}', 'Koncenterade nitrat för prestanda', 'Ugnsrostade rödbetor koncentrerar nitrat som kan förbättra syrgastransport och fysisk prestanda enligt idrottsforskning.', ARRAY['Som tillbehör','I sallader','Som purée'], ARRAY['Höst','Vinter'], ARRAY[]::text[], true, 'Kylskåp', '1 vecka', '1 år fryst', 'Ugnsrostade rödbetor - Nitrat för prestanda | ViHandlar', 'Lär dig om rostade rödbetors koncentrerade nitrat för fysisk prestanda. Data från Livsmedelsverket.'),

-- V foods  
('Valnötter', 'valnotter', 'V', (SELECT id FROM food_categories WHERE slug = 'notter-fron'), 654, 15.2, 65.2, 13.7, 6.7, 0.002, '{"Folat":"98μg","B6":"0.5mg","E":"0.7mg"}', '{"Omega-3":"9.1g","Magnesium":"158mg","Mangan":"3.4mg"}', 'Omega-3-rika nötter för kognition', 'Valnötter har högst omega-3-halt av alla nötter och koppling till hjärnhälsa. Vanliga i Blue Zone Loma Linda bland Adventister.', ARRAY['Som snacks','I müsli','Till bakning'], ARRAY['Höst'], ARRAY['Nötter'], true, 'Kylskåp', '6 månader', '1 år fryst', 'Valnötter - Omega-3 för hjärnan | ViHandlar', 'Lär dig om valnötters omega-3 för hjärnhälsa från Blue Zone Loma Linda. Data från USDA.'),

-- W foods
('Wasabi', 'wasabi', 'W', (SELECT id FROM food_categories WHERE slug = 'kryddor-orter'), 109, 4.8, 0.6, 23.5, 7.8, 0.017, '{"C":"41mg","B6":"0.3mg","Folat":"18μg"}', '{"Kalium":"568mg","Isotiocyanat":"mycket högt","Kalcium":"128mg"}', 'Japansk pepparrot med kraftfulla isotiocyanat', 'Wasabi innehåller isotiocyanat som ger stark smak och kan ha antimikrobiella egenskaper. Traditionell del av japansk Blue Zone-kost.', ARRAY['Till sushi','Som krydda','I marinader'], ARRAY['Året runt'], ARRAY[]::text[], false, 'Kylskåp färsk', '1 vecka färsk', '1 år pulver', 'Wasabi - Isotiocyanat från Japan | ViHandlar', 'Upptäck wasabis isotiocyanat och antimikrobiella egenskaper från japansk Blue Zone. Data från USDA.');

-- Update timestamps
UPDATE foods SET updated_at = NOW() WHERE created_at > NOW() - interval '1 minute';