-- Add final batch of E-additives: Övriga tillsatser (Other additives)

INSERT INTO e_additives (e_number, name, category, slug) VALUES 

-- Övriga tillsatser (Other additives)
('E450', 'Magnesiumdivätefosfat', 'Övriga tillsatser', 'e450-magnesiumdivatefosf at'),
('E463a', 'Lågsubstituerad hydroxipropylcellulosa', 'Övriga tillsatser', 'e463a-lagsubstituerad-hydroxipropylcellulosa'),
('E500', 'Natriumkarbonater', 'Övriga tillsatser', 'e500-natriumkarbonater'),
('E501', 'Kaliumkarbonater', 'Övriga tillsatser', 'e501-kaliumkarbonater'),
('E503', 'Ammoniumkarbonater', 'Övriga tillsatser', 'e503-ammoniumkarbonater'),
('E504', 'Magnesiumkarbonater', 'Övriga tillsatser', 'e504-magnesiumkarbonater'),
('E507', 'Saltsyra', 'Övriga tillsatser', 'e507-saltsyra'),
('E508', 'Kaliumklorid', 'Övriga tillsatser', 'e508-kaliumklorid'),
('E509', 'Kalciumklorid', 'Övriga tillsatser', 'e509-kalciumklorid'),
('E511', 'Magnesiumklorid', 'Övriga tillsatser', 'e511-magnesiumklorid'),
('E512', 'Tennklorid', 'Övriga tillsatser', 'e512-tennklorid'),
('E513', 'Svavelsyra', 'Övriga tillsatser', 'e513-svavelsyra'),
('E514', 'Natriumsulfater', 'Övriga tillsatser', 'e514-natriumsulfater'),
('E515', 'Kaliumsulfater', 'Övriga tillsatser', 'e515-kaliumsulfater'),
('E516', 'Kalciumsulfat', 'Övriga tillsatser', 'e516-kalciumsulfat'),
('E517', 'Ammoniumsulfat', 'Övriga tillsatser', 'e517-ammoniumsulfat'),
('E520', 'Aluminiumsulfat', 'Övriga tillsatser', 'e520-aluminiumsulfat'),
('E521', 'Aluminiumnatriumsulfat', 'Övriga tillsatser', 'e521-aluminiumnatriumsulfat'),
('E522', 'Aluminiumkaliumsulfat', 'Övriga tillsatser', 'e522-aluminiumkaliumsulfat'),
('E523', 'Aluminiumammoniumsulfat', 'Övriga tillsatser', 'e523-aluminiumammoniumsulfat'),
('E524', 'Natriumhydroxid', 'Övriga tillsatser', 'e524-natriumhydroxid'),
('E525', 'Kaliumhydroxid', 'Övriga tillsatser', 'e525-kaliumhydroxid'),
('E526', 'Kalciumhydroxid', 'Övriga tillsatser', 'e526-kalciumhydroxid'),
('E527', 'Ammoniumhydroxid', 'Övriga tillsatser', 'e527-ammoniumhydroxid'),
('E528', 'Magnesiumhydroxid', 'Övriga tillsatser', 'e528-magnesiumhydroxid'),
('E529', 'Kalciumoxid', 'Övriga tillsatser', 'e529-kalciumoxid'),
('E530', 'Magnesiumoxid', 'Övriga tillsatser', 'e530-magnesiumoxid'),
('E534', 'Järntartrat', 'Övriga tillsatser', 'e534-jarntartrat'),
('E535', 'Natriumferrocyanid', 'Övriga tillsatser', 'e535-natriumferrocyanid'),
('E536', 'Kaliumferrocyanid', 'Övriga tillsatser', 'e536-kaliumferrocyanid'),
('E538', 'Kalciumferrocyanid', 'Övriga tillsatser', 'e538-kalciumferrocyanid'),
('E541', 'Natriumaluminiumfosfat, surt', 'Övriga tillsatser', 'e541-natriumaluminiumfosfat-surt'),
('E551', 'Kiseldioxid', 'Övriga tillsatser', 'e551-kiseldioxid'),
('E552', 'Kalciumsilikat', 'Övriga tillsatser', 'e552-kalciumsilikat'),
('E553a', 'Magnesiumsilikater', 'Övriga tillsatser', 'e553a-magnesiumsilikater'),
('E553b', 'Talk', 'Övriga tillsatser', 'e553b-talk'),
('E554', 'Natriumaluminiumsilikat', 'Övriga tillsatser', 'e554-natriumaluminiumsilikat'),
('E555', 'Kaliumaluminiumsilikat', 'Övriga tillsatser', 'e555-kaliumaluminiumsilikat'),
('E570', 'Fettsyror', 'Övriga tillsatser', 'e570-fettsyror'),
('E574', 'Glukonsyra', 'Övriga tillsatser', 'e574-glukonsyra'),
('E575', 'Glukonsyrans deltalakton', 'Övriga tillsatser', 'e575-glukonsyrans-deltalakton'),
('E576', 'Natriumglukonat', 'Övriga tillsatser', 'e576-natriumglukonat'),
('E577', 'Kaliumglukonat', 'Övriga tillsatser', 'e577-kaliumglukonat'),
('E578', 'Kalciumglukonat', 'Övriga tillsatser', 'e578-kalciumglukonat'),
('E579', 'Järnglukonat (Ferroglukonat)', 'Övriga tillsatser', 'e579-jarnglukonat-ferroglukonat'),
('E585', 'Järnlaktat (Ferrolaktat)', 'Övriga tillsatser', 'e585-jarnlaktat-ferrolaktat'),
('E620', 'Glutaminsyra', 'Övriga tillsatser', 'e620-glutaminsyra'),
('E621', 'Mononatriumglutamat', 'Övriga tillsatser', 'e621-mononatriumglutamat'),
('E622', 'Monokaliumglutamat', 'Övriga tillsatser', 'e622-monokaliumglutamat'),
('E623', 'Kalciumdiglutamat', 'Övriga tillsatser', 'e623-kalciumdiglutamat'),
('E624', 'Monoammoniumglutamat', 'Övriga tillsatser', 'e624-monoammoniumglutamat'),
('E625', 'Magnesiumdiglutamat', 'Övriga tillsatser', 'e625-magnesiumdiglutamat'),
('E626', 'Guanylsyra', 'Övriga tillsatser', 'e626-guanylsyra'),
('E627', 'Dinatriumguanylat', 'Övriga tillsatser', 'e627-dinatriumguanylat'),
('E628', 'Dikaliumguanylat', 'Övriga tillsatser', 'e628-dikaliumguanylat'),
('E629', 'Kalciumguanylat', 'Övriga tillsatser', 'e629-kalciumguanylat'),
('E630', 'Inosinsyra', 'Övriga tillsatser', 'e630-inosinsyra'),
('E631', 'Dinatriuminosinat', 'Övriga tillsatser', 'e631-dinatriuminosinat'),
('E632', 'Dikaliuminosinat', 'Övriga tillsatser', 'e632-dikaliuminosinat'),
('E633', 'Kalciuminosinat', 'Övriga tillsatser', 'e633-kalciuminosinat'),
('E634', 'Kalcium-5''-ribonukleotider', 'Övriga tillsatser', 'e634-kalcium-5-ribonukleotider'),
('E635', 'Dinatrium-5''-ribonukleotider', 'Övriga tillsatser', 'e635-dinatrium-5-ribonukleotider'),
('E640', 'Glycin', 'Övriga tillsatser', 'e640-glycin'),
('E641', 'L-Leucin', 'Övriga tillsatser', 'e641-l-leucin'),
('E650', 'Zinkacetat', 'Övriga tillsatser', 'e650-zinkacetat'),
('E900', 'Dimetylpolysiloxan', 'Övriga tillsatser', 'e900-dimetylpolysiloxan'),
('E901', 'Bivax', 'Övriga tillsatser', 'e901-bivax'),
('E902', 'Kandelillavax', 'Övriga tillsatser', 'e902-kandelillavax'),
('E903', 'Karnaubavax', 'Övriga tillsatser', 'e903-karnaubavax'),
('E904', 'Shellack', 'Övriga tillsatser', 'e904-shellack'),
('E905', 'Mikrokristallint vax', 'Övriga tillsatser', 'e905-mikrokristallint-vax'),
('E907', 'Hydrogenerat poly-1-deken', 'Övriga tillsatser', 'e907-hydrogenerat-poly-1-deken'),
('E914', 'Oxiderat polyetylenvax', 'Övriga tillsatser', 'e914-oxiderat-polyetylenvax'),
('E920', 'L-cystein', 'Övriga tillsatser', 'e920-l-cystein'),
('E927b', 'Karbamid', 'Övriga tillsatser', 'e927b-karbamid'),
('E938', 'Argon', 'Övriga tillsatser', 'e938-argon'),
('E939', 'Helium', 'Övriga tillsatser', 'e939-helium'),
('E941', 'Kväve', 'Övriga tillsatser', 'e941-kvave'),
('E942', 'Dikväveoxid', 'Övriga tillsatser', 'e942-dikvaveoxid'),
('E943a', 'Butan', 'Övriga tillsatser', 'e943a-butan'),
('E943b', 'Isobutan', 'Övriga tillsatser', 'e943b-isobutan'),
('E944', 'Propan', 'Övriga tillsatser', 'e944-propan'),
('E948', 'Syre', 'Övriga tillsatser', 'e948-syre'),
('E949', 'Väte', 'Övriga tillsatser', 'e949-vate'),
('E999', 'Kvillajaextrakt', 'Övriga tillsatser', 'e999-kvillajaextrakt'),
('E1103', 'Invertas', 'Övriga tillsatser', 'e1103-invertas'),
('E1105', 'Lysozym', 'Övriga tillsatser', 'e1105-lysozym'),
('E1200', 'Polydextros', 'Övriga tillsatser', 'e1200-polydextros'),
('E1201', 'Polyvinylpyrrolidon', 'Övriga tillsatser', 'e1201-polyvinylpyrrolidon'),
('E1202', 'Polyvinylpolypyrrolidon', 'Övriga tillsatser', 'e1202-polyvinylpolypyrrolidon'),
('E1203', 'Polyvinylalkohol', 'Övriga tillsatser', 'e1203-polyvinylalkohol'),
('E1205', 'Basisk metakrylatsampolymer', 'Övriga tillsatser', 'e1205-basisk-metakrylatsampolymer'),
('E1206', 'Neutral metakrylatsampolymer', 'Övriga tillsatser', 'e1206-neutral-metakrylatsampolymer'),
('E1207', 'Anjonisk metakrylatsampolymer', 'Övriga tillsatser', 'e1207-anjonisk-metakrylatsampolymer'),
('E1208', 'Polyvinylpyrrolidon-vinylacetatsampolymer', 'Övriga tillsatser', 'e1208-polyvinylpyrrolidon-vinylacetatsampolymer'),
('E1209', 'Polyvinylalkohol-polyetylenglykol-ymp-sampolymer', 'Övriga tillsatser', 'e1209-polyvinylalkohol-polyetylenglykol-ymp-sampolymer'),
('E1404-1452', 'Stärkelse', 'Övriga tillsatser', 'e1404-1452-starkelse'),
('E1505', 'Trietylcitrat', 'Övriga tillsatser', 'e1505-trietylcitrat'),
('E1517', 'Glyceryldiacetat', 'Övriga tillsatser', 'e1517-glyceryldiacetat'),
('E1518', 'Glyceryltriacetat', 'Övriga tillsatser', 'e1518-glyceryltriacetat'),
('E1519', 'Benzylalkohol', 'Övriga tillsatser', 'e1519-benzylalkohol'),
('E1520', 'Propan-1,2-diol', 'Övriga tillsatser', 'e1520-propan-12-diol'),
('E1521', 'Polyetylenglykol', 'Övriga tillsatser', 'e1521-polyetylenglykol')

ON CONFLICT (e_number) DO NOTHING;