-- Slutbatch för att nå närmare 316-330 E-ämnen från Livsmedelsverket
-- Fokuserar på viktiga saknade E-nummer från olika kategorier

INSERT INTO e_additives (
  e_number, name, common_name, category, slug, 
  short_description, long_description, risk_score, 
  adi_value, adi_source, origin, health_effects, 
  common_products, avoidance_tips, natural_alternatives,
  children_note, longevity_impact
) VALUES

-- SAKNADE FRÅN 322A SERIEN
('E322a', 'Havrelecitin', 'Lecitin från havre', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e322a-havrelecitin',
'Naturligt lecitin från havre för emulgering.',
'Havrelecitin är en naturlig emulgerare från havre som är ett bra alternativ till sojalecitin.',
1, NULL, 'Quantum satis', 'Naturlig (havre)',
'{"positive": ["Naturligt från havre", "Allergivänligt", "Emulgerare"], "negative": [], "neutral": ["Alternativ till soja"]}',
'{"categories": ["Choklad", "Bakverk", "Margarin"], "note": "Sojaallergialternativ"}',
ARRAY['Mycket säkert och naturligt'],
ARRAY['Sojalecitin', 'Naturlig äggula'],
'Mycket säkert för barn',
'Positiv'),

-- SAKNADE 345 SERIEN
('E345', 'Trimagnesiumdicitrat', 'Magnesiumsalt av citronsyra', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e345-trimagnesiumdicitrat',
'Magnesiumsalt av citronsyra för stabilisering.',
'Trimagnesiumdicitrat fungerar som stabilisator och tillför magnesium.',
2, NULL, 'Quantum satis', 'Syntetisk',
'{"positive": ["Magnesiumkälla", "Stabilisator"], "negative": [], "neutral": ["Teknisk funktion"]}',
'{"categories": ["Pulver", "Kosttillskott"], "note": "Magnesiumförstärkt"}',
ARRAY['Fördelaktigt för magnesiumintag'],
ARRAY['Naturligt magnesium'],
'Fördelaktigt för barn (magnesium)',
'Positiv'),

-- SAKNADE 350-SERIEN
('E350', 'Natriummalater', 'Natriumsalt av äppelsyra', 'Antioxidationsmedel', 'e350-natriummalat',
'Natriumsalt av äppelsyra för pH-kontroll.',
'Natriummalat är natriumsaltet av naturlig äppelsyra och fungerar som pH-regulator.',
2, NULL, 'Quantum satis', 'Naturlig/syntetisk',
'{"positive": ["Från naturlig äppelsyra"], "negative": [], "neutral": ["pH-regulator"]}',
'{"categories": ["Drycker", "Konfekt"], "note": "pH-kontroll"}',
ARRAY['Säkert att använda'],
ARRAY['Naturlig äppelsyra från äpplen'],
'Säkert för barn',
'Positiv'),

('E351', 'Kaliummalat', 'Kaliumsalt av äppelsyra', 'Antioxidationsmedel', 'e351-kaliummalat',
'Kaliumsalt av äppelsyra för pH-kontroll och mineraltillförsel.',
'Kaliummalat kombinerar pH-reglering med kaliumtillförsel.',
2, NULL, 'Quantum satis', 'Naturlig/syntetisk',
'{"positive": ["Kaliumkälla", "Från äppelsyra"], "negative": [], "neutral": ["pH-regulator"]}',
'{"categories": ["Sportdrycker", "Funktionella livsmedel"], "note": "Kaliumförstärkt"}',
ARRAY['Fördelaktigt för kaliumintag'],
ARRAY['Naturligt kalium från bananer'],
'Fördelaktigt för barn (kalium)',
'Positiv'),

('E352', 'Kalciummalater', 'Kalciumsalt av äppelsyra', 'Antioxidationsmedel', 'e352-kalciummalat',
'Kalciumsalt av äppelsyra för pH-kontroll och kalciumtillförsel.',
'Kalciummalat kombinerar surhetsreglering med kalciumtillförsel.',
1, NULL, 'Quantum satis', 'Naturlig/syntetisk',
'{"positive": ["Kalciumkälla", "pH-regulator"], "negative": [], "neutral": ["Från äppelsyra"]}',
'{"categories": ["Kosttillskott", "Drycker"], "note": "Kalciumberikning"}',
ARRAY['Mycket fördelaktigt för kalciumintag'],
ARRAY['Naturligt kalcium från mejeri'],
'Mycket fördelaktigt för barn',
'Positiv'),

-- SAKNADE 353-SERIEN
('E353', 'Metavinsyra', 'Polymeriserad vinsyra', 'Antioxidationsmedel', 'e353-metavinsyra',
'Polymeriserad form av vinsyra för stabilisering.',
'Metavinsyra förhindrar kristallbildning i vin och andra produkter.',
2, NULL, 'Quantum satis', 'Syntetisk (från vinsyra)',
'{"positive": ["Från naturlig vinsyra"], "negative": [], "neutral": ["Kristalliseringsinhibitor"]}',
'{"categories": ["Vin", "Vissa drycker"], "note": "Kristallkontroll"}',
ARRAY['Säkert att använda'],
ARRAY['Naturlig vinsyra'],
'Säkert för barn',
'Neutral'),

('E354', 'Kalciumtartrat', 'Kalciumsalt av vinsyra', 'Antioxidationsmedel', 'e354-kalciumtartrat',
'Kalciumsalt av vinsyra för stabilisering och kalciumtillförsel.',
'Kalciumtartrat fungerar som stabilisator och tillför kalcium.',
2, NULL, 'Quantum satis', 'Naturlig/syntetisk',
'{"positive": ["Kalciumkälla", "Från vinsyra"], "negative": [], "neutral": ["Stabilisator"]}',
'{"categories": ["Bakverk", "Vineriska produkter"], "note": "Kalciumförstärkt"}',
ARRAY['Fördelaktigt för kalciumintag'],
ARRAY['Naturlig vinsyra'],
'Fördelaktigt för barn',
'Positiv'),

-- SAKNADE 355-SERIEN 
('E355', 'Adipinsyra', 'Hexandisyra', 'Antioxidationsmedel', 'e355-adipinsyra',
'Dikarboxylsyra för pH-kontroll och smakförstärkning.',
'Adipinsyra används för att ge syrlig smak och reglera pH.',
3, 5, 'mg/kg kroppsvikt/dag - EFSA', 'Syntetisk',
'{"positive": ["pH-kontroll"], "negative": [], "neutral": ["Syrlig smak"]}',
'{"categories": ["Dryckespulver", "Geléprodukter"], "note": "Syrlig smakgivare"}',
ARRAY['Säkert inom ADI-gräns'],
ARRAY['Citronsyra', 'Andra naturliga syror'],
'Säkert för barn inom gränser',
'Neutral'),

('E356', 'Natriumadipat', 'Natriumsalt av adipinsyra', 'Antioxidationsmedel', 'e356-natriumadipat',
'Natriumsalt av adipinsyra för pH-kontroll.',
'Natriumadipat är natriumsaltet av adipinsyra och fungerar som pH-regulator.',
3, 5, 'mg/kg kroppsvikt/dag - EFSA', 'Syntetisk',
'{"positive": ["pH-regulator"], "negative": [], "neutral": ["Teknisk funktion"]}',
'{"categories": ["Drycker", "Geléprodukter"], "note": "pH-buffert"}',
ARRAY['Säkert inom ADI-värde'],
ARRAY['Andra pH-regulatorer'],
'Säkert för barn',
'Neutral'),

('E357', 'Kaliumadipat', 'Kaliumsalt av adipinsyra', 'Antioxidationsmedel', 'e357-kaliumadipat',
'Kaliumsalt av adipinsyra för pH-kontroll och mineraltillförsel.',
'Kaliumadipat kombinerar pH-reglering med kaliumtillförsel.',
3, 5, 'mg/kg kroppsvikt/dag - EFSA', 'Syntetisk',
'{"positive": ["Kaliumkälla", "pH-regulator"], "negative": [], "neutral": ["Teknisk funktion"]}',
'{"categories": ["Drycker", "Funktionella produkter"], "note": "Kaliumförstärkt"}',
ARRAY['Fördelaktigt för kaliumintag'],
ARRAY['Naturligt kalium'],
'Fördelaktigt för barn',
'Positiv'),

-- SAKNADE 363
('E363', 'Bärnstenssyra', 'Succinic acid', 'Antioxidationsmedel', 'e363-barnstenssyra',
'Naturlig dikarboxylsyra för pH-kontroll.',
'Bärnstenssyra är en naturlig syra som används för pH-reglering och smakmodifiering.',
2, NULL, 'Quantum satis', 'Naturlig',
'{"positive": ["Naturlig syra", "pH-kontroll"], "negative": [], "neutral": ["Teknisk användning"]}',
'{"categories": ["Drycker", "Vissa livsmedel"], "note": "Naturlig syra"}',
ARRAY['Helt säkert och naturligt'],
ARRAY['Andra naturliga syror'],
'Säkert för barn',
'Positiv'),

-- SAKNADE 380
('E380', 'Triammoniumcitrat', 'Ammoniumsalt av citronsyra', 'Antioxidationsmedel', 'e380-triammoniumcitrat',
'Ammoniumsalt av citronsyra för antioxidation.',
'Triammoniumcitrat fungerar som antioxidant och pH-buffert.',
3, NULL, 'Quantum satis', 'Syntetisk',
'{"positive": ["Antioxidant", "pH-buffert"], "negative": [], "neutral": ["Ammoniumsalt"]}',
'{"categories": ["Vissa bearbetade produkter"], "note": "Teknisk antioxidant"}',
ARRAY['Säkert vid godkända nivåer'],
ARRAY['Naturliga antioxidanter'],
'Säkert för barn',
'Neutral'),

-- SAKNADE 392
('E392', 'Extrakt av rosmarin', 'Naturligt rosmarinextrakt', 'Antioxidationsmedel', 'e392-extrakt-av-rosmarin',
'Naturligt antioxidant från rosmarin med stark effekt.',
'Rosmarinextrakt innehåller karnosol och karnosinsyra som är kraftfulla naturliga antioxidanter.',
1, NULL, 'Quantum satis', 'Naturlig (rosmarin)',
'{"positive": ["Naturligt växrtextrakt", "Kraftfullt antioxidant", "Anti-inflammatoriskt"], "negative": [], "neutral": ["Kan påverka smak"]}',
'{"categories": ["Oljor", "Kött", "Snacks"], "note": "Naturligt kraftfullt antioxidant"}',
ARRAY['Mycket hälsofrämjande och säkert'],
ARRAY['Färsk rosmarin', 'Andra örtantioxidanter'],
'Mycket fördelaktigt för barn',
'Positiv'),

-- SAKNADE HÖGA NUMMER

-- E407a - Bearbetad Eucheumaalg
('E407a', 'Bearbetad Eucheumaalg', 'PES (Processed Eucheuma Seaweed)', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e407a-bearbetad-eucheumaalg',
'Bearbetad rödalg för gelering och förtjockning.',
'Bearbetad Eucheumaalg är en form av karragenan som genomgått alkalibehandling.',
3, NULL, 'Quantum satis', 'Bearbetad alg',
'{"positive": ["Naturligt ursprung från alg"], "negative": ["Alkalibehandling"], "neutral": ["Alternativ till vanlig karragenan"]}',
'{"categories": ["Mejerivaror", "Veganska produkter"], "note": "Alternativ karragenan"}',
ARRAY['Måttlig användning rekommenderas'],
ARRAY['E406 (Agar)', 'Gelatin'],
'Måttlig användning för barn',
'Neutral'),

-- E413 - Dragant
('E413', 'Dragant', 'Tragakanth', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e413-dragant',
'Naturligt växrexsudat från Astragalus-växter.',
'Dragant är en naturlig gummi som utsöndras av Astragalus-träd och används som förtjockningsmedel.',
2, NULL, 'Quantum satis', 'Naturlig (trädsaft)',
'{"positive": ["Helt naturlig", "Traditionellt använd"], "negative": [], "neutral": ["Dyr råvara"]}',
'{"categories": ["Glass", "Konditoriprodukter"], "note": "Premium naturligt förtjockningsmedel"}',
ARRAY['Helt säkert och naturligt'],
ARRAY['Gummi arabicum', 'Andra naturliga gummin'],
'Säkert för barn',
'Positiv'),

-- E423 - Gummi arabicum modifierat med oktenylbärnstenssyra
('E423', 'Gummi arabicum modifierat med oktenylbärnstenssyra', 'OSA-modifierat gummi arabicum', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e423-modifierat-gummi-arabicum',
'Kemiskt modifierat gummi arabicum för förbättrad emulgering.',
'Gummi arabicum behandlat med oktenylbärnstenssyra för förbättrade emulgeringsegenskaper.',
3, NULL, 'Quantum satis', 'Modifierad naturlig',
'{"positive": ["Förbättrade egenskaper"], "negative": ["Kemisk modifiering"], "neutral": ["Teknisk förbättring"]}',
'{"categories": ["Drycker", "Emulsioner"], "note": "Förbättrat emulgeringsmedel"}',
ARRAY['Säkert vid godkänd användning'],
ARRAY['Vanligt gummi arabicum'],
'Säkert för barn',
'Neutral'),

-- E425 - Konjakgummi
('E425', 'Konjakgummi', 'Glukomanan från konjak', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e425-konjakgummi',
'Naturlig fiber från konjakrot med viktminskningseffekter.',
'Konjakgummi är en löslig fiber som sväller enormt i vatten och kan hjälpa med viktminskning.',
2, NULL, 'Quantum satis', 'Naturlig (konjakrot)',
'{"positive": ["Viktminskning", "Löslig fiber", "Mättnadskänsla"], "negative": ["Kan blockera matstrupe om ej tillräckligt vätskeintag"], "neutral": ["Kräver mycket vätska"]}',
'{"categories": ["Viktminska produkter", "Nudlar", "Kosttillskott"], "note": "Viktminskning fiber"}',
ARRAY['Ta med mycket vätska', 'Följ doseringsanvisningar'],
ARRAY['Andra lösliga fibrer'],
'Försiktighet för små barn (kvävningsrisk)',
'Positiv'),

-- E426 - Sojabönshemicellulosa
('E426', 'Sojabönshemicellulosa', 'Sojafiber', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e426-sojabonshemicellulosa',
'Naturlig fiber från sojabönor för texturförbättring.',
'Sojabönshemicellulosa är en naturlig fiber som förbättrar textur och tillför kostfiber.',
1, NULL, 'Quantum satis', 'Naturlig (soja)',
'{"positive": ["Naturlig fiber", "Texturförbättring", "Kostfiber"], "negative": [], "neutral": ["Från soja"]}',
'{"categories": ["Köttsubstitut", "Veganska produkter"], "note": "Naturlig sojafiber"}',
ARRAY['Mycket säkert och nyttigt', 'Undvik vid sojaallergi'],
ARRAY['Andra naturliga fibrer'],
'Säkert för barn (ej vid sojaallergi)',
'Positiv'),

-- E427 - Cassiagummi
('E427', 'Cassiagummi', 'Gummi från Cassia-träd', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e427-cassiagummi',
'Naturligt trädgummi med förtjockande egenskaper.',
'Cassiagummi utvinns från Cassia-träd och används som naturligt förtjockningsmedel.',
2, NULL, 'Quantum satis', 'Naturlig (träd)',
'{"positive": ["Naturligt trädgummi"], "negative": [], "neutral": ["Sällan använt"]}',
'{"categories": [], "note": "Sällan använt"}',
ARRAY['Säkert och naturligt'],
ARRAY['Andra naturliga gummin'],
'Säkert för barn',
'Positiv'),

-- SAKNADE POLYSORBATER
('E432', 'Polyoxietylensorbitanmonolaurat', 'Polysorbat 20', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e432-polysorbat-20',
'Syntetiskt emulgeringsmedel från sorbitol och fettsyror.',
'Polysorbat 20 är ett mångsidigt emulgeringsmedel som blandar olja och vatten.',
4, 10, 'mg/kg kroppsvikt/dag - WHO/FAO', 'Syntetisk',
'{"positive": ["Effektivt emulgeringsmedel"], "negative": ["Syntetiskt"], "neutral": ["Vanligt använt"]}',
'{"categories": ["Glass", "Såser", "Kosmetika"], "note": "Vanligt emulgeringsmedel"}',
ARRAY['Säkert inom ADI-gräns'],
ARRAY['Naturligt lecitin', 'Äggula'],
'Säkert för barn inom gränser',
'Neutral'),

('E433', 'Polyoxietylensorbitanmonooleat', 'Polysorbat 80', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e433-polysorbat-80',
'Vanligaste polysorbatet för emulgering.',
'Polysorbat 80 är det mest använda polysorbatet för emulgering av olja i vatten.',
4, 10, 'mg/kg kroppsvikt/dag - WHO/FAO', 'Syntetisk',
'{"positive": ["Mycket effektiv emulgering"], "negative": ["Kan påverka tarmflora"], "neutral": ["Mycket vanligt"]}',
'{"categories": ["Glass", "Bakprodukter", "Såser"], "note": "Vanligaste polysorbatet"}',
ARRAY['Måttlig konsumtion rekommenderas', 'Variera emulgeringsmedel'],
ARRAY['Naturligt lecitin'],
'Måttlig användning för barn',
'Negativ'),

-- SAKNADE 434-436
('E434', 'Polyoxietylensorbitanmonopalmitat', 'Polysorbat 40', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e434-polysorbat-40',
'Polysorbat baserat på palmitinsyra för emulgering.',
'Polysorbat 40 är specialiserat för emulgering med palmitinsyra.',
4, 10, 'mg/kg kroppsvikt/dag - WHO/FAO', 'Syntetisk',
'{"positive": ["Specifik emulgeringsegenskaper"], "negative": ["Syntetiskt"], "neutral": ["Specialiserat användning"]}',
'{"categories": ["Speciella emulsioner"], "note": "Specialiserat polysorbat"}',
ARRAY['Säkert inom ADI'],
ARRAY['Andra emulgeringsmedel'],
'Säkert för barn inom gränser',
'Neutral'),

('E435', 'Polyoxietylensorbitanmonostearat', 'Polysorbat 60', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e435-polysorbat-60',
'Polysorbat för emulgering av stearinsyra.',
'Polysorbat 60 är optimerat för emulgering av stearinsyrehaltiga system.',
4, 10, 'mg/kg kroppsvikt/dag - WHO/FAO', 'Syntetisk',
'{"positive": ["Effektiv för fasta fetter"], "negative": ["Syntetiskt"], "neutral": ["Specialiserat"]}',
'{"categories": ["Bakverk", "Margarin"], "note": "För fasta fettsystem"}',
ARRAY['Säkert inom ADI-värde'],
ARRAY['Naturligt lecitin'],
'Säkert för barn inom gränser',
'Neutral'),

('E436', 'Polyoxietylensorbitantristearat', 'Polysorbat 65', 'Emulgerings-, stabiliserings-, förtjocknings- och geleringsmedel', 'e436-polysorbat-65',
'Polysorbat för emulgering av tristearin.',
'Polysorbat 65 används för emulgering av system med högt innehåll av mättade fettsyror.',
4, 10, 'mg/kg kroppsvikt/dag - WHO/FAO', 'Syntetisk',
'{"positive": ["Specialiserad emulgering"], "negative": ["Syntetiskt"], "neutral": ["Sällan använt"]}',
'{"categories": ["Vissa margarintyper"], "note": "Specialiserat polysorbat"}',
ARRAY['Säkert inom ADI'],
ARRAY['Andra emulgeringsmedel'],
'Säkert för barn inom gränser',
'Neutral');