-- Fix the previous migration with proper quotes and complete remaining foods
UPDATE foods SET long_description = 'Potatis är en näringsrik rotfrukt som är rik på kolhydrater, kalium och vitamin C. En medelstor potatis med skal innehåller mer kalium än en banan och betydande mängder fiber. Potatis innehåller också vitamin B6, magnesium och antioxidanter. Olika sorter har olika egenskaper - fastkokarande potatis håller formen bra i sallader medan mjölig potatis är perfekt för mos. Skalet innehåller mycket av näringsämnena, så skala så lite som möjligt. Förvara potatis mörkt och svalt men inte i kylskåp. Grön potatis ska undvikas då den innehåller giftiga alkaloider.' WHERE slug = 'potatis';

UPDATE foods SET long_description = 'Quinoa är en näringsrik pseudospannmål från Sydamerika som innehåller alla nio essentiella aminosyror, vilket gör den till ett komplett protein. Det är glutenfritt och rik på fiber, magnesium, järn och mangan. Quinoa har lägre glykemiskt index än ris och pasta, vilket gör den bra för blodsockerkontroll. Skölj quinoa innan kokning för att ta bort de naturliga saponinerna som kan smaka bittert. Koka i förhållandet 1:2 (quinoa:vätska) i 15 minuter. Quinoa är mångsidig och kan användas som tillbehör, i sallader eller som frukostgröt.' WHERE slug = 'quinoa';

UPDATE foods SET long_description = 'Räkor är magra skaldjur som är rika på protein och låga i kalorier - 100 gram räkor innehåller cirka 18 gram protein och endast 85 kalorier. De är en utmärkt källa till selen, jod och vitamin B12. Räkor innehåller också omega-3-fettsyror och astaxantin, en kraftfull antioxidant. Färska räkor ska lukta hav och ha fast konsistens. De tillagas snabbt - för länge kokning gör dem gummiga. Räkor är perfekta i wok, sallader, pasta eller som tilltugg. Frys råa räkor om de inte ska användas samma dag.' WHERE slug = 'rakor';

UPDATE foods SET long_description = 'Rödlök har en mild, söt smak jämfört med gul lök och innehåller höga halter av antocyaniner som ger den lila färgen och kraftfulla antioxidantegenskaper. Den innehåller quercetin, svavel föreningar och vitamin C. Rödlök är perfekt rå i sallader eftersom den är mindre skarp än gul lök. Den behåller sin vackra färg bäst när den inte kokas för länge. Rödlök kan marineras i vinäger för ännu mildare smak. Förvara som vanlig lök i torr, mörk miljö.' WHERE slug = 'rodlok';

UPDATE foods SET long_description = 'Ruccola är en pepparig salladsblad som tillhör familjen korsblommiga växter. Den innehåller höga halter av vitamin K för benhälsa, folsyra och antioxidanter som beta-karoten. Ruccola har en distinkt pepparig, nötig smak som blir starkare när bladen mognar. Den är perfekt i sallader, på pizza eller som garnering. Ruccola innehåller naturliga nitrater som kan stödja blodcirkulationen. Förvara i kylskåp och använd snabbt eftersom den vissnar lätt.' WHERE slug = 'ruccola';