-- Add remaining E-additives to reach target of 330 (corrected array syntax)
-- This batch adds various E-numbers from Livsmedelsverket including more specialized additives

INSERT INTO public.e_additives (
  e_number, name, common_name, slug, category, origin, 
  risk_score, adi_value, adi_source, short_description, 
  long_description, health_effects, common_products,
  avoidance_tips, natural_alternatives, longevity_impact,
  children_note, meta_title, meta_description
) VALUES

-- E500 series - Mineral salts and pH regulators
('E500', 'Natriumkarbonat', 'Soda', 'e500-natriumkarbonat', 'Mineraliska salter', 'Mineral', 1, NULL, 'Livsmedelsverket', 
'Alkaliskt salt som används för pH-reglering',
'Natriumkarbonat är ett alkaliskt salt som används som pH-reglerande medel i livsmedelsindustrin. Det hjälper till att kontrollera surhetsgraden i olika produkter.',
'[{"effect": "Generellt säker", "severity": "low", "description": "Inga kända negativa hälsoeffekter vid normal konsumtion"}]',
'[{"category": "Bakverk", "products": ["Pepparkakor", "Kex"]}, {"category": "Konditorivaror", "products": ["Choklad", "Karameller"]}]',
'{"Används i små mängder", "Naturligt förekommande mineral"}',
'{"Kaliumkarbonat", "Kalciumkarbonat"}',
'Neutral påverkan på livslängd',
'Säker för barn i normala mängder',
'E500 Natriumkarbonat - Mineraliskt salt för pH-reglering',
'Läs om E500 Natriumkarbonat, dess användning som pH-reglerare och säkerhet enligt Livsmedelsverket.'),

('E501', 'Kaliumkarbonat', 'Potaska', 'e501-kaliumkarbonat', 'Mineraliska salter', 'Mineral', 1, NULL, 'Livsmedelsverket', 
'Alkaliskt kaliumsalt för pH-reglering',
'Kaliumkarbonat används som pH-reglerande medel och alkaliserande ämne i livsmedel. Det är ett naturligt mineral som hjälper till att kontrollera surhetsgraden.',
'[{"effect": "Generellt säker", "severity": "low", "description": "Inga kända hälsorisker vid normal användning"}]',
'[{"category": "Choklad", "products": ["Kakaopulver", "Chokladprodukter"]}, {"category": "Bakverk", "products": ["Kex", "Kakor"]}]',
'{"Används i begränsade mängder", "Naturligt mineral"}',
'{"Natriumkarbonat", "Kalciumkarbonat"}',
'Neutral påverkan på livslängd',
'Säker för barn',
'E501 Kaliumkarbonat - Alkaliskt salt för pH-kontroll',
'Information om E501 Kaliumkarbonat, användning som pH-reglerare och säkerhetsbedömning.'),

('E503', 'Ammoniumkarbonat', 'Hjorthornssalt', 'e503-ammoniumkarbonat', 'Jäsmedel', 'Syntetisk', 1, NULL, 'Livsmedelsverket', 
'Traditionellt jäsmedel för bakning',
'Ammoniumkarbonat är ett traditionellt jäsmedel som används i bakning, särskilt för tunna kakor och kex. Det avger ammoniak vid uppvärmning vilket ger jäseffekt.',
'[{"effect": "Generellt säker", "severity": "low", "description": "Bryts ned till koldioxid, vatten och ammoniak under bakning"}]',
'[{"category": "Bakverk", "products": ["Pepparkakor", "Tunnbröd", "Kex"]}, {"category": "Konditorivaror", "products": ["Kakor", "Småkakor"]}]',
'{"Ammoniaklukt försvinner vid bakning", "Används bara i tunna produkter"}',
'{"Bakpulver", "Jäst", "Natriumbikarbonat"}',
'Neutral påverkan på livslängd',
'Säker för barn efter bakning',
'E503 Ammoniumkarbonat - Traditionellt jäsmedel för bakning',
'Läs om E503 Ammoniumkarbonat (hjorthornssalt), dess användning som jäsmedel och säkerhet.'),

('E504', 'Magnesiumkarbonat', 'Magnesia', 'e504-magnesiumkarbonat', 'Mineraliska salter', 'Mineral', 1, NULL, 'Livsmedelsverket', 
'Mineraliskt salt som antiklumpmedel',
'Magnesiumkarbonat används som antiklumpmedel för att förhindra att pulverformiga livsmedel klumpar sig. Det är också en källa till magnesium.',
'[{"effect": "Generellt säker", "severity": "low", "description": "Bidrar till magnesiumintaget, inga kända risker"}]',
'[{"category": "Kryddor", "products": ["Salt", "Kryddpulver"]}, {"category": "Pulver", "products": ["Bakpulver", "Proteinpulver"]}]',
'{"Naturligt mineral", "Bidrar till magnesiumintaget"}',
'{"Kalciumkarbonat", "Kiseldioxid"}',
'Positiv påverkan - källa till magnesium',
'Säker för barn, bidrar till mineralintaget',
'E504 Magnesiumkarbonat - Mineraliskt antiklumpmedel',
'Information om E504 Magnesiumkarbonat, dess användning som antiklumpmedel och hälsofördelar.'),

('E507', 'Saltsyra', 'Klorväte', 'e507-saltsyra', 'Surhetsreglerare', 'Syntetisk', 2, NULL, 'Livsmedelsverket', 
'Stark syra för pH-reglering',
'Saltsyra används som surhetsreglerande medel i vissa livsmedelstillämpningar. Det är en stark oorganisk syra som används i begränsade mängder.',
'[{"effect": "Stark syra", "severity": "medium", "description": "Kan vara irriterande i höga koncentrationer"}]',
'[{"category": "Processat", "products": ["Vissa konserver", "Industriella tillämpningar"]}]',
'{"Används i mycket små mängder", "Professionell hantering krävs"}',
'{"Citronsyra", "Ättika", "Mjölksyra"}',
'Neutral påverkan vid normal användning',
'Används i mycket begränsade mängder',
'E507 Saltsyra - Stark syra för pH-reglering',
'Läs om E507 Saltsyra, dess industriella användning och säkerhetsaspekter.'),

('E508', 'Kaliumklorid', 'Kaliumsalt', 'e508-kaliumklorid', 'Smakförstärkare', 'Mineral', 1, NULL, 'Livsmedelsverket', 
'Kaliumsalt som saltsubstitut',
'Kaliumklorid används som saltsubstitut och smakförstärkare. Det ger en saltliknande smak men med mindre natrium.',
'[{"effect": "Fördelaktigt", "severity": "low", "description": "Bidrar till kaliumintaget, minskar natriumintaget"}]',
'[{"category": "Saltsubstitut", "products": ["Dietsalt", "Kryddmixer"]}, {"category": "Hälsoprodukter", "products": ["Lågsaltprodukter"]}]',
'{"Bra alternativ till vanligt salt", "Bidrar till kaliumintaget"}',
'{"Havssalt", "Kryddsalt"}',
'Positiv påverkan - minskar natrium, ökar kalium',
'Fördelaktigt för barn med normal njurfunktion',
'E508 Kaliumklorid - Hälsosamt saltsubstitut',
'Information om E508 Kaliumklorid som saltsubstitut och dess hälsofördelar.'),

('E509', 'Kalciumklorid', 'Kalksalt', 'e509-kalciumklorid', 'Mineraliska salter', 'Mineral', 1, NULL, 'Livsmedelsverket', 
'Kalciumsalt för hårdhet och konservering',
'Kalciumklorid används för att bibehålla hårdhet i konserverade grönsaker och som kalciumkälla. Det hjälper till att bevara struktur.',
'[{"effect": "Fördelaktigt", "severity": "low", "description": "Bidrar till kalciumintaget, bibehåller livsmedelskvalitet"}]',
'[{"category": "Konserver", "products": ["Inlagda grönsaker", "Konserverade frukter"]}, {"category": "Mejeri", "products": ["Ost", "Tofuproduktion"]}]',
'{"Naturligt mineral", "Bidrar till kalciumintaget"}',
'{"Kalciumlaktat", "Kalciumcitrat"}',
'Positiv påverkan - källa till kalcium',
'Fördelaktigt för barn, stödjer benutveckling',
'E509 Kalciumklorid - Kalciumrikt mineraliskt salt',
'Läs om E509 Kalciumklorid, dess användning i konserver och som kalciumkälla.'),

('E511', 'Magnesiumklorid', 'Magnesiumsalt', 'e511-magnesiumklorid', 'Mineraliska salter', 'Mineral', 1, NULL, 'Livsmedelsverket', 
'Magnesiumsalt för koagulering',
'Magnesiumklorid används vid tofutillverkning som koaguleringsmedel och som magnesiumkälla i olika livsmedel.',
'[{"effect": "Fördelaktigt", "severity": "low", "description": "Bidrar till magnesiumintaget"}]',
'[{"category": "Tofuprodukter", "products": ["Tofu", "Sojaprodukter"]}, {"category": "Asiatisk mat", "products": ["Koagulerade produkter"]}]',
'{"Naturligt mineral", "Viktig för muskel- och nervfunktion"}',
'{"Kalciumsulfat", "Nigari"}',
'Positiv påverkan - essentiellt mineral',
'Fördelaktigt för barn, stödjer tillväxt',
'E511 Magnesiumklorid - Magnesiumrikt koaguleringsmedel',
'Information om E511 Magnesiumklorid, dess användning i tofuproduktion och hälsofördelar.'),

('E520', 'Aluminiumsulfat', 'Alun', 'e520-aluminiumsulfat', 'Stabiliseringsmedel', 'Mineral', 3, NULL, 'Livsmedelsverket', 
'Aluminiumföreningar som stabiliserare',
'Aluminiumsulfat används som stabiliseringsmedel i vissa tillämpningar. Aluminiumföreningar kan ackumuleras i kroppen.',
'[{"effect": "Potentiell risk", "severity": "medium", "description": "Aluminiumackumulering kan vara problematisk över tid"}]',
'[{"category": "Processat", "products": ["Vissa bakprodukter", "Industriella tillämpningar"]}]',
'{"Begränsa exponering", "Välj aluminiumfria alternativ"}',
'{"Vinsyra", "Citronsyra"}',
'Negativ påverkan - minimera exponering',
'Undvik för barn när möjligt',
'E520 Aluminiumsulfat - Aluminiumföreningar att undvika',
'Läs om E520 Aluminiumsulfat, potentiella hälsorisker och säkrare alternativ.'),

('E521', 'Aluminiumnatriumsulfat', 'Natriumalun', 'e521-aluminiumnatriumsulfat', 'Stabiliseringsmedel', 'Syntetisk', 3, NULL, 'Livsmedelsverket', 
'Aluminiumföreningar som stabiliserare',
'Aluminiumnatriumsulfat används som stabiliserare men kan bidra till aluminiumexponering som bör minimeras.',
'[{"effect": "Potentiell risk", "severity": "medium", "description": "Aluminiumexponering bör begränsas"}]',
'[{"category": "Bakprodukter", "products": ["Vissa bakpulver", "Processat bröd"]}]',
'{"Undvik aluminiumhaltiga produkter", "Läs ingredienslistor"}',
'{"Bakpulver utan aluminium", "Naturliga jäsmedel"}',
'Negativ påverkan - begränsa exponering',
'Undvik för barn',
'E521 Aluminiumnatriumsulfat - Aluminiumföreningar att undvika',
'Information om E521 och varför aluminiumföreningar bör undvikas för bättre hälsa.'),

('E530', 'Magnesiumoxid', 'Magnesia', 'e530-magnesiumoxid', 'Antiklumpmedel', 'Mineral', 1, NULL, 'Livsmedelsverket', 
'Magnesiumföreningar som antiklumpmedel',
'Magnesiumoxid används som antiklumpmedel och är en källa till magnesium, ett essentiellt mineral för kroppen.',
'[{"effect": "Fördelaktigt", "severity": "low", "description": "Bidrar till magnesiumintaget"}]',
'[{"category": "Pulver", "products": ["Kryddor", "Proteinpulver"]}, {"category": "Kosttillskott", "products": ["Mineraltillskott"]}]',
'{"Naturligt mineral", "Stödjer muskel- och nervfunktion"}',
'{"Magnesiumkarbonat", "Magnesiumcitrat"}',
'Positiv påverkan - essentiellt mineral',
'Fördelaktigt för barn',
'E530 Magnesiumoxid - Magnesiumrikt antiklumpmedel',
'Läs om E530 Magnesiumoxid, dess användning som antiklumpmedel och magnesiumkälla.'),

('E540', 'Dikalciumdifosfit', 'Kalciumfosfit', 'e540-dikalciumdifosfit', 'Emulgeringsmedel', 'Syntetisk', 2, NULL, 'Livsmedelsverket', 
'Kalcium- och fosfatföreningar',
'Dikalciumdifosfit används som emulgeringsmedel och stabiliserare i vissa livsmedel. Bidrar till kalcium- och fosfatintaget.',
'[{"effect": "Måttlig säkerhet", "severity": "low", "description": "Generellt säker men överdrivet fosfatintag kan vara problematiskt"}]',
'[{"category": "Processat", "products": ["Emulgerade produkter", "Stabiliserade livsmedel"]}]',
'{"Måttlig konsumtion", "Balansera fosfatintaget"}',
'{"Lecithin", "Naturliga emulgerare"}',
'Neutral påverkan vid måttlig konsumtion',
'Måttlig användning för barn',
'E540 Dikalciumdifosfit - Kalcium- och fosfatföreningar',
'Information om E540 Dikalciumdifosfit som emulgeringsmedel och dess säkerhetsaspekter.'),

('E550', 'Natriumsilikat', 'Vattenglas', 'e550-natriumsilikat', 'Antiklumpmedel', 'Mineral', 2, NULL, 'Livsmedelsverket', 
'Silikatföreningar som antiklumpmedel',
'Natriumsilikat används som antiklumpmedel för att förhindra klumpbildning i pulverformiga livsmedel.',
'[{"effect": "Generellt säker", "severity": "low", "description": "Används i begränsade mängder"}]',
'[{"category": "Pulver", "products": ["Kryddpulver", "Torrvaror"]}]',
'{"Används sparsamt", "Naturligt förekommande mineral"}',
'{"Kiseldioxid", "Magnesiumkarbonat"}',
'Neutral påverkan på livslängd',
'Säker för barn i små mängder',
'E550 Natriumsilikat - Mineraliskt antiklumpmedel',
'Läs om E550 Natriumsilikat, dess användning som antiklumpmedel och säkerhet.'),

('E551', 'Kiseldioxid', 'Kiselgel', 'e551-kiseldioxid', 'Antiklumpmedel', 'Mineral', 1, NULL, 'Livsmedelsverket', 
'Naturlig kiselföreningar som antiklumpmedel',
'Kiseldioxid är ett mycket vanligt antiklumpmedel som förhindrar klumpbildning. Det är naturligt förekommande och generellt mycket säkert.',
'[{"effect": "Mycket säker", "severity": "low", "description": "Passerar genom kroppen utan absorption"}]',
'[{"category": "Kryddor", "products": ["Salt", "Kryddpulver", "Bakpulver"]}, {"category": "Kosttillskott", "products": ["Tabletter", "Pulver"]}]',
'{"Naturligt mineral", "Passerar genom kroppen oförändrat"}',
'{"Magnesiumkarbonat", "Kalciumkarbonat"}',
'Neutral påverkan på livslängd',
'Mycket säker för barn',
'E551 Kiseldioxid - Naturligt och säkert antiklumpmedel',
'Information om E551 Kiseldioxid, det vanligaste antiklumpmedlet och dess säkerhet.'),

('E552', 'Kalciumsilikat', 'Kalkkisel', 'e552-kalciumsilikat', 'Antiklumpmedel', 'Mineral', 1, NULL, 'Livsmedelsverket', 
'Kalcium- och kiselföreningar som antiklumpmedel',
'Kalciumsilikat används som antiklumpmedel och bidrar både med kalcium och kisel, båda naturliga mineraler.',
'[{"effect": "Säker och fördelaktig", "severity": "low", "description": "Bidrar till mineralintaget"}]',
'[{"category": "Kryddor", "products": ["Kryddmixer", "Salt"]}, {"category": "Pulver", "products": ["Proteinpulver"]}]',
'{"Naturliga mineraler", "Bidrar till kalciumintaget"}',
'{"Kiseldioxid", "Magnesiumkarbonat"}',
'Neutral till positiv påverkan',
'Säker och fördelaktig för barn',
'E552 Kalciumsilikat - Mineralrikt antiklumpmedel',
'Läs om E552 Kalciumsilikat som antiklumpmedel och dess bidrag till mineralintaget.'),

('E553a', 'Magnesiumsilikat', 'Talk', 'e553a-magnesiumsilikat', 'Antiklumpmedel', 'Mineral', 2, NULL, 'Livsmedelsverket', 
'Magnesium- och kiselföreningar',
'Magnesiumsilikat (talk) används som antiklumpmedel. Livsmedelstalk ska vara asbesterifri och av livsmedelskvalitet.',
'[{"effect": "Generellt säker", "severity": "low", "description": "Livsmedelstalk är asbesterifri"}]',
'[{"category": "Processat", "products": ["Vissa pulver", "Tabletter"]}]',
'{"Säkerställ livsmedelskvalitet", "Undvik industriell talk"}',
'{"Kiseldioxid", "Magnesiumkarbonat"}',
'Neutral påverkan vid korrekt kvalitet',
'Säker för barn vid livsmedelskvalitet',
'E553a Magnesiumsilikat - Talk av livsmedelskvalitet',
'Information om E553a Magnesiumsilikat (talk) och vikten av livsmedelskvalitet.'),

('E553b', 'Talkumpulver', 'Talk', 'e553b-talkumpulver', 'Antiklumpmedel', 'Mineral', 2, NULL, 'Livsmedelsverket', 
'Talkumpulver som antiklumpmedel',
'Talkumpulver av livsmedelskvalitet används som antiklumpmedel och släppmedel vid livsmedelstillverkning.',
'[{"effect": "Generellt säker", "severity": "low", "description": "Måste vara asbesterifritt och av livsmedelskvalitet"}]',
'[{"category": "Processat", "products": ["Tabletter", "Vissa livsmedel"]}]',
'{"Kontrollera kvalitetscertifiering", "Livsmedelsgodkänt talk endast"}',
'{"Kiseldioxid", "Stärkelse"}',
'Neutral påverkan vid korrekt kvalitet',
'Säker för barn vid livsmedelskvalitet',
'E553b Talkumpulver - Kvalitetskontrollerat antiklumpmedel',
'Läs om E553b Talkumpulver och vikten av livsmedelsgodkänd kvalitet.'),

('E554', 'Natriumalumosilikat', 'Aluminiumsilikat', 'e554-natriumalumosilikat', 'Antiklumpmedel', 'Mineral', 3, NULL, 'Livsmedelsverket', 
'Aluminium- och silikatföreningar',
'Natriumalumosilikat innehåller aluminium vilket kan ackumuleras i kroppen och bör därför begränsas.',
'[{"effect": "Potentiell risk", "severity": "medium", "description": "Innehåller aluminium som kan ackumuleras"}]',
'[{"category": "Processat", "products": ["Vissa kryddor", "Antiklumpmedel"]}]',
'{"Undvik aluminiumhaltiga tillsatser", "Välj aluminiumfria alternativ"}',
'{"Kiseldioxid", "Magnesiumkarbonat"}',
'Negativ påverkan - begränsa exponering',
'Undvik för barn',
'E554 Natriumalumosilikat - Aluminiumhaltigt att undvika',
'Information om E554 och varför aluminiumhaltiga tillsatser bör undvikas.'),

('E555', 'Kaliumalumosilikat', 'Kaliumaluminium', 'e555-kaliumalumosilikat', 'Antiklumpmedel', 'Mineral', 3, NULL, 'Livsmedelsverket', 
'Kalium-aluminium-silikatföreningar',
'Kaliumalumosilikat innehåller aluminium som kan vara problematiskt vid långvarig exponering.',
'[{"effect": "Potentiell risk", "severity": "medium", "description": "Aluminiuminnehåll bör begränsas"}]',
'[{"category": "Processat", "products": ["Antiklumpmedel", "Vissa kryddor"]}]',
'{"Minimera aluminiumexponering", "Läs ingredienslistor noggrant"}',
'{"Aluminiumfria alternativ", "Naturliga antiklumpmedel"}',
'Negativ påverkan - minimera användning',
'Undvik för barn',
'E555 Kaliumalumosilikat - Aluminiumhaltigt att begränsa',
'Läs om E555 och vikten av att begränsa aluminiumexponering.'),

('E556', 'Kalciumalumosilikat', 'Kalciumaluminium', 'e556-kalciumalumosilikat', 'Antiklumpmedel', 'Mineral', 3, NULL, 'Livsmedelsverket', 
'Kalcium-aluminium-silikatföreningar',
'Kalciumalumosilikat bidrar med kalcium men innehåller också aluminium som bör begränsas.',
'[{"effect": "Blandad effekt", "severity": "medium", "description": "Kalcium är fördelaktigt men aluminium problematiskt"}]',
'[{"category": "Processat", "products": ["Antiklumpmedel"]}]',
'{"Välj aluminiumfria kalciumkällor", "Begränsa exponering"}',
'{"Kalciumkarbonat", "Kalciumcitrat"}',
'Blandad påverkan - undvik om möjligt',
'Begränsad användning för barn',
'E556 Kalciumalumosilikat - Blandade hälsoeffekter',
'Information om E556 och varför aluminiumfria kalciumkällor är att föredra.');