-- Add 31 more foods to reach total of 50 in Livsmedel A-Ö database

-- Insert additional Mejeri & Ostar (8 foods)
INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

('Parmigiano Reggiano', 'parmigiano-reggiano', 'P', 
(SELECT id FROM public.food_categories WHERE slug = 'mejeri'), 
'Hårdost', 
'Kylskåp 4-8°C, helst i ostpapper', 
'4-6 veckor', 
'6-8 månader', 
true, 
'Riv osten innan frysning för bästa resultat', 
ARRAY[]::text[],
ARRAY['mjölk'], 
431, 38.5, 29.0, 0.0, 0.0, 1.60,
'{"A": "300μg", "B12": "2.0μg", "D": "0.5μg"}'::jsonb,
'{"calcium": "1184mg", "fosfor": "680mg"}'::jsonb,
'Italiensk hårdost med rik, nötig smak och granulär textur.',
ARRAY['Riv över pasta', 'Tugga som snacks', 'Använd i risotto', 'Toppa sallader'],
'[{"name": "Grana Padano", "reason": "Liknande smak men mildare"}, {"name": "Pecorino Romano", "reason": "Saltare men liknande textur"}]'::jsonb,
'Parmigiano Reggiano - Näringsvärde och Användning | Livsmedel A-Ö',
'Komplett guide om Parmigiano Reggiano: näringsvärde, förvaring, användning och italienska osttraditionen. Tips för bästa smak.',
'[{"question": "Hur länge håller Parmigiano Reggiano?", "answer": "Hela bitar håller 6-8 månader oöppnade, 4-6 veckor efter öppning i kylskåp."}, {"question": "Kan man frysa Parmigiano Reggiano?", "answer": "Ja, men riv osten först för bästa resultat efter upptining."}]'::jsonb,
ARRAY['Pasta Carbonara', 'Caesar Sallad', 'Italiensk middag']),

('Mozzarella', 'mozzarella', 'M',
(SELECT id FROM public.food_categories WHERE slug = 'mejeri'),
'Färskost',
'Kylskåp 4-8°C i egen vätska',
'3-5 dagar',
'1-2 veckor',
false,
'Rekommenderas ej att frysa',
ARRAY[]::text[],
ARRAY['mjölk'],
280, 18.1, 22.4, 2.2, 0.0, 0.60,
'{"A": "179μg", "B12": "2.3μg"}'::jsonb,
'{"calcium": "505mg", "fosfor": "354mg"}'::jsonb,
'Italiensk färskost med mild smak och krämig konsistens.',
ARRAY['Pizza topping', 'Caprese sallad', 'Gratäng', 'Smörgås'],
'[{"name": "Burrata", "reason": "Krämigare variant av mozzarella"}, {"name": "Ricotta", "reason": "Mildare smak för bakning"}]'::jsonb,
'Mozzarella - Näringsvärde och Tillagning | Livsmedel A-Ö',
'Allt om mozzarella: näringsvärde, förvaring, tillagning och italienska recept. Guide för bästa kvalitet och användning.',
'[{"question": "Hur förvaras mozzarella bäst?", "answer": "I kylskåp i sin egen vätska eller saltlake för att behålla fuktigheten."}, {"question": "Varför blir mozzarella gummiaktig?", "answer": "Överuppvärmning gör att proteiner drar ihop sig - använd låg värme."}]'::jsonb,
ARRAY['Pizza Margherita', 'Italiensk sallad', 'Lasagne']),

('Yoghurt Naturell', 'yoghurt-naturell', 'Y',
(SELECT id FROM public.food_categories WHERE slug = 'mejeri'),
'Fermenterad mjölkprodukt',
'Kylskåp 4-8°C',
'1 vecka efter öppning',
'2-3 veckor oöppnad',
true,
'Textur förändras efter frysning',
ARRAY[]::text[],
ARRAY['mjölk'],
59, 10.0, 0.4, 3.6, 0.0, 0.05,
'{"B2": "0.27mg", "B12": "0.75μg", "D": "0.1μg"}'::jsonb,
'{"calcium": "110mg", "fosfor": "135mg"}'::jsonb,
'Naturell yoghurt utan tillsatser, rik på probiotika.',
ARRAY['Frukost med müsli', 'Smoothies', 'Sås bas', 'Marinad'],
'[{"name": "Filmjölk", "reason": "Liknande probiotika"}, {"name": "Skyr", "reason": "Högre protinhalt"}]'::jsonb,
'Yoghurt Naturell - Näringsvärde och Hälsofördelar | Livsmedel A-Ö',
'Komplett guide om naturell yoghurt: näringsvärde, probiotika, användning och hälsofördelar.',
'[{"question": "Vilka probiotika finns i yoghurt?", "answer": "Lactobacillus bulgaricus och Streptococcus thermophilus är de vanligaste kulturerna."}, {"question": "Kan man laga mat med yoghurt?", "answer": "Ja, men undvik hög värme som kan få den att separera."}]'::jsonb,
ARRAY['Hälsosam frukost', 'Smoothie bowl', 'Indisk mat']),

('Fetaost', 'fetaost', 'F',
(SELECT id FROM public.food_categories WHERE slug = 'mejeri'),
'Saltost',
'Kylskåp 4-8°C i saltlake',
'1 vecka',
'2-3 månader',
true,
'Kan frysas men textur förändras',
ARRAY[]::text[],
ARRAY['mjölk'],
264, 14.2, 21.3, 4.1, 0.0, 4.00,
'{"A": "125μg", "B12": "1.7μg"}'::jsonb,
'{"calcium": "493mg", "fosfor": "337mg"}'::jsonb,
'Grekisk saltost med distinkt smak och krumblig textur.',
ARRAY['Grekisk sallad', 'Bakad med örter', 'Paj fyllning', 'Pasta sås'],
'[{"name": "Getost", "reason": "Liknande salthet och textur"}, {"name": "Cottage cheese", "reason": "Mildare alternativ med krumblig textur"}]'::jsonb,
'Fetaost - Näringsvärde och Recept | Livsmedel A-Ö',
'Komplett guide om fetaost: näringsvärde, förvaring, grekiska recept och användning i matlagning.',
'[{"question": "Är fetaost hälsosam?", "answer": "Ja, rik på protein och kalcium men hög salthalt - ät i måttliga mängder."}, {"question": "Kan man äta fetaost som är rumstempererad?", "answer": "Ja, många föredrar den vid rumstemperatur för bästa smak."}]'::jsonb,
ARRAY['Grekisk sallad', 'Medelhavsmat', 'Vegetarisk middag']);

-- Insert Kött & Fågel (7 foods)
INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

('Nötfärs', 'notfars', 'N',
(SELECT id FROM public.food_categories WHERE slug = 'kott'),
'Malet kött',
'Kylskåp 0-4°C',
'1-2 dagar',
'1-2 dagar',
true,
'Frys inom 2 dagar, håller 3-4 månader fryst',
ARRAY[]::text[],
ARRAY[]::text[],
254, 26.1, 15.0, 0.0, 0.0, 0.07,
'{"B12": "2.6μg", "B6": "0.4mg", "Niacin": "4.2mg"}'::jsonb,
'{"järn": "2.6mg", "zink": "4.5mg", "selen": "14.2μg"}'::jsonb,
'Malet nötkött, perfekt för köttfärssås och köttbullar.',
ARRAY['Köttfärssås', 'Köttbullar', 'Tacos', 'Lasagne'],
'[{"name": "Fläskfärs", "reason": "Fetare och saftigare"}, {"name": "Blandfärs", "reason": "Kombination av nöt och fläsk"}]'::jsonb,
'Nötfärs - Näringsvärde och Tillagning | Livsmedel A-Ö',
'Komplett guide om nötfärs: näringsvärde, säkerhetstips, tillagning och klassiska recept.',
'[{"question": "Hur länge håller nötfärs i kylskåpet?", "answer": "Max 1-2 dagar i kylskåp, använd eller frys omgående efter köp."}, {"question": "Vilken temperatur ska nötfärs ha när den är klar?", "answer": "Minst 70°C i centrum för att döda eventuella bakterier."}]'::jsonb,
ARRAY['Köttfärssås', 'Tacos', 'Lasagne']),

('Bacon', 'bacon', 'B',
(SELECT id FROM public.food_categories WHERE slug = 'kott'),
'Rökt fläsk',
'Kylskåp 0-4°C',
'1 vecka efter öppning',
'2-3 veckor oöppnad',
true,
'Portionera innan frysning',
ARRAY[]::text[],
ARRAY[]::text[],
541, 37.0, 42.0, 1.4, 0.0, 2.30,
'{"B1": "0.4mg", "B12": "0.7μg", "Niacin": "11.6mg"}'::jsonb,
'{"fosfor": "280mg", "selen": "28.5μg"}'::jsonb,
'Rökt och saltat fläsksida med intensiv smak.',
ARRAY['Frukost', 'Sallad topping', 'Pasta', 'Burgare'],
'[{"name": "Pancetta", "reason": "Italiensk variant utan rök"}, {"name": "Chorizo", "reason": "Kryddigare spansk variant"}]'::jsonb,
'Bacon - Näringsvärde och Tillagning | Livsmedel A-Ö',
'Allt om bacon: näringsvärde, olika typer, tillagning och användning i matlagning.',
'[{"question": "Vilket är det bästa sättet att steka bacon?", "answer": "Starta med kall panna på medelhög värme för jämn tillagning och mindre stänk."}, {"question": "Kan man äta bacon rått?", "answer": "Nej, bacon ska alltid tillagas ordentligt för att vara säkert att äta."}]'::jsonb,
ARRAY['Engelsk frukost', 'Amerikansk mat', 'Brunch']),

('Fläskfilé', 'flaskfile', 'F',
(SELECT id FROM public.food_categories WHERE slug = 'kott'),
'Magert kött',
'Kylskåp 0-4°C',
'3-5 dagar',
'3-5 dagar',
true,
'Marinera innan frysning för bästa smak',
ARRAY[]::text[],
ARRAY[]::text[],
143, 23.0, 5.0, 0.0, 0.0, 0.05,
'{"B1": "0.9mg", "B6": "0.4mg", "B12": "0.7μg"}'::jsonb,
'{"selen": "26.4μg", "fosfor": "230mg", "zink": "2.0mg"}'::jsonb,
'Mager och mör köttbit från fläskryggen.',
ARRAY['Schnitzel', 'Wok', 'Ugnsstekt', 'Grillad'],
'[{"name": "Kycklingfilé", "reason": "Ännu magrare"}, {"name": "Kalvfilé", "reason": "Mörare men dyrare"}]'::jsonb,
'Fläskfilé - Näringsvärde och Tillagning | Livsmedel A-Ö',
'Allt om fläskfilé: näringsvärde, tillagningsmetoder, marinader och tips för perfekt resultat.',
'[{"question": "Hur får man fläskfilé saftig?", "answer": "Stek inte för länge och låt köttet vila efter stekning. Innertemperatur 63°C."}, {"question": "Behöver man marinera fläskfilé?", "answer": "Inte nödvändigt men förbättrar smak och saftighet, speciellt för grillning."}]'::jsonb,
ARRAY['Vardagsmiddag', 'Grillmat', 'Snabb middag']);

-- Insert Fisk & Skaldjur (6 foods)  
INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

('Lax', 'lax', 'L',
(SELECT id FROM public.food_categories WHERE slug = 'fisk-skaldjur'),
'Fet fisk',
'Kylskåp 0-4°C på is',
'1-2 dagar',
'1-2 dagar',
true,
'Vakuumförpacka innan frysning',
ARRAY['maj', 'juni', 'juli', 'augusti', 'september'],
ARRAY['fisk'],
208, 25.4, 13.0, 0.0, 0.0, 0.05,
'{"D": "11μg", "B12": "4.9μg", "Niacin": "8.5mg"}'::jsonb,
'{"selen": "41.4μg", "fosfor": "371mg", "kalium": "628mg"}'::jsonb,
'Näringsrik fet fisk med högt innehåll av omega-3.',
ARRAY['Grillad', 'Rimmad', 'Sushi', 'Ugnsbakad'],
'[{"name": "Regnbågslax", "reason": "Liknande smak och textur"}, {"name": "Makrill", "reason": "Hög omega-3 halt"}]'::jsonb,
'Lax - Näringsvärde och Omega-3 | Livsmedel A-Ö',
'Komplett guide om lax: näringsvärde, omega-3 fördelar, tillagning och skillnad mellan odlad och vild lax.',
'[{"question": "Vilka fördelar har omega-3?", "answer": "Omega-3 är viktigt för hjärtat, hjärnan och kan minska inflammation i kroppen."}, {"question": "Skillnad mellan odlad och vild lax?", "answer": "Vild lax har fastare kött och mer intensiv smak, odlad lax är fetare och tillgänglig året runt."}]'::jsonb,
ARRAY['Hälsosam middag', 'Omega-3 källa', 'Nordisk mat']),

('Räkor', 'rakor', 'R',
(SELECT id FROM public.food_categories WHERE slug = 'fisk-skaldjur'),
'Skaldjur',
'Kylskåp 0-4°C',
'2-3 dagar kokta',
'2-3 dagar',
true,
'Frys kokta räkor upp till 3 månader',
ARRAY['maj', 'juni', 'juli', 'augusti', 'september'],
ARRAY['skaldjur'],
99, 20.3, 1.4, 0.0, 0.0, 0.25,
'{"B12": "1.3μg", "D": "0.2μg", "E": "1.1mg"}'::jsonb,
'{"selen": "38μg", "zink": "1.6mg", "jod": "35μg"}'::jsonb,
'Populära skaldjur med söt smak och fast textur.',
ARRAY['Räksmörgås', 'Räksallad', 'Pasta', 'Sushi'],
'[{"name": "Kräftor", "reason": "Liknande skaldjur"}, {"name": "Havskräfta", "reason": "Större med mer kött"}]'::jsonb,
'Räkor - Näringsvärde och Svensk Tradition | Livsmedel A-Ö',
'Komplett guide om räkor: näringsvärde, svensk räktradition, tillagning och hållbarhetsaspekter.',
'[{"question": "Hur kokar man räkor?", "answer": "Saltvatten (30g salt per liter), koka 2-3 minuter för färska räkor tills de blir rosa."}, {"question": "Kan man äta räkor som gravid?", "answer": "Ja, kokta räkor är säkra, undvik dock råa räkor som i vissa sushirätter."}]'::jsonb,
ARRAY['Räksmörgås', 'Midsommar', 'Kräftskiva']),

('Torsk', 'torsk', 'T',
(SELECT id FROM public.food_categories WHERE slug = 'fisk-skaldjur'),
'Mager fisk',
'Kylskåp 0-4°C på is',
'1-2 dagar',
'1-2 dagar',
true,
'Frys inom 24 timmar efter köp',
ARRAY['oktober', 'november', 'december', 'januari', 'februari'],
ARRAY['fisk'],
105, 23.0, 0.9, 0.0, 0.0, 0.18,
'{"B12": "1.0μg", "B6": "0.2mg", "Niacin": "2.3mg"}'::jsonb,
'{"selen": "33.1μg", "fosfor": "203mg", "jod": "110μg"}'::jsonb,
'Mager vitfisk med mild smak och fast kött.',
ARRAY['Fish and chips', 'Kokt med äggstuvning', 'Fisksoppa', 'Panerad'],
'[{"name": "Kolja", "reason": "Liknande mild smak"}, {"name": "Vitling", "reason": "Mer prisvärt alternativ"}]'::jsonb,
'Torsk - Näringsvärde och Nordisk Tradition | Livsmedel A-Ö',
'Allt om torsk: näringsvärde, nordiska fisktraditionen, tillagning och hållbarhet.',
'[{"question": "Varför är torsk så populär?", "answer": "Mild smak som passar de flesta, mager och proteinrik, samt traditionell i nordisk matkultur."}, {"question": "Hur vet man att torsk är färsk?", "answer": "Klara ögon, röda gälar, fast kött som studsar tillbaka när man trycker på det."}]'::jsonb,
ARRAY['Svensk husmanskost', 'Fish and chips', 'Nordisk mat']);

-- Insert Grönsaker (7 foods)
INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

('Paprika Röd', 'paprika-rod', 'P',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Fruktgrönsak',
'Kylskåp 7-10°C',
'1 vecka',
'1-2 veckor',
true,
'Skär i remsor innan frysning',
ARRAY['juli', 'augusti', 'september'],
ARRAY[]::text[],
31, 1.0, 0.3, 6.0, 2.5, 0.01,
'{"C": "128mg", "A": "157μg", "B6": "0.3mg"}'::jsonb,
'{"kalium": "211mg", "folat": "46μg"}'::jsonb,
'Söt och färgstark grönsak med mycket vitamin C.',
ARRAY['Wok', 'Sallader', 'Grillad', 'Fyllning'],
'[{"name": "Gul paprika", "reason": "Liknande sötma"}, {"name": "Chilipaprika", "reason": "Hetare variant"}]'::jsonb,
'Paprika Röd - Vitamin C Källa | Livsmedel A-Ö',
'Komplett guide om röd paprika: näringsvärde, vitamin C fördelar, tillagning och odling.',
'[{"question": "Varför är röd paprika sötare?", "answer": "Röd paprika är fullt mogen och har utvecklat mer socker än grön paprika."}, {"question": "Kan man äta paprikakärnor?", "answer": "Ja, de är ätbara men kan vara lite beska."}]'::jsonb,
ARRAY['Wok mat', 'Medelhavsmat', 'Vitamin C']),

('Broccoli', 'broccoli', 'B',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Kålväxt',
'Kylskåp 0-4°C',
'3-5 dagar',
'1 vecka',
true,
'Blanchera innan frysning',
ARRAY['juni', 'juli', 'augusti', 'september'],
ARRAY[]::text[],
34, 2.8, 0.4, 7.0, 2.6, 0.03,
'{"C": "89mg", "K": "102μg", "Folat": "63μg"}'::jsonb,
'{"kalium": "316mg", "järn": "0.7mg", "kalcium": "47mg"}'::jsonb,
'Näringsrik kålväxt med högt innehåll av vitamin C och K.',
ARRAY['Ångkokt', 'Wok', 'Gratäng', 'Soppa'],
'[{"name": "Blomkål", "reason": "Liknande textur"}, {"name": "Romanesco", "reason": "Nötighare smak"}]'::jsonb,
'Broccoli - Supervärden och Tillagning | Livsmedel A-Ö',
'Komplett guide om broccoli: näringsvärde, hälsofördelar, tillagning för bästa smak och näring.',
'[{"question": "Hur kokar man broccoli utan att förlora näring?", "answer": "Ångkoka i 3-4 minuter eller koka i lite vatten kort tid för att bevara vitaminer."}, {"question": "Kan man äta broccoli rå?", "answer": "Ja, rå broccoli i sallader ger mest näring och en krispig textur."}]'::jsonb,
ARRAY['Hälsosam mat', 'Vitamin C källa', 'Antioxidanter']),

('Avokado', 'avokado', 'A',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Fruktgrönsak',
'Rumstemperatur tills mogen',
'2-3 dagar mogen',
'3-7 dagar',
true,
'Mosa innan frysning',
ARRAY[]::text[],
ARRAY[]::text[],
160, 2.0, 14.7, 8.5, 6.7, 0.01,
'{"K": "21μg", "Folat": "20μg", "E": "2.1mg"}'::jsonb,
'{"kalium": "485mg", "magnesium": "29mg", "fiber": "6.7g"}'::jsonb,
'Näringsrik frukt med hälsosamma enfettade fetter.',
ARRAY['Guacamole', 'Sallad', 'Smoothies', 'Toast'],
'[{"name": "Olivolja", "reason": "Liknande hälsosamma fetter"}, {"name": "Nötter", "reason": "Andra källor till bra fetter"}]'::jsonb,
'Avokado - Hälsosamma Fetter och Näring | Livsmedel A-Ö',
'Komplett guide om avokado: näringsvärde, hälsosamma fetter, mognad och användning.',
'[{"question": "Hur vet man att avokado är mogen?", "answer": "Ska ge lätt efter tryck men inte vara för mjuk, färg spelar mindre roll."}, {"question": "Varför blir avokado brun?", "answer": "Oxidation när frukten exponeras för luft - citronjuice förhindrar brunfärgning."}]'::jsonb,
ARRAY['Hälsosamma fetter', 'Vegetarisk kost', 'Trendig mat']);

-- Insert Kryddor & Örter (4 foods)
INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

('Oregano', 'oregano', 'O',
(SELECT id FROM public.food_categories WHERE slug = 'kryddor-orter'),
'Torkad ört',
'Torrt och mörkt',
'2 år',
'2-3 år',
false,
'Redan torkad',
ARRAY['juli', 'augusti'],
ARRAY[]::text[],
265, 9.0, 4.3, 69.0, 42.5, 0.03,
'{"K": "622μg", "E": "18.3mg", "A": "85μg"}'::jsonb,
'{"kalium": "1260mg", "kalcium": "159mg", "järn": "36.8mg"}'::jsonb,
'Klassisk medelhavsört med starkt, varmt arom.',
ARRAY['Pizza', 'Pasta såser', 'Grekisk mat', 'Marinader'],
'[{"name": "Mejram", "reason": "Liknande medelhavsört"}, {"name": "Timjan", "reason": "Annan stark ört"}]'::jsonb,
'Oregano - Medelhavsört och Pizza | Livsmedel A-Ö',
'Allt om oregano: användning i medelhavsmat, pizza, skillnad mellan färsk och torkad oregano.',
'[{"question": "Skillnad mellan oregano och mejram?", "answer": "Oregano är starkare och mer bitter, mejram är mildare och sötare."}, {"question": "När tillsätter man oregano?", "answer": "Torkad oregano tål värme - tillsätt tidigt. Färsk oregano i slutet av tillagningen."}]'::jsonb,
ARRAY['Pizza', 'Italiensk mat', 'Grekisk mat']),

('Vitlök', 'vitlok', 'V',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Lökväxt',
'Mörkt, torrt och svalt',
'3-6 månader',
'6 månader',
true,
'Hacka innan frysning',
ARRAY['juli', 'augusti'],
ARRAY[]::text[],
149, 6.4, 0.5, 33.1, 2.1, 0.02,
'{"C": "31mg", "B6": "1.2mg", "Mangan": "1.7mg"}'::jsonb,
'{"fosfor": "153mg", "kalium": "401mg", "selen": "14μg"}'::jsonb,
'Kraftfull aromgrönsak med antibakteriella egenskaper.',
ARRAY['Marinader', 'Såser', 'Stekt', 'Rå i dressing'],
'[{"name": "Schalottenlök", "reason": "Mildare aromgrönsak"}, {"name": "Ingefära", "reason": "Annan stark smaksättare"}]'::jsonb,
'Vitlök - Hälsofördelar och Användning | Livsmedel A-Ö',
'Komplett guide om vitlök: näringsvärde, hälsofördelar, förvaring och kulinarisk användning.',
'[{"question": "Vilka hälsofördelar har vitlök?", "answer": "Allicin i vitlök kan ha antibakteriella och hjärt-kärlskyddande effekter."}, {"question": "Hur får man bort vitlöksandedräkt?", "answer": "Tugga persilja, drick mjölk eller ät äpple efter vitlök."}]'::jsonb,
ARRAY['Medelhavsmat', 'Hälsosam krydda', 'Antibakteriellt']);

-- Set up cross-references between related foods
UPDATE public.foods SET related_foods = 
ARRAY(SELECT id FROM public.foods WHERE slug IN ('mozzarella', 'basilika', 'tomat') AND id IS NOT NULL LIMIT 3)
WHERE slug = 'parmigiano-reggiano';

UPDATE public.foods SET related_foods = 
ARRAY(SELECT id FROM public.foods WHERE slug IN ('parmigiano-reggiano', 'basilika', 'tomat') AND id IS NOT NULL LIMIT 3)
WHERE slug = 'mozzarella';

UPDATE public.foods SET related_foods = 
ARRAY(SELECT id FROM public.foods WHERE slug IN ('spaghetti', 'parmigiano-reggiano', 'basilika') AND id IS NOT NULL LIMIT 3)
WHERE slug = 'tomat';

UPDATE public.foods SET related_foods = 
ARRAY(SELECT id FROM public.foods WHERE slug IN ('tomat', 'mozzarella', 'spaghetti') AND id IS NOT NULL LIMIT 3)
WHERE slug = 'basilika';