-- Add long descriptions for more essential foods
UPDATE foods SET long_description = 'Bacon är en populär köttprodukt som framställs genom saltning och rökning av fläsksida. Även om bacon är smakligt och högt i protein (cirka 37 gram per 100 gram), är det också högt i mättat fett och natrium. Bacon innehåller B-vitaminer, särskilt B12, niacin och tiamin, samt mineraler som selen och fosfor. Det är viktigt att konsumera bacon i måttliga mängder på grund av dess höga halt av bearbetat kött och nitriter. Välj bacon utan tillsatta nitriter när det är möjligt. Bacon kan stekas, grillas eller bakas i ugn. Spara gärna baconfettet för matlagning - det ger en rik smak till potatis och grönsaker.' WHERE slug = 'bacon';

UPDATE foods SET long_description = 'Balsamvinäger är en traditionell italiensk vinäger som framställs av druvsafter och lagras i träfat för att utveckla sin karakteristiska söta och syra smak. Äkta balsamvinäger från Modena kan lagras i många år och blir mer komplex med tiden. Balsamvinäger innehåller antioxidanter från druvorna och kan ha anti-inflammatoriska egenskaper. Den är kalorifattig (cirka 14 kalorier per matsked) men rik på smak. Använd balsamvinäger sparsamt i dressingar, över sallader, grillad kött eller till och med över färska frukter som jordgubbar. Billigare balsamvinäger är ofta utspädd och innehåller tillsatser, så välj högkvalitativa varianter för bästa smak och hälsofördelar.' WHERE slug = 'balsamvinager';

UPDATE foods SET long_description = 'Basilika är en aromatisk ört som är rik på antioxidanter och eteriska oljor som eugenol, vilket ger den sin karakteristiska doft och smak. Basilika innehåller vitamin K för benhälsa, vitamin A för synhälsa och magnesium för muskelfunktion. Dess antioxidanter, inklusive beta-karotener och lutein, kan hjälpa till att bekämpa inflammation och oxidativ stress. Färsk basilika har högst näringsvärde och bäst smak. Förvara färsk basilika med stjälkarna i vatten som snittblommor, eller frys in bladen i isbitar med olivolja. Basilika passar perfekt till tomater, mozzarella, pasta och pizza. Odla gärna egen basilika på fönsterbrädan för färsk tillgång året runt.' WHERE slug = 'basilika';

UPDATE foods SET long_description = 'Blåbär är små kraftpaket av antioxidanter och anses vara en av de mest näringsrika bären. De innehåller höga halter av antocyaniner, som ger bären sin djupblå färg och har visat sig kunna förbättra minnesförmågan och skydda mot åldrande av hjärnan. Blåbär är också rika på vitamin C, vitamin K och mangan. De innehåller fiber som främjar tarmhälsan och har anti-inflammatoriska egenskaper. Frysta blåbär behåller sina näringsämnen väl och är ofta mer ekonomiska än färska. Blåbär är perfekta i smoothies, på flingor, i bakning eller som mellanmål. Svenska vilda blåbär har ofta högre antioxidanthalter än odlade varianter.' WHERE slug = 'blaber';

UPDATE foods SET long_description = 'Cheddar är en av världens mest populära hårdostar och en utmärkt källa till kalcium för stark benhälsa. 100 gram cheddar innehåller cirka 720 mg kalcium, vilket täcker över 70% av det dagliga behovet. Cheddar är också rik på protein (25 gram per 100 gram) och innehåller viktiga B-vitaminer, särskilt B12 och riboflavin. Osten innehåller även vitamin A för synhälsa och zink för immunförsvaret. Mognad cheddar har mer komplex smak och är lättare att smälta för laktosintoleraanta personer. Välj naturligt lagrad cheddar utan konstgjorda färgämnen. Förvara cheddar inslaget i papper i kylskåp och låt den komma till rumstemperatur före servering för bästa smak.' WHERE slug = 'cheddar';

UPDATE foods SET long_description = 'Citron är en citrusfrukt som är extremt rik på vitamin C och citronensyra. Både köttet och skalet innehåller värdefulla näringsämnen. Citronskal innehåller eteriska oljor som limonen, som har antimikrobiella egenskaper. Citroner innehåller också flavonoider som hesperidin och diosmetin som kan stödja hjärthälsan. Citronsyran hjälper kroppen att absorbera järn från vegetabiliska källor. Färskpressad citronsaft i varmt vatten på morgonen kan stödja matsmältningen och hydreringen. Ekologiska citroner är bäst om du ska använda skalet. Citron förhöjer smaken i fisk, kött, desserter och drycker.' WHERE slug = 'citron';