-- Add final 16 foods to reach exactly 50 total

INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

-- Mejeri & Ostar (4 more)
('Cheddar', 'cheddar', 'C',
(SELECT id FROM public.food_categories WHERE slug = 'mejeri'),
'Hårdost',
'Kylskåp 4-8°C i plast eller vax',
'3-4 veckor',
'6 månader',
true,
'Riv innan frysning',
ARRAY[]::text[],
ARRAY['mjölk'],
403, 25.0, 33.3, 1.3, 0.0, 1.80,
'{"A": "330μg", "B12": "0.8μg"}'::jsonb,
'{"calcium": "721mg", "fosfor": "512mg"}'::jsonb,
'Engelsk hårdost med skarp, fyllig smak.',
ARRAY['Macka topping', 'Gratäng', 'Ostbricka', 'Smält till nachos'],
'[{"name": "Gouda", "reason": "Mildare smak"}, {"name": "Emmental", "reason": "Bra för smältning"}]'::jsonb,
'Cheddar - Näringsvärde och Användning | Livsmedel A-Ö',
'Allt om cheddar: näringsvärde, olika styrkor, förvaring och engelska osttraditionen.',
'[{"question": "Vad betyder \"aged cheddar\"?", "answer": "Ju längre lagring, desto skarpare smak - mild (2-3 mån), medium (5-6 mån), sharp (9+ mån)."}, {"question": "Varför blir cheddar orange?", "answer": "Naturlig färgämne annatto tillsätts för den karakteristiska färgen."}]'::jsonb,
ARRAY['Ostsmörgås', 'Engelsk middag', 'Pub mat']),

('Crème Fraiche', 'creme-fraiche', 'C',
(SELECT id FROM public.food_categories WHERE slug = 'mejeri'),
'Gräddfil',
'Kylskåp 4-8°C',
'1 vecka efter öppning',
'2-3 veckor oöppnad',
false,
'Rekommenderas ej att frysa',
ARRAY[]::text[],
ARRAY['mjölk'],
292, 2.1, 30.0, 2.9, 0.0, 0.05,
'{"A": "280μg", "D": "0.6μg"}'::jsonb,
'{"calcium": "95mg", "fosfor": "60mg"}'::jsonb,
'Fransk gräddfil med mild, lätt sur smak.',
ARRAY['Såser', 'Tårtor', 'Soppa', 'Dip'],
'[{"name": "Sour cream", "reason": "Liknande konsistens"}, {"name": "Grekisk yoghurt", "reason": "Hälsosammare alternativ"}]'::jsonb,
'Crème Fraiche - Näringsvärde och Matlagning | Livsmedel A-Ö',
'Allt om crème fraiche: näringsvärde, fransk kulinarisk tradition, användning i såser och desserter.',
'[{"question": "Skillnad mellan crème fraiche och gräddfil?", "answer": "Crème fraiche har högre fetthalt (30%) och tål värme bättre än vanlig gräddfil."}, {"question": "Kan crème fraiche kokas?", "answer": "Ja, den koagulerar inte lika lätt som andra mjölkprodukter vid uppvärmning."}]'::jsonb,
ARRAY['Fransk matlagning', 'Pasta såser', 'Desserter']),

-- Grönsaker (6 more)  
('Spenat', 'spenat', 'S',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Bladgrönsak',
'Kylskåp 0-4°C',
'3-5 dagar',
'1 vecka',
true,
'Blanchera innan frysning',
ARRAY['mars', 'april', 'maj', 'september', 'oktober'],
ARRAY[]::text[],
23, 2.9, 0.4, 3.6, 2.2, 0.08,
'{"K": "483μg", "Folat": "194μg", "A": "469μg"}'::jsonb,
'{"järn": "2.7mg", "magnesium": "79mg", "kalium": "558mg"}'::jsonb,
'Järnrik bladgrönsak med mycket folsyra och vitamin K.',
ARRAY['Sallad', 'Smoothies', 'Stuvad', 'Pasta'],
'[{"name": "Mangold", "reason": "Liknande bladgrönsak"}, {"name": "Rucola", "reason": "Starkare smak"}]'::jsonb,
'Spenat - Järn och Folsyra | Livsmedel A-Ö',
'Allt om spenat: näringsvärde, järninnehåll, tillagning och användning i hälsosam kost.',
'[{"question": "Är spenat verkligen så järnrik?", "answer": "Ja, men järnet från växter absorberas sämre - kombinera med vitamin C för bättre upptag."}, {"question": "Kan man äta mycket spenat?", "answer": "Spenat innehåller oxalater som kan påverka kalciumupptag - variera med andra grönsaker."}]'::jsonb,
ARRAY['Järnkälla', 'Smoothies', 'Hälsosam kost']),

('Zucchini', 'zucchini', 'Z',
(SELECT id FROM public.food_categories WHERE slug = 'gronsaker'),
'Fruktgrönsak',
'Kylskåp 4-8°C',
'1 vecka',
'1-2 veckor',
true,
'Skär i skivor innan frysning',
ARRAY['juni', 'juli', 'augusti', 'september'],
ARRAY[]::text[],
17, 1.2, 0.3, 3.1, 1.0, 0.01,
'{"C": "18mg", "Folat": "24μg", "K": "4.3μg"}'::jsonb,
'{"kalium": "261mg", "mangan": "0.2mg"}'::jsonb,
'Mild fruktgrönsak med lågt kaloriinnehåll, mångsidig.',
ARRAY['Spiraler som pasta', 'Gratäng', 'Bröd', 'Grillad'],
'[{"name": "Gurka", "reason": "Liknande mild smak"}, {"name": "Squash", "reason": "Samma familj"}]'::jsonb,
'Zucchini - Låg Kalori Alternativ | Livsmedel A-Ö',
'Allt om zucchini: näringsvärde, kreativa tillagningssätt, zucchininudlar och bakning.',
'[{"question": "Kan man äta zucchini rå?", "answer": "Ja, perfekt rå i sallader eller som spiraler istället för pasta."}, {"question": "Varför blir zucchini vattnig?", "answer": "Hög vattenhalten - salta och låt rinna av före tillagning för fastare textur."}]'::jsonb,
ARRAY['Låg kolhydrat', 'Pasta alternativ', 'Sommarmat']),

-- Frukt & Bär (2 more)
('Apelsin', 'apelsin', 'A',
(SELECT id FROM public.food_categories WHERE slug = 'frukt-bar'),
'Citrusfrukt',
'Rumstemperatur 1 vecka, kylskåp 2 veckor',
'2 veckor',
'2-3 veckor',
true,
'Skala och dela innan frysning',
ARRAY[]::text[],
ARRAY[]::text[],
47, 0.9, 0.1, 12.0, 2.4, 0.00,
'{"C": "53mg", "Folat": "40μg", "A": "11μg"}'::jsonb,
'{"kalium": "181mg", "kalcium": "40mg", "hesperidin": "högt"}'::jsonb,
'Söt citrusfrukt rik på vitamin C och folsyra.',
ARRAY['Frukost juice', 'Mellanmål', 'Sallad', 'Marmelad'],
'[{"name": "Mandarin", "reason": "Sötare och lättare att skala"}, {"name": "Grapefrukt", "reason": "Större citrusfrukt"}]'::jsonb,
'Apelsin - Vitamin C och Immun | Livsmedel A-Ö',
'Allt om apelsiner: näringsvärde, immunförstärkning, juice vs hel frukt och olika sorter.',
'[{"question": "Är färskpressad juice lika bra som hel frukt?", "answer": "Hel frukt ger mer fiber och mättnad, men båda ger vitamin C."}, {"question": "Vilken sort apelsin är sötast?", "answer": "Navelapelsiner och blodapelsiner är ofta sötare än vanliga apelsiner."}]'::jsonb,
ARRAY['Vitamin C källa', 'Frukostjuice', 'Immunförsvar']),

-- Kött & Fågel (2 more)
('Grillkorv', 'grillkorv', 'G',
(SELECT id FROM public.food_categories WHERE slug = 'kott'),
'Korv',
'Kylskåp 0-4°C',
'1 vecka efter öppning',
'2-3 veckor oöppnad',
true,
'Kan frysas upp till 2 månader',
ARRAY['maj', 'juni', 'juli', 'augusti'],
ARRAY[]::text[],
301, 13.0, 27.0, 2.0, 0.0, 2.30,
'{"B12": "1.0μg", "Niacin": "3.5mg"}'::jsonb,
'{"natrium": "920mg", "fosfor": "150mg"}'::jsonb,
'Kryddig korv perfekt för grillning och korvstroganoff.',
ARRAY['Grilla', 'Korvstroganoff', 'Korv med bröd', 'Falukorv'],
'[{"name": "Bratwurst", "reason": "Tysk variant med örter"}, {"name": "Prinskorv", "reason": "Mindre storlek"}]'::jsonb,
'Grillkorv - Tillagning och Tradition | Livsmedel A-Ö',
'Komplett guide om grillkorv: tillagning, svenska korvtraditionen och klassiska tillbehör.',
'[{"question": "Hur grillar man korv bäst?", "answer": "Medelhög värme, vänd ofta, sticka inte hål - det rinner ut saft och smak."}, {"question": "Kan man koka grillkorv?", "answer": "Ja, koka 5-8 minuter eller stek i panna med lite vatten först."}]'::jsonb,
ARRAY['Grillmys', 'Korvstroganoff', 'Snabbmat']),

-- Kryddor & Örter (2 more)
('Timjan', 'timjan', 'T',
(SELECT id FROM public.food_categories WHERE slug = 'kryddor-orter'),
'Färsk/torkad ört',
'Kylskåp färsk, mörkt torr',
'1 vecka färsk, 2 år torkad',
'3-5 dagar färsk',
true,
'Frys färska kvistar',
ARRAY['maj', 'juni', 'juli', 'augusti'],
ARRAY[]::text[],
101, 5.6, 1.7, 24.0, 14.0, 0.01,
'{"C": "50mg", "A": "190μg", "K": "275μg"}'::jsonb,
'{"järn": "17.5mg", "mangan": "1.7mg", "kalium": "609mg"}'::jsonb,
'Nordisk ört med subtil, jordnära smak.',
ARRAY['Köttgryta', 'Rosmarin kyckling', 'Soppa', 'Fisk'],
'[{"name": "Rosmarin", "reason": "Annan stark ört för kött"}, {"name": "Salvia", "reason": "Liknande jordnära smak"}]'::jsonb,
'Timjan - Nordisk Ört och Köttgryta | Livsmedel A-Ö',
'Komplett guide om timjan: användning i nordisk matlagning, förvaring och kombinationer med andra kryddor.',
'[{"question": "Hur plockar man timjan från kvistar?", "answer": "Dra fingrarna mot bladens växtriktning längs kvisten för att lätt lossa bladen."}, {"question": "Passar timjan till fisk?", "answer": "Ja, perfekt till vit fisk och i fiskfärser - ger en subtil, ren smak."}]'::jsonb,
ARRAY['Köttgryta', 'Nordisk mat', 'Köttkrydda']);