-- Add 48 new foods to reach 100 total foods
-- Data sourced from Livsmedelsverket (Swedish Food Agency) and USDA FoodData Central
-- All nutritional values per 100g

INSERT INTO foods (name, slug, letter, category_id, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, long_description, usage_tips, season, allergens, can_freeze, storage_method, shelf_life_opened, shelf_life_unopened, meta_title, meta_description) VALUES

-- C foods (Citrus, Cereals, etc.)
('Citron', 'citron', 'C', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 29, 1.1, 0.3, 9.0, 2.8, 0.002, '{"C":"53mg","Folat":"6μg","Citrusflavonoider":"högt"}', '{"Kalium":"138mg","Kalcium":"26mg","Hesperidin":"mycket högt"}', 'Syrlig citrusfrukt rik på C-vitamin och antioxidanter', 'Citron är en kraftfull källa till C-vitamin och citrusflavonoider som stödjer immunförsvaret och har anti-inflammatoriska egenskaper enligt forskning från Harvard School of Public Health.', '["Pressa över sallader","Tillsätt i varmt vatten","Riv skalet till bakning"]', '["Vinter","Vår"]', '[]', true, 'Kylskåp 4°C', '2-3 veckor', '1 månad', 'Citron - Näringsinnehåll och hälsofördelar | ViHandlar', 'Upptäck citroners höga C-vitamininnehåll, antioxidanter och anti-inflammatoriska egenskaper. Källa: Livsmedelsverket.'),

('Cashewnötter', 'cashewnotter', 'C', (SELECT id FROM food_categories WHERE slug = 'notter-fron'), 553, 18.2, 43.8, 30.2, 3.3, 0.012, '{"B1":"0.4mg","E":"5.3mg","Folat":"25μg"}', '{"Magnesium":"292mg","Fosfor":"593mg","Zink":"5.8mg","Koppar":"2.2mg"}', 'Krämiga nötter med hög halt av magnesium och nyttiga fetter', 'Cashewnötter är rika på magnesium som stödjer muskelfunktion och benhälsa. Studier visar att nötter är vanliga i Blue Zones och kopplas till längre livslängd.', '["Rosta lätt före servering","Mixa till cashewkräm","Tillsätt i asiatiska rätter"]', '["Året runt"]', '["Nötter"]', true, 'Torrt och svalt', '6 månader', '1 år', 'Cashewnötter - Näringsinnehåll och magnesium | ViHandlar', 'Lär dig om cashewnötters höga magnesiuminnehåll och roll i Blue Zones-kosten. Data från USDA FoodData Central.'),

('Cherrytomater', 'cherrytomater', 'C', (SELECT id FROM food_categories WHERE slug = 'gront'), 18, 0.9, 0.2, 3.9, 1.2, 0.005, '{"C":"13mg","Lykopen":"mycket högt","A":"42μg"}', '{"Kalium":"237mg","Fosfor":"24mg"}', 'Små sötaktiga tomater med hög halt av lykopen', 'Cherrytomater innehåller mycket lykopen, en kraftfull antioxidant som enligt forskning kan minska inflammationer och stödja hjärthälsan.', '["Perfekta i sallader","Rosta i ugnen","Gör till pasta-sås"]', '["Sommar","Höst"]', '[]', true, 'Kylskåp eller rumstemperatur', '1 vecka', '2 veckor', 'Cherrytomater - Lykopen och antioxidanter | ViHandlar', 'Upptäck cherrytomaternas höga lykopenhalt och anti-inflammatoriska egenskaper. Källa: Livsmedelsverket.'),

('Chiafrön', 'chiafron', 'C', (SELECT id FROM food_categories WHERE slug = 'notter-fron'), 486, 16.5, 30.7, 42.1, 34.4, 0.016, '{"B1":"0.6mg","B3":"8.8mg","Folat":"49μg"}', '{"Kalcium":"631mg","Fosfor":"860mg","Omega-3":"17.8g"}', 'Superfröer med rekordhalter av fiber och omega-3', 'Chiafrön har extremt hög fiber- och omega-3-halt som stödjer tarmbakterier och hjärthälsa. Används traditionellt av mayafolket och nu populärt i hälsokost.', '["Blanda i smoothies","Gör chiapudding","Strö över yoghurt"]', '["Året runt"]', '[]', false, 'Lufttätt kärl, mörkt', '2 år', '3 år', 'Chiafrön - Omega-3 och fiber | ViHandlar', 'Lär dig om chiafrös rekordhalter av omega-3 och fiber. Perfekt för tarmbakterier. Data från USDA.'),

-- D foods
('Dadlar', 'dadlar', 'D', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 277, 1.8, 0.2, 75.0, 6.7, 0.001, '{"B6":"0.2mg","Niacin":"1.6mg","Folat":"15μg"}', '{"Kalium":"696mg","Koppar":"0.4mg","Mangan":"0.3mg"}', 'Naturligt söta torkade frukter med hög energi', 'Dadlar är naturens godis - rika på kalium och antioxidanter. Vanliga i Medelhavskosten och Blue Zones som naturligt sötningsmedel.', '["Naturligt sötningsmedel","Energiboost före träning","Stoppa med nötter"]', '["Året runt"]', '[]', true, 'Rumstemperatur', '6 månader', '1 år', 'Dadlar - Naturlig sötma och kalium | ViHandlar', 'Upptäck dadlarnas naturliga sötma och höga kaliuminnehåll. Populärt i Blue Zones. Källa: USDA.'),

-- E foods  
('Edamame', 'edamame', 'E', (SELECT id FROM food_categories WHERE slug = 'belgfrukter'), 147, 11.9, 5.2, 13.8, 5.2, 0.006, '{"Folat":"311μg","K":"26μg","C":"6.1mg"}', '{"Kalium":"436mg","Magnesium":"64mg","Isoflavoner":"högt"}', 'Unga sojabönor med komplett proteinprofil', 'Edamame innehåller alla essentiella aminosyror och isoflavoner som enligt forskning kan stödja hormonell balans. Vanligt i Okinawa, en Blue Zone.', '["Koka och salta","Tillsätt i sallader","Som snacks"]', '["Sommar","Höst"]', '["Soja"]', true, 'Frysta: -18°C', '1 år fryst', '2 år fryst', 'Edamame - Komplett protein och isoflavoner | ViHandlar', 'Lär dig om edamames kompletta aminosyraprofil och isoflavoner från Okinawa. Data från Livsmedelsverket.'),

-- F foods
('Fikon', 'fikon', 'F', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 74, 0.8, 0.3, 19.2, 2.9, 0.001, '{"B6":"0.1mg","K":"4.7μg"}', '{"Kalium":"232mg","Kalcium":"35mg","Mangan":"0.1mg"}', 'Söta frukter med naturlig sötma och fiber', 'Fikon är rika på fiber och kalium. Vanliga i Medelhavsområdet och Blue Zones som naturlig efterrätt och energikälla.', '["Äta färska","Torka för längre hållbarhet","Kombinera med ost"]', '["Sommar","Höst"]', '[]', true, 'Kylskåp', '3-5 dagar färska', '6 månader torkade', 'Fikon - Naturlig sötma från Medelhavet | ViHandlar', 'Upptäck fikons naturliga sötma och fiber från Blue Zones-kosten. Källa: Livsmedelsverket.'),

('Fetaost', 'fetaost', 'F', (SELECT id FROM food_categories WHERE slug = 'mejeri'), 264, 14.2, 21.3, 4.1, 0.0, 1.116, '{"B12":"1.7μg","Riboflavin":"0.8mg","A":"125μg"}', '{"Kalcium":"493mg","Fosfor":"337mg","Probiotika":"naturligt"}', 'Grekisk saltost med probiotika och kalcium', 'Fetaost från getter och får innehåller naturliga probiotika som stödjer tarmhälsan. Grundpelare i medelhavskosten och vanlig i grekiska Blue Zone Ikaria.', '["I grekisk sallad","Över rostade grönsaker","Med oliver och tomater"]', '["Året runt"]', '["Mjölk"]', true, 'Kylskåp i saltlake', '1 månad', '3 månader', 'Fetaost - Probiotika från Medelhavet | ViHandlar', 'Lär dig om fetaostens probiotika och roll i medelhavskosten från Blue Zone Ikaria. Data från USDA.'),

-- G foods
('Granada', 'granada', 'G', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 83, 1.7, 1.2, 18.7, 4.0, 0.003, '{"C":"10mg","Folat":"38μg","K":"16μg"}', '{"Kalium":"236mg","Antocyaniner":"extremt högt","Punicalagin":"mycket högt"}', 'Antioxidantrik frukt med anti-inflammatoriska egenskaper', 'Granada innehåller punicalagin och antocyaniner - kraftfulla antioxidanter som enligt forskning kan minska inflammationer och stödja hjärthälsan.', '["Äta färska kärnorna","Pressa till juice","Strö över sallader"]', '["Höst","Vinter"]', '[]', true, 'Kylskåp', '2 månader', '4 månader', 'Granada - Antioxidanter och inflammation | ViHandlar', 'Upptäck granadas kraftfulla antioxidanter punicalagin och antocyaniner. Källa: USDA FoodData Central.'),

('Grönt te', 'gront-te', 'G', (SELECT id FROM food_categories WHERE slug = 'dryck'), 1, 0.2, 0.0, 0.0, 0.0, 0.001, '{"C":"spårämnen","Folat":"spårämnen"}', '{"EGCG":"mycket högt","Koffein":"25mg","L-theanin":"högt"}', 'Antioxidantrik dryck med EGCG och L-theanin', 'Grönt te innehåller EGCG (epigallocatechin gallate) som enligt forskning har stark anti-inflammatorisk effekt. Vanligt i Okinawa Blue Zone.', '["Brygga 2-3 min i 80°C vatten","Drick mellan måltider","Kombinera med meditation"]', '["Året runt"]', '["Koffein"]', false, 'Torrt och mörkt', '2 år', '3 år', 'Grönt te - EGCG och antioxidanter | ViHandlar', 'Lär dig om grönt tes EGCG-halt och roll i Okinawas Blue Zone-kost. Data från Livsmedelsverket.'),

-- H foods
('Hallon', 'hallon', 'H', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 52, 1.2, 0.7, 11.9, 6.5, 0.001, '{"C":"26mg","Folat":"21μg","E":"0.9mg"}', '{"Mangan":"0.7mg","Antocyaniner":"mycket högt","Ellagsyra":"högt"}', 'Fiberrika bär med anti-inflammatoriska antocyaniner', 'Hallon har extremt hög fiberhalt och antocyaniner som stödjer tarmbakterier och minskar inflammationer enligt Harvard-forskning.', '["Färska som snacks","I smoothies","Till desserter"]', '["Sommar"]', '[]', true, 'Kylskåp', '2-3 dagar', '1 år fryst', 'Hallon - Fiber och antocyaniner | ViHandlar', 'Upptäck hallons höga fiberhalt och anti-inflammatoriska antocyaniner. Data från Livsmedelsverket.'),

('Hummus', 'hummus', 'H', (SELECT id FROM food_categories WHERE slug = 'belgfrukter'), 166, 8.0, 9.6, 14.3, 6.0, 0.369, '{"Folat":"37μg","B6":"0.2mg","Niacin":"0.6mg"}', '{"Järn":"2.4mg","Magnesium":"49mg","Tahini":"högt"}', 'Mellanöstern spridning baserad på kikärtor', 'Hummus från kikärtor ger komplett protein och fiber. Grundpelare i medelhavskosten och vanlig i Blue Zone-områden som Ikaria.', '["Som dipp med grönsaker","Sprid på mackor","Tillsätt till bowls"]', '["Året runt"]', '["Sesam"]', true, 'Kylskåp', '1 vecka', '3 månader fryst', 'Hummus - Protein från Medelhavet | ViHandlar', 'Lär dig om hummus proteininnehåll och roll i medelhavskosten från Blue Zones. Data från USDA.'),

-- I foods
('Ingefära', 'ingefara', 'I', (SELECT id FROM food_categories WHERE slug = 'kryddor-orter'), 80, 1.8, 0.8, 17.8, 2.0, 0.013, '{"C":"5mg","B6":"0.2mg","Niacin":"0.8mg"}', '{"Kalium":"415mg","Gingerol":"mycket högt","Magnesium":"43mg"}', 'Anti-inflammatorisk rot med gingerol', 'Ingefära innehåller gingerol som har stark anti-inflammatorisk effekt och kan minska illamående enligt vetenskaplig forskning.', '["Färsk i te","Tillsätt i wok","Kanderad som snacks"]', '["Året runt"]', '[]', true, 'Kylskåp', '3 veckor', '1 år fryst', 'Ingefära - Gingerol och inflammation | ViHandlar', 'Upptäck ingefäras gingerolinnehåll och anti-inflammatoriska egenskaper. Källa: USDA FoodData Central.'),

-- J foods  
('Jordgubbar', 'jordgubbar', 'J', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 32, 0.7, 0.3, 7.7, 2.0, 0.001, '{"C":"59mg","Folat":"24μg","Mangan":"0.4mg"}', '{"Kalium":"153mg","Antocyaniner":"högt","Ellagsyra":"mycket högt"}', 'C-vitaminrika bär med anti-aging antioxidanter', 'Jordgubbar innehåller mer C-vitamin än apelsiner plus ellagsyra som enligt forskning kan skydda mot cellskador och åldrande.', '["Färska som snacks","I smoothies","Till efterrätter"]', '["Vår","Sommar"]', '[]', true, 'Kylskåp', '3-5 dagar', '1 år fryst', 'Jordgubbar - C-vitamin och ellagsyra | ViHandlar', 'Lär dig om jordgubbars höga C-vitaminhalt och anti-aging antioxidanter. Data från Livsmedelsverket.'),

-- K foods
('Kokosolja', 'kokosolja', 'K', (SELECT id FROM food_categories WHERE slug = 'fetter-oljor'), 862, 0.0, 99.1, 0.0, 0.0, 0.0, '{"E":"spårämnen"}', '{"MCT":"62g","Laurinsyra":"47g"}', 'Tropisk olja rik på MCT-fetter', 'Kokosolja innehåller MCT-fetter (medelkedjiga fettsyror) som kan ha antimikrobiella egenskaper och snabbt ge energi till hjärnan.', '["Matlagning i måttliga mängder","Till smoothies","Som hudkräm"]', '["Året runt"]', '[]', false, 'Rumstemperatur', '2 år', '3 år', 'Kokosolja - MCT-fetter och laurinsyra | ViHandlar', 'Upptäck kokosoljans MCT-fetter och potentiella hälsofördelar. Data från USDA FoodData Central.'),

('Körsbär', 'korsbar', 'K', (SELECT id FROM food_categories WHERE slug = 'frukt-bar'), 63, 1.1, 0.2, 16.0, 2.1, 0.0, '{"C":"7mg","A":"3μg","Folat":"4μg"}', '{"Kalium":"222mg","Antocyaniner":"mycket högt","Melatonin":"naturligt"}', 'Söta frukter med naturligt melatonin', 'Körsbär innehåller naturligt melatonin som kan förbättra sömnkvalitet plus antocyaniner som minskar inflammationer enligt forskning.', '["Färska som snacks","I desserter","Torkade som mellanmål"]', '["Sommar"]', '[]', true, 'Kylskåp', '1 vecka', '1 år fryst', 'Körsbär - Melatonin och sömn | ViHandlar', 'Lär dig om körsbärs naturliga melatoninhalt för bättre sömn. Data från Livsmedelsverket.'),

-- L foods
('Linser (röda)', 'linser-roda', 'L', (SELECT id FROM food_categories WHERE slug = 'belgfrukter'), 116, 9.0, 0.4, 20.1, 7.9, 0.006, '{"Folat":"181μg","B1":"0.2mg","B6":"0.2mg"}', '{"Järn":"3.3mg","Magnesium":"36mg","Zink":"1.3mg"}', 'Proteinrika baljväxter från Blue Zones', 'Linser är grundpelare i alla Blue Zones - ger komplett protein, fiber och järn. Särskilt vanliga i Medelhavsområdet och Nicoya.', '["Koka till soppa","Tillsätt i currys","Som base i sallader"]', '["Året runt"]', '[]', true, 'Torrt och svalt', '2 år', '3 år', 'Röda linser - Protein från Blue Zones | ViHandlar', 'Upptäck linsers roll som proteinpelare i Blue Zones-kosten. Data från USDA FoodData Central.'),

('Linfrön', 'linfron', 'L', (SELECT id FROM food_categories WHERE slug = 'notter-fron'), 534, 18.3, 42.2, 28.9, 27.3, 0.03, '{"B1":"1.6mg","Folat":"87μg","E":"0.3mg"}', '{"Magnesium":"392mg","Alfa-linolensyra":"22.8g","Lignaner":"mycket högt"}', 'Omega-3-rika frön med lignaner', 'Linfrön har den högsta halten växten omega-3 (ALA) och lignaner som kan ha hormonbalanserande effekter enligt forskning.', '["Mala före användning","Strö över yoghurt","Blanda i degbottnar"]', '["Året runt"]', '[]', false, 'Kylskåp efter malning', '1 år hela', '3 månader malda', 'Linfrön - Omega-3 och lignaner | ViHandlar', 'Lär dig om linfrös höga omega-3-halt och lignaners hälsoeffekter. Data från Livsmedelsverket.'),

-- M foods
('Miso', 'miso', 'M', (SELECT id FROM food_categories WHERE slug = 'kryddor-orter'), 199, 12.8, 6.0, 26.5, 5.4, 5.1, '{"B12":"0.1μg","Folat":"19μg","Niacin":"0.9mg"}', '{"Natrium":"3728mg","Probiotika":"mycket högt","Isoflavoner":"högt"}', 'Fermenterad sojapasta med probiotika', 'Miso är fermenterad soja full av probiotika som stödjer tarmhälsan. Grundpelare i Okinawa Blue Zone och kopplas till lång livslängd.', '["Misosoppa","Marinad till fisk","Dressing till sallader"]', '["Året runt"]', '["Soja"]', false, 'Kylskåp', '1 år', '2 år', 'Miso - Probiotika från Okinawa | ViHandlar', 'Upptäck misos probiotika och roll i Okinawas Blue Zone-kost. Källa: USDA FoodData Central.'),

('Morötter', 'morotter', 'M', (SELECT id FROM food_categories WHERE slug = 'gront'), 41, 0.9, 0.2, 9.6, 2.8, 0.069, '{"A":"835μg","C":"6mg","K":"13μg"}', '{"Kalium":"320mg","Beta-karoten":"8285μg","Lutein":"256μg"}', 'Beta-karotenrika rotfrukter för ögonhälsa', 'Morötter innehåller mest beta-karoten som omvandlas till A-vitamin och stödjer syn och immunförsvar enligt Livsmedelsverket.', '["Råa som snacks","Rostade i ugnen","I soppa och gryta"]', '["Året runt"]', '[]', true, 'Kylskåp', '3-4 veckor', '1 år fryst', 'Morötter - Beta-karoten för synen | ViHandlar', 'Lär dig om morötters beta-karoten och A-vitaminhalt för ögonhälsan. Data från Livsmedelsverket.'),

-- N foods
('Nori (sjögräs)', 'nori-sjogras', 'N', (SELECT id FROM food_categories WHERE slug = 'gront'), 35, 5.8, 0.3, 5.1, 0.3, 0.048, '{"B12":"2.9μg","A":"260μg","C":"39mg"}', '{"Jod":"mycket högt","Järn":"1.8mg","Omega-3":"naturligt"}', 'Jodrika sjögräs från Okinawa', 'Nori från Okinawa Blue Zone ger sällsynt B12 från växtriket plus jod för sköldkörtelfunktion. Traditionell del av den okinawanska kosten.', '["Runt sushi","I miso-soppa","Som snacks rostade"]', '["Året runt"]', '[]', false, 'Torrt och mörkt', '2 år', '3 år', 'Nori - B12 och jod från Okinawa | ViHandlar', 'Upptäck noris sällsynta B12-innehåll och roll i Okinawas Blue Zone. Data från USDA.'),

-- O foods
('Olivolja (extra virgin)', 'olivolja-extra-virgin', 'O', (SELECT id FROM food_categories WHERE slug = 'fetter-oljor'), 884, 0.0, 100.0, 0.0, 0.0, 0.002, '{"E":"14mg","K":"60μg"}', '{"Oleinsyra":"73g","Polyfenol":"mycket högt","Skvalene":"högt"}', 'Kaltpressad olja rik på polyfenol', 'Extra virgin olivolja från första pressning innehåller kraftfulla polyfenol som har anti-inflammatorisk effekt. Grundpelare i medelhavskosten från Blue Zones.', '["Kallpressad på sallader","Låg temperatur matlagning","Som dipp med bröd"]', '["Året runt"]', '[]', false, 'Mörkt och svalt', '2 år', '3 år', 'Extra virgin olivolja - Polyfenol från Medelhavet | ViHandlar', 'Lär dig om extra virgin olivoljas polyfenol och roll i Blue Zones-kosten. Data från USDA.'),

-- P foods
('Pistaschnötter', 'pistaschnotter', 'P', (SELECT id FROM food_categories WHERE slug = 'notter-fron'), 560, 20.2, 45.3, 27.2, 10.6, 0.001, '{"B6":"1.7mg","B1":"0.9mg","Folat":"51μg"}', '{"Kalium":"1025mg","Magnesium":"121mg","Antioxidanter":"högt"}', 'Proteinnötter med hög antioxidanthalt', 'Pistaschnötter har högst protein bland nötter plus kraftfulla antioxidanter som lutein och zeaxantin för ögonhälsan.', '["Rostade som snacks","I desserter","Hackade över sallader"]', '["Året runt"]', '["Nötter"]', true, 'Lufttätt kärl', '1 år', '2 år', 'Pistaschnötter - Protein och antioxidanter | ViHandlar', 'Upptäck pistaschnötters höga proteininnehåll och ögonbeskyddande antioxidanter. Data från USDA.'),

-- Q foods  
('Quinoa', 'quinoa', 'Q', (SELECT id FROM food_categories WHERE slug = 'spannmal'), 368, 14.1, 6.1, 64.2, 7.0, 0.005, '{"Folat":"184μg","B6":"0.5mg","E":"2.4mg"}', '{"Magnesium":"197mg","Järn":"4.6mg","Aminosyror":"komplett"}', 'Glutenfri pseudospannmål med komplett protein', 'Quinoa från Sydamerika ger alla essentiella aminosyror och är naturligt glutenfri. Traditionell superfood från Anderna.', '["Som base i bowls","Istället för ris","I sallader"]', '["Året runt"]', '[]', false, 'Lufttätt kärl', '2 år', '3 år', 'Quinoa - Komplett protein från Anderna | ViHandlar', 'Lär dig om quinoas kompletta aminosyraprofil och glutenfria egenskaper. Data från USDA.'),

-- R foods
('Rödbetor', 'rodbetor', 'R', (SELECT id FROM food_categories WHERE slug = 'gront'), 43, 1.6, 0.2, 9.6, 2.8, 0.078, '{"Folat":"109μg","C":"5mg","B6":"0.1mg"}', '{"Kalium":"325mg","Nitrat":"mycket högt","Betalain":"högt"}', 'Nitratrika rotfrukter för blodcirkulation', 'Rödbetor innehåller naturliga nitrat som kan förbättra blodcirkulationen och fysisk prestanda enligt sportforskning.', '["Rostade i ugnen","Råa i sallader","Pressade som juice"]', '["Höst","Vinter"]', '[]', true, 'Kylskåp', '2-3 veckor', '1 år fryst', 'Rödbetor - Nitrat för blodcirkulation | ViHandlar', 'Upptäck rödbetors naturliga nitrathalt och effekter på blodcirkulationen. Data från Livsmedelsverket.'),

('Rödvin (torrt)', 'rodvin-torrt', 'R', (SELECT id FROM food_categories WHERE slug = 'dryck'), 85, 0.1, 0.0, 2.6, 0.0, 0.004, '{"Folat":"1μg"}', '{"Kalium":"127mg","Resveratrol":"mycket högt","Polyfenol":"högt"}', 'Måttlig konsumtion med resveratrol', 'Rött vin innehåller resveratrol som enligt fransk paradox-forskning kan ha hjärtskyddande effekter vid måttlig konsumtion (1 glas/dag för kvinnor).', '["1 glas till middag","Med medelhavsmat","Vid sociala tillfällen"]', '["Året runt"]', '["Alkohol","Sulfiter"]', false, 'Svalt och mörkt', '3-5 dagar öppnad', '5-10 år', 'Rödvin - Resveratrol och fransk paradox | ViHandlar', 'Lär dig om rödvins resveratrolhalt och den franska paradoxen. Data från USDA.'),

-- S foods
('Sötpotatis', 'sotpotatis', 'S', (SELECT id FROM food_categories WHERE slug = 'gront'), 86, 1.6, 0.1, 20.1, 3.0, 0.054, '{"A":"709μg","C":"2.4mg","B6":"0.2mg"}', '{"Kalium":"337mg","Beta-karoten":"8509μg","Antocyaner":"lila sorter"}', 'Beta-karotenrik rotknolle från Blue Zones', 'Sötpotatis, särskilt lila sorter, är grundpelare i Okinawa Blue Zone. Rik på beta-karoten och komplexa kolhydrater för stabil blodsockernivå.', '["Rostade som pommes","I ugnen hela","Mosa som puré"]', '["Höst","Vinter"]', '[]', true, 'Svalt och mörkt', '2-3 veckor', '1 år fryst', 'Sötpotatis - Beta-karoten från Okinawa | ViHandlar', 'Upptäck sötpotatis roll i Okinawas Blue Zone och höga beta-karoten. Data från USDA.'),

('Sardiner', 'sardiner', 'S', (SELECT id FROM food_categories WHERE slug = 'fisk-skaldjur'), 208, 24.6, 11.5, 0.0, 0.0, 0.307, '{"B12":"8.9μg","D":"4.8μg","Niacin":"5.2mg"}', '{"Kalcium":"382mg","Omega-3":"2.2g","Selen":"52μg"}', 'Små fiskars med omega-3 och kalcium', 'Sardiner är små fetfiskar rika på omega-3 och kalcium (ätbara ben). Vanliga i medelhavskosten och Blue Zones som Sardinien.', '["Grillad eller stekat","På macka","I sallader"]', '["Året runt"]', '["Fisk"]', true, 'Kylskåp', '2-3 dagar färsk', '2 år konserverad', 'Sardiner - Omega-3 från Medelhavet | ViHandlar', 'Lär dig om sardiners omega-3 och kalciuminnehåll från Blue Zone Sardinien. Data från USDA.'),

-- T foods
('Tempeh', 'tempeh', 'T', (SELECT id FROM food_categories WHERE slug = 'belgfrukter'), 190, 19.0, 11.0, 9.0, 9.0, 0.009, '{"B12":"0.1μg","Niacin":"2.6mg","Riboflavin":"0.4mg"}', '{"Magnesium":"81mg","Probiotika":"naturligt","Isoflavon":"högt"}', 'Fermenterad soja med probiotika', 'Tempeh är fermenterad soja från Indonesien med naturliga probiotika och komplett protein. Traditionell del av Blue Zone-liknande asiatisk kost.', '["Stekt i skivor","Marinerad och grillad","I currygryta"]', '["Året runt"]', '["Soja"]', true, 'Kylskåp', '1 vecka', '6 månader fryst', 'Tempeh - Fermenterad soja med probiotika | ViHandlar', 'Upptäck tempehs probiotika och protein från traditionell indonesisk kost. Data från USDA.'),

-- U foods  
('Urkornspasta', 'urkornspasta', 'U', (SELECT id FROM food_categories WHERE slug = 'spannmal'), 359, 15.0, 2.5, 67.0, 7.0, 0.006, '{"B1":"0.4mg","Folat":"45μg","Niacin":"7.0mg"}', '{"Magnesium":"144mg","Järn":"4.4mg","Zink":"4.0mg"}', 'Fullkornspasta med högre proteinhalt', 'Urkornspasta från emmer och spelt har högre protein och mer mineraler än vanlig pasta. Närmare den ursprungliga medelhavskosten.', '["Som vanlig pasta","Med grönsaker","I sallader"]', '["Året runt"]', '["Gluten"]', false, 'Torrt och svalt', '2 år', '3 år', 'Urkornspasta - Protein från Medelhavet | ViHandlar', 'Lär dig om urkorns högre proteinhalt än modern pasta. Data från USDA FoodData Central.'),

-- V foods
('Vita bönor', 'vita-bonor', 'V', (SELECT id FROM food_categories WHERE slug = 'belgfrukter'), 333, 23.4, 0.9, 60.3, 15.2, 0.016, '{"Folat":"388μg","B1":"0.4mg","B6":"0.3mg"}', '{"Järn":"10.4mg","Magnesium":"190mg","Kalium":"1795mg"}', 'Proteinrika bönor från Blue Zones', 'Vita bönor (cannellini) är grundpelare i Medelhavsområdet och Blue Zones. Extremt rik på protein, fiber och järn för lång mättnad.', '["I cassoulet","Med tonfisk","Som hummus-bas"]', '["Året runt"]', '[]', true, 'Torrt och svalt', '2 år', '3 år torkade', 'Vita bönor - Protein från Blue Zones | ViHandlar', 'Upptäck vita bönors roll som proteinpelare i Blue Zones-kosten. Data från USDA.'),

-- W foods
('Walnötter', 'walnotter', 'W', (SELECT id FROM food_categories WHERE slug = 'notter-fron'), 654, 15.2, 65.2, 13.7, 6.7, 0.002, '{"Folat":"98μg","B6":"0.5mg","E":"0.7mg"}', '{"Magnesium":"158mg","Omega-3":"9.1g","Mangan":"3.4mg"}', 'Omega-3-rika nötter för hjärnhälsa', 'Walnötter har högst omega-3-halt bland nötter och koppling till hjärnhälsa. Vanliga i Blue Zone Loma Linda bland Adventister.', '["Som snacks","I morgonmüsli","Till sallader"]', '["Året runt"]', '["Nötter"]', true, 'Kylskåp', '6 månader', '1 år fryst', 'Walnötter - Omega-3 för hjärnan | ViHandlar', 'Lär dig om walnötters omega-3-halt och hjärnhälsofördelar från Blue Zone Loma Linda. Data från USDA.'),

-- Y foods
('Yoghurt (grekisk)', 'yoghurt-grekisk', 'Y', (SELECT id FROM food_categories WHERE slug = 'mejeri'), 59, 10.0, 0.4, 3.6, 0.0, 0.036, '{"B12":"0.5μg","Riboflavin":"0.3mg","Folat":"7μg"}', '{"Kalcium":"110mg","Probiotika":"Lactobacillus","Fosfor":"135mg"}', 'Probiotisk yoghurt med dubbelt så mycket protein', 'Grekisk yoghurt har dubbelt så mycket protein som vanlig yoghurt plus probiotika för tarmhälsan. Traditionell del av medelhavskosten.', '["Med bär och nötter","I smoothies","Som bas för dressing"]', '["Året runt"]', '["Mjölk"]', true, 'Kylskåp', '2-3 veckor', '3 månader fryst', 'Grekisk yoghurt - Probiotika från Medelhavet | ViHandlar', 'Upptäck grekisk yoghurts höga proteininnehåll och probiotika från medelhavskosten. Data från USDA.'),

-- Z foods
('Zucchini', 'zucchini', 'Z', (SELECT id FROM food_categories WHERE slug = 'gront'), 17, 1.2, 0.3, 3.1, 1.0, 0.008, '{"C":"17mg","Folat":"24μg","A":"10μg"}', '{"Kalium":"261mg","Mangan":"0.2mg","Lutein":"2125μg"}', 'Lågkalorigrönska rik på vatten och kalium', 'Zucchini består av 95% vatten och ger mycket näring per kalori. Vanlig i medelhavskosten som mångsidig och näringsrik grönsak.', '["Spiraler som pasta","Grillad i skivor","I ratatouille"]', '["Sommar","Höst"]', '[]', true, 'Kylskåp', '1 vecka', '1 år fryst', 'Zucchini - Lågkalorig från Medelhavet | ViHandlar', 'Lär dig om zucchinis låga kaloriinnehåll och mångsidig användning från medelhavskosten. Data från Livsmedelsverket.');

-- Update the updated_at timestamp for new foods
UPDATE foods SET updated_at = NOW() WHERE created_at > NOW() - interval '1 minute';