-- Add long descriptions for essential food items
UPDATE foods SET long_description = 'Ägg är en av naturens mest kompletta proteinkällor och innehåller alla essentiella aminosyror som kroppen behöver. Ett medelstort ägg (cirka 60 gram) innehåller ungefär 6 gram högkvalitativt protein och endast 70 kalorier. Ägg är rika på kolin, som är viktigt för hjärnhälsa och minnesfunktion, samt lutein och zeaxantin som skyddar ögonen. De innehåller också viktiga B-vitaminer, vitamin D och mineraler som järn och selen. Ägg från frigående höns innehåller ofta högre halter av omega-3-fettsyror. De är extremt mångsidiga och kan tillagas på otaliga sätt - kokta, stekta, pocherade, eller användas i bakning. Välj ekologiska ägg när det är möjligt för bästa kvalitet och djurvälfärd.' WHERE slug = 'agg';

UPDATE foods SET long_description = 'Äpplen är en av världens mest populära frukter och för gott skäl. De är rika på fiber, särskilt pektin, som hjälper till att reglera blodsockret och främjar mättnadskänsla. Ett medelstort äpple innehåller cirka 4 gram fiber och endast 95 kalorier. Äpplen innehåller kraftfulla antioxidanter som quercetin och katekiner som kan hjälpa till att minska inflammation och stödja hjärthälsan. Skalet innehåller flest näringsstoffer, så ät gärna äpplet med skalet efter noggrann sköljning. Svenska sorter som Ingrid Marie, Aroma och Discovery har utmärkt smak och näringsvärde. Äpplen håller sig fräscha längst när de förvaras i kylskåp och är perfekta som mellanmål, i bakning eller som en del av en balanserad frukost.' WHERE slug = 'apple';

UPDATE foods SET long_description = 'Apelsiner är citrusfrukter fyllda med vitamin C - en medelstor apelsin täcker hela det dagliga behovet av vitamin C (cirka 70 mg). Vitamin C stärker immunförsvaret, hjälper kroppen att absorbera järn och är viktig för kollagenproduktion. Apelsiner innehåller också folsyra som är särskilt viktigt för gravida kvinnor, samt flavonoider som hesperidin som kan hjälpa till att sänka kolesterol och blodtryck. Fibern i apelsiner, särskilt pektinet, hjälper till att reglera blodsockret och främjar god tarmhälsa. Välj apelsiner som känns tunga för sin storlek och har fast, spänd skal. De håller sig fräscha i rumstemperatur i en vecka eller i kylskåp i upp till en månad. Nypress juicen för bästa smak och näringsvärde.' WHERE slug = 'apelsin';

UPDATE foods SET long_description = 'Avokado är en unik frukt som är rik på nyttiga enomättade fetter, särskilt oljesyra som är bra för hjärthälsan. En halv avokado innehåller cirka 15 gram nyttiga fetter, 7 gram fiber och över 10 olika vitaminer och mineraler. Avokadon är särskilt rik på kalium (mer än bananer), vitamin K, folsyra och vitamin E. De nyttiga fetterna i avokado hjälper kroppen att absorbera fettlösliga vitaminer från andra livsmedel. Avokado har en krämig konsistens som gör den perfekt för allt från guacamole till smoothies och som brödpålägg. En mogen avokado ger efter lätt när man trycker försiktigt på den. Förvara omogna avokados i rumstemperatur och mogna avokados i kylskåp för att förlänga hållbarheten.' WHERE slug = 'avokado';

UPDATE foods SET long_description = 'Bananer är en av världens mest populära frukter och en utmärkt källa till kalium, vitamin B6 och vitamin C. En medelstor banan innehåller cirka 400 mg kalium, vilket är viktigt för hjärt- och muskelfunktion. Bananer innehåller också naturligt socker (fruktos, glukos och sackaros) som ger snabb energi, vilket gör dem populära bland idrottare. De innehåller resistente stärkelser, särskilt i omoget tillstånd, som fungerar som prebiotika och gynnar tarmfloran. Bananer innehåller även tryptofan som kroppen omvandlar till serotonin, vilket kan förbättra humöret. Gula, mogna bananer är sötast medan gröna bananer har mer stärkelse och fiber. Använd överrumpna bananer i bakning - de blir extra söta och saftiga i bröd och muffins.' WHERE slug = 'banan';

UPDATE foods SET long_description = 'Broccoli är en av de mest näringstäta grönsakerna och tillhör familjen korsblommiga växter tillsammans med kål och blomkål. Den är exceptionellt rik på vitamin C - 100 gram broccoli innehåller mer vitamin C än en apelsin. Broccoli innehåller kraftfulla antioxidanter som sulforafan, som har visat sig ha cancerbekämpande egenskaper i studier. Den är också en bra källa till vitamin K för benhälsa, folsyra för celldelning och fiber för tarmhälsa. Broccoli innehåller även järn, kalium och krom. För att bevara näringsvärdet, ångkoka eller woka broccolin kort så att den behåller sin ljusgröna färg och knapriga konsistens. Överkokning förstör både smak och näringsämnen. Färsk broccoli ska ha fastslutna, mörkgröna blomknippen utan gula partier.' WHERE slug = 'broccoli';

UPDATE foods SET long_description = 'Bröd är en grundläggande näringskälla i den svenska kosten och finns i många varianter från ljust vitt bröd till mörkt fullkornsbröd. Fullkornsbröd är det mest näringsrika alternativet eftersom det innehåller hela kornet med dess fiber, vitaminer och mineraler. Bröd är en god källa till kolhydrater för energi, B-vitaminer särskilt tiamin och niacin, samt järn och magnesium. Surdegsbröd har fördelen att vara lättare att smälta och kan ha lägre glykemiskt index än vanligt jästbröd. Välj bröd med hög fiberhalt (minst 6 gram per 100 gram) för bästa hälsoeffekt. Förvara bröd i rumstemperatur för daglig konsumtion och frys in portioner för längre hållbarhet. Rosta gärna brödet för bättre smak och textur.' WHERE slug = 'brod';