-- Add long descriptions for remaining foods (batch 3)
UPDATE foods SET long_description = 'Mozzarella är en mild, krämig ost som ursprungligen kommer från Italien och traditionellt gjordes på buffel mjölk. Modern mozzarella görs oftast på komjölk och är rik på kalcium, protein och vitamin B12. Färsk mozzarella har hög vattenhalt och mild smak, medan lagrad mozzarella är fastare och mer koncentrerad i smak. Mozzarella smälter jämnt och drar långa strängar, vilket gör den perfekt för pizza och gratänger. Den innehåller probiotiska bakterier som kan gynna tarmhälsan. Förvara färsk mozzarella i sin egen vätska i kylskåp och konsumera inom några dagar för bästa kvalitet och säkerhet.' WHERE slug = 'mozzarella';

UPDATE foods SET long_description = 'Nötfärs är malet nötkött som är en rik källa till protein, järn och B-vitaminer. Det innehåller hemjärn som absorberas lättare än järn från vegetabiliska källor. Nötfärs är också en bra källa till zink, selen och kreatin. Välj nötfärs med lägre fetthalt (max 15%) för hälsosammare alternativ. Ekologiskt nötfärs från betesdjur innehåller ofta högre halter av omega-3-fettsyror och konjugerad linolsyra (CLA). Tillaga nötfärs till minst 70°C inuti för säkerhet. Använd färskt nötfärs inom 1-2 dagar eller frys in för längre hållbarhet. Perfekt för köttfärsås, köttbullar och hamburgare.' WHERE slug = 'notfars';

UPDATE foods SET long_description = 'Extra virgin olivolja är kaldpressad från oliver och behåller sina naturliga antioxidanter och smakämnen. Den är rik på enomättade fetter, särskilt oljesyra, som kan hjälpa till att sänka inflammation och stödja hjärthälsan. Olivolja innehåller vitamin E och kraftfulla antioxidanter som oleocanthal som har anti-inflammatoriska egenskaper. Medelhavskost med extra virgin olivolja har kopplats till minskad risk för hjärt-kärlsjukdomar. Förvara olivolja mörkt och svalt för att bevara kvaliteten. Använd för dressingar, lätt stekning och som finish på färdiga rätter. Undvik hög värme som kan bryta ner näringsämnen.' WHERE slug = 'olivolja-extra-virgin';

UPDATE foods SET long_description = 'Oregano är en aromatisk ört som är rik på antioxidanter och har naturliga antimikrobiella egenskaper. Det innehåller eteriska oljor som karvakrol och tymol som kan ha antibakteriella och anti-inflammatoriska effekter. Oregano är en bra källa till vitamin K, mangan och antioxidanter. Torkad oregano har mer koncentrerad smak än färsk och håller sig längre. Oregano är en grundpelare i medelhavskosten och passar perfekt till tomater, kött och pizza. Förvara torkad oregano i lufttät behållare borta från ljus. Tillsätt oregano sent i matlagningen för att bevara smaken.' WHERE slug = 'oregano';

UPDATE foods SET long_description = 'Röd paprika är rik på vitamin C - en medelstor röd paprika innehåller mer än dubbelt så mycket vitamin C som en apelsin. Den får sin röda färg från karotener, särskilt beta-karoten och lycopene, kraftfulla antioxidanter som kan skydda mot cellskador. Röd paprika innehåller också vitamin A för synhälsa, folsyra och kalium. Röd paprika är sötare än grön paprika eftersom den får mogna längre på plantan. Den är perfekt råa i sallader, grillad, stekt eller fylld. Förvara i kylskåp och använd inom en vecka för bästa kvalitet.' WHERE slug = 'paprika-rod';

UPDATE foods SET long_description = 'Parmigiano Reggiano är "ostkungarnas kung" från Italien, lagrad i minst 12 månader för att utveckla sin karakteristiska nötiga, komplexa smak. Det är extremt rikt på kalcium - 100 gram innehåller över 1000 mg kalcium. Parmigiano Reggiano är också en utmärkt källa till protein och innehåller alla essentiella aminosyror. Den naturligt låga laktoshalten gör den lämplig för många laktosintoleraanta personer. Äkta Parmigiano Reggiano är märkt med ursprungsbeteckning. Köp helst hela bitar och riv själv för bästa smak. Förvara inslaget i kylskåp och använd skorpan i soppor och såser för extra smak.' WHERE slug = 'parmigiano-reggiano';