-- Add long descriptions for remaining foods (batch 2)
UPDATE foods SET long_description = 'Gul lök är en grundläggande ingrediens i matlagning världen över och innehåller kraftfulla svavelhaltiga föreningar som ger både smak och hälsofördelar. Lök innehåller quercetin, en stark antioxidant som kan ha anti-inflammatoriska egenskaper och stödja hjärthälsan. Den innehåller också prebiotikers fibrer som gynnar tarmfloran, vitamin C för immunförsvaret och mangan. Lök har naturligt antibakteriella egenskaper och kan hjälpa till att bekämpa infektioner. Förvara lök i torr, mörk plats med god luftcirkulation. Skär lök under rinnande vatten för att minska tårflöde. Karamelliserad lök utvecklar naturlig sötma perfekt för såser och gratänger.' WHERE slug = 'lok-gul';

UPDATE foods SET long_description = 'Makrill är en fet fisk som är rik på omega-3-fettsyror och har en av de högsta halterna av dessa hälsosamma fetter bland alla fisksorter. 100 gram makrill innehåller över 4 gram omega-3-fettsyror, vilket är mer än dubbelt så mycket som lax. Makrill är också en utmärkt källa till protein, vitamin D, B12 och selen. Den innehåller CoQ10, ett viktigt antioxidant för hjärthälsan. Färsk makrill ska lukta hav och ha klara ögon. På grund av sitt höga fettinnehåll är makrill särskilt smakfull grillad eller rökt. Konsumera makrill regelbundet för optimal hjärn- och hjärthälsa.' WHERE slug = 'makrill';

UPDATE foods SET long_description = 'Mandlar är näringstäta nötter som är rika på nyttiga enomättade fetter, protein och fiber. De är en utmärkt källa till vitamin E, en kraftfull antioxidant som skyddar cellerna från oxidativ stress. Mandlar innehåller också magnesium för muskel- och nervfunktion, samt kalcium för benhälsa. Studier visar att mandlar kan hjälpa till att sänka kolesterol och stabilisera blodsockret. En handfull mandlar (cirka 23 stycken) ger långvarig mättnad och energi. Välj osaltade mandlar för bästa hälsoeffekt. Mandlar kan användas hela, malda till mjöl eller som mandelmjölk.' WHERE slug = 'mandel';

UPDATE foods SET long_description = 'Vetemjöl är en grundläggande bakingrediensk som framställs genom malning av vetekorv. Vanligt vetemjöl innehåller främst kolhydrater och protein (gluten) som ger deg dess struktur och elasticitet. Det är berikadt med järn, tiamin, riboflavin, niacin och folsyra enligt livsmedelslagstiftning. Fullkornsvetemjöl innehåller mer fiber, vitaminer och mineraler än vitt mjöl. Förvara mjöl torrt och svalt, helst i lufttäta behållare. Olika proteinhalter passar olika bakverk - högproteinmjöl för bröd, lågproteinmjöl för kakor. Kontrollera utgångsdatum regelbundet då gammalt mjöl kan bli härsket.' WHERE slug = 'mjol-vetemjol';

UPDATE foods SET long_description = 'Mjölk är en komplett näringskälla som innehåller högkvalitativt protein med alla essentiella aminosyror, kalcium för stark benhälsa och vitamin D för kalciumabsorption. En kopp mjölk (250 ml) täcker cirka 30% av det dagliga kalciumbehovet. Mjölk innehåller också riboflavin, vitamin B12 och fosfor. Laktosfri mjölk finns för de som inte tål laktos. Ekologisk mjölk från betesdjur innehåller ofta högre halter av omega-3-fettsyror. Förvara mjölk i kylskåp vid max 4°C och konsumera före bäst före-datum. Mjölk är mångsidig och används i allt från drycker till bakning.' WHERE slug = 'mjolk';

UPDATE foods SET long_description = 'Morötter är rika på beta-karoten som kroppen omvandlar till vitamin A, viktigt för syn, immunförsvar och celldelning. En stor morot kan täcka hela det dagliga behovet av vitamin A. Morötter innehåller också fiber, kalium och antioxidanten lutein. Beta-karotenet absorberas bättre när morötter kokas och äts med lite fett. Morötter har naturlig sötma som ökar vid tillagning. De är perfekta råa som mellanmål, kokta som tillbehör eller som bas i soppor och såser. Förvara morötter i kylskåp utan blast för bästa hållbarhet. Ekologiska morötter behöver inte skalas, bara skrubbas.' WHERE slug = 'morot';