-- Add 45 new foods to reach total of 50 in Livsmedel A-Ö database

-- Insert Mejeri & Ostar (8 foods)
INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, long_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

('Parmigiano Reggiano', 'parmigiano-reggiano', 'P', 
(SELECT id FROM public.food_categories WHERE slug = 'mejeri'), 
'Hårdost', 
'Kylskåp 4-8°C, helst i ostpapper', 
'4-6 veckor', 
'6-8 månader', 
true, 
'Riv osten innan frysning för bästa resultat', 
ARRAY['mjölk'], 
431, 38.5, 29.0, 0.0, 0.0, 1.6,
'{"A": "300μg", "B12": "2.0μg", "D": "0.5μg"}'::jsonb,
'{"calcium": "1184mg", "fosfor": "680mg"}'::jsonb,
'Italiensk hårdost med rik, nötig smak och granulär textur.',
'Parmigiano Reggiano är en av världens mest uppskattade hårdostar, tillverkad enligt traditionella metoder i Norditalien. Osten lagras i minst 12 månader och utvecklar en komplex, nötig smak med kristallina texturer.',
ARRAY['Riv över pasta', 'Tugga som snacks', 'Använd i risotto', 'Toppa sallader'],
'[{"name": "Grana Padano", "reason": "Liknande smak men mildare"}, {"name": "Pecorino Romano", "reason": "Saltare men liknande textur"}]'::jsonb,
'Parmigiano Reggiano - Näringsvärde och Användning | Livsmedel A-Ö',
'Komplett guide om Parmigiano Reggiano: näringsvärde, förvaring, användning och italienska osttraditionen. Tips för bästa smak.',
'[{"question": "Hur länge håller Parmigiano Reggiano?", "answer": "Hela bitar håller 6-8 månader oöppnade, 4-6 veckor efter öppning i kylskåp."}, {"question": "Kan man frysa Parmigiano Reggiano?", "answer": "Ja, men riv osten först för bästa resultat efter upptining."}]'::jsonb,
ARRAY['Pasta Carbonara', 'Caesar Sallad', 'Italiensk middag']),

('Mozzarella', 'mozzarella', 'M',
(SELECT id FROM public.food_categories WHERE slug = 'mejeri'),
'Färskost',
'Kylskåp 4-8°C i egen vätska',
'3-5 dagar',
'1-2 veckor',
false,
'Rekommenderas ej att frysa',
ARRAY['mjölk'],
280, 18.1, 22.4, 2.2, 0.0, 0.6,
'{"A": "179μg", "B12": "2.3μg"}'::jsonb,
'{"calcium": "505mg", "fosfor": "354mg"}'::jsonb,
'Italiensk färskost med mild smak och krämig konsistens.',
'Mozzarella är en traditionell italiensk färskost som ursprungligen gjordes av buffelmodersmjölk. Idag tillverkas den oftast av komjölk och är känd för sin milda smak och elastiska textur.',
ARRAY['Pizza topping', 'Caprese sallad', 'Gratäng', 'Smörgås'],
'[{"name": "Burrata", "reason": "Krämigare variant av mozzarella"}, {"name": "Ricotta", "reason": "Mildare smak för bakning"}]'::jsonb,
'Mozzarella - Näringsvärde och Tillagning | Livsmedel A-Ö',
'Allt om mozzarella: näringsvärde, förvaring, tillagning och italienska recept. Guide för bästa kvalitet och användning.',
'[{"question": "Hur förvaras mozzarella bäst?", "answer": "I kylskåp i sin egen vätska eller saltlake för att behålla fuktigheten."}, {"question": "Varför blir mozzarella gummiaktig?", "answer": "Överuppvärmning gör att proteiner drar ihop sig - använd låg värme."}]'::jsonb,
ARRAY['Pizza Margherita', 'Italiensk sallad', 'Lasagne']),

('Fetaost', 'fetaost', 'F',
(SELECT id FROM public.food_categories WHERE slug = 'mejeri'),
'Saltost',
'Kylskåp 4-8°C i saltlake',
'1 vecka',
'2-3 månader',
true,
'Kan frysas men textur förändras',
ARRAY['mjölk'],
264, 14.2, 21.3, 4.1, 0.0, 4.0,
'{"A": "125μg", "B12": "1.7μg"}'::jsonb,
'{"calcium": "493mg", "fosfor": "337mg"}'::jsonb,
'Grekisk saltost med distinkt smak och krumblig textur.',
null,
ARRAY['Grekisk sallad', 'Bakad med örter', 'Paj fyllning', 'Pasta sås'],
'[{"name": "Getost", "reason": "Liknande salthet och textur"}, {"name": "Cottage cheese", "reason": "Mildare alternativ med krumblig textur"}]'::jsonb,
'Fetaost - Näringsvärde och Recept | Livsmedel A-Ö',
'Komplett guide om fetaost: näringsvärde, förvaring, grekiska recept och användning i matlagning.',
'[{"question": "Är fetaost hälsosam?", "answer": "Ja, rik på protein och kalcium men hög salthalt - ät i måttliga mängder."}, {"question": "Kan man äta fetaost som är rumstempererad?", "answer": "Ja, många föredrar den vid rumstemperatur för bästa smak."}]'::jsonb,
ARRAY['Grekisk sallad', 'Medelhavsmat', 'Vegetarisk middag']),

('Cheddar', 'cheddar', 'C',
(SELECT id FROM public.food_categories WHERE slug = 'mejeri'),
'Hårdost',
'Kylskåp 4-8°C i plast eller vax',
'3-4 veckor',
'6 månader',
true,
'Riv innan frysning',
ARRAY['mjölk'],
403, 25.0, 33.3, 1.3, 0.0, 1.8,
'{"A": "330μg", "B12": "0.8μg"}'::jsonb,
'{"calcium": "721mg", "fosfor": "512mg"}'::jsonb,
'Engelsk hårdost med skarp, fyllig smak.',
null,
ARRAY['Macka topping', 'Gratäng', 'Ostbricka', 'Smält till nachos'],
'[{"name": "Gouda", "reason": "Mildare smak"}, {"name": "Emmental", "reason": "Bra för smältning"}]'::jsonb,
'Cheddar - Näringsvärde och Användning | Livsmedel A-Ö',
'Allt om cheddar: näringsvärde, olika styrkor, förvaring och engelska osttraditionen.',
'[{"question": "Vad betyder \"aged cheddar\"?", "answer": "Ju längre lagring, desto skarpare smak - mild (2-3 mån), medium (5-6 mån), sharp (9+ mån)."}, {"question": "Varför blir cheddar orange?", "answer": "Naturlig färgämne annatto tillsätts för den karakteristiska färgen."}]'::jsonb,
ARRAY['Ostsmörgås', 'Engelsk middag', 'Pub mat']),

('Yoghurt Naturell', 'yoghurt-naturell', 'Y',
(SELECT id FROM public.food_categories WHERE slug = 'mejeri'),
'Fermenterad mjölkprodukt',
'Kylskåp 4-8°C',
'1 vecka efter öppning',
'2-3 veckor oöppnad',
true,
'Textur förändras efter frysning',
ARRAY['mjölk'],
59, 10.0, 0.4, 3.6, 0.0, 0.05,
'{"B2": "0.27mg", "B12": "0.75μg", "D": "0.1μg"}'::jsonb,
'{"calcium": "110mg", "fosfor": "135mg"}'::jsonb,
'Naturell yoghurt utan tillsatser, rik på probiotika.',
null,
ARRAY['Frukost med müsli', 'Smoothies', 'Sås bas', 'Marinad'],
'[{"name": "Filmjölk", "reason": "Liknande probiotika"}, {"name": "Skyr", "reason": "Högre protinhalt"}]'::jsonb,
'Yoghurt Naturell - Näringsvärde och Hälsofördelar | Livsmedel A-Ö',
'Komplett guide om naturell yoghurt: näringsvärde, probiotika, användning och hälsofördelar.',
'[{"question": "Vilka probiotika finns i yoghurt?", "answer": "Lactobacillus bulgaricus och Streptococcus thermophilus är de vanligaste kulturerna."}, {"question": "Kan man laga mat med yoghurt?", "answer": "Ja, men undvik hög värme som kan få den att separera."}]'::jsonb,
ARRAY['Hälsosam frukost', 'Smoothie bowl', 'Indisk mat']),

('Crème Fraiche', 'creme-fraiche', 'C',
(SELECT id FROM public.food_categories WHERE slug = 'mejeri'),
'Gräddfil',
'Kylskåp 4-8°C',
'1 vecka efter öppning',
'2-3 veckor oöppnad',
false,
'Rekommenderas ej att frysa',
ARRAY['mjölk'],
292, 2.1, 30.0, 2.9, 0.0, 0.05,
'{"A": "280μg", "D": "0.6μg"}'::jsonb,
'{"calcium": "95mg", "fosfor": "60mg"}'::jsonb,
'Fransk gräddfil med mild, lätt sur smak.',
null,
ARRAY['Såser', 'Tårtor', 'Soppa', 'Dip'],
'[{"name": "Sour cream", "reason": "Liknande konsistens"}, {"name": "Grekisk yoghurt", "reason": "Hälsosammare alternativ"}]'::jsonb,
'Crème Fraiche - Näringsvärde och Matlagning | Livsmedel A-Ö',
'Allt om crème fraiche: näringsvärde, fransk kulinarisk tradition, användning i såser och desserter.',
'[{"question": "Skillnad mellan crème fraiche och gräddfil?", "answer": "Crème fraiche har högre fetthalt (30%) och tål värme bättre än vanlig gräddfil."}, {"question": "Kan crème fraiche kokas?", "answer": "Ja, den koagulerar inte lika lätt som andra mjölkprodukter vid uppvärmning."}]'::jsonb,
ARRAY['Fransk matlagning', 'Pasta såser', 'Desserter']),

('Cottage Cheese', 'cottage-cheese', 'C',
(SELECT id FROM public.food_categories WHERE slug = 'mejeri'),
'Färskost',
'Kylskåp 4-8°C',
'3-5 dagar efter öppning',
'1-2 veckor oöppnad',
true,
'Textur kan förändras',
ARRAY['mjölk'],
98, 11.1, 4.3, 3.4, 0.0, 0.4,
'{"B12": "0.43μg", "B2": "0.37mg"}'::jsonb,
'{"calcium": "83mg", "fosfor": "159mg", "selen": "20.4μg"}'::jsonb,
'Proteinrik färskost med krumblig textur och mild smak.',
null,
ARRAY['Proteinrik frukost', 'Sallad topping', 'Smoothies', 'Bakning'],
'[{"name": "Kvarg", "reason": "Högre proteinhalt"}, {"name": "Ricotta", "reason": "Liknande textur för bakning"}]'::jsonb,
'Cottage Cheese - Näringsvärde och Protein | Livsmedel A-Ö',
'Komplett guide om cottage cheese: näringsvärde, proteinfördelar, användning i hälsosam kost.',
'[{"question": "Varför är cottage cheese bra för träning?", "answer": "Högt proteininnehåll (kasein) som ger långsam aminosyrafrisättning, perfekt före sömn."}, {"question": "Kan man baka med cottage cheese?", "answer": "Ja, utmärkt i pannkakor, cheesecake och protein muffins."}]'::jsonb,
ARRAY['Proteinrik kost', 'Träningsmat', 'Hälsosam frukost']),

('Gouda', 'gouda', 'G',
(SELECT id FROM public.food_categories WHERE slug = 'mejeri'),
'Halvhård ost',
'Kylskåp 4-8°C i ostpapper',
'3-4 veckor',
'4-6 månader',
true,
'Riv innan frysning',
ARRAY['mjölk'],
356, 25.2, 27.4, 2.2, 0.0, 2.0,
'{"A": "270μg", "B12": "1.5μg"}'::jsonb,
'{"calcium": "700mg", "fosfor": "546mg"}'::jsonb,
'Holländsk ost med mild, nötig smak och krämig textur.',
null,
ARRAY['Ostbricka', 'Smörgås', 'Gratäng', 'Ostfondue'],
'[{"name": "Edam", "reason": "Liknande holländsk ost"}, {"name": "Cheddar", "reason": "Skarpare smak"}]'::jsonb,
'Gouda - Näringsvärde och Holländsk Tradition | Livsmedel A-Ö',
'Allt om gouda: näringsvärde, holländska osttraditionen, olika lagringsgrader och användning.',
'[{"question": "Skillnad mellan ung och gammal gouda?", "answer": "Ung gouda (4 veckors lagring) är mild och krämig, gammal gouda (18+ månader) är skarp med kristaller."}, {"question": "Varför har gouda vax på sig?", "answer": "Vaxlagret skyddar osten från uttorkning och bakterier under lagring."}]'::jsonb,
ARRAY['Holländsk mat', 'Ostbricka', 'Vardagsmat']);

-- Insert Kött & Fågel (7 foods)
INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, long_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

('Nötfärs', 'notfars', 'N',
(SELECT id FROM public.food_categories WHERE slug = 'kott'),
'Malet kött',
'Kylskåp 0-4°C',
'1-2 dagar',
'1-2 dagar',
true,
'Frys inom 2 dagar, håller 3-4 månader fryst',
null,
ARRAY[],
254, 26.1, 15.0, 0.0, 0.0, 0.07,
'{"B12": "2.6μg", "B6": "0.4mg", "Niacin": "4.2mg"}'::jsonb,
'{"järn": "2.6mg", "zink": "4.5mg", "selen": "14.2μg"}'::jsonb,
'Malet nötkött, perfekt för köttfärssås och köttbullar.',
null,
ARRAY['Köttfärssås', 'Köttbullar', 'Tacos', 'Lasagne'],
'[{"name": "Fläskfärs", "reason": "Fetare och saftigare"}, {"name": "Blandfärs", "reason": "Kombination av nöt och fläsk"}]'::jsonb,
'Nötfärs - Näringsvärde och Tillagning | Livsmedel A-Ö',
'Komplett guide om nötfärs: näringsvärde, säkerhetstips, tillagning och klassiska recept.',
'[{"question": "Hur länge håller nötfärs i kylskåpet?", "answer": "Max 1-2 dagar i kylskåp, använd eller frys omgående efter köp."}, {"question": "Vilken temperatur ska nötfärs ha när den är klar?", "answer": "Minst 70°C i centrum för att döda eventuella bakterier."}]'::jsonb,
ARRAY['Köttfärssås', 'Tacos', 'Lasagne']),

('Fläskfilé', 'flaskfile', 'F',
(SELECT id FROM public.food_categories WHERE slug = 'kott'),
'Magert kött',
'Kylskåp 0-4°C',
'3-5 dagar',
'3-5 dagar',
true,
'Marinera innan frysning för bästa smak',
null,
ARRAY[],
143, 23.0, 5.0, 0.0, 0.0, 0.05,
'{"B1": "0.9mg", "B6": "0.4mg", "B12": "0.7μg"}'::jsonb,
'{"selen": "26.4μg", "fosfor": "230mg", "zink": "2.0mg"}'::jsonb,
'Mager och mör köttbit från fläskryggen.',
null,
ARRAY['Schnitzel', 'Wok', 'Ugnsstekt', 'Grillad'],
'[{"name": "Kycklingfilé", "reason": "Ännu magrare"}, {"name": "Kalvfilé", "reason": "Mörare men dyrare"}]'::jsonb,
'Fläskfilé - Näringsvärde och Tillagning | Livsmedel A-Ö',
'Allt om fläskfilé: näringsvärde, tillagningsmetoder, marinader och tips för perfekt resultat.',
'[{"question": "Hur får man fläskfilé saftig?", "answer": "Stek inte för länge och låt köttet vila efter stekning. Innertemperatur 63°C."}, {"question": "Behöver man marinera fläskfilé?", "answer": "Inte nödvändigt men förbättrar smak och saftighet, speciellt för grillning."}]'::jsonb,
ARRAY['Vardagsmiddag', 'Grillmat', 'Snabb middag']),

('Grillkorv', 'grillkorv', 'G',
(SELECT id FROM public.food_categories WHERE slug = 'kott'),
'Korv',
'Kylskåp 0-4°C',
'1 vecka efter öppning',
'2-3 veckor oöppnad',
true,
'Kan frysas upp till 2 månader',
ARRAY['maj', 'juni', 'juli', 'augusti'],
ARRAY[],
301, 13.0, 27.0, 2.0, 0.0, 2.3,
'{"B12": "1.0μg", "Niacin": "3.5mg"}'::jsonb,
'{"natrium": "920mg", "fosfor": "150mg"}'::jsonb,
'Kryddig korv perfekt för grillning och korvstroganoff.',
null,
ARRAY['Grilla', 'Korvstroganoff', 'Korv med bröd', 'Falukorv'],
'[{"name": "Bratwurst", "reason": "Tysk variant med örter"}, {"name": "Prinskorv", "reason": "Mindre storlek"}]'::jsonb,
'Grillkorv - Tillagning och Tradition | Livsmedel A-Ö',
'Komplett guide om grillkorv: tillagning, svenska korvtraditionen och klassiska tillbehör.',
'[{"question": "Hur grillar man korv bäst?", "answer": "Medelhög värme, vänd ofta, sticka inte hål - det rinner ut saft och smak."}, {"question": "Kan man koka grillkorv?", "answer": "Ja, koka 5-8 minuter eller stek i panna med lite vatten först."}]'::jsonb,
ARRAY['Grillmys', 'Korvstroganoff', 'Snabbmat']),

('Bacon', 'bacon', 'B',
(SELECT id FROM public.food_categories WHERE slug = 'kott'),
'Rökt fläsk',
'Kylskåp 0-4°C',
'1 vecka efter öppning',
'2-3 veckor oöppnad',
true,
'Portionera innan frysning',
null,
ARRAY[],
541, 37.0, 42.0, 1.4, 0.0, 2.3,
'{"B1": "0.4mg", "B12": "0.7μg", "Niacin": "11.6mg"}'::jsonb,
'{"fosfor": "280mg", "selen": "28.5μg"}'::jsonb,
'Rökt och saltat fläsksida med intensiv smak.',
null,
ARRAY['Frukost', 'Sallad topping', 'Pasta', 'Burgare'],
'[{"name": "Pancetta", "reason": "Italiensk variant utan rök"}, {"name": "Chorizo", "reason": "Kryddigare spansk variant"}]'::jsonb,
'Bacon - Näringsvärde och Tillagning | Livsmedel A-Ö',
'Allt om bacon: näringsvärde, olika typer, tillagning och användning i matlagning.',
'[{"question": "Vilket är det bästa sättet att steka bacon?", "answer": "Starta med kall panna på medelhög värme för jämn tillagning och mindre stänk."}, {"question": "Kan man äta bacon rått?", "answer": "Nej, bacon ska alltid tillagas ordentligt för att vara säkert att äta."}]'::jsonb,
ARRAY['Engelsk frukost', 'Amerikansk mat', 'Brunch']),

('Kalkon', 'kalkon', 'K',
(SELECT id FROM public.food_categories WHERE slug = 'kott'),
'Fågel',
'Kylskåp 0-4°C',
'2-3 dagar',
'2-3 dagar',
true,
'Tina långsamt i kylskåp',
ARRAY['november', 'december'],
ARRAY[],
189, 29.0, 7.0, 0.0, 0.0, 0.07,
'{"B3": "6.3mg", "B6": "0.5mg", "B12": "1.6μg"}'::jsonb,
'{"selen": "27.4μg", "fosfor": "230mg", "zink": "2.0mg"}'::jsonb,
'Mager fågel med mild smak, traditionell julmat.',
null,
ARRAY['Helstekt', 'Smörgås pålägg', 'Sallad', 'Soppa'],
'[{"name": "Kyckling", "reason": "Liknande smak men mindre"}, {"name": "And", "reason": "Fetare med starkare smak"}]'::jsonb,
'Kalkon - Näringsvärde och Jultraditioner | Livsmedel A-Ö',
'Komplett guide om kalkon: näringsvärde, tillagning, jultraditioner och amerikanska recept.',
'[{"question": "Hur länge ska kalkon stekas?", "answer": "Ca 20 min per kg vid 175°C, innertemperatur ska nå 74°C i tjockaste delen."}, {"question": "Varför äter man kalkon på jul?", "answer": "Tradition från Amerika som spridit sig, kalkon blev populärt som festmat på 1900-talet."}]'::jsonb,
ARRAY['Julbord', 'Amerikanska recept', 'Festmat']),

('Lammkött', 'lammkott', 'L',
(SELECT id FROM public.food_categories WHERE slug = 'kott'),
'Rött kött',
'Kylskåp 0-4°C',
'3-5 dagar',
'3-5 dagar',
true,
'Marinera med örter innan frysning',
ARRAY['mars', 'april', 'maj'],
ARRAY[],
294, 24.5, 21.0, 0.0, 0.0, 0.07,
'{"B12": "3.0μg", "Niacin": "6.2mg", "B6": "0.1mg"}'::jsonb,
'{"järn": "1.9mg", "zink": "3.9mg", "selen": "26.4μg"}'::jsonb,
'Rött kött med distinkt smak, populärt i medelhavsområdet.',
null,
ARRAY['Lammracks', 'Gryta', 'Kebab', 'Rosmarinmarinerad'],
'[{"name": "Gettkött", "reason": "Liknande smak"}, {"name": "Nötkött", "reason": "Mildare alternativ"}]'::jsonb,
'Lammkött - Näringsvärde och Medelhavstradition | Livsmedel A-Ö',
'Allt om lammkött: näringsvärde, medelhavsrecept, marinader och olika styckningsdelar.',
'[{"question": "Varför smakar lamm så starkt?", "answer": "Fettet innehåller fettsyror som ger den karakteristiska smaken, särskilt hos äldre djur."}, {"question": "Vilka kryddor passar till lamm?", "answer": "Rosmarin, timjan, vitlök, mynta och medelhavskryddor kompletterar smaken perfekt."}]'::jsonb,
ARRAY['Medelhavsmiddag', 'Påskmiddag', 'Kryddig mat']),

('Oxfilé', 'oxfile', 'O',
(SELECT id FROM public.food_categories WHERE slug = 'kott'),
'Premium kött',
'Kylskåp 0-4°C',
'3-5 dagar',
'3-5 dagar',
true,
'Slå in väl och frys max 6 månader',
null,
ARRAY[],
248, 26.2, 15.0, 0.0, 0.0, 0.05,
'{"B12": "2.8μg", "B6": "0.6mg", "Niacin": "6.0mg"}'::jsonb,
'{"järn": "2.5mg", "zink": "4.2mg", "selen": "24.9μg"}'::jsonb,
'Den möraste köttbiten från nötkreatur, lyxig festmat.',
null,
ARRAY['Beef Wellington', 'Tournedos', 'Carpaccio', 'Teppanyaki'],
'[{"name": "Ryggbiff", "reason": "Näst möraste alternativ"}, {"name": "Entrecôte", "reason": "Mer marmorerad med mer smak"}]'::jsonb,
'Oxfilé - Tillagning och Lyxmatlagning | Livsmedel A-Ö',
'Komplett guide om oxfilé: tillagning, lyxrecept, grader av stekhet och professionella tips.',
'[{"question": "Vad är skillnaden mellan rare och medium?", "answer": "Rare: 50-52°C (rött centrum), Medium: 57-60°C (rosa centrum), Well-done: 65°C+ (genomstekt)."}, {"question": "Varför är oxfilé så dyrt?", "answer": "Endast ca 2-3% av slaktkroppen är filé, och det är den möraste muskeln som knappt används."}]'::jsonb,
ARRAY['Lyxmiddag', 'Fransk matlagning', 'Festmat']);

-- Insert Fisk & Skaldjur (6 foods)  
INSERT INTO public.foods (name, slug, letter, category_id, subcategory, storage_method, shelf_life_opened, shelf_life_unopened, can_freeze, freezing_tips, season, allergens, calories, protein, fat, carbohydrates, fiber, salt, key_vitamins, key_minerals, short_description, long_description, usage_tips, substitutes, meta_title, meta_description, faq, common_in_lists) VALUES

('Lax', 'lax', 'L',
(SELECT id FROM public.food_categories WHERE slug = 'fisk-skaldjur'),
'Fet fisk',
'Kylskåp 0-4°C på is',
'1-2 dagar',
'1-2 dagar',
true,
'Vakuumförpacka innan frysning',
ARRAY['maj', 'juni', 'juli', 'augusti', 'september'],
ARRAY['fisk'],
208, 25.4, 13.0, 0.0, 0.0, 0.05,
'{"D": "11μg", "B12": "4.9μg", "Niacin": "8.5mg"}'::jsonb,
'{"selen": "41.4μg", "fosfor": "371mg", "kalium": "628mg"}'::jsonb,
'Näringsrik fet fisk med högt innehåll av omega-3.',
'Lax är en av de mest näringsrika fiskarna med högt innehåll av omega-3-fettsyror, protein och vitamin D. Atlantlax odlas extensivt medan vild lax har säsong sommartid.',
ARRAY['Grillad', 'Rimmad', 'Sushi', 'Ugnsbakad'],
'[{"name": "Regnbågslax", "reason": "Liknande smak och textur"}, {"name": "Makrill", "reason": "Hög omega-3 halt"}]'::jsonb,
'Lax - Näringsvärde och Omega-3 | Livsmedel A-Ö',
'Komplett guide om lax: näringsvärde, omega-3 fördelar, tillagning och skillnad mellan odlad och vild lax.',
'[{"question": "Vilka fördelar har omega-3?", "answer": "Omega-3 är viktigt för hjärtat, hjärnan och kan minska inflammation i kroppen."}, {"question": "Skillnad mellan odlad och vild lax?", "answer": "Vild lax har fastare kött och mer intensiv smak, odlad lax är fetare och tillgänglig året runt."}]'::jsonb,
ARRAY['Hälsosam middag', 'Omega-3 källa', 'Nordisk mat']),

('Torsk', 'torsk', 'T',
(SELECT id FROM public.food_categories WHERE slug = 'fisk-skaldjur'),
'Mager fisk',
'Kylskåp 0-4°C på is',
'1-2 dagar',
'1-2 dagar',
true,
'Frys inom 24 timmar efter köp',
ARRAY['oktober', 'november', 'december', 'januari', 'februari'],
ARRAY['fisk'],
105, 23.0, 0.9, 0.0, 0.0, 0.18,
'{"B12": "1.0μg", "B6": "0.2mg", "Niacin": "2.3mg"}'::jsonb,
'{"selen": "33.1μg", "fosfor": "203mg", "jod": "110μg"}'::jsonb,
'Mager vitfisk med mild smak och fast kött.',
null,
ARRAY['Fish and chips', 'Kokt med äggstuvning', 'Fisksoppa', 'Panerad'],
'[{"name": "Kolja", "reason": "Liknande mild smak"}, {"name": "Vitling", "reason": "Mer prisvärt alternativ"}]'::jsonb,
'Torsk - Näringsvärde och Nordisk Tradition | Livsmedel A-Ö',
'Allt om torsk: näringsvärde, nordiska fisktraditionen, tillagning och hållbarhet.',
'[{"question": "Varför är torsk så populär?", "answer": "Mild smak som passar de flesta, mager och proteinrik, samt traditionell i nordisk matkultur."}, {"question": "Hur vet man att torsk är färsk?", "answer": "Klara ögon, röda gälar, fast kött som studsar tillbaka när man trycker på det."}]'::jsonb,
ARRAY['Svensk husmanskost', 'Fish and chips', 'Nordisk mat']),

('Räkor', 'rakor', 'R',
(SELECT id FROM public.food_categories WHERE slug = 'fisk-skaldjur'),
'Skaldjur',
'Kylskåp 0-4°C',
'2-3 dagar kokta',
'2-3 dagar',
true,
'Frys kokta räkor upp till 3 månader',
ARRAY['maj', 'juni', 'juli', 'augusti', 'september'],
ARRAY['skaldjur'],
99, 20.3, 1.4, 0.0, 0.0, 0.25,
'{"B12": "1.3μg", "D": "0.2μg", "E": "1.1mg"}'::jsonb,
'{"selen": "38μg", "zink": "1.6mg", "jod": "35μg"}'::jsonb,
'Populära skaldjur med söt smak och fast textur.',
null,
ARRAY['Räksmörgås', 'Räksallad', 'Pasta', 'Sushi'],
'[{"name": "Kräftor", "reason": "Liknande skaldjur"}, {"name": "Havskräfta", "reason": "Större med mer kött"}]'::jsonb,
'Räkor - Näringsvärde och Svensk Tradition | Livsmedel A-Ö',
'Komplett guide om räkor: näringsvärde, svensk räktradition, tillagning och hållbarhetsaspekter.',
'[{"question": "Hur kokar man räkor?", "answer": "Saltvatten (30g salt per liter), koka 2-3 minuter för färska räkor tills de blir rosa."}, {"question": "Kan man äta räkor som gravid?", "answer": "Ja, kokta räkor är säkra, undvik dock råa räkor som i vissa sushirätter."}]'::jsonb,
ARRAY['Räksmörgås', 'Midsommar', 'Kräftskiva']),

('Tonfisk Konserverad', 'tonfisk-konserverad', 'T',
(SELECT id FROM public.food_categories WHERE slug = 'fisk-skaldjur'),
'Konserverad fisk',
'Rumstemperatur före öppning',
'3-4 dagar i kylskåp',
'2-5 år oöppnad',
false,
'Rekommenderas ej att frysa',
null,
ARRAY['fisk'],
128, 25.5, 2.5, 0.0, 0.0, 0.4,
'{"B12": "2.6μg", "B3": "18.8mg", "B6": "1.0mg"}'::jsonb,
'{"selen": "78.2μg", "fosfor": "267mg"}'::jsonb,
'Proteinrik konserverad fisk, perfekt för snabba måltider.',
null,
ARRAY['Tonfisksallad', 'Pasta', 'Smörgås', 'Nicoise sallad'],
'[{"name": "Konserverad makrill", "reason": "Högre omega-3 halt"}, {"name": "Konserverad sardiner", "reason": "Mindre fisk med ben"}]'::jsonb,
'Tonfisk Konserverad - Näringsvärde och Användning | Livsmedel A-Ö',
'Allt om konserverad tonfisk: näringsvärde, hållbarhet, olika varianter och snabba recept.',
'[{"question": "Vilken tonfisk är mest hållbar?", "answer": "Leta efter MSC-märkt tonfisk som kommer från hållbart fiske med selektiva fångstmetoder."}, {"question": "Skillnad mellan tonfisk i olja och vatten?", "answer": "Tonfisk i olja är saftigare men mer kaloririk, i vatten är magrare men kan vara torrare."}]'::jsonb,
ARRAY['Snabb lunch', 'Protein källa', 'Vardagsmat']),

('Makrill', 'makrill', 'M',
(SELECT id FROM public.food_categories WHERE slug = 'fisk-skaldjur'),
'Fet fisk',
'Kylskåp 0-4°C på is',
'1-2 dagar',
'1-2 dagar',
true,
'Rengör och frys inom 24 timmar',
ARRAY['april', 'maj', 'juni', 'juli', 'augusti', 'september'],
ARRAY['fisk'],
305, 18.6, 25.1, 0.0, 0.0, 0.15,
'{"D": "4.0μg", "B12": "19μg", "Niacin": "9.7mg"}'::jsonb,
'{"selen": "51.6μg", "fosfor": "217mg", "omega-3": "2670mg"}'::jsonb,
'Mycket fet fisk med högt omega-3 innehåll och stark smak.',
null,
ARRAY['Grillad', 'Rökt', 'Inkokt', 'Stekt'],
'[{"name": "Sill", "reason": "Liknande fet fisk"}, {"name": "Sardiner", "reason": "Mindre storlek samma familj"}]'::jsonb,
'Makrill - Omega-3 Källa och Tillagning | Livsmedel A-Ö',
'Komplett guide om makrill: extremt hög omega-3 halt, tillagning, säsong och hälsofördelar.',
'[{"question": "Varför är makrill så hälsosam?", "answer": "Extremt högt innehåll av omega-3 (över 2g per 100g) och vitamin B12, bra för hjärta och hjärna."}, {"question": "Hur får man bort den starka smaken?", "answer": "Marinera i citron och salt före tillagning, eller välj mindre exemplar som är mildare."}]'::jsonb,
ARRAY['Hälsosam fisk', 'Omega-3 källa', 'Grillmat']),

('Mussla', 'mussla', 'M',
(SELECT id FROM public.food_categories WHERE slug = 'fisk-skaldjur'),
'Skaldjur',
'Kylskåp 0-4°C levande',
'1 dag levande',
'1 dag levande',
false,
'Rekommenderas ej att frysa levande',
ARRAY['september', 'oktober', 'november', 'december', 'januari', 'februari'],
ARRAY['skaldjur', 'mollusker'],
172, 24.2, 4.6, 7.0, 0.0, 0.29,
'{"B12": "20.4μg", "Folat": "76μg", "C": "13.6mg"}'::jsonb,
'{"järn": "6.7mg", "zink": "2.7mg", "mangan": "6.8mg"}'::jsonb,
'Näringsrika skaldjur med hög halt av B12 och järn.',
null,
ARRAY['Vin och vitlök', 'Mariniere', 'Pasta', 'Soppa'],
'[{"name": "Ostron", "reason": "Liknande skaldjur"}, {"name": "Kammusslor", "reason": "Större med sötare smak"}]'::jsonb,
'Mussla - Näringsvärde och Säsongstips | Livsmedel A-Ö',
'Allt om musslor: näringsvärde, säsong, tillagning och säkerhetstips för skaldjur.',
'[{"question": "När är musslor säkrast att äta?", "answer": "Under månader med R (september-april) när vattnet är kallare och mindre bakterier."}, {"question": "Hur vet man att musslor är färska?", "answer": "Skalet ska vara stängt eller stängas när man knackar på det, kassera öppna musslor."}]'::jsonb,
ARRAY['Fransk matlagning', 'Skaldjursafton', 'Medelhavsmat']);

-- Continue with remaining categories...
-- Due to length constraints, I'll add the remaining categories in the next part