-- Add missing E-additives from Livsmedelsverket - Phase 3: Fixed syntax errors

INSERT INTO public.e_additives (e_number, name, common_name, slug, category, origin, risk_score, longevity_impact, adi_value, adi_source, short_description, long_description, meta_title, meta_description) VALUES

-- More Color Additives (E100-199) - Fixed syntax
('E155', 'Brunfärgämne HT', 'Brown HT', 'e155-brunfargamne-ht', 'Färgämne', 'Syntetisk', 6, 'Negativ', 1.5, 'WHO/EFSA', 'Syntetiskt brunt färgämne som kan orsaka allergier', 'Brunfärgämne HT är ett syntetiskt brunt färgämne som används i choklad, kex och bakvaror. Det kan orsaka allergiska reaktioner och hyperaktivitet hos känsliga barn.', 'E155 Brunfärgämne HT - Brunt färgämne i choklad | Vihandlar.se', 'E155 Brunfärgämne HT kan orsaka allergier och hyperaktivitet. Läs om detta bruna färgämne i chokladprodukter.'),

('E160e', 'Beta-apo-8''-karotenal', 'Apocarotenal', 'e160e-apokarotenal', 'Färgämne', 'Syntetisk', 3, 'Neutral', 5.0, 'WHO/EFSA', 'Syntetiskt orange färgämne besläktat med karoten', 'Beta-apo-8''-karotenal är ett syntetiskt orange färgämne som är kemiskt besläktat med naturliga karotenoider. Det används för att ge livsmedel en orange färg och anses vara relativt säkert.', 'E160e Beta-apo-8-karotenal - Orange karotenoid | Vihandlar.se', 'E160e Beta-apo-8-karotenal är ett säkert orange färgämne. Läs om denna syntetiska karotenoid och dess användning.'),

('E161g', 'Kantaxantin', 'Canthaxanthin', 'e161g-kantaxantin', 'Färgämne', 'Syntetisk', 4, 'Neutral', 0.03, 'WHO/EFSA', 'Orange-röd karotenoid som används som färgämne', 'Kantaxantin är en syntetisk karotenoid som ger orange-röd färg. Det används i livsmedel och som kosttillskott för att ge brunare hy, men kan orsaka orangefärgning av huden vid höga doser.', 'E161g Kantaxantin - Orange karotenoid färgämne | Vihandlar.se', 'E161g Kantaxantin kan färga huden orange vid höga doser. Läs om denna karotenoid och dess användning.'),

('E172', 'Järnoxider', 'Iron Oxides', 'e172-jarnoxider', 'Färgämne', 'Naturlig', 2, 'Neutral', NULL, NULL, 'Naturliga mineralfärgämnen i olika färger', 'Järnoxider är naturliga mineralfärgämnen som finns i olika färger - gul, röd, svart och brun. De används som säkra färgämnen i livsmedel och kosmetika och anses vara helt säkra.', 'E172 Järnoxider - Säkra mineralfärgämnen | Vihandlar.se', 'E172 Järnoxider är helt säkra naturliga färgämnen. Läs om dessa mineralfärgämnen och deras användning.'),

('E173', 'Aluminium', 'Aluminium', 'e173-aluminium', 'Färgämne', 'Syntetisk', 5, 'Negativ', 1.0, 'WHO/EFSA', 'Metalliskt silver färgämne med aluminiumrisker', 'Aluminium används som silver-metalliskt färgämne på kakor och konfektyr. Det finns oro för aluminiums potentiella koppling till Alzheimers sjukdom och andra neurologiska problem.', 'E173 Aluminium - Metalliskt färgämne med risker | Vihandlar.se', 'E173 Aluminium kan ha neurologiska risker. Läs om detta metalliska färgämne och dess säkerhet.'),

('E174', 'Silver', 'Silver', 'e174-silver', 'Färgämne', 'Naturlig', 2, 'Neutral', NULL, NULL, 'Ädelmetall som används som dekorativt färgämne', 'Silver är en ädelmetall som används som dekorativt färgämne på exklusiva bakverk och konfektyr. Det anses vara säkert i de små mängder som används i livsmedel.', 'E174 Silver - Ädelmetall som färgämne | Vihandlar.se', 'E174 Silver är säkert som dekorativt färgämne. Läs om denna ädelmetall i exklusiva bakverk.'),

('E175', 'Guld', 'Gold', 'e175-guld', 'Färgämne', 'Naturlig', 1, 'Neutral', NULL, NULL, 'Ädelmetall som används som lyxigt dekorativt färgämne', 'Guld är en ädelmetall som används som lyxigt dekorativt färgämne på exklusiva bakverk, choklad och drycker. Det passerar genom kroppen utan att absorberas och anses vara helt säkert.', 'E175 Guld - Lyxigt ädelmetall färgämne | Vihandlar.se', 'E175 Guld är helt säkert som lyxigt färgämne. Läs om denna ädelmetall i exklusiva produkter.'),

-- More Preservatives (E200-299)
('E214', 'Etylparahydroxibenzoat', 'Ethyl 4-hydroxybenzoate', 'e214-etylparaben', 'Konserveringsmedel', 'Syntetisk', 6, 'Negativ', 10.0, 'WHO/EFSA', 'Paraben konserveringsmedel med hormonstörande egenskaper', 'Etylparahydroxibenzoat (etylparaben) är ett konserveringsmedel som kan ha hormonstörande egenskaper, särskilt östrogenliknande effekter. Det kan orsaka allergiska reaktioner hos känsliga personer.', 'E214 Etylparaben - Hormonstörande konserveringsmedel | Vihandlar.se', 'E214 Etylparaben kan störa hormoner. Läs om detta kontroversielle konserveringsmedel och dess risker.'),

('E215', 'Natriumetylparahydroxibenzoat', 'Sodium Ethyl 4-hydroxybenzoate', 'e215-natriumetylparaben', 'Konserveringsmedel', 'Syntetisk', 6, 'Negativ', 10.0, 'WHO/EFSA', 'Natriumsalt av etylparaben med liknande risker', 'Natriumetylparahydroxibenzoat är natriumsaltet av etylparaben och har liknande hormonstörande egenskaper. Det används som konserveringsmedel men finns det oro för dess säkerhet.', 'E215 Natriumetylparaben - Hormonstörande salt | Vihandlar.se', 'E215 Natriumetylparaben har hormonstörande egenskaper. Läs om detta konserveringsmedels risker.'),

('E224', 'Kaliummetabisulfit', 'Potassium Metabisulfite', 'e224-kaliummetabisulfit', 'Konserveringsmedel', 'Syntetisk', 6, 'Negativ', 0.7, 'WHO/EFSA', 'Sulfitkonserveringsmedel som kan utlösa astma', 'Kaliummetabisulfit är ett kraftfullt sulfitkonserveringsmedel som används i vinframställning. Det kan frigöra svaveldioxid och orsaka allvarliga astmaanfall hos känsliga personer.', 'E224 Kaliummetabisulfit - Astmaframkallande sulfit | Vihandlar.se', 'E224 Kaliummetabisulfit kan utlösa allvarliga astmaanfall. Läs om detta sulfitkonserveringsmedel.'),

('E227', 'Kalciumbisulfit', 'Calcium Bisulfite', 'e227-kalciumbisulfit', 'Konserveringsmedel', 'Syntetisk', 6, 'Negativ', 0.7, 'WHO/EFSA', 'Sulfitkonserveringsmedel med astma- och allergirisk', 'Kalciumbisulfit används som konserveringsmedel främst i drycker och konserver. Det kan orsaka allergiska reaktioner och astmaanfall hos personer med sulfitöverkänslighet.', 'E227 Kalciumbisulfit - Sulfit med allergirisker | Vihandlar.se', 'E227 Kalciumbisulfit kan orsaka allergier och astma. Läs om detta sulfitkonserveringsmedel.'),

('E252', 'Kaliumnitrat', 'Potassium Nitrate', 'e252-kaliumnitrat', 'Konserveringsmedel', 'Syntetisk', 6, 'Negativ', 3.7, 'WHO/EFSA', 'Konserveringsmedel som kan bilda cancerframkallande nitrosaminer', 'Kaliumnitrat används för att konservera kött och ge den karakteristiska färgen. Liksom andra nitrat kan det bilda potentiellt cancerframkallande nitrosaminer, särskilt vid upphettning.', 'E252 Kaliumnitrat - Nitrat med cancerrisker | Vihandlar.se', 'E252 Kaliumnitrat kan bilda cancerframkallande ämnen. Läs om riskerna med detta konserveringsmedel.');

-- Add more in next batch to avoid too long query
UPDATE public.e_additives SET 
  health_effects = '{"documented": ["Hormonstörning", "Allergiska reaktioner"], "suspected": ["Fortplantningspåverkan"], "risk_groups": ["Gravida", "Barn", "Hormonsensitiva"]}',
  common_products = '[{"category": "Konserver", "products": ["Sylt", "Läsk"], "average_amount": "50-200mg per portion"}]'
WHERE e_number IN ('E214', 'E215');